### ISSUE TITLE
Unsupported pickle protocol errors with master on Python 2.7

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [bokeh/bokeh#1018]
I `conda` upgraded `bokeh` to `0.5.2` in my Python `2.7` environment. I separately cloned `master` from GitHub to try to run examples.

If I run `bokeh-server` from the cloned copy (e.g. cd to the clone and then run bokeh-server in the clone) I run into the following errors. However, if I run the `bokeh-server` one installed with conda I don't run into any errors.

Any thoughts why?
```
Bokeh Server Configuration
==========================
listening      : 127.0.0.1:5006
backend        : shelve
python options : debug:OFF, verbose:OFF, filter-logs:OFF, multi-user:OFF
js options     : splitjs:OFF, debugjs:OFF
data-directory : None


Starting Bokeh plot server on port 5006...
View http://127.0.0.1:5006/bokeh to see plots

2014-08-18 09:30:32,719:ERROR:bokeh.server:Exception on /bokeh/ [GET]
Traceback (most recent call last):
  File "/Users/josh/anaconda/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/josh/anaconda/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/josh/anaconda/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/josh/anaconda/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/josh/anaconda/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/josh/local_clones/bokeh/bokeh/server/views/main.py", line 35, in index
    bokehuser = bokeh_app.current_user()
  File "/Users/josh/local_clones/bokeh/bokeh/server/app.py", line 34, in current_user
    return self.authentication.current_user()
  File "/Users/josh/local_clones/bokeh/bokeh/server/server_backends.py", line 184, in current_user
    bokehuser = user.User.load(bokeh_app.servermodel_storage, username)
  File "/Users/josh/local_clones/bokeh/bokeh/server/models/user.py", line 56, in load
    attrs = cls.load_json(client, objid)
  File "/Users/josh/local_clones/bokeh/bokeh/server/models/__init__.py", line 36, in load_json
    data = client.get(cls.modelkey(objid))
  File "/Users/josh/local_clones/bokeh/bokeh/server/server_backends.py", line 90, in get
    data = _data.get(key, None)
  File "/Users/josh/anaconda/envs/py27/lib/python2.7/shelve.py", line 114, in get
    return self[key]
  File "/Users/josh/anaconda/envs/py27/lib/python2.7/shelve.py", line 122, in __getitem__
    value = Unpickler(f).load()
ValueError: unsupported pickle protocol: 3
2014-08-18 09:30:32,806:INFO:bokeh.server.start:GET /bokeh/ 500 INTERNAL SERVER ERROR 412 97.0ms
2014-08-18 09:30:33,222:INFO:bokeh.server.start:GET /favicon.ico 404 NOT FOUND 342 767.9us
```

**Comment by bryevdv** [comment]
@ribonoous do yo know if this problem persists in 0.7 or master?

**Comment by bryevdv** [comment]
Closing, lacking new information. Please re-open if there is additional information or the problem persists.
