### ISSUE TITLE
Linker error trying to include luma.gl/gltools

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10230]
@mattpap I am just trying to include some things from `@luma.gl/gltools` (which does not have typings AFAICT) but I am running in to an error thrown by our custom linker code. This is what I have tried:
```diff
diff --git a/bokehjs/package.json b/bokehjs/package.json
index ccaa43315..f70155957 100644
--- a/bokehjs/package.json
+++ b/bokehjs/package.json
@@ -76,6 +76,7 @@
     "@typescript-eslint/parser": "^2.24.0"
   },
   "dependencies": {
+    "@luma.gl/gltools": "^8.1.3",
     "tslib": "^1.11.0",
     "es5-ext": "^0.10.53",
     "es6-promise": "4.2.8",
diff --git a/bokehjs/src/lib/external/gltools.d.ts b/bokehjs/src/lib/external/gltools.d.ts
new file mode 100644
index 000000000..61fd9d615
--- /dev/null
+++ b/bokehjs/src/lib/external/gltools.d.ts
@@ -0,0 +1,3 @@
+declare module "@luma.gl/gltools" {
+  export function polyfillContext(context: WebGLRenderingContext): WebGLRenderingContext
+}
diff --git a/bokehjs/src/lib/models/canvas/canvas.ts b/bokehjs/src/lib/models/canvas/canvas.ts
index 80ea03a5d..a81a7b23f 100644
--- a/bokehjs/src/lib/models/canvas/canvas.ts
+++ b/bokehjs/src/lib/models/canvas/canvas.ts
@@ -9,6 +9,9 @@ import {BBox} from "core/util/bbox"
 import {Context2d, fixup_ctx} from "core/util/canvas"
 import {SVGRenderingContext2D} from "core/util/svg"

+import {polyfillContext} from "@luma.gl/gltools"
+
+
 export type FrameBox = [number, number, number, number]

 // Notes on WebGL support:
@@ -32,6 +35,8 @@ const global_webgl: WebGLState | undefined = (() => {
   // we avoid the limitation of max 16 contexts that most browsers have.
   const canvas = document.createElement("canvas")
   const gl = canvas.getContext("webgl", {premultipliedAlpha: true})
+  const gl2 = polyfillContext(gl!)
+  console.log(gl2)

   // If WebGL is available, we store a reference to the gl canvas on
   // the ctx object, because that's what gets passed everywhere.
```

Which blows up like this:
```
14:29:28] Starting 'scripts:compile'...
[14:29:36] Finished 'scripts:compile' after 8.54 s
[14:29:36] Starting 'scripts:bundle'...
[14:29:39] Finished 'scripts:bundle' after 2.58 s
[14:29:39] failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
[14:29:39]     at validateString (internal/validators.js:121:11)
[14:29:39]     at Object.join (path.js:1039:7)
[14:29:39]     at /Users/bvandeven/work/bokeh/bokehjs/src/compiler/linker.ts:618:29
[14:29:39]     at Linker.new_module (/Users/bvandeven/work/bokeh/bokehjs/src/compiler/linker.ts:629:7)
[14:29:39]     at Linker.resolve (/Users/bvandeven/work/bokeh/bokehjs/src/compiler/linker.ts:712:27)
[14:29:39]     at Linker.link (/Users/bvandeven/work/bokeh/bokehjs/src/compiler/linker.ts:268:28)
[14:29:39]     at Task.fn (/Users/bvandeven/work/bokeh/bokehjs/make/tasks/scripts.ts:69:26)
[14:29:39]     at exec_task (/Users/bvandeven/work/bokeh/bokehjs/make/task.ts:162:34)
[14:29:39]     at _run (/Users/bvandeven/work/bokeh/bokehjs/make/task.ts:196:24)
[14:29:39]     at _run (/Users/bvandeven/work/bokeh/bokehjs/make/task.ts:187:24)
```
Can you tell me what I am missing?

**Comment by mattpap** [comment]
It's a bug. Well, luma includes some helpers from babel's utils, and babel is doing something non-standard with package layout.
