### ISSUE TITLE
Bokeh giving an websocket error while trying to use serve

### ISSUE THREAD

**Issue by ascoril** [bokeh/bokeh#10327]
I am trying to run the movies sample using the bokeh serve

WINDOWS 10 - OS
Python 3.6.5 :: Anaconda, Inc.

\Anaconda\Scripts\bokeh.exe serve --show movies
2020-07-21 15:04:15,288 Starting Bokeh server version 2.0.2 (running on Tornado 5.0.2)
2020-07-21 15:04:15,333 User authentication hooks NOT provided (default user enabled)
2020-07-21 15:04:15,348 Bokeh app running at: http://localhost:5006/movies
2020-07-21 15:04:15,348 Starting Bokeh server with process id: 5852
2020-07-21 15:04:20,343 WebSocket connection opened
2020-07-21 15:04:20,343 Uncaught exception in /movies/ws
Traceback (most recent call last):
  File "D:\tools-other-than-android\Anaconda\lib\site-packages\tornado\websocket.py", line 498, in _run_callback
    result = callback(*args, **kwargs)
  File "D:\tools-other-than-android\Anaconda\lib\site-packages\bokeh\server\views\ws.py", line 121, in open
    if self.selected_subprotocol != 'bokeh':
AttributeError: 'WSHandler' object has no attribute 'selected_subprotocol'
2020-07-21 15:04:20,365 WebSocket connection closed: code=None, reason=None

**Comment by philippjfr** [comment]
Thanks for the issue, bokeh requires Tornado>=5.1, unfortunately I don't think this was appropriately pinned at the time but upgrading to a more recent Tornado version should fix your issue.
