### ISSUE TITLE
[BUG] font awesome example is broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10410]
```
bk22rc ❯ python font-awesome.py 
Traceback (most recent call last):
  File "font-awesome.py", line 10, in <module>
    show(column(btn))
  File "/home/bryan/anaconda/envs/bk22rc/lib/python3.8/site-packages/bokeh/io/showing.py", line 139, in show
    return _show_with_state(obj, state, browser, new, notebook_handle=notebook_handle)
  File "/home/bryan/anaconda/envs/bk22rc/lib/python3.8/site-packages/bokeh/io/showing.py", line 177, in _show_with_state
    _show_file_with_state(obj, state, new, controller)
  File "/home/bryan/anaconda/envs/bk22rc/lib/python3.8/site-packages/bokeh/io/showing.py", line 160, in _show_file_with_state
    filename = save(obj, state=state)
  File "/home/bryan/anaconda/envs/bk22rc/lib/python3.8/site-packages/bokeh/io/saving.py", line 86, in save
    _save_helper(obj, filename, resources, title, template, theme)
  File "/home/bryan/anaconda/envs/bk22rc/lib/python3.8/site-packages/bokeh/io/saving.py", line 148, in _save_helper
    html = file_html(obj, resources, title=title, template=template, theme=theme)
  File "/home/bryan/anaconda/envs/bk22rc/lib/python3.8/site-packages/bokeh/embed/standalone.py", line 306, in file_html
    bundle = bundle_for_objs_and_resources([doc], resources)
  File "/home/bryan/anaconda/envs/bk22rc/lib/python3.8/site-packages/bokeh/embed/bundle.py", line 195, in bundle_for_objs_and_resources
    ext = bundle_models(models)
  File "/home/bryan/anaconda/envs/bk22rc/lib/python3.8/site-packages/bokeh/util/compiler.py", line 295, in bundle_models
    _bundle_cache[key] = bundle = _bundle_models(custom_models)
  File "/home/bryan/anaconda/envs/bk22rc/lib/python3.8/site-packages/bokeh/util/compiler.py", line 508, in _bundle_models
    custom_impls = _compile_models(custom_models)
  File "/home/bryan/anaconda/envs/bk22rc/lib/python3.8/site-packages/bokeh/util/compiler.py", line 479, in _compile_models
    _run_npmjs(["install", "--no-progress"] + [ name + "@" + version for (name, version) in dependencies ])
  File "/home/bryan/anaconda/envs/bk22rc/lib/python3.8/site-packages/bokeh/util/compiler.py", line 435, in _run_npmjs
    return _run(_npmjs_path(), argv, input)
  File "/home/bryan/anaconda/envs/bk22rc/lib/python3.8/site-packages/bokeh/util/compiler.py", line 427, in _run
    raise RuntimeError(errout.decode('utf-8'))
RuntimeError
```

**Comment by bryevdv** [comment]
OK it seems npm on my system is just borked:
```
bk22rc ❯ npm
[1]    48757 segmentation fault  npm

```
so I will close this.
