### ISSUE TITLE
Lots of problems when following the Bokeh developer guide.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [bokeh/bokeh#10523]
Bokeh branch: branch-2.3 (fix-button-no-space-when-no-label)
OS: Windows 10

I'm trying to follow along the Bokeh developer getting setup guide but get the below error.

```bash
XYZ MINGW64 /c/repos/private/bokeh/bokehjs (fix-button-no-space-when-no-label)
$ npm install -g npm
npm ERR! code EEXIST
npm ERR! path C:\Users\XYZ\AppData\Local\Continuum\anaconda3\envs\bkdev\npm.cmd
npm ERR! Refusing to delete C:\Users\XYZ\AppData\Local\Continuum\anaconda3\envs\bkdev\npm.cmd: is outside C:\Users\XYZ\AppData\Local\Continuum\anaconda3\envs\bkdev\node_modules\npm and not a link
npm ERR! File exists: C:\Users\XYZ\AppData\Local\Continuum\anaconda3\envs\bkdev\npm.cmd
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XYZ\AppData\Roaming\npm-cache\_logs\2020-09-24T03_44_54_648Z-debug.log
```

## Additional Context

I can see that it asks me to remove the existing file. But since I don't know the consequence and is using npm in other projects I don't feel comfortable doing that.

I've installed locally with `npm install npm` and it worked but the next step does not

```bash
$ node_modules/npm/bin/npm ci
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module 'C:\repos\private\bokeh\bokehjs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module 'C:\repos\private\bokeh\bokehjs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
(bkdev)
```

**Comment by MarcSkovMadsen** [comment]
Ok I went back and looked closer at the error message. It's a file in the `bkdev` environment. That should be ok to rename. So I did but still I got.

```bash
$ npm install -g npm
npm ERR! code EEXIST
npm ERR! path C:\Users\XYZ\AppData\Local\Continuum\anaconda3\envs\bkdev\npm.cmd
npm ERR! Refusing to delete C:\Users\XYZ\AppData\Local\Continuum\anaconda3\envs\bkdev\npm.cmd: is outside C:\Users\XYZ\AppData\Local\Continuum\anaconda3\envs\bkdev\node_modules\npm and not a link
npm ERR! File exists: C:\Users\XYZ\AppData\Local\Continuum\anaconda3\envs\bkdev\npm.cmd
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XYZ\AppData\Roaming\npm-cache\_logs\2020-09-24T04_01_28_741Z-debug.log
(bkdev)
``

**Comment by MarcSkovMadsen** [comment]
But this worked

```bash
$ npm install --force -g npm
npm WARN using --force I sure hope you know what you are doing.
C:\Users\XYZ\AppData\Roaming\npm\npm -> C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
C:\Users\XYZ\AppData\Roaming\npm\npx -> C:\Users\XYZ\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js
+ npm@6.14.8
added 434 packages from 885 contributors in 17.167s
(.venv)
```

**Comment by MarcSkovMadsen** [comment]
Next I get this

The I get this error message

```bash
$ python setup.py develop --install-js

ERROR: Cannot install BokehJS: files missing in `./bokehjs/build`.


Please build BokehJS by running setup.py with the `--build-js` option.
  Dev Guide: https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html.

(bkdev)
```

so instead I run the below. It worked with some warnings

```bash
$ python setup.py develop --build-js
Building BokehJS... Success!

Build output:

   [06:08:25] Starting 'styles:compile'...
   [06:08:25] Finished 'styles:compile' after 289 ms
   [06:08:25] Starting 'scripts:styles'...
   [06:08:25] Finished 'scripts:styles' after 27 ms
   [06:08:25] Starting 'scripts:version'...
   [06:08:25] Finished 'scripts:version' after 1 ms
   [06:08:25] Starting 'scripts:compile'...
   [06:08:37] Finished 'scripts:compile' after 12.19 s
   [06:08:37] Starting 'scripts:bundle'...
   [06:08:51] Finished 'scripts:bundle' after 14.37 s
   [06:08:51] Finished 'lib:build'
   [06:08:51] Starting 'scripts:bundle-legacy'...
   [06:09:06] Finished 'scripts:bundle-legacy' after 14.56 s
   [06:09:06] Finished 'scripts:build'
   [06:09:06] Starting 'compiler:ts'...
   [06:09:07] Finished 'compiler:ts' after 1.36 s
   [06:09:07] Starting 'compiler:build'...
   [06:09:17] Finished 'compiler:build' after 9.97 s
   [06:09:17] Finished 'build'
   [06:09:17] Finished 'top-level'

Build time: 75.2 seconds

Build artifact sizes:
  - bokeh.js              : 1757.3 KB
  - bokeh.min.js          :  740.1 KB
  - bokeh-widgets.js      :  659.5 KB
  - bokeh-widgets.min.js  :  253.1 KB
  - bokeh-tables.js       :  913.1 KB
  - bokeh-tables.min.js   :  289.3 KB
  - bokeh-api.js          :  111.2 KB
  - bokeh-api.min.js      :   72.1 KB
C:\Users\XYZ\AppData\Local\Continuum\anaconda3\envs\bkdev\lib\site-packages\setuptools\dist.py:472: UserWarning: The version specified ('2.3.0dev1-9-g30dccab3b-dirty') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running develop
running egg_info
creating bokeh.egg-info
writing bokeh.egg-info\PKG-INFO
writing dependency_links to bokeh.egg-info\dependency_links.txt
writing entry points to bokeh.egg-info\entry_points.txt
writing requirements to bokeh.egg-info\requires.txt
writing top-level names to bokeh.egg-info\top_level.txt
writing manifest file 'bokeh.egg-info\SOURCES.txt'
reading manifest file 'bokeh.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tests'
no previously-included directories found matching 'sphinx'
warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
warning: no previously-included files matching '__pycache__\**' found anywhere in distribution
writing manifest file 'bokeh.egg-info\SOURCES.txt'
running build_ext
Creating c:\users\XYZ\appdata\local\continuum\anaconda3\envs\bkdev\lib\site-packages\bokeh.egg-link (link to .)
Adding bokeh 2.3.0dev1-9-g30dccab3b-dirty to easy-install.pth file
Installing bokeh-script.py script to C:\Users\XYZ\AppData\Local\Continuum\anaconda3\envs\bkdev\Scripts
Installing bokeh.exe script to C:\Users\XYZ\AppData\Local\Continuum\anaconda3\envs\bkdev\Scripts

Installed c:\repos\private\bokeh
Processing dependencies for bokeh===2.3.0dev1-9-g30dccab3b-dirty
Searching for typing-extensions==3.7.4.2
Best match: typing-extensions 3.7.4.2
Adding typing-extensions 3.7.4.2 to easy-install.pth file

Using c:\users\XYZ\appdata\local\continuum\anaconda3\envs\bkdev\lib\site-packages
Searching for tornado==6.0.4
Best match: tornado 6.0.4
Adding tornado 6.0.4 to easy-install.pth file

Using c:\users\XYZ\appdata\local\continuum\anaconda3\envs\bkdev\lib\site-packages
Searching for packaging==20.4
Best match: packaging 20.4
Adding packaging 20.4 to easy-install.pth file

Using c:\users\XYZ\appdata\local\continuum\anaconda3\envs\bkdev\lib\site-packages
Searching for Pillow==7.2.0
Best match: Pillow 7.2.0
Adding Pillow 7.2.0 to easy-install.pth file

Using c:\users\XYZ\appdata\local\continuum\anaconda3\envs\bkdev\lib\site-packages
Searching for numpy==1.19.1
Best match: numpy 1.19.1
Adding numpy 1.19.1 to easy-install.pth file
Installing f2py-script.py script to C:\Users\XYZ\AppData\Local\Continuum\anaconda3\envs\bkdev\Scripts
Installing f2py.exe script to C:\Users\XYZ\AppData\Local\Continuum\anaconda3\envs\bkdev\Scripts

Using c:\users\XYZ\appdata\local\continuum\anaconda3\envs\bkdev\lib\site-packages
Searching for Jinja2==2.11.2
Best match: Jinja2 2.11.2
Adding Jinja2 2.11.2 to easy-install.pth file

Using c:\users\XYZ\appdata\local\continuum\anaconda3\envs\bkdev\lib\site-packages
Searching for python-dateutil==2.8.1
Best match: python-dateutil 2.8.1
Adding python-dateutil 2.8.1 to easy-install.pth file

Using c:\users\XYZ\appdata\local\continuum\anaconda3\envs\bkdev\lib\site-packages
Searching for PyYAML==5.3.1
Best match: PyYAML 5.3.1
Adding PyYAML 5.3.1 to easy-install.pth file

Using c:\users\XYZ\appdata\local\continuum\anaconda3\envs\bkdev\lib\site-packages
Searching for six==1.15.0
Best match: six 1.15.0
Adding six 1.15.0 to easy-install.pth file

Using c:\users\XYZ\appdata\local\continuum\anaconda3\envs\bkdev\lib\site-packages
Searching for pyparsing==2.4.7
Best match: pyparsing 2.4.7
Adding pyparsing 2.4.7 to easy-install.pth file

Using c:\users\XYZ\appdata\local\continuum\anaconda3\envs\bkdev\lib\site-packages
Searching for MarkupSafe==1.1.1
Best match: MarkupSafe 1.1.1
Adding MarkupSafe 1.1.1 to easy-install.pth file

Using c:\users\XYZ\appdata\local\continuum\anaconda3\envs\bkdev\lib\site-packages
Finished processing dependencies for bokeh===2.3.0dev1-9-g30dccab3b-dirty

Installed Bokeh for DEVELOPMENT:
  - using NEWLY built BokehJS from bokehjs/build


(bkdev)
```

**Comment by MarcSkovMadsen** [comment]
This went well

```bash
$ bokeh sampledata
Using data directory: C:\Users\masma\.bokeh\data
Skipping 'CGM.csv' (checksum match)
Skipping 'US_Counties.zip' (checksum match)
Skipping 'us_cities.json' (checksum match)
Skipping 'unemployment09.csv' (checksum match)
Skipping 'AAPL.csv' (checksum match)
Skipping 'FB.csv' (checksum match)
Skipping 'GOOG.csv' (checksum match)
Skipping 'IBM.csv' (checksum match)
Skipping 'MSFT.csv' (checksum match)
Skipping 'WPP2012_SA_DB03_POPULATION_QUINQUENNIAL.zip' (checksum match)
Skipping 'gapminder_fertility.csv' (checksum match)
Skipping 'gapminder_population.csv' (checksum match)
Skipping 'gapminder_life_expectancy.csv' (checksum match)
Skipping 'gapminder_regions.csv' (checksum match)
Skipping 'world_cities.zip' (checksum match)
Skipping 'airports.json' (checksum match)
Skipping 'movies.db.zip' (checksum match)
Skipping 'airports.csv' (checksum match)
Skipping 'routes.csv' (checksum match)
Skipping 'haarcascade_frontalface_default.xml' (checksum match)
(.venv)
```

**Comment by MarcSkovMadsen** [comment]
This did not work

```bash
$ python -m bokeh info
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python37\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\Python37\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\repos\private\bokeh\bokeh\__init__.py", line 73, in <module>
    from .util import logconfig # isort:skip
  File "C:\repos\private\bokeh\bokeh\util\logconfig.py", line 40, in <module>
    from ..settings import settings
  File "C:\repos\private\bokeh\bokeh\settings.py", line 124, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
(.venv)
```

**Comment by mattpap** [comment]
The problems with npm are (most likely) related to using windows build of npm with a linux shell (git bash I guess?). If you install nodejs with conda (as we suggest to do), then you should run `npm install`, `node make`, etc. from a windows' shell. PowerShell (especially the one configured automatically by miniconda or anaconda distribution) works best. My personal workflow on windows is to use both powershell and git bash, the former for building and running software, and the other for git, fs manipulation, etc.

**Comment by mattpap** [comment]
> `npm install --force -g npm`

If I recall correctly, this broke my installation of npm, which required reinstall of nodejs.

**Comment by mattpap** [comment]
> `python setup.py develop --install-js`

If you didn't run `(cd bokehjs; node make build)` before this, then the error message is correct.

**Comment by MarcSkovMadsen** [comment]
you May close the issue. I Got it working.

I primarely opened the issue to share how this works for a Windows contributor. Dont know if you have many of those.

**Comment by bryevdv** [comment]
Agree with @mattpap re NPM there are lots of ways to install NPM and unfortunately lots of potential problem paths. There's just not any way we can cover every possible contingency when installing NPM. We might simply mention this and suggest some places to go for NPM troubleshooting specifically. 

RE: `--install-js`, I thought we had this covered in the docs, which do say:

> 
> You may skip this prompt by supplying the appropriate command line option to setup.py, e.g.
> 
> python setup.py develop --build-js
> 
> python setup.py develop --install-js
> 
> Note that you will need to build BokehJS any time that the BokehJS source code changes (either by you or by pulling new revisions from GitHub). ***In particular, at the very least, you must build BokehJS the first time you install.***

If there is some suggestion or making this clearer or more apparent, please let us know. (I will go ahead and close this issue, though)
