### ISSUE TITLE
Document that some AR example need scipy + PIL to work

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#1060]
Testing today in a clean conda env I realized that you can install scipy without PIL and get the following error running remote_image.py:

```
Traceback (most recent call last):
  File "/home/damian/miniconda/envs/bokeh/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/damian/miniconda/envs/bokeh/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/damian/miniconda/envs/bokeh/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/damian/miniconda/envs/bokeh/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/damian/miniconda/envs/bokeh/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/damian/miniconda/envs/bokeh/lib/python2.7/site-packages/bokeh/server/crossdomain.py", line 29, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/damian/miniconda/envs/bokeh/lib/python2.7/site-packages/bokeh/server/views/data.py", line 43, in get_data
    result = bokeh_app.datamanager.get_data(request_username, serverdatasource, parameters, plot_state)
  File "/home/damian/miniconda/envs/bokeh/lib/python2.7/site-packages/bokeh/server/server_backends.py", line 547, in get_data
    parameters, plot_state)
  File "/home/damian/miniconda/envs/bokeh/lib/python2.7/site-packages/bokeh/server/server_backends.py", line 525, in heatmap_downsample
    y_resolution)
  File "/home/damian/miniconda/envs/bokeh/lib/python2.7/site-packages/bokeh/transforms/image_downsample.py", line 44, in downsample
    image = scipy.misc.imresize(subset, (x_resolution, y_resolution),
AttributeError: 'module' object has no attribute 'imresize'
```

For example, I had installed PIL in my old working env for other causes, so it never failed until I create a new and clean one specifically to test the examples...

**Comment by peteflorence** [comment]
Thanks for this helpful documented comment!  Wasn't too easy to find that PIL was a dependency for scipy.misc.imresize

**Comment by damianavila** [comment]
>Thanks for this helpful documented comment! Wasn't too easy to find that PIL was a dependency for scipy.misc.imresize

This is why I am pushing to make a comment on the docs about that... I will open a PR tomorrow, thanks for your feedback!
