### ISSUE TITLE
CI is failing with ModuleNotFoundError: No module named 'bokeh'

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#10721]
For example:

https://github.com/bokeh/bokeh/pull/10718/checks?check_run_id=1444690851
https://github.com/bokeh/bokeh/pull/10718/checks?check_run_id=1444690936

This happens in other PRs as well. I'm guessing this has something to do with setting up `PYTHONPATH`.

**Comment by bryevdv** [comment]
Well, it always seems to be the same three jobs: examples, js-tests, and docs. Not sure offhand what is different about those, or what changed.

**Comment by bryevdv** [comment]
I suspect this is the difference

#### Working
```
Run bash ci/install_bokeh_package.sh
+ conda install --yes --quiet --offline /tmp/conda-bld/noarch/bokeh-b7f16af-py_0.tar.bz2
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ python setup.py --install-js
```

#### Failing
```
Run bash ci/install_bokeh_package.sh
+ conda install --yes --quiet --offline '/tmp/conda-bld/noarch/bokeh-*.bz2'
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - /tmp/conda-bld/noarch/bokeh-*.bz2

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

+ python setup.py --install-js
```

This doesn't affect all builds because no doubt some of them are using the install from the source tree. This is absolutely another reason we should start planning to move to a `src` tree layout and away from `bokeh/bokeh` to help make sure we are always testing from a built and installed package. 

Anyway, I don't know offhand why the conda install of the local package is suddenly failing yet.

**Comment by bryevdv** [comment]
Conda package build is failing (but the build job is not failing for some reason):
```
Run bash ci/build_conda_pacakge.sh
+ conda build conda.recipe --quiet --no-test --no-anaconda-upload --no-verify
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/bk-test/bin/conda-build", line 7, in <module>
    from conda_build.cli.main_build import main
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 18, in <module>
    import conda_build.api as api
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import (Config, get_or_merge_config, get_channel_urls,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/conda_build/config.py", line 17, in <module>
    from .variants import get_default_variant
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/conda_build/variants.py", line 15, in <module>
    from conda_build.utils import ensure_list, trim_empty_keys, get_logger
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/conda_build/utils.py", line 10, in <module>
    import libarchive
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libiconv.so.2: cannot open shared object file: No such file or directory
+ pushd /usr/share/miniconda3/envs/bk-test
/usr/share/miniconda3/envs/bk-test ~/work/bokeh/bokeh
+ tar cvzf conda-bld-noarch.tgz conda-bld/noarch
tar: conda-bld/noarch: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
+ popd
~/work/bokeh/bokeh
+ mv /usr/share/miniconda3/envs/bk-test/conda-bld-noarch.tgz .
```

**Comment by bryevdv** [comment]
IIRC a new version of Anaconda was just released. Perhaps this is relevant.
