### ISSUE TITLE
On Python 3.9, the import fails becaus of PIL[BUG]

### ISSUE THREAD

**Issue by Jobenas** [bokeh/bokeh#10790]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Software Version INFO:
OS: Windows 10.
Python Version: 3.9.1
IDE: Pycharm 2020.3

#### Description of expected behavior and the observed behavior
When importing bokeh on the project it files with error "ModuleNotFoundError: No module named 'PIL'".

#### Complete, minimal, self-contained example code that reproduces the issue
Code that creates the problem

```
from bokeh.embed import components
# code goes here between backticks

```

#### Stack traceback and/or browser JavaScript console output
Traceback:
Traceback (most recent call last):
  File "C:\Users\joben\EAT\ECM\SW\ecm_server\server.py", line 105, in <module>
    create_app()
  File "C:\Users\joben\EAT\ECM\SW\ecm_server\server.py", line 95, in create_app
    register_blueprints(app)
  File "C:\Users\joben\EAT\ECM\SW\ecm_server\server.py", line 44, in register_blueprints
    module = import_module('{}.routes'.format(module_name))
  File "C:\Users\joben\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\joben\EAT\ECM\SW\ecm_server\home\routes.py", line 45, in <module>
    from bokeh.embed import components
  File "C:\Users\joben\Python\Python39\lib\site-packages\bokeh\embed\__init__.py", line 54, in <module>
    from .server import server_document
  File "C:\Users\joben\Python\Python39\lib\site-packages\bokeh\embed\server.py", line 30, in <module>
    from ..resources import DEFAULT_SERVER_HTTP_URL
  File "C:\Users\joben\Python\Python39\lib\site-packages\bokeh\resources.py", line 42, in <module>
    from .model import Model
  File "C:\Users\joben\Python\Python39\lib\site-packages\bokeh\model.py", line 33, in <module>
    from .core.properties import Any, Dict, Instance, List, String
  File "C:\Users\joben\Python\Python39\lib\site-packages\bokeh\core\properties.py", line 273, in <module>
    from .property.dataspec import AngleSpec; AngleSpec
  File "C:\Users\joben\Python\Python39\lib\site-packages\bokeh\core\property\dataspec.py", line 40, in <module>
    from .visual import FontSize, HatchPatternType, MarkerType
  File "C:\Users\joben\Python\Python39\lib\site-packages\bokeh\core\property\visual.py", line 29, in <module>
    import PIL.Image
ModuleNotFoundError: No module named 'PIL'

Process finished with exit code 1

#### Screenshots or screencasts of the bug in action

My theory is that the problem is dependent the version of Pillow, my system is currently using version 8.0.1, on this version the import should be 

```
import pil
```

instead of 

```
import PIL
```

I've changed this on the visual.py file of the bokeh module  for line 29

```
import PIL.Image
```

and that solves the issue. 

I'm not sure if this issue is specific for my system or it is a compatibility issue, but wanted to report it as a bug before attempting any pull request.

Thanks!

Jorge.

**Comment by bryevdv** [comment]
Hi @jorge I think this must be some install issue, or environment/path mixup, local on your system? We test with Python 3.9 on Win, OSX, and Linux and I just checked that all the jobs are passing and do install pillow 8.0.1, e.g.

https://github.com/bokeh/bokeh/runs/1573481842?check_suite_focus=true#step:3:1157

I also can't find any mention of any breaking API changes around this import in the pillow 8.x release notes:

https://pillow.readthedocs.io/en/stable/releasenotes/8.0.0.html

**Comment by Jobenas** [comment]
Hi @bryevdv what information can I provide you with to check out the specific issue? I've already resolved it on my system, and is not actually affecting any production systems right now, but for some reason I got this problem on this specific instance.

**Comment by bryevdv** [comment]
Hi @Jobenas as I mentioned I think this is a local issue on your end. Here is further evidence that the existing imports work fine:
```
In [6]: import PIL

In [7]: import PIL.Image

In [8]: PIL.__version__
Out[8]: '8.0.0'
```
I don't think any changes are appropriate, so I will close this now.

**Comment by Jobenas** [comment]
Thanks @bryevdv, I'll check those out then

**Comment by PorterG2003** [comment]
I am having the same issue. @Jobenas How did you resolve it?

**Comment by Jobenas** [comment]
> I am having the same issue. @Jobenas How did you resolve it?

Hi @PorterG2003 When the issue presented itself I modified the file I mentioned in a previous comment on my system, this is not ideal because that's not something that should be done, but as bryevdv commented, it was something on my system, because on further installs of the module I was able to use it as is. My recommendation is to do a fresh install on a virtual environment so you are absolutely sure that everything is installing as expected.
