### ISSUE TITLE
Cannot import (fast-components) module in bokeh extension - "Export" statement may only appear at top level

### ISSUE THREAD

**Issue by MarcSkovMadsen** [bokeh/bokeh#10812]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh: 2.2.3
Python: 3.7.8
OS: Win

#### Context

I'm trying to develop a custom bokeh extension in typescript using the [Fast.design](https://www.fast.design/) web components.

#### Description of expected behavior and the observed behavior

I would expect to be able to `npm install --save @microsoft/fast-components` and then add the following 3 lines of code to my `index.ts` file

```typescript
import { FASTDesignSystemProvider, FASTButton } from "@microsoft/fast-components";
FASTDesignSystemProvider;
FASTButton;
```

But when I run `bokeh build` I get the error

```bash
"Export" statement may only appear at the top level
    at minify
```

#### Complete, minimal, self-contained example code that reproduces the issue

[bokeh-fast.zip](https://github.com/bokeh/bokeh/files/5760791/bokeh-fast.zip)

The .zip file contains a README file describing the minimal steps to setup the project as well as the project setup with package.json etc.

#### Stack traceback and/or browser JavaScript console output

```bash
$ bokeh build
Working directory: C:\repos\private\bokeh-fast
Using different version of bokeh, rebuilding from scratch.
Running npm install.
audited 63 packages in 1.079s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Using C:\repos\private\bokeh-fast\tsconfig.json
Compiling TypeScript (1 files)
Linking modules
Error: C:\repos\private\bokeh-fast\node_modules\@microsoft\fast-components\dist\esm\index.js:1:4: "Export" statement may only appear at the top level
    at minify (c:\repos\private\bokeh-fast\.venv\lib\site-packages\bokeh\server\static\js\compiler.js:150331:19)
    at c:\repos\private\bokeh-fast\.venv\lib\site-packages\bokeh\server\static\js\compiler.js:149953:56
    at Array.map (<anonymous>)
    at artifacts (c:\repos\private\bokeh-fast\.venv\lib\site-packages\bokeh\server\static\js\compiler.js:149947:32)
    at Linker.link (c:\repos\private\bokeh-fast\.venv\lib\site-packages\bokeh\server\static\js\compiler.js:149963:50)
    at Object.build (c:\repos\private\bokeh-fast\.venv\lib\site-packages\bokeh\server\static\js\compiler.js:148834:32)
    at main (c:\repos\private\bokeh-fast\.venv\lib\site-packages\bokeh\server\static\js\compiler.js:214:46)
    at Object._ (c:\repos\private\bokeh-fast\.venv\lib\site-packages\bokeh\server\static\js\compiler.js:246:5)
    at require (c:\repos\private\bokeh-fast\.venv\lib\site-packages\bokeh\server\static\js\compiler.js:94:23)
    at c:\repos\private\bokeh-fast\.venv\lib\site-packages\bokeh\server\static\js\compiler.js:105:16
```

**Comment by mattpap** [comment]
This is because `fast-components` doesn't identify itself as an ES module, thus gets wrapped but not transpiled. Technically a bug on our side, because we always should transpile imports/exports, but if the module was set properly up, it would work regardless.

**Comment by MarcSkovMadsen** [comment]
Thanks @mattpap . Is there something I can do? I do I just have to wait for a bokeh fix?

**Comment by mattpap** [comment]
One can modify `fast-components`' `package.json` and add `type: "module"` or add `module` entry point (instead of `main`). I think that should be enough, but this will get erased every time the package is updated. I will see if a quick fix can be applied to bokehjs.

**Comment by EisenbergEffect** [comment]
This is a bit of a tricky situation for us. I believe we originally had the type set to "module" in a very early version of FAST, and that ended up causing various issues in other configurations. If I recall it was different versions of Node and testing configurations that were failing. So, we opted for the current configuration we have. That decision was almost a year ago, so the details are a bit fuzzy in my mind. It's something we can certainly revisit but we want to be careful about it because the change could have other unintended consequences.

**Comment by MarcSkovMadsen** [comment]
Thanks @EisenbergEffect . This is a bit outside my domain of expertise. But i hope there will be a solution. I’m working on getting a Fast Template into Panel. The natural step after that is to begin building custom Fast components.
