### ISSUE TITLE
[BUG]Bokeh Client does not establish connection with server with self signed certificates

### ISSUE THREAD

**Issue by alucab** [bokeh/bokeh#10866]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 2.2.3
python 3.9.1
windows 10
#### Description of expected behavior and the observed behavior
I try to establish a session through the client pull_session to a bokeh server launched with self signed certificates
I would expect to establish the session, but the client fails. 
I'm trying this as i'm trying to embed bokeh in flask and i want flask/bokeh to terminate the ssl 
I know it's not good for production but it is VERY better for testing.
SSL termination is required to interact with external authentication services like Auth0, so if you want to experiment with Auth0 locally you need an SSL. 
I think it's also useful in other contexts.
I think the issue is that the HTTPClient in the Bokeh Client doesn't catch the exception launched when ssl sees the self signed certificate, when i connect from browser the connection works well, if i try from curl without -k breaks

#### Complete, minimal, self-contained example code that reproduces the issue
SERVER
python -m bokeh serve --allow-websocket-origin=* --use-xheaders --ssl-certfile easypcr-localhost.cert --ssl-keyfile easypcr-localhost.key --log-level debug ..\\samples_explorerpython -m bokeh serve --allow-websocket-origin=* --use-xheaders --ssl-certfile easypcr-localhost.cert --ssl-keyfile easypcr-localhost.key --log-level debug ..\\samples_explorer

```
#tried with or without this
ssl._create_default_https_context = ssl._create_unverified_context
#--------------------------------------------------------

BOKEH_URL='https://localhost:5006/samples_explorer'

incoming_session_id = "abcdef" 
filename = 'V9NJQODGRQMQIUC78W70'
session = pull_session( url=BOKEH_URL,arguments=dict(filename=filename,incoming_session_id=incoming_session_id))
# generate a script to load the customized session
bokeh_script = server_session(session_id=session.id, url=BOKEH_URL )

```

#### Stack traceback and/or browser JavaScript console output
CLIENT:
Traceback (most recent call last):
  File "c:\DDCT\server\samples_explorer\test_bokeh_client.py", line 66, in <module>
    session = pull_session( url=BOKEH_URL,arguments=dict(filename=filename,incoming_session_id=incoming_session_id))
  File "C:\Users\lbarba\AppData\Local\Programs\Python\Python39\lib\site-packages\bokeh\client\session.py", line 120, in pull_session
    session.pull()
  File "C:\Users\lbarba\AppData\Local\Programs\Python\Python39\lib\site-packages\bokeh\client\session.py", line 381, in pull
    self.check_connection_errors()
  File "C:\Users\lbarba\AppData\Local\Programs\Python\Python39\lib\site-packages\bokeh\client\session.py", line 369, in check_connection_errors
    raise OSError("We failed to connect to the server (to start the server, try the 'bokeh serve' command)")
OSError: We failed to connect to the server (to start the server, try the 'bokeh serve' command)

SERVER
2021-01-24 11:39:04,562 SSL Error on 2572 ('127.0.0.1', 54888): [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1123)
2021-01-24 11:39:09,231 [pid 19848] 1 clients connected

**Comment by bryevdv** [comment]
@alucab I think I'd be OK with adding support for this, but I also think it might be preferable for it to be activated behind a flag, e.g. something like:
```
bokeh serve app.py --accept-self-signed
```
to enable it. 

Would you like to work on a PR for this? The changes would be purely Python-side (so more accessible) and we would be happy to provide guidance.

**Comment by alucab** [comment]
Sorry for the late answer.
In principle yes, I never looked the core code before looking for this so I am not very expert on compiling the library etc... 

Have you got any guidelines on how to develop/build/compile?

**Comment by mustafasoylu** [comment]
I'm having some trouble with this issue, and it's making development and deployment more complicated than it needs to be. Can you help me out with a fix?

**Comment by mustafasoylu** [comment]
Can you provide an update on the status of this matter?

**Comment by bryevdv** [comment]
@mustafasoylu There is no update. No one has yet decided to work this. As with all OSS projects, any updates will be in the issue, so there is never really any reason to ask explicitly.

**Comment by bryevdv** [comment]
@alucab I am not sure if you would still be interested, your question seems to have slipped through the cracks. But just in case, dev guide is here: https://docs.bokeh.org/en/latest/docs/dev_guide.html
