### ISSUE TITLE
[BUG] hbar_stack example in documentation does not work

### ISSUE THREAD

**Issue by markgras** [bokeh/bokeh#10906]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
OS: Windows 10 64-bit
bokeh: 2.2.3
python: 3.6.8 64-bit

#### Description of expected behavior and the observed behavior
The hbar_stack example in [the documentation](https://docs.bokeh.org/en/latest/docs/reference/plotting.html#bokeh.plotting.Figure.hbar_stack) is incorrect and does not work when run. It is an exact copy of the [vbar_stack example](https://docs.bokeh.org/en/latest/docs/reference/plotting.html#bokeh.plotting.Figure.vbar_stack) on the same web page. Changing the hbar `x` keyword argument to `y` fixes the problem.

#### Complete, minimal, self-contained example code that reproduces the issue
The documentation example is not self-contained, so here is an expanded version:
```
from bokeh.io import show
from bokeh.models import ColumnDataSource
from bokeh.plotting import Figure


source = ColumnDataSource({
    '2016': [2],
    '2017': [4],
})
p = Figure()
p.hbar_stack(['2016', '2017'], x=10, width=0.9, color=['blue', 'red'], source=source)
show(p)

```

#### Stack traceback and/or browser JavaScript console output
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    p.hbar_stack(['2016', '2017'], x=10, width=0.9, color=['blue', 'red'], source=source)
  File "C:\Users\markgras\Desktop\venvs\test36\lib\site-packages\bokeh\plotting\figure.py", line 1283, in hbar_stack
    result.append(self.hbar(**kw))
  File "C:\Users\markgras\Desktop\venvs\test36\lib\site-packages\bokeh\plotting\_decorators.py", line 54, in wrapped
    return create_renderer(glyphclass, self, **kwargs)
  File "C:\Users\markgras\Desktop\venvs\test36\lib\site-packages\bokeh\plotting\_renderer.py", line 118, in create_renderer
    glyph=make_glyph(glyphclass, kwargs, glyph_visuals),
  File "C:\Users\markgras\Desktop\venvs\test36\lib\site-packages\bokeh\plotting\_renderer.py", line 140, in make_glyph
    return glyphclass(**kws)
  File "C:\Users\markgras\Desktop\venvs\test36\lib\site-packages\bokeh\model.py", line 235, in __init__
    super().__init__(**kwargs)
  File "C:\Users\markgras\Desktop\venvs\test36\lib\site-packages\bokeh\core\has_props.py", line 249, in __init__
    setattr(self, name, value)
  File "C:\Users\markgras\Desktop\venvs\test36\lib\site-packages\bokeh\core\has_props.py", line 286, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))
AttributeError: unexpected attribute 'x' to HBar, possible attributes are fill_alpha, fill_color, hatch_alpha, hatch_color, hatch_extra, hatch_pattern, hatch_scale, hatch_weight, height, js_event_callbacks, js_property_callba
cks, left, line_alpha, line_cap, line_color, line_dash, line_dash_offset, line_join, line_width, name, right, subscribed_events, tags or y

```

**Comment by bryevdv** [comment]
Thanks for the catch @markgras would you like to submit the PR to fix the docs? The line in question is here:


https://github.com/bokeh/bokeh/blob/b85c299ceb7ae4f51eff19cbbc43bcd89805b2de/bokeh/plotting/figure.py#L1307

**Comment by markgras** [comment]
Sure. I'll submit a fix shortly.
