### ISSUE TITLE
[BUG] Stream data with datatypes other than numpy.ndarray or list

### ISSUE THREAD

**Issue by rad83** [bokeh/bokeh#10904]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
python: 3.9.1
bokeh: 2.2.3
numpy: 1.20.0
pandas: 1.2.1

#### Description of expected behavior and the observed behavior
Method ```stream()``` of ```ColunmDataSource``` expect the columns data to be either ```list``` or ```numpy.ndarray```. However if created from Pandas ```DataFrame```, the columns can have different data types. For instance it can be ```pandas.core.arrays.integer.IntegerArray``` or ```pandas.core.arrays.categorical.Categorical```. In both those cases attempt to stream new data to such source will raise ```AttributeError``` complaining about missing ```extend``` attribute (as it expect it to be list).

#### Complete, minimal, self-contained example code that reproduces the issue
```
import pandas as pd
from bokeh.models import ColumnDataSource as CDS

df = pd.DataFrame({'a': [1, 2, 3], 'b': [1, 2, 3], 'c': [1, 2, 3]})
df.b = df.b.astype('Int64')
df.c = df.c.astype('category')

cds = CDS(df)
cds.stream({'index': [3], 'a': [4], 'b': [pd.NA], 'c': [1]})
```

#### Stack traceback and/or browser JavaScript console output
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/bokeh/models/sources.py", line 415, in stream
    self._stream(new_data, rollover)
  File "/usr/lib/python3.9/site-packages/bokeh/models/sources.py", line 527, in _stream
    self.data._stream(self.document, self, new_data, rollover, setter)
  File "/usr/lib/python3.9/site-packages/bokeh/core/property/wrappers.py", line 423, in _stream
    L.extend(new_data[k])
AttributeError: 'IntegerArray' object has no attribute 'extend'
```

#### Code responsible for the streaming
(bokeh/core/property/wrappers.py)
```
def _stream(self, doc, source, new_data, rollover=None, setter=None):
    ...
    for k, v in  new_data.items():
        if isinstance(self[k], np.ndarray) or isinstance(new_data[k], np.ndarray):
            data = np.append(self[k], new_data[k])
            if rollover and len(data) > rollover:
                data = data[-rollover:]
            dict.__setitem__(self, k, data)
        else:
            L = self[k]
            L.extend(new_data[k])
            if rollover is not None:
                del L[:-rollover]
    ...
```

**Comment by bryevdv** [comment]
Some Pandas types are evidently already supported (there are tests) but not all. The code snippet above can probably add another case to handle Pandas types appropriately.

**Comment by K-Monty** [comment]
@bryevdv Hi, I am from #10905. For collaborating on Github, I learned about the basic procedure mostly from https://github.com/K-Monty/first-contributions.

**Comment by BLuchterhand** [comment]
Hi! Looking for a good first contribution. I'm new to this; can I get in on this one?

**Comment by bryevdv** [comment]
@BLuchterhand Great, are you already familiar with Bokeh generally?

**Comment by K-Monty** [comment]
Since BLuchterhand is already interested in this issue, should I go for another one then? For me, I have been using Bokeh this year for my project, and I have developed a small app using it for my research group (I can't put the link here since the research is still on-going, I am sorry)

**Comment by BLuchterhand** [comment]
> @BLuchterhand Great, are you already familiar with Bokeh generally?

I'm not; I found it in a list of repos and found it to be very interesting... I can take this one if you think it's fine, otherwise, if you have a more appropriate first issue I can always take that up!

**Comment by bryevdv** [comment]
@BLuchterhand when I asked that I actually thought you were @K-Monty since I had already just sent them here. In light of that I'd say @K-Monty should take this issue. Without knowing your background it's hard to make specific recommendations, the best thing is usually to look over [good first issues](https://github.com/bokeh/bokeh/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) and see which ones jump out at you.

**Comment by K-Monty** [comment]
@bryevdv Thanks a lot! I had made the first attempt on this issue. Any comment(s) are welcomed.

**Comment by rad83** [comment]
I am not familiar with how bokeh handles data internaly, so it is just a comment.
Feel free to ignor it if it does not make much sense.

What you do is to apply ```numpy.append``` on any pandas column regardless of the actuall data type.
This will always result in ```numpy.array```. It seems that bokeh is using ```pandas.DataFrame.values``` to get the columns from ```DataFrame``` which does keep the original types. Your approach is equivalent more to using ```pandas.DataFrame.to_numpy()``` method, where the data will be always casted to available numpy types (or object if nothing native is available). So the question is, whether we are not loosing something by this casting and if maintaining original types would not be actually better.

Maybe just using pandas append on pandas columns and numpy's append on numpy's arrays would be sufficient.

**Comment by sriakshata** [comment]
Hello, I am trying to figure out the reason behind the casting in the above mentioned code snippet @rad83.
`import pandas as pd
from bokeh.models import ColumnDataSource as CDS

df = pd.DataFrame({'a': [1, 2, 3], 'b': [1, 2, 3], 'c': [1, 2, 3]})
**df.b = df.b.astype('Int64')**
**df.c = df.c.astype('category')**

cds = CDS(df)
cds.stream({'index': [3], 'a': [4], 'b': [pd.NA], 'c': [1]})`

Without casting , it is just working fine.  Please clarify the reason as I might have misunderstood the cause or this issue . I am new to open source contributing so please guide me.

**Comment by rad83** [comment]
@sriakshata
The main purpose of the code sniplet is to demonstrate some inconsistency in data type support. You are allowed to create bokehs ```ColumnDataSource``` from pandas ```DataFrame``` however not all potential pandas data types are actually supported like ```IntegerArrays``` and```CategoricalArrays``` and probably others . That is the main issue here.

To demonstrate that I just needed a quick way to create pandas column with unsupported data type and casting is a simple way how to get one (so the code acts as a minimal working example). And of course in this case, the casting is just silly, however the correct way how to read that example is: "If I call method ```stream``` of ```ColumnDataSource``` object which was created from pandas ```DataFrame``` that contained columns of particular data types (no matter how you got it) it breaks".

**Comment by sriakshata** [comment]
Thank you @rad83  for clarifying with me. I appreciate it. Now, I understand the issue clearly. Yes, it will be nice to have pandas support various datatypes with stream(). I am actually interested in this issue. I will try to look into it.

**Comment by sriakshata** [comment]
Hello @rad83 , I can see that there has been a lot of progress on this issue. Is there a chance I work on this issue as most of it has already been done by @K-Monty. I guess the work is in progress, so this issue is open. Please let me know.

**Comment by rad83** [comment]
@sriakshata

Here is the thing. @K-Monty  indeed did some work on this issue, but as far as I know, he never finished it and it was eventually closed. So I beleive you can/should start over. If you follow this pull request [https://github.com/bokeh/bokeh/pull/10955](https://github.com/bokeh/bokeh/pull/10955#) (which you are probably already familiar with) you will find some suggestions that might be helpful.

I think there are two reasons why this was not finished. First, it requires some _political_ decisions on what to do if different data types are mixed. And second, it is not just this single ```stream()``` method that should be corrected/expanded but ideally also some additional parts of ```ColumnDataSource``` object, most probably including constructor and some other methods (```patch()```, ```add()```). I wanted to do it myself, but I was kinda lost in the level of abstraction they using and did not feel comfortable enough to touch it. Also it requires (or at least it is beneficial to have) some knowledge on Pandas and NumPy.

**Comment by bryevdv** [comment]
This seems to have been fixed at some point, the OP code no longer generates any errors
