### ISSUE TITLE
pip install -e raises exception

### ISSUE THREAD

**Issue by MarcSkovMadsen** [bokeh/bokeh#11177]
- I have followed the [dev-guide](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html#devguide-setup) and have a working version of the git repository.
- I have checked OUT `branch-2.4` under the new name `suburls` as I intend to contribute to https://github.com/bokeh/bokeh/issues/9671. I have also made the changes suggested by Bryan to the bokeh/server/tornado.py file.
- When I want to try the changes manually in my `awesome-panel` repository I would like to do this by running `pip install -e ABSOLUTEPATH/.` or similar. But this fails

```bash
$ pip install -e C:/repos/private/bokeh/.
Obtaining file:///C:/repos/private/bokeh
    ERROR: Command errored out with exit status 1:
     command: 'c:\repos\private\awesome-panel\.venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\repos\\private\\bokeh\\setup.py'"'"'; __file__='"'"'C:\\repos\\private\\bokeh\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\masma\AppData\Local\Temp\1\pip-pip-egg-info-g6d6vwf7'
         cwd: C:\repos\private\bokeh\
    Complete output (16 lines):

    Bokeh includes a JavaScript library (BokehJS) that has its own
    build process. How would you like to handle BokehJS:

      File "<string>", line 1, in <module>
      File "C:\repos\private\bokeh\setup.py", line 86, in <module>
        bokehjs_action = build_or_install_bokehjs()
      File "C:\repos\private\bokeh\_setup_support.py", line 138, in build_or_install_bokehjs
        jsbuild = jsbuild_prompt()
      File "C:\repos\private\bokeh\_setup_support.py", line 225, in jsbuild_prompt
        value = input("Choice? ")  # lgtm [py/use-of-input]
    EOFError: EOF when reading a line
    ----------------------------------------
WARNING: Discarding file:///C:/repos/private/bokeh. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 21.0; however, version 21.0.1 is available.
You should consider upgrading via the 'c:\repos\private\awesome-panel\.venv\scripts\python.exe -m pip install --upgrade pip' command.
```

**Comment by bryevdv** [comment]
`pip -e` is never going to be workable, because of the need to build BokehJS which requires an extensive JS toolchain that is not common to typical Python projects.

**Comment by MarcSkovMadsen** [comment]
How would I try it out in other projects then?

**Comment by bryevdv** [comment]
@MarcSkovMadsen I don't understand the question. You could run `python setup.py develop ` in as many env as you need. `python setup.py install` is also an option. Again with `--build-js` or `--install-js` as appropriate.

**Comment by MarcSkovMadsen** [comment]
I tried running `python setup.py install --install-js` in my other repository/ virtual environment. But when I run `pip show bokeh` it shows nothing. So I assumed it was not installed. Thus my reasoning is that I need to do `pip install -e PATH/.` to get bokeh installed.

**Comment by MarcSkovMadsen** [comment]
By changing the below line

![image](https://user-images.githubusercontent.com/42288570/115134670-77851d00-a012-11eb-9ab1-8a9255e8c2ce.png)

I can get `pip install -e ` working (I think).

```bash
$ pip install -e C:/repos/private/bokeh/.
Obtaining file:///C:/repos/private/bokeh
Requirement already satisfied: Jinja2>=2.7 in c:\repos\private\awesome-panel\.venv\lib\site-packages (from bokeh===2.3.0-77-g187803263-dirty) (2.11.2)
Requirement already satisfied: numpy>=1.11.3 in c:\repos\private\awesome-panel\.venv\lib\site-packages (from bokeh===2.3.0-77-g187803263-dirty) (1.20.1)
Requirement already satisfied: packaging>=16.8 in c:\repos\private\awesome-panel\.venv\lib\site-packages (from bokeh===2.3.0-77-g187803263-dirty) (20.4)
Requirement already satisfied: pillow>=7.1.0 in c:\repos\private\awesome-panel\.venv\lib\site-packages (from bokeh===2.3.0-77-g187803263-dirty) (7.1.0)
Requirement already satisfied: PyYAML>=3.10 in c:\repos\private\awesome-panel\.venv\lib\site-packages (from bokeh===2.3.0-77-g187803263-dirty) (5.3.1)
Requirement already satisfied: tornado>=5.1 in c:\repos\private\awesome-panel\.venv\lib\site-packages (from bokeh===2.3.0-77-g187803263-dirty) (5.1.1)
Requirement already satisfied: typing_extensions>=3.7.4 in c:\repos\private\awesome-panel\.venv\lib\site-packages (from bokeh===2.3.0-77-g187803263-dirty) (3.7.4.2)
Requirement already satisfied: MarkupSafe>=0.23 in c:\repos\private\awesome-panel\.venv\lib\site-packages (from Jinja2>=2.7->bokeh===2.3.0-77-g187803263-dirty) (1.1.1)
Requirement already satisfied: pyparsing>=2.0.2 in c:\repos\private\awesome-panel\.venv\lib\site-packages (from packaging>=16.8->bokeh===2.3.0-77-g187803263-dirty) (2.4.7)
Requirement already satisfied: six in c:\repos\private\awesome-panel\.venv\lib\site-packages (from packaging>=16.8->bokeh===2.3.0-77-g187803263-dirty) (1.14.0)
Installing collected packages: bokeh
  Running setup.py develop for bokeh
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
panel 0.11.3 requires bokeh<2.4.0,>=2.3.0, but you have bokeh 2.3.0-77-g187803263-dirty which is incompatible.
panel-highcharts 20210403.1.2 requires bokeh==2.3, but you have bokeh 2.3.0-77-g187803263-dirty which is incompatible.
jupyter-bokeh 2.0.0 requires bokeh>=2.0.0, but you have bokeh 2.3.0-77-g187803263-dirty which is incompatible.
ipywidgets-bokeh 1.0.2 requires bokeh>=2.0.1, but you have bokeh 2.3.0-77-g187803263-dirty which is incompatible.
hvplot 0.7.1 requires bokeh>=1.0.0, but you have bokeh 2.3.0-77-g187803263-dirty which is incompatible.
awesome-panel-extensions 20210326.3 requires bokeh==2.3, but you have bokeh 2.3.0-77-g187803263-dirty which is incompatible.
Successfully installed bokeh
WARNING: You are using pip version 21.0; however, version 21.0.1 is available.
You should consider upgrading via the 'c:\repos\private\awesome-panel\.venv\scripts\python.exe -m pip install --upgrade pip' command.
(.venv) 
```

**Comment by bryevdv** [comment]
@MarcSkovMadsen It does not, in fact, work in general. You have not installed a locally built BokehJS. Coincidentally, you don't need to work on or evaluate any BokehJS changes, so the fact that Bokeh will use the last released CDN version of BokehJS means that you just have not noticed this fact. But anyone who does need to work on BokehJS would be met with silent and confusing problems. That's arguably a worse situation. 

This  build system has been in place for nearly 10 years. The reasons for why things are the way they are are very well-established, and what we have not represents the best compromises we can settle on.

**Comment by MarcSkovMadsen** [comment]
@bryevdv . I think we are misunderstanding each other.

When working with the bokeh directory directly I can do everything you say and it works perfectly.

But when I want to work with the `awesome-panel` repository and my bokeh branch I need to get it installed in another virtual environment. And running `python setup.py install --install-js` does work as you can see below.

```bash
$ pip show bokeh
WARNING: Package(s) not found: bokeh
(.venv)
MASMA@PC81978 MINGW64 /c/repos/private/awesome-panel (master)
$ python 'C:\repos\private\bokeh\setup.py' --install-js
(.venv) 
MASMA@PC81978 MINGW64 /c/repos/private/awesome-panel (master)
$ panel serve 'application\pages\custom_bokeh_model\custom_bokeh_model.py' --auto --show
Traceback (most recent call last):
  File "C:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\repos\private\awesome-panel\.venv\Scripts\panel.exe\__main__.py", line 4, in <module>
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\__init__.py", line 1, in <module>
    from . import layout # noqa
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\layout\__init__.py", line 1, in <module>
    from .accordion import Accordion # noqa
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\layout\accordion.py", line 3, in <module>
    from bokeh.models import Column as BkColumn, CustomJS
ModuleNotFoundError: No module named 'bokeh'
(.venv) 
```

**Comment by bryevdv** [comment]
@MarcSkovMadsen I am afraid I don't know how to advise you any further. I haven't used a non-Anaconda env since 2012. You might consider building an sdist instead, and pip installing the local sdist file 
```
python setup.py sdist --build-js
```

**Comment by MarcSkovMadsen** [comment]
Thanks @bryevdv . I have something I believe will be working. For developing bokeh I can follow exactly what the bokeh dev-guide says. For manual testing in my other repository this works https://github.com/bokeh/bokeh/issues/11177#issuecomment-821932457.
