### ISSUE TITLE
examples' tests fail in CI

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#11319]
They fail with:
```
tests/test_examples.py::test_file_examples[/home/runner/work/bokeh/bokeh/examples/models/file/anscombe.py-example0-config0] 
[INFO] Example run in 0.662s
[FAIL] Unhandled rejection at:  ProtocolError: Invalid parameters (Failed to deserialize params.clip.width - BINDINGS: double value expected at position 42)
    at /home/runner/work/bokeh/bokeh/bokehjs/node_modules/chrome-remote-interface/lib/chrome.js:94:35
    at Chrome._handleMessage (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/chrome-remote-interface/lib/chrome.js:257:17)
    at WebSocket.<anonymous> (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/chrome-remote-interface/lib/chrome.js:235:22)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/ws/lib/websocket.js:834:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/ws/lib/receiver.js:437:14)
    at /home/runner/work/bokeh/bokeh/bokehjs/node_modules/ws/lib/receiver.js:394:23
    at /home/runner/work/bokeh/bokeh/bokehjs/node_modules/ws/lib/permessage-deflate.js:308:9
    at /home/runner/work/bokeh/bokeh/bokehjs/node_modules/ws/lib/permessage-deflate.js:391:7 {
  request: {
    method: 'Page.captureScreenshot',
    params: { format: 'png', clip: [Object] },
    sessionId: undefined
  },
  response: {
    code: -32602,
    message: 'Invalid parameters',
    data: 'Failed to deserialize params.clip.width - BINDINGS: double value expected at position 42'
  }
}
```
This is most likely due to upgraded Chrome and possible API breakage. Though I'm not able to reproduce this locally for now.

**Comment by mattpap** [comment]
Looks like they installed a buggy pre-release version of Chrome in Actions.

We may want to investigate a project like https://github.com/browser-actions/setup-chrome as a basis for tightly controlling the version of Chrome installed in tests and update it when we want to, not when we're forced to.

**Comment by mattpap** [comment]
I worked around the bug, but baselines need updating and they differ significantly between pre-release and stable versions of Chrome.
