### ISSUE TITLE
BokehJS build failing in release CI

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11981]
@mattpap any ideas? The build linked below failed (even though the UI reports "success", I will look at that separately...)

ref: https://github.com/bokeh/bokeh/runs/4960578378?check_suite_focus=true

```
------ Starting task build_bokehjs
+cd bokehjs # [now: /home/runner/work/bokeh/bokeh/bokehjs]
+node make
[FAIL] BokehJS build did NOT succeed
    make/tasks/lint.ts(36,31): error TS2339: Property 'trim' does not exist on type 'string | Promise<string>'.
      Property 'trim' does not exist on type 'Promise<string>'.
    
    [02:08:47] Starting 'styles:compile'...
    [02:08:47] Finished 'styles:compile' after 252 ms
    [02:08:47] Starting 'scripts:styles'...
    [02:08:47] Finished 'scripts:styles' after 58 ms
    [02:08:47] Starting 'scripts:glsl'...
    [02:08:47] Finished 'scripts:glsl' after 5 ms
    [02:08:47] Starting 'scripts:version'...
    [02:08:47] Finished 'scripts:version' after 1 ms
    [02:08:47] Starting 'scripts:compile'...
    [02:09:10] Finished 'scripts:compile' after 22.53 s
    [02:09:10] failed: There were 3 TypeScript errors:
    error TS2688: Cannot find type definition file for 'hammerjs'.
      The file is in the program because:
        Entry point of type library 'hammerjs' specified in compilerOptions
    src/lib/models/widgets/multichoice.ts:1:21 - error TS7016: Could not find a declaration file for module 'choices.js'. '/home/runner/work/bokeh/bokeh/bokehjs/node_modules/choices.js/public/assets/scripts/choices.js' implicitly has an 'any' type.
      Try `npm i --save-dev @types/choices.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'choices.js';`
    
    1 import Choices from "choices.js"
                          ~~~~~~~~~~~~
    src/lib/models/widgets/multichoice.ts:2:36 - error TS7016: Could not find a declaration file for module 'choices.js'. '/home/runner/work/bokeh/bokeh/bokehjs/node_modules/choices.js/public/assets/scripts/choices.js' implicitly has an 'any' type.
      Try `npm i --save-dev @types/choices.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'choices.js';`
    
    2 import {Choices as ChoicesNS} from "choices.js"
                                         ~~~~~~~~~~~~
    
    [02:09:10] Starting 'scripts:bundle'...
    [02:10:00] Finished 'scripts:bundle' after 50.32 s
    [02:10:00] Finished 'lib:build'
    [02:10:00] Finished 'scripts:build'
    [02:10:00] Starting 'compiler:ts'...
    [02:10:02] Finished 'compiler:ts' after 2.39 s
    [02:10:02] failed: There were 1 TypeScript errors:
    src/compiler/build.ts:96:31 - error TS2339: Property 'trim' does not exist on type 'string | Promise<string>'.
      Property 'trim' does not exist on type 'Promise<string>'.
    
    96     for (const line of output.trim().split("\n"))
                                     ~~~~
    
    [02:10:02] failed: There were 1 TypeScript errors:
    src/compiler/build.ts:96:31 - error TS2339: Property 'trim' does not exist on type 'string | Promise<string>'.
      Property 'trim' does not exist on type 'Promise<string>'.
    
    96     for (const line of output.trim().split("\n"))
                                     ~~~~
    
    [02:10:02] failed: task 'top-level' failed because 'compiler:ts' failed
    [02:10:02] failed: task 'top-level' failed because 'compiler:ts' failed
    [02:10:02] failed: task 'top-level' failed because 'compiler:build' failed
    [02:10:02] failed: task 'top-level' failed because 'compiler:build' failed
    [02:10:02] failed: task 'top-level' failed because 'compiler:build' failed
    [02:10:02] failed: task 'top-level' failed because 'build' failed
    [02:10:02] failed: task 'top-level' failed because 'build' failed
    [02:10:02] failed: task 'top-level' failed because 'build' and 'install' failed
    [02:10:02] failed: task 'top-level' failed because 'build' and 'install' failed
    [02:10:02] failed: task 'top-level' failed because 'default' failed
    [02:10:02] failed: task 'top-level' failed because 'default' failed
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/bk-release-build/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/share/miniconda3/envs/bk-release-build/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/bokeh/bokeh/release/__main__.py", line 32, in <module>
    steps.execute()
  File "/home/runner/work/bokeh/bokeh/release/pipeline.py", line 60, in execute
    self._system.abort()
  File "/home/runner/work/bokeh/bokeh/release/system.py", line 51, in abort
    raise RuntimeError()
RuntimeError
```

**Comment by bryevdv** [comment]
Well the build job is not reporting failure because of this `|| true`` in the workflow definition

https://github.com/bokeh/bokeh/blob/e94b49ba7df0004127060acf56ea3d52412fba9d/.github/workflows/bokeh-release-build.yml#L63

I'm guess it was something left over from previous debugging. Let's remove that with whatever fix goes in for BokehJS build

**Comment by bryevdv** [comment]
Well I re-ran an earlier test CI build and it still works so there must be an actual different between that and what's done in https://github.com/bokeh/bokeh/blob/branch-3.0/.github/workflows/bokeh-release-build.yml but I don't see it offhand.

**Comment by mattpap** [comment]
bokehjs build failures are a result of `package-lock.json` being disrespected one way or another. I will upgrade outdated dependencies in an unrelated PR, but whatever is going on with package locking need to be resolved, because this will happen again sooner than later.

**Comment by mattpap** [comment]
I don't see how this can fail like this. If `package-lock.json` was missing or broken, `npm ci` would fail. If `npm install` was run before `npm ci`, then this could be only partially reproduced (choices.js wouldn't be updated). The hammerjs part is completely bizarre, as I can't reproduce it after upgrading all packages. btw. I submitted PR #11982, but as I said before, this issue needs to be resolved regardless.

**Comment by mattpap** [comment]
We need `npm --version` after `npm install -g npm`.

**Comment by bryevdv** [comment]
@mattpap I added in https://github.com/bokeh/bokeh/compare/19d1caa97d08...d0a7791b4ff6

**Comment by bryevdv** [comment]
Fixed by your recent PR and the commit above
