### ISSUE TITLE
[BUG] Bokeh doesn't wait until all scripts loaded before embedding document in jupyter notebook

### ISSUE THREAD

**Issue by stas-sl** [bokeh/bokeh#12023]
### Software versions

Python version : 3.9.7 (default, Sep 16 2021, 08:50:36)
IPython version : 7.31.1
Tornado version : 6.1
Bokeh version : 2.4.2
BokehJS static path : /Users/stas/.pyenv/versions/anaconda3-2021.11/lib/python3.9/site-packages/bokeh/server/static
node.js version : v17.4.0
npm version : 8.3.1
Operating system : macOS-10.15.7-x86_64-i386-64bit

### Browser name and version

Version 98.0.4758.102 (Official Build) (x86_64) 

### Jupyter notebook / Jupyter Lab version

jupyterlab : 3.2.9

### Expected behavior

Bokeh waits until all scripts loaded and displays widgets correctly.

### Observed behavior

I'm using bokeh widgets and convert jupyter notebook to html using command:
```bash
jupyter nbconvert bug.ipynb --to html
```
What I observed is that if I disable script caching and try to load resulting html page I get the following error `Model 'Slider' does not exist. This could be due to a widget or a custom model not being registered before first usage.`.

 It looks like Bokeh calls embed_document before all scripts (including widgets) are loaded and that is why this error occurs.

https://github.com/bokeh/bokeh/blob/ca239b9a92605710f4ea6681da29696979d98824/bokeh/core/_templates/try_run.js#L11-L14

Maybe an additional condition should be added here?

```javascript
 if (root.Bokeh !== undefined && root._bokeh_is_loading === 0) { 
```

Though with caching enabled or if I use `output_notebook(resources=INLINE)` it works fine.

### Example code

```Python
from bokeh.plotting import output_notebook, show
from bokeh.models import Slider

output_notebook()

show(Slider(value=0, start=0, end=10))
```

### Stack traceback or browser console output

Uncaught Error: Model 'Slider' does not exist. This could be due to a widget or a custom model not being registered before first usage.
    at _.get (bokeh-2.4.2.min.js:166:1015)
    at Function._instantiate_object (bokeh-2.4.2.min.js:165:4956)
    at Function._instantiate_references_json (bokeh-2.4.2.min.js:165:5144)
    at Function.from_json (bokeh-2.4.2.min.js:165:8794)
    at Object.t.embed_items_notebook (bokeh-2.4.2.min.js:591:2451)
    at embed_document (test_bokeh_load.html:14931:20)
    at test_bokeh_load.html:14941:9

### Screenshots

https://user-images.githubusercontent.com/4602302/155892308-f8e1cbdd-f039-4bbd-9e4f-65cefc937522.mp4

**Comment by bryevdv** [comment]
@mattpap Do you have input? Offhand it seems like the suggestion above would work, but it would couple two templates to the private `_bokeh_is_loading` variable, which does not seem very clean.
