### ISSUE TITLE
Trying to start bokeh server on EC2 Public DNS URL and getting Runtime Error Crash

### ISSUE THREAD

**Issue by robbyki** [bokeh/bokeh#1207]
Trying to test out bokeh plot server on Ubuntu 14.01 Trusty with Bokeh v.6.0 and trying to just serve up the plots on my ec2 public dns url such as: https://publicdns.compute-1.amazonaws.com but when I do `bokeh-server --ip https://publicdns.compute-1.amazonaws.com` it seems to start the server but then a few seconds later crashes with below runtime error. I have also made 5006 available as an inbound in my ec2 configuration. I also tried `bokeh-server --ip 0.0.0.0` but although that successfully launches server when I execute a plot and then navigate to `https://publicdns.compute-1.amazonaws.com:5006/bokeh` I can see it interacting with the server but I get a lot of errors and invalid HTTP method responses.

          Bokeh Server Configuration
    ==========================
    python version : 2.7.8
    bokeh version  : 0.6.0
    listening      : https://publicdns.compute-1.amazonaws.com:5006
    backend        : shelve
    python options : debug:OFF, verbose:OFF, filter-logs:OFF, multi-user:OFF
    js options     : splitjs:OFF, debugjs:OFF
    data-directory : None

    zmqpub starting

    Starting Bokeh plot server on port 5006...
    View http://https://publicdns.compute-1.amazonaws.com:5006/bokeh to see plots

    Traceback (most recent call last):
      File "/home/ubuntu/anaconda/bin/bokeh-server", line 7, in <module>
        bokeh.server.run()
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/bokeh/server/__init__.py", line 208, in run
        start_server(args)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/bokeh/server/__init__.py", line 239, in start_server
        start.start_app(host=args.ip, port=args.port, verbose=args.verbose)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/bokeh/server/start.py", line 165, in start_app
        http_server.serve_forever()
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/gevent/baseserver.py", line 282, in serve_forever
        self.start()
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/gevent/baseserver.py", line 234, in start
        self.init_socket()
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/gevent/pywsgi.py", line 639, in init_socket
        StreamServer.init_socket(self)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/gevent/server.py", line 78, in init_socket
        self.socket = self.get_listener(self.address, self.backlog, self.family)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/gevent/server.py", line 89, in get_listener
        return _tcp_listener(address, backlog=backlog, reuse_addr=self.reuse_addr, family=family)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/gevent/server.py", line 153, in _tcp_listener
        sock.bind(address)
      File "<string>", line 1, in bind
    socket.gaierror: [Errno -3] Temporary failure in name resolution: ('https://publicdns.compute-1.amazonaws.com', 5006)
    stop services
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
        func(*targs, **kargs)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/bokeh/server/start.py", line 155, in stop_services
        bokeh_app.subscriber.stop()
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/bokeh/server/websocket.py", line 65, in stop
        self.subscriber.thread.join()
      File "/home/ubuntu/anaconda/lib/python2.7/threading.py", line 938, in join
        raise RuntimeError("cannot join thread before it is started")
    RuntimeError: cannot join thread before it is started
    Error in sys.exitfunc:
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
        func(*targs, **kargs)
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/bokeh/server/start.py", line 155, in stop_services
        bokeh_app.subscriber.stop()
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/bokeh/server/websocket.py", line 65, in stop
        self.subscriber.thread.join()
      File "/home/ubuntu/anaconda/lib/python2.7/threading.py", line 938, in join
        raise RuntimeError("cannot join thread before it is started")
    RuntimeError: cannot join thread before it is started

**Comment by kyzyl** [comment]
@bryevdv FWIW (after all this time) I resolved this issue on 0.81 by running the bokeh-server with the actual NIC IP (--ip=<ip from ifconfig>) on each EC2 node and then navigating to the public domain/IP to see the server output. Seems to be working, but I can't say much as to how robust it is to ephemeral changes in Amazon's infrastructure and the like.

**Comment by bryevdv** [comment]
@kyzyl thanks for the update, coming up with standard deployment instructions for several different scenarios is high on my priority list for the next major release, so this information is useful. Of course, we should also investigate whether there is some better way or changes needed to support a better way.
