### ISSUE TITLE
[FEATURE] Provide API for accessing callbacks registered to a widget

### ISSUE THREAD

**Issue by lunarspectrum** [bokeh/bokeh#12345]
### Problem description

If one wants to temporarily inhibit callbacks on a widget, the callbacks need to be removed and then added back. The current method of removing an `on_change` callback is to use `remove_on_change(attr)`. However, the latter method does not return the callback that was removed, so if a user wants to add the callback again, knowledge of what callback to put back must come from elsewhere. 

For more, see [this Discourse thread](https://discourse.bokeh.org/t/boomerang-update-avoidance/9506) 

### Feature description

Add a return value to `remove_on_change`

### Potential alternatives

Add a public interface for `widget._callbacks` (e.g. a property getter).

**Comment by bryevdv** [comment]
Tentatively triaging as `feature`. Having `remove_on_change` return the callback seems like it would be a minimal isolated change that does provide utility. FYI @lunarspectrum if you'd like to submit a PR, chances are you might get to it quicker than anyone else.

**Comment by benrussell80** [comment]
I might be missing something here, but doesn't `remove_on_change` require passing both the attr and the callback itself?

Edit: example code. @bryevdv `remove_on_change` requires the callback(s) to be passed. It could be possible for the function to return a list of functions removed but the caller must have a reference to them in order to remove them anyway so this seems superfluous.

```py
from bokeh.plotting import show
from bokeh.models import Slider, CustomJS
from bokeh.layouts import row


slider = Slider(start=0, end=100, value=50, step=10)
cb = CustomJS(code='''
console.log(this.value);
''')
slider.js_on_change('value', cb)
slider.remove_on_change('value')  # <- error occurs here

layout = row([slider])
show(layout)
```

Traceback:
```
Traceback (most recent call last):
  File "/home/ben/Projects/bokeh/test_cb.py", line 19, in <module>
    main()
  File "/home/ben/Projects/bokeh/test_cb.py", line 12, in main
    slider.remove_on_change('value')
  File "/home/ben/Projects/bokeh/src/bokeh/util/callback_manager.py", line 163, in remove_on_change
    raise ValueError("remove_on_change takes an attribute name and one or more callbacks, got only one parameter")
ValueError: remove_on_change takes an attribute name and one or more callbacks, got only one parameter
```
Specifically addressing the issue
> if a user wants to add the callback again, knowledge of what callback to put back must come from elsewhere.
The user already needs to specify which callback they are removing. Adding and removing take the same amount of orchestration.

**Comment by harshithakolipaka** [comment]
hello, I would like to work on this issue. Could you @lunarspectrum @bryevdv please help me know in which file do we have the code for the remove_on_change function?

**Comment by lunarspectrum** [comment]
I believe the places to look that may require attention to get consistent behavior will be:

`/src/bokeh/util/callback_manager.py`  (probably the main one?)
`/src/bokeh/document/callbacks.py`
`/src/bokeh/document/document.py`

These were found by searching `def remove_on_change` in the repository.

**Comment by bryevdv** [comment]
Thanks @lunarspectrum I agree those are the main relevant files (there will also be some related test files to update)

**Comment by bryevdv** [comment]
@lunarspectrum I do think @benrussell80 has a point to consider. In order to call `remove_on_change` in the first place, you have to have a reference to the callback you want to remove to pass to it. Can you elaborate on why `remove_on_change` needs to return a reference to the callback that you already have right there? 

edit: re-triaging to `discussion` for now

**Comment by lunarspectrum** [comment]
@bryevdv, oh!  @benrussell80 is correct here that this doesn't solve the problem that I had been hoping to solve, which was to temporarily suppress `on_change` callbacks by removing them, executing some code, and adding them back, without having to keep track of them externally during any time other than execution of this small block of code. If one still wanted to implement a feature that would allow that, the solution suggested in under **Potential alternatives** above would still work. 

However, I dug into my old code and into the discourse thread from before putting in this issue. I think the entire source of this problem was that I used `on_change` to assign callbacks to a toggle instead of `on_click`, and then needed to suppress boomerang updates when the model was updated by something other than bokeh and executed a command to change the toggle state to synchronize with the model state. 

If it's correct that the problem goes away when using `on_click`, then even the alternate solution can be categorized as a solution in search of a problem, and this can be closed! 

Sorry for the confused feature request, and thank you both!
