### ISSUE TITLE
[BUG] Cannot terminate busy pool processes in Bokeh app

### ISSUE THREAD

**Issue by TheoMathurin** [bokeh/bokeh#12452]
### Software versions

Python: 3.9.7
Bokeh version: 2.4.3
Operating systems: Linux (Fedora 36, RHEL7, Ubuntu 18.04)

### Expected behavior

In my application I have to put a timeout on a pool of processes executing jobs in parallel so that it is terminated if it takes too long. It works fine in a standalone script.

### Observed behavior

In a Bokeh app the pool fails to terminate. The issue is serious because the main process hangs so that the app not only becomes unresponsive in the current session but cannot serve new sessions. The only solution it seems is to restart the server.

The minimal example provided works as expected when executed directly, but blocks at `p.terminate()` in the context of a Bokeh app (see output). The two processes that are still busy when `p.terminate()` is reached are not terminated (they fail to join in the [_terminate_pool](https://github.com/python/cpython/blob/3.9/Lib/multiprocessing/pool.py#L678) function of multiprocessing's pool.py module).

I do not think it's a usage issue or a misuse of python's multiprocessing but my apologies if it turns out that it is.

Note: originally filed an issue [in Panel](https://github.com/holoviz/panel/issues/3938) but it's not related to Panel itself. I hope it's not a consequence that is inherent to the implementation of Bokeh server.

### Example code

```Python
import multiprocessing as mp
import time
import os
from bokeh.io import curdoc
from bokeh.models import Button


def task(num):
    print('Start', os.getpid(), num)
    time.sleep(num)
    print('End', os.getpid(), num)


def callback(new):

    p = mp.Pool(processes=4)
    res = p.map_async(task, [1, 2, 3, 4])
    try:
        res.get(timeout=2.5)
    except mp.context.TimeoutError:
        print('Timeout')
    p.terminate()
    print('Pool terminated')


button = Button()
button.on_click(callback)

curdoc().add_root(button)

if __name__ == '__main__':
    callback()
```

### Stack traceback or browser console output

$ python3 script.py
Start 6209 1
Start 6210 2
Start 6211 3
Start 6212 4
End 6209 1
End 6210 2
Timeout
Pool terminated

$ bokeh serve script.py
2022-10-02 21:37:23,760 Starting Bokeh server version 2.4.3 (running on Tornado 6.1)
2022-10-02 21:37:23,761 User authentication hooks NOT provided (default user enabled)
2022-10-02 21:37:23,765 Bokeh app running at: http://localhost:5006/script
2022-10-02 21:37:23,766 Starting Bokeh server with process id: 7744
2022-10-02 21:37:28,903 404 GET /favicon.ico (127.0.0.1) 2.51ms
2022-10-02 21:37:28,904 WebSocket connection opened
2022-10-02 21:37:28,905 ServerConnection created
Start 7808 1
Start 7809 2
Start 7810 3
Start 7811 4
End 7808 1
End 7809 2
Timeout
Received signal 15, shutting down
Received signal 15, shutting down
End 7810 3
End 7811 4
# Hangs

**Comment by bryevdv** [comment]
@TheoMathurin offhand, I would speculate that things like this will almost certainly require explicit setup/teardwown in session lifecycle hooks:

https://docs.bokeh.org/en/latest/docs/user_guide/server.html#lifecycle-hooks

(this is the reason such hooks exist)

**Comment by TheoMathurin** [comment]
I am familiar with lifecycle hooks as I use them for various purposes.

I don't see how they could help here though. What I can say is that the session itself is not destroyed, so you could not use hooks to clean up these processes.

**Comment by bryevdv** [comment]
@TheoMathurin your use of the main check to invoke `callback` was confusing. I thought you were asking about a session-lived worker (what that would usually indicate), rather than a debugging comparison. I get a different result with `branch-3.0` 
```
dev-3.9 ❯ bokeh serve --show foo.py
2022-10-03 12:03:08,693 Starting Bokeh server version 3.0.0.dev19+4.ga3d3bcc1 (running on Tornado 6.1)
2022-10-03 12:03:09,136 User authentication hooks NOT provided (default user enabled)
2022-10-03 12:03:09,142 Bokeh app running at: http://localhost:5006/foo
2022-10-03 12:03:09,142 Starting Bokeh server with process id: 42546
2022-10-03 12:03:09,652 WebSocket connection opened
2022-10-03 12:03:09,653 ServerConnection created
Process SpawnPoolWorker-1:
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/queues.py", line 368, in get
    return _ForkingPickler.loads(res)
Traceback (most recent call last):
ModuleNotFoundError: No module named 'bokeh_app_db1a0f57fd5a4ae8b9ff3cdad9228e00'
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/queues.py", line 368, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'bokeh_app_db1a0f57fd5a4ae8b9ff3cdad9228e00'
Process SpawnPoolWorker-3:
Traceback (most recent call last):
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/queues.py", line 368, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'bokeh_app_db1a0f57fd5a4ae8b9ff3cdad9228e00'
Process SpawnPoolWorker-4:
Traceback (most recent call last):
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/multiprocessing/queues.py", line 368, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'bokeh_app_db1a0f57fd5a4ae8b9ff3cdad9228e00'
Timeout
Pool terminated
```

Which is better in one way and worse in another I suppose. I am not sure offhand what to do or how to resolve, however. Every time  a session is created, Bokeh programmatically creates and installs a module (with a unique name) to execute the code in. It gets placed in `sys.modules` like any other regular module. I am not sure what the proximate cause of the pickling error would be.

**Comment by bryevdv** [comment]
I did try converting to a directory style app an moving the `task` function to a separate module entirely but that did not help.

**Comment by TheoMathurin** [comment]
Ok to make things perhaps clearer, here is an even more minimal script. In fact there's no need to trigger a callback for the issue to arise.

```python
import multiprocessing as mp
import time
import os
from bokeh.io import curdoc
from bokeh.models import Button


def task(num):
    print('Start', os.getpid(), num)
    time.sleep(num)
    print('End', os.getpid(), num)


curdoc().add_root(Button())

p = mp.Pool(processes=4)
res = p.map_async(task, [1, 2, 3, 4])
try:
    res.get(timeout=2.5)
except mp.context.TimeoutError:
    print('Timeout')
p.terminate()
print('Pool terminated')
```

> I did try converting to a directory style app an moving the `task` function to a separate module entirely but that did not help.

In my real-world app this is in fact the case. The `task` function and even the code that creates the pool are in a separate module.

I will do more testing on `branch-3.0`.

**Comment by bryevdv** [comment]
Well, I was on OSX, I might speculate that is the difference then, instead.

**Comment by bryevdv** [comment]
@TheoMathurin are thread executors an option for you in the short term?

**Comment by TheoMathurin** [comment]
Unfortunately the tasks are typically CPU bound so I really needs parallel execution.

I have been having hanging processes and pool deadlocks for a while now within Bokeh apps, including using the non-async pool.map. This is why I wanted to set a timeout in the first place, to prevent the app from freezing, while I try to understand why that happens and if my code is to blame.

However I could not find much user feedback on the matter.

**Comment by bryevdv** [comment]
I am afraid this is under-developed/explored territory and will require some investigation to see what is going awry in this case, and what is feasible to expect. I don't have any immediate simple suggestions. 

Looking at the docs for process pool executors, there may be some assumptions/requirements that relevant, but I'm not sure

https://docs.python.org/3.9/library/concurrent.futures.html#processpoolexecutor

**Comment by TheoMathurin** [comment]
Thanks, I will try to dig deeper.

If I have any new insight, valuable information or potential workarounds, I will make sure to share them. If it remains unclear or if it turns out that these issues are inherent to Bokeh server and in some sense unavoidable, in time I would propose to address the subject in the documentation.

**Comment by TheoMathurin** [comment]
@bryevdv 

It turns out the fact that we were not getting the same error is indeed related to the OS, but only indirectly.

The Python docs says that since Python 3.8 the default start method used by multiprocessing on macOS is "spawn", while it is "fork" on Linux. I can reproduce your error on Linux if I specify the "spawn" context on my pool.

Note that this `ModuleNotFoundError` also occurs if the multiprocessing work happens in a separate module, which is not suffixed by Bokeh as it is the case for the app module. We can therefore rule this out as the proximate cause of the error.

**Comment by itsgifnotjiff** [comment]
I work with a Panel Server and am trying to parallelize the population of a cache dict but run into the same errors as the OP. Is there a workaround I could use as using multiprocessing, concurrent.features or asyncio does not work.

**Comment by bryevdv** [comment]
I don't have any new information to add, unfortunately. I did just try putting the mp code into a more recent `DocumentReady` callback in case deferring the process spawns might help, but I got the same result as before.
```
def cb(event):
    p = mp.Pool(processes=4)
    res = p.map_async(task, [1, 2, 3, 4])
    try:
        res.get(timeout=2.5)
    except mp.context.TimeoutError:
        print('Timeout')
    p.terminate()
    print('Pool terminated')

curdoc().on_event("document_ready", cb)
```

**Comment by TheoMathurin** [comment]
As stated in https://github.com/bokeh/bokeh/issues/12713, I've had more luck using `concurrent.futures.ProcessPoolExecutor` instead of `multiprocessing.Pool`.

I've just tried the MRE and it also behaves better for me on Linux with Python 3.12. The processes are not killed and finish the task, but at least the pool can be shut down and execution is not blocked.

@bryevdv If this is confirmed, maybe we could add guidance for parallel execution in the docs and close these two issues?
