### ISSUE TITLE
[BUG] IndexError when using bokeh serve --dev without app directory or script

### ISSUE THREAD

**Issue by salsasepp** [bokeh/bokeh#12469]
### Software versions

Python version      :  3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.0.0.dev19
BokehJS static path :  /home/stefan/.local/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v16.16.0
npm version         :  8.11.0
Operating system    :  Linux-5.15.0-48-generic-x86_64-with-glibc2.35

### Expected behavior

The command line with `--dev` option might not even make sense with an empty document, but IMO it should either
- silently pass on autoreloading target files, or
- print a useful error message

### Observed behavior

```
Traceback (most recent call last):
  File "/home/stefan/.local/bin/bokeh", line 8, in <module>
    sys.exit(main())
  File "/home/stefan/.local/lib/python3.10/site-packages/bokeh/__main__.py", line 59, in main
    _main(sys.argv)
  File "/home/stefan/.local/lib/python3.10/site-packages/bokeh/command/bootstrap.py", line 109, in main
    ret = args.invoke(args)
  File "/home/stefan/.local/lib/python3.10/site-packages/bokeh/command/subcommands/serve.py", line 946, in invoke
    find_autoreload_targets(args.files[0])
IndexError: list index out of range
```

### Example code

```Python
export BOKEH_DEV=true; bokeh serve --dev
```

**Comment by bryevdv** [comment]
@salsasepp Would you like to submit a pull request to catch the exception and print an error message?

**Comment by salsasepp** [comment]
@bryevdv You mean I should finally educate myself on how to do a pull request? Okay... About time. I'll take this one. Please allow for a few weeks, this will be my first PR ever.

**Comment by bryevdv** [comment]
That's great @salsasepp please let us know if you have any questions!

**Comment by bryevdv** [comment]
re-triaging as `task`. Not providing an app with `--dev` is a usage error, so nothing can be expected to work regardless. It just needs a better error message.
