### ISSUE TITLE
[BUG] ImportError: cannot import name 'NotRequired' from 'typing_extensions'

### ISSUE THREAD

**Issue by kernc** [bokeh/bokeh#12537]
### Software versions

Bokeh version: 3.0.0rc6
typing-extensions: 3.10.0.2

### Expected behavior

```py
import bokeh  # No error
```

### Observed behavior

```
Traceback (most recent call last):
  File "script.py", line 13, in <module>
    from bokeh.colors import RGB
  File ".venv/lib/python3.9/site-packages/bokeh/colors/__init__.py", line 25, in <module>
    from . import groups, named
  File ".venv/lib/python3.9/site-packages/bokeh/colors/groups.py", line 24, in <module>
    from .util import ColorGroup
  File ".venv/lib/python3.9/site-packages/bokeh/colors/util.py", line 27, in <module>
    from .color import RGB
  File ".venv/lib/python3.9/site-packages/bokeh/colors/color.py", line 39, in <module>
    from ..core.serialization import AnyRep, Serializable, Serializer
  File ".venv/lib/python3.9/site-packages/bokeh/core/serialization.py", line 46, in <module>
    from typing_extensions import NotRequired, TypeAlias
ImportError: cannot import name 'NotRequired' from 'typing_extensions'
```

### Stack traceback or browser console output

`NotRequired` seems to actually require typing-extensions>=4.0:
https://github.com/bokeh/bokeh/blob/9175e148b516c3d27fc78f996370d4ef1f5f5e01/src/bokeh/core/serialization.py#L46
https://github.com/bokeh/bokeh/blob/9175e148b516c3d27fc78f996370d4ef1f5f5e01/pyproject.toml#L20

The import may also want to appear behind a `if typing.TYPE_CHECKING:` check?

**Comment by bryevdv** [comment]
@kernc would you be interested to submit a PR to make these updates?
