### ISSUE TITLE
[BUG] `get_screenshot_as_png` 

### ISSUE THREAD

**Issue by dankovacek** [bokeh/bokeh#12611]
### Software versions

Python version      :  3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.0.1
BokehJS static path :  /home/Documents/env/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.15.0-52-generic-x86_64-with-glibc2.35

### Expected behavior

Given a layout, the `export_png` or `get_screenshot_as_png` functions should create a png image.

### Observed behavior

In a composite layout, if I don't specify width and height in all widgets, an error is thrown inside Pillow.

In the MRE pasted below, if I specify all width and height attributes, the functions behave as expected.  If I remove either of the dimension attributes (width, height) from the `break_section` div, i.e. change 

`break_section = Div(text=f"Another div.", width=950, height=100)`

to 

`break_section  = Div(text=f"Another div.", width=950)`

I get the error posted below.

### Example code

```Python
from bokeh.io import export_png
from bokeh.plotting import figure
from bokeh.models import Div
from bokeh.layouts import column, row

import numpy as np

from selenium import webdriver
from selenium.webdriver.chrome.options import Options

from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager

class pdf_driver:
    def __init__(self):    
        chrome_options = Options()
        chrome_options.headless = True 
        svc = ChromeService(ChromeDriverManager().install())
        self.driver = webdriver.Chrome(service=svc, options=chrome_options)       

    def quit_driver(self):
        self.driver.quit()

driver = pdf_driver()


all_rows = []
for i in range(2):
    # prepare some data
    x = np.linspace(0, 5, 5)
    y = [np.random.normal() for n in x]

    # create a new plot with a title and axis labels
    p = figure(title="Simple line example", x_axis_label="x", y_axis_label="y", width=912)
    # add a line renderer with legend and line thickness to the plot
    p.line(x, y, legend_label="Temp.", line_width=2)

    div = Div(
        text=f"""Your <a href="https://en.wikipedia.org/wiki/HTML">HTML</a>-
                supported text is initialized with the <b>text</b> argument.""",
                width=950, height=100
        )
    break_section = Div(text=f"Another div.", width=950, height=100)
    
    this_row = column(div, p, break_section)
    all_rows.append(this_row)


layout = column(all_rows)

export_png(layout, filename="test_file.png")

pdf_driver.quit_driver
```

### Stack traceback or browser console output

```
Traceback (most recent call last):
  File "/home/Documents/bokeh/tests/export_png_test.py", line 64, in <module>
    export_png(layout, filename='test_out/test_file.png')
  File "/home/Documents/env/lib/python3.10/site-packages/bokeh/io/export.py", line 116, in export_png
    image = get_screenshot_as_png(obj, width=width, height=height, driver=webdriver, timeout=timeout, state=state)
  File "/home/Documents/env/lib/python3.10/site-packages/bokeh/io/export.py", line 264, in get_screenshot_as_png
    .resize((width, height)))
  File "/home/Documents/env/lib/python3.10/site-packages/PIL/Image.py", line 2093, in resize
    im = im.resize(size, resample, box)
  File "/home/Documents/env/lib/python3.10/site-packages/PIL/Image.py", line 2115, in resize
    return self._new(self.im.resize(size, resample, box))
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by mattpap** [comment]
It's a simple case of lack of rounding when computing viewport dimensions in JS runtime.
