### ISSUE TITLE
[BUG] Seemingly random deadlocks with multiprocessing pools

### ISSUE THREAD

**Issue by TheoMathurin** [bokeh/bokeh#12713]
### Software versions

I first noticed the issue with previous versions of bokeh and python but it is still there with bokeh 3.0.3. It occurs on all Linux distributions I have tried so far (Ubuntu 18.04 and 22.04, Fedora 36, RHEL7).

```
Python version      :  3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.0.3
BokehJS static path :  /home/mathurin/miniconda3/envs/bokeh3/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.15.0-56-generic-x86_64-with-glibc2.35
```

### Expected behavior

I have an app which uses multiprocessing. I would expect that parallel tasks can be carried out seamlessly within a bokeh server process.

### Observed behavior

I noticed about a year ago that for no obvious reason, multiprocessing pools created within a bokeh server sometimes happen to be stuck. To circumvent that I tried to set up a mechanism to kill the pool if it hit a timeout. However it does not work, while it does work in a plain python script (see issue #12452).

When investigating the original issue I found that even a pool with a trivial task (no network I/O, no disk access, no heavy computation, no nothing) can result in a deadlock in a seemingly random fashion.

### Example code

Once triggered, the callback in the app below will indefinitely perform a very simple task. In my case, if I let it run for a few minutes I will inevitably get a deadlock, although I cannot predict when (can be a few tens as well as a few thousands of iterations).

As a control I tried several times to execute the callback in a python script and I got no hanging past 20k iterations. 

```Python
import multiprocessing as mp
import time
from bokeh.io import curdoc
from bokeh.models import Button


def task(num):
    return 2*num


def callback(new=None):

    a = 0
    while True:
        a += 1
        with mp.Pool(4) as p:
            res = p.map(task, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
        print(f'Finished another set of tasks (#{a})')
        time.sleep(0.1)


button = Button()
button.on_click(callback)

curdoc().add_root(button)
```

Another difference with multiprocessing within a bokeh server is the presence of lines that read "Received signal 15, shutting down" in the logs.

### Stack traceback or browser console output

Below is the traceback when I stop the deadlock process manually. Locks are involved.

```
Traceback (most recent call last):
  File "/home/mathurin/miniconda3/envs/bokeh3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/mathurin/miniconda3/envs/bokeh3/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mathurin/miniconda3/envs/bokeh3/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/home/mathurin/miniconda3/envs/bokeh3/lib/python3.11/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/mathurin/miniconda3/envs/bokeh3/lib/python3.11/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by bryevdv** [comment]
This actually fails immediately on OSX:
```
Process SpawnPoolWorker-10:
Traceback (most recent call last):
  File "/Users/bryan/anaconda/envs/dev-311/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/bryan/anaconda/envs/dev-311/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bryan/anaconda/envs/dev-311/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Users/bryan/anaconda/envs/dev-311/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'bokeh_app_a1a8d9919776428583ccbb8dc9e80df1'
```
Unfortunately this is not an area of deep expertise for me so I expect it may take an extended investigation at some point. I don't have any immediate workarounds to suggest so if `multiprocessing` is a hard requirement you may want to look at other tools.

**Comment by TheoMathurin** [comment]
Thank you @bryevdv 

Could you try with the 'fork' start method on OSX, see if you can reproduce my issue?
```python
mp.set_start_method('fork')
```

Because this may be the cause of this `ModuleNotFoundError`. See my comment [here](https://github.com/bokeh/bokeh/issues/12452#issuecomment-1307792308).

**Comment by TheoMathurin** [comment]
It seems that the issue disappears for some reason when using `concurrent.futures.ProcessPoolExecutor` instead of `multiprocessing.Pool`.

If that's confirmed, I'm not sure if this issue should be left open as there is a clear and easy workaround.

**Comment by bryevdv** [comment]
@TheoMathurin I missed your comment, apologies. Can you provide a complete minimal updated example code that uses `concurrent.futures.ProcessPoolExecutor` that does work for reference? I might re-triage this issue to simply add guidance to the docs to use that over `multiprocessing`.

**Comment by TheoMathurin** [comment]
@bryevdv sure!

Here is the updated snippet using `ProcessPoolExecutor`, it's basically the same code as the API is similar.

```python
import time
from bokeh.io import curdoc
from bokeh.models import Button
from concurrent.futures import ProcessPoolExecutor


def task(num):
    return 2*num


def callback(new=None):

    a = 0
    while True:
        a += 1
        with ProcessPoolExecutor(4) as p:
            res = p.map(task, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
        print(f'Finished another set of tasks (#{a})')
        time.sleep(0.1)


button = Button()
button.on_click(callback)

curdoc().add_root(button)
```
