### ISSUE TITLE
[BUG] Cannot plot `pandas.DataFrame` with columns of type string

### ISSUE THREAD

**Issue by yuji38kwmt** [bokeh/bokeh#12821]
### Software versions

Python: 3.10.2
pandas: 1.5.3
bokeh: 3.0.3

### Browser name and version

Chrome 109.0.5414.119（Official Build）

### Expected behavior

I want to use tooltips.

I expect to be able to plot with the following example code.

### Observed behavior

When I execute the following example code, the error occurred.

```
bokeh.core.serialization.SerializationError: can't serialize <class 'pandas.core.arrays.string_.StringArray'>
```

### Example code

```Python
from bokeh.plotting import ColumnDataSource, figure, output_file, show
import pandas

output_file("toolbar.html")
data = dict(
    x=[1, 2, 3, 4, 5],
    y=[2, 5, 8, 2, 7],
    desc=["A", "b", "C", "d", "E"],
)
df = pandas.DataFrame(data)
# convert `desc` column type to `string` from `object`
df["desc"] = df["desc"].astype("string")

source = ColumnDataSource(data=df)
TOOLTIPS = [
    ("desc", "@desc"),
]
p = figure(tooltips=TOOLTIPS)
p.circle("x", "y", size=20, source=source)
show(p)
```

### Stack traceback or browser console output

* When bokeh version is 2.4.3, an error did not occur.

* Stack traceback

```
$ poetry run python sample.py
Traceback (most recent call last):
  File "/home/vagrant/Documents/study/20230219/sample.py", line 20, in <module>
    show(p)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/io/showing.py", line 143, in show
    return _show_with_state(obj, state, browser, new, notebook_handle=notebook_handle)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/io/showing.py", line 194, in _show_with_state
    _show_file_with_state(obj, state, new, controller)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/io/showing.py", line 175, in _show_file_with_state
    filename = save(obj, state=state)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/io/saving.py", line 98, in save
    _save_helper(obj, filename, resources, title, template, theme)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/io/saving.py", line 164, in _save_helper
    html = file_html(obj, resources, title=title, template=template or FILE, theme=theme)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/embed/standalone.py", line 357, in file_html
    (docs_json, render_items) = standalone_docs_json_and_render_items(models_seq, suppress_callback_warning=suppress_callback_warning)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/embed/util.py", line 330, in standalone_docs_json_and_render_items
    docs_json[docid] = doc.to_json(deferred=False)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/document/document.py", line 728, in to_json
    roots = serializer.encode(self._roots)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 274, in _encode
    return self._encode_list(obj)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 317, in _encode_list
    return [self.encode(item) for item in obj]
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 317, in <listcomp>
    return [self.encode(item) for item in obj]
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 258, in _encode
    return obj.to_serializable(self)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/model/model.py", line 525, in to_serializable
    super_rep = super().to_serializable(serializer)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/has_props.py", line 406, in to_serializable
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/has_props.py", line 406, in <dictcomp>
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 274, in _encode
    return self._encode_list(obj)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 317, in _encode_list
    return [self.encode(item) for item in obj]
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 317, in <listcomp>
    return [self.encode(item) for item in obj]
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 258, in _encode
    return obj.to_serializable(self)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/model/model.py", line 525, in to_serializable
    super_rep = super().to_serializable(serializer)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/has_props.py", line 406, in to_serializable
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/has_props.py", line 406, in <dictcomp>
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 258, in _encode
    return obj.to_serializable(self)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/model/model.py", line 525, in to_serializable
    super_rep = super().to_serializable(serializer)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/has_props.py", line 406, in to_serializable
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/has_props.py", line 406, in <dictcomp>
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 278, in _encode
    return self._encode_dict(obj)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 334, in _encode_dict
    entries=[(self.encode(key), self.encode(val)) for key, val in obj.items()],
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 334, in <listcomp>
    entries=[(self.encode(key), self.encode(val)) for key, val in obj.items()],
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 290, in _encode
    return self._encode_other(obj)
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 458, in _encode_other
    self.error(f"can't serialize {type(obj)}")
  File "/home/vagrant/Documents/study/20230219/.venv/lib/python3.10/site-packages/bokeh/core/serialization.py", line 461, in error
    raise SerializationError(message)
bokeh.core.serialization.SerializationError: can't serialize <class 'pandas.core.arrays.string_.StringArray'>
```

**Comment by bryevdv** [comment]
Triaging this as `feature` since Bokeh predates the existence of `StringArray` by many years. This would be new development to support that (relatively) new feature in Pandas. (StringArray has existed for a while since Pandas 1.0 but this is the first time anyone has asked about it)
