### ISSUE TITLE
[BUG] Cannot serialize pandas numeric arrays

### ISSUE THREAD

**Issue by benrussell80** [bokeh/bokeh#12839]
### Software versions

Python version      :  3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]
IPython version     :  8.10.0
Tornado version     :  6.2
Bokeh version       :  3.1.0.dev3+1.g0539444b.dirty
BokehJS static path :  /home/ben/Projects/bokeh/src/bokeh/server/static
node.js version     :  v16.17.1
npm version         :  8.15.0
Operating system    :  Linux-5.19.0-32-generic-x86_64-with-glibc2.35

### Expected behavior

Pandas numeric arrays should serialize in the same way that pandas `StringArray`s do.

### Observed behavior

Since pandas `IntegerArray` and `FloatArray` do not inherit from `PandasArray` a serialization error is raised.

### Example code

```Python
import pandas as pd
import numpy as np

from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource


arr = np.random.rand(10)
source = ColumnDataSource({
    'x': np.arange(10),
    'y': pd.array(arr)
})

p = figure()

p.circle(source=source)

show(p)
```

### Stack traceback or browser console output

```
Traceback (most recent call last):
  File "/home/ben/Projects/bokeh/test_sparse.py", line 23, in <module>
    main()
  File "/home/ben/Projects/bokeh/test_sparse.py", line 19, in main
    show(p)
  File "/home/ben/Projects/bokeh/src/bokeh/io/showing.py", line 143, in show
    return _show_with_state(obj, state, browser, new, notebook_handle=notebook_handle)
  File "/home/ben/Projects/bokeh/src/bokeh/io/showing.py", line 194, in _show_with_state
    _show_file_with_state(obj, state, new, controller)
  File "/home/ben/Projects/bokeh/src/bokeh/io/showing.py", line 175, in _show_file_with_state
    filename = save(obj, state=state)
  File "/home/ben/Projects/bokeh/src/bokeh/io/saving.py", line 98, in save
    _save_helper(obj, filename, resources, title, template, theme)
  File "/home/ben/Projects/bokeh/src/bokeh/io/saving.py", line 164, in _save_helper
    html = file_html(obj, resources, title=title, template=template or FILE, theme=theme)
  File "/home/ben/Projects/bokeh/src/bokeh/embed/standalone.py", line 357, in file_html
    (docs_json, render_items) = standalone_docs_json_and_render_items(models_seq, suppress_callback_warning=suppress_callback_warning)
  File "/home/ben/Projects/bokeh/src/bokeh/embed/util.py", line 330, in standalone_docs_json_and_render_items
    docs_json[docid] = doc.to_json(deferred=False)
  File "/home/ben/Projects/bokeh/src/bokeh/document/document.py", line 737, in to_json
    roots = serializer.encode(self._roots)
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 274, in _encode
    return self._encode_list(obj)
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 317, in _encode_list
    return [self.encode(item) for item in obj]
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 317, in <listcomp>
    return [self.encode(item) for item in obj]
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 258, in _encode
    return obj.to_serializable(self)
  File "/home/ben/Projects/bokeh/src/bokeh/model/model.py", line 525, in to_serializable
    super_rep = super().to_serializable(serializer)
  File "/home/ben/Projects/bokeh/src/bokeh/core/has_props.py", line 406, in to_serializable
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "/home/ben/Projects/bokeh/src/bokeh/core/has_props.py", line 406, in <dictcomp>
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 274, in _encode
    return self._encode_list(obj)
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 317, in _encode_list
    return [self.encode(item) for item in obj]
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 317, in <listcomp>
    return [self.encode(item) for item in obj]
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 258, in _encode
    return obj.to_serializable(self)
  File "/home/ben/Projects/bokeh/src/bokeh/model/model.py", line 525, in to_serializable
    super_rep = super().to_serializable(serializer)
  File "/home/ben/Projects/bokeh/src/bokeh/core/has_props.py", line 406, in to_serializable
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "/home/ben/Projects/bokeh/src/bokeh/core/has_props.py", line 406, in <dictcomp>
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 258, in _encode
    return obj.to_serializable(self)
  File "/home/ben/Projects/bokeh/src/bokeh/model/model.py", line 525, in to_serializable
    super_rep = super().to_serializable(serializer)
  File "/home/ben/Projects/bokeh/src/bokeh/core/has_props.py", line 406, in to_serializable
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "/home/ben/Projects/bokeh/src/bokeh/core/has_props.py", line 406, in <dictcomp>
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 278, in _encode
    return self._encode_dict(obj)
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 334, in _encode_dict
    entries=[(self.encode(key), self.encode(val)) for key, val in obj.items()],
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 334, in <listcomp>
    entries=[(self.encode(key), self.encode(val)) for key, val in obj.items()],
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 249, in encode
    return self._encode(obj)
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 290, in _encode
    return self._encode_other(obj)
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 460, in _encode_other
    self.error(f"can't serialize {type(obj)}")
  File "/home/ben/Projects/bokeh/src/bokeh/core/serialization.py", line 463, in error
    raise SerializationError(message)
bokeh.core.serialization.SerializationError: can't serialize <class 'pandas.core.arrays.floating.FloatingArray'>
```

**Comment by benrussell80** [comment]
Solution would be to check if array is instance of from `pandas.core.arrays.numeric.NumericArray`

Edit: the inheritance tree is really different for each of the array types in `pandas.arrays`. It seems like the common ancestor between them is `pandas.api.extensions.ExtensionArray`. This class has a `.to_numpy()` method which should work for serialization. As a bonus, pandas sparse arrays inherit from this class too
