### ISSUE TITLE
Downsample example

### ISSUE THREAD

**Issue by tartavull** [bokeh/bokeh#1290]
Hi ,
I'm trying to display a ~1gb timeseries hdf5 file, that's why I'm trying to learn how serversource.py example works but I'm not able to make it run.

Firstly I open a terminal to run bokeh-server as:
```
    nacho@HP-Notebook:~/Programming/bokeh$ bokeh-server -D remotedata

    Bokeh Server Configuration
    ==========================
    python version : 2.7.8
    bokeh version  : 0.6.0-71-ga4e2384-dirty
    listening      : 127.0.0.1:5006
    backend        : shelve
    python options : debug:OFF, verbose:OFF, filter-logs:OFF, multi-user:OFF
    js options     : splitjs:OFF, debugjs:OFF
    data-directory : remotedata

   zmqpub starting

  Starting Bokeh plot server on port 5006...
  View http://127.0.0.1:5006/bokeh to see plots

Then, I open a new one to run the example:

  nacho@HP-Notebook:~/Programming/bokeh/examples/plotting/server$ python serversource.py 
  Using saved session configuration for http://localhost:5006/
  To override, pass 'load_from_config=False' to Session
  Traceback (most recent call last):
    File "serversource.py", line 18, in <module>
      output_server("remotedata")
    File "/home/nacho/anaconda/lib/python2.7/site-packages/bokeh/plotting.py", line 153, in output_server
      session.use_doc(docname)
    File "/home/nacho/anaconda/lib/python2.7/site-packages/bokeh/session.py", line 485, in use_doc
      self.docid = self.find_doc(name)
    File "/home/nacho/anaconda/lib/python2.7/site-packages/bokeh/session.py", line 448, in find_doc
      docs = self.userinfo.get('docs')
    File "/home/nacho/anaconda/lib/python2.7/site-packages/bokeh/session.py", line 403, in userinfo
      self._userinfo = self.get_json(url)
    File "/home/nacho/anaconda/lib/python2.7/site-packages/bokeh/session.py", line 381, in get_json
      return self.execute_json('get', url, headers=headers, **kwargs)
    File "/home/nacho/anaconda/lib/python2.7/site-packages/bokeh/session.py", line 365, in execute_json
      return utils.get_json(resp)
    File "/home/nacho/anaconda/lib/python2.7/site-packages/bokeh/utils.py", line 33, in get_json
      return request.json()
    File "/home/nacho/anaconda/lib/python2.7/site-packages/requests/models.py", line 793, in json
      return json.loads(self.text, **kwargs)
    File "/home/nacho/anaconda/lib/python2.7/json/__init__.py", line 338, in loads
      return _default_decoder.decode(s)
    File "/home/nacho/anaconda/lib/python2.7/json/decoder.py", line 366, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/home/nacho/anaconda/lib/python2.7/json/decoder.py", line 384, in raw_decode
      raise ValueError("No JSON object could be decoded")
  ValueError: No JSON object could be decoded
```
and as soon as I run this, the server crashes with:
 ```
  2014-10-09 10:14:14,705:ERROR:bokeh.server:Exception on /bokeh/userinfo/ [GET]
  Traceback (most recent call last):
    File "/home/nacho/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
      response = self.full_dispatch_request()
    File "/home/nacho/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
      rv = self.handle_user_exception(e)
    File "/home/nacho/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
      reraise(exc_type, exc_value, tb)
    File "/home/nacho/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
      rv = self.dispatch_request()
    File "/home/nacho/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
      return self.view_functions[rule.endpoint](**req.view_args)
    File "/home/nacho/Programming/bokeh/bokeh/server/crossdomain.py", line 32, in wrapped_function
      resp = make_response(f(*args, **kwargs))
    File "/home/nacho/Programming/bokeh/bokeh/server/views/main.py", line 130, in get_user
      bokehuser = bokeh_app.current_user()
    File "/home/nacho/Programming/bokeh/bokeh/server/app.py", line 33, in current_user
      return self.authentication.current_user()
    File "/home/nacho/Programming/bokeh/bokeh/server/server_backends.py", line 185, in current_user
      bokehuser = user.User.load(bokeh_app.servermodel_storage, username)
    File "/home/nacho/Programming/bokeh/bokeh/server/models/user.py", line 59, in load
      attrs = cls.load_json(client, objid)
    File "/home/nacho/Programming/bokeh/bokeh/server/models/__init__.py", line 36, in load_json
      data = client.get(cls.modelkey(objid))
    File "/home/nacho/Programming/bokeh/bokeh/server/server_backends.py", line 94, in get
      _data = shelve.open('bokeh.server')
    File "/home/nacho/anaconda/lib/python2.7/shelve.py", line 239, in open
      return DbfilenameShelf(filename, flag, protocol, writeback)
    File "/home/nacho/anaconda/lib/python2.7/shelve.py", line 223, in __init__
      Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
    File "/home/nacho/anaconda/lib/python2.7/anydbm.py", line 84, in open
      mod = __import__(result)
    File "/home/nacho/anaconda/lib/python2.7/dbhash.py", line 7, in <module>
      import bsddb
    File "/home/nacho/anaconda/lib/python2.7/bsddb/__init__.py", line 67, in <module>
      import _bsddb
  ImportError: No module named _bsddb
```
What am I doing wrong?

**Comment by bryevdv** [comment]
Closing from inactivity. Please re-open or create new issue with instructions to reproduce if this problem persists.
