### ISSUE TITLE
`autocompleteinput.py` example doesn't work with pandas 2.0

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#13056]
```py
tests/test_examples.py::test_file_examples[/home/runner/work/bokeh/bokeh/examples/interaction/widgets/autocompleteinput.py-example175-config175] 
[INFO] Example run in 0.845s
[PY] Traceback (most recent call last):
[PY]   File "<string>", line 18, in <module>
[PY]   File "/home/runner/work/bokeh/bokeh/examples/interaction/widgets/autocompleteinput.py", line 7, in <module>
[PY]     auto_complete_input =  AutocompleteInput(title="Enter a city:", completions=completion_list)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/widgets/inputs.py", line 386, in __init__
[PY]     super().__init__(*args, **kwargs)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/widgets/inputs.py", line 331, in __init__
[PY]     super().__init__(*args, **kwargs)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/widgets/inputs.py", line 301, in __init__
[PY]     super().__init__(*args, **kwargs)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/widgets/inputs.py", line 83, in __init__
[PY]     super().__init__(*args, **kwargs)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/widgets/widget.py", line 56, in __init__
[PY]     super().__init__(*args, **kwargs)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/layouts.py", line 97, in __init__
[PY]     super().__init__(*args, **kwargs)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/ui/ui_element.py", line 61, in __init__
[PY]     super().__init__(*args, **kwargs)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/model/model.py", line 110, in __init__
[PY]     super().__init__(**kwargs)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/core/has_props.py", line 298, in __init__
[PY]     setattr(self, name, value)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/core/has_props.py", line 327, in __setattr__
[PY]     return super().__setattr__(name, value)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/core/property/descriptors.py", line 332, in __set__
[PY]     value = self.property.prepare_value(obj, self.name, value)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/core/property/bases.py", line 365, in prepare_value
[PY]     raise ValueError(f"failed to validate {obj_repr}.{name}: {error}")
[PY] ValueError: failed to validate AutocompleteInput(id='p1001', ...).completions: expected an element of List(String), got seq with invalid items [nan]
FAILED
```

**Comment by mattpap** [comment]
According to pandas 2.0:
```
None,44.93645,7.54015
```
 is 
```
ipdb> p data.loc[22422]
name         NaN
lat     44.93645
lng      7.54015
Name: 22422, dtype: object
```
