### ISSUE TITLE
[BUG] CDS updated from DataTable fix input value in callback error

### ISSUE THREAD

**Issue by RaphaelRosset** [bokeh/bokeh#13110]
### Software versions

Python version      :  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  2.4.3
BokehJS static path :  C:\Appl\env\buildup_auto_qc_310\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19045-SP0

panel                      : 0.14.4

### Expected behavior

Example is in a panel app but this sounds like a bokeh issue as I am not using any panel widgets as such.
Added panel version in environment information in case.

Current app has 1 ColumnDataSource with some dummy Time - Value pairs.
Those are shown both in an editable DataTable and a crossplot which has PointEditTool setup.

The important point is that the "Time" valid value are limited to match a given time step of 0.5.
So when the user drag a point on the figure and change Time value in the table, there is callback which automatically find the modified values and snap their Time value to a valid value.

### Observed behavior

Dragging points on the plot and getting the Time value fixed to a valid value on the fly works fine

However when modifying a Time value in the DataTable, the refresh ends up in a crash
The app is still responsive after the error and it may look like it can be ignored. However everything is not fine.
Look at the color column green if "Time" > 3 else blue.

This Colour is updated in the callback function as well, so it is always synchronized with modified points "Time" values.

While editing the  "Time" value by dragging points on the plot, color is always updated.
While editing the "Time" value by changing it in the table, if the "Time" value is properly updated, the color does not updated.
So this error may end up with loosing some of the UI expected updates

### Example code

```Python

import bokeh
import panel as pn
import pandas as pd
import numpy as np

pn.extension()


def roundup_to_nearest(x: float, to_nearest: float) -> float:
    return x if np.isclose(x % to_nearest, 0.0) else x + to_nearest - x % to_nearest


def get_color(v: float) -> str:
    if v > 3:
        return "lightgreen"
    else:
        return "lightblue"


class AppWindow(pn.Column):
    def __init__(self):
        super().__init__()
        df = pd.DataFrame(
            {
                "Time": [1, 2.5, 3, 4.5, 5],
                "Value": [2.98, 4.6, 7.65, 4.56, 5.05],
            }
        )

        self.source = bokeh.plotting.ColumnDataSource(
            {
                "Time": df["Time"],
                "Value": df["Value"],
                "Color": [get_color(v) for v in df["Time"]],
            }
        )
        self.source.on_change("data", self.source_updated)

        columns = [
            bokeh.models.TableColumn(
                field="Time",
                formatter=bokeh.models.NumberFormatter(format="0.0"),
            ),
            bokeh.models.TableColumn(
                field="Value",
                formatter=bokeh.models.NumberFormatter(format="0.00"),
            ),
            bokeh.models.TableColumn(
                field="Color",
                formatter=bokeh.models.HTMLTemplateFormatter(
                    template=f"""
                                <div style="background:<%= Color %>; color: black">
                                <%= value %>
                                </div>
                            """
                ),
                sortable=False,
            ),
        ]

        table = bokeh.models.DataTable(
            source=self.source,
            columns=columns,
            editable=True,
        )

        tools = [
            bokeh.models.PanTool(),
            bokeh.models.BoxZoomTool(),
            bokeh.models.WheelZoomTool(),
            bokeh.models.ResetTool(),
        ]

        fig = bokeh.plotting.figure(
            title="Value vs Time",
            x_axis_label="Time",
            y_axis_label="Value",
            tools=tools,
            sizing_mode="stretch_both",
            toolbar_location="above",
        )

        render = fig.scatter(
            x="Time",
            y="Value",
            size=20,
            source=self.source,
        )

        pdt = bokeh.models.PointDrawTool(
            renderers=[render],
            empty_value="",
            add=False,
        )
        fig.add_tools(pdt)

        self.append(table)
        self.append(pn.pane.Bokeh(fig))

    def source_updated(self, attr, old, new):
        try:
            # remove callback to avoid infinite loop
            self.source.remove_on_change("data", self.source_updated)
        except (KeyError, ValueError):
            pass

        # time values only valid at specific interval of 0.5
        # so if user entered inbetween time we snap the point
        # to closest valid time value above selected
        df = pd.DataFrame(self.source.data)
        df = df.astype(dtype={"Time": "float64", "Value": "float64"})

        invalid_times_indexes = []
        for i, row in df.iterrows():
            if not np.isclose(row["Time"] % 0.5, 0.0):
                invalid_times_indexes.append(i)

        for invalid_times_index in invalid_times_indexes:
            invalid_time = df["Time"][invalid_times_index]
            closest_valid_value = roundup_to_nearest(x=invalid_time, to_nearest=0.5)
            print(
                invalid_time, " => closest above valid time is : ", closest_valid_value
            )
            df.iloc[
                invalid_times_index,
                df.columns.get_loc("Time"),
            ] = closest_valid_value

        self.source.data = {
            "Time": df["Time"],
            "Value": df["Value"],
            "Color": [get_color(v) for v in df["Time"]],
        }

        # reset callback
        self.source.on_change("data", self.source_updated)


def create_app():
    webbapp = AppWindow()

    return webbapp


if __name__ == "__main__":
    APP_ROUTES = {"app": create_app}

    pannel_server = pn.serve(
        APP_ROUTES,
        port=8000,
        start=True,
        show=False,
        autoreload=True,
        dev=True,
    )

    pannel_server.start()
    pannel_server.io_loop.start()
```

### Stack traceback or browser console output

(test_env_310) C:\Users\XXX\test>C:/Appl/env/test_env_310/Scripts/python.exe c:/Users/XXX/test/test_fix_user_input_CDS.py
Launching server at http://localhost:8000
4.5435345  => closest above valid time is :  5.0
C:\Appl\env\test_env_310\lib\site-packages\numpy\core\numeric.py:2463: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return bool(asarray(a1 == a2).all())
ERROR:bokeh.server.protocol_handler:error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ColumnsPatched', 'column_source': {'id': '1002'}, 'patches': {'Time': [[3, '4.5435345']]}}], 'references': []}
 error: RuntimeError('Set changed size during iteration')
Traceback (most recent call last):
  File "C:\Appl\env\test_env_310\lib\site-packages\bokeh\server\protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
  File "C:\Appl\env\test_env_310\lib\site-packages\bokeh\server\session.py", line 95, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "C:\Appl\env\test_env_310\lib\site-packages\bokeh\server\session.py", line 289, in _handle_patch
    message.apply_to_document(self.document, self)
  File "C:\Appl\env\test_env_310\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 115, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.content, setter))
  File "C:\Appl\env\test_env_310\lib\site-packages\bokeh\document\callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "C:\Appl\env\test_env_310\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 115, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.content, setter))
  File "C:\Appl\env\test_env_310\lib\site-packages\bokeh\document\document.py", line 391, in apply_json_patch
    DocumentPatchedEvent.handle_json(self, event_json, references, setter)
  File "C:\Appl\env\test_env_310\lib\site-packages\bokeh\document\events.py", line 259, in handle_json
    handler(doc, event_json, references, setter)
  File "C:\Appl\env\test_env_310\lib\site-packages\bokeh\document\events.py", line 767, in _handle_json
    source.patch(patches, setter)
  File "C:\Appl\env\test_env_310\lib\site-packages\bokeh\models\sources.py", line 721, in patch
    self.data._patch(self.document, self, patches, setter)
  File "C:\Appl\env\test_env_310\lib\site-packages\bokeh\core\property\wrappers.py", line 489, in _patch
    self._notify_owners(old, hint=ColumnsPatchedEvent(doc, source, patches, setter))
  File "C:\Appl\env\test_env_310\lib\site-packages\bokeh\core\property\wrappers.py", line 168, in _notify_owners
    for (owner, descriptor) in self._owners:
RuntimeError: Set changed size during iteration
C:\Appl\env\test_env_310\lib\site-packages\bokeh\server\protocol_handler.py:101: RuntimeWarning: coroutine 'WSHandler.send_message' was never awaited
  work = connection.error(message, repr(e))

**Comment by RaphaelRosset** [comment]
I just noticed that the app is still responsive after the error and with the example above it may look like it can be ignored.
However this is not the case as it is shown with updated example below.
Only difference is I have added a color column to the CDS if "Time" > 3, green else blue.

This Colour is updated in the callback function as well, so it is always synchronized with modified points "Time" values.

If you edit the "Time" value by dragging points on the plot, everything is fine, colour is always updated.
If you edit the "Time" value by changing it in the table, the crash occurs and if the "Time" value is properly updated in the table and everything looks fine, the color change does not happen. So some of the UI update is lost due to this error)

`
import bokeh
import panel as pn
import pandas as pd
import numpy as np

pn.extension()


def roundup_to_nearest(x: float, to_nearest: float) -> float:
    return x if np.isclose(x % to_nearest, 0.0) else x + to_nearest - x % to_nearest


def get_color(v: float) -> str:
    if v > 3:
        return "lightgreen"
    else:
        return "lightblue"


class AppWindow(pn.Column):
    def __init__(self):
        super().__init__()
        df = pd.DataFrame(
            {
                "Time": [1, 2.5, 3, 4.5, 5],
                "Value": [2.98, 4.6, 7.65, 4.56, 5.05],
            }
        )

        self.source = bokeh.plotting.ColumnDataSource(
            {
                "Time": df["Time"],
                "Value": df["Value"],
                "Color": [get_color(v) for v in df["Time"]],
            }
        )
        self.source.on_change("data", self.source_updated)

        columns = [
            bokeh.models.TableColumn(
                field="Time",
                formatter=bokeh.models.NumberFormatter(format="0.0"),
            ),
            bokeh.models.TableColumn(
                field="Value",
                formatter=bokeh.models.NumberFormatter(format="0.00"),
            ),
            bokeh.models.TableColumn(
                field="Color",
                formatter=bokeh.models.HTMLTemplateFormatter(
                    template=f"""
                                <div style="background:<%= Color %>; color: black">
                                <%= value %>
                                </div>
                            """
                ),
                sortable=False,
            ),
        ]

        table = bokeh.models.DataTable(
            source=self.source,
            columns=columns,
            editable=True,
        )

        tools = [
            bokeh.models.PanTool(),
            bokeh.models.BoxZoomTool(),
            bokeh.models.WheelZoomTool(),
            bokeh.models.ResetTool(),
        ]

        fig = bokeh.plotting.figure(
            title="Pressure vs Time",
            x_axis_label="Time",
            y_axis_label="Value",
            tools=tools,
            sizing_mode="stretch_both",
            toolbar_location="above",
        )

        render = fig.scatter(
            x="Time",
            y="Value",
            size=20,
            source=self.source,
        )

        pdt = bokeh.models.PointDrawTool(
            renderers=[render],
            empty_value="",
            add=False,
        )
        fig.add_tools(pdt)

        self.append(table)
        self.append(pn.pane.Bokeh(fig))

    def source_updated(self, attr, old, new):
        try:
            # remove callback to avoid infinite loop
            self.source.remove_on_change("data", self.source_updated)
        except (KeyError, ValueError):
            pass

        # time values only valid at specific interval of 0.5
        # so if user entered inbetween time we snap the point
        # to closest valid time value above selected
        df = pd.DataFrame(self.source.data)
        df = df.astype(dtype={"Time": "float64", "Value": "float64"})

        invalid_times_indexes = []
        for i, row in df.iterrows():
            if not np.isclose(row["Time"] % 0.5, 0.0):
                invalid_times_indexes.append(i)

        for invalid_times_index in invalid_times_indexes:
            invalid_time = df["Time"][invalid_times_index]
            closest_valid_value = roundup_to_nearest(x=invalid_time, to_nearest=0.5)
            print(
                invalid_time, " => closest above valid time is : ", closest_valid_value
            )
            df.iloc[
                invalid_times_index,
                df.columns.get_loc("Time"),
            ] = closest_valid_value

        self.source.data = {
            "Time": df["Time"],
            "Value": df["Value"],
            "Color": [get_color(v) for v in df["Time"]],
        }

        # reset callback
        self.source.on_change("data", self.source_updated)


def create_app():
    webbapp = AppWindow()

    return webbapp


if __name__ == "__main__":
    APP_ROUTES = {"app": create_app}

    pannel_server = pn.serve(
        APP_ROUTES,
        port=8000,
        start=True,
        show=False,
        autoreload=True,
        dev=True,
    )

    pannel_server.start()
    pannel_server.io_loop.start()
`

**Comment by RaphaelRosset** [comment]
Modified example with new color column showing that even if value is updated in the DataTable with the error, other info like the color may not be updated

And also in the callback function, one can only keep the start and the end and comment all the code regarding modifying Time to a valid value and the same error will occur:

```Python

    def source_updated(self, attr, old, new):
        try:
            # remove callback to avoid infinite loop
            self.source.remove_on_change("data", self.source_updated)
        except (KeyError, ValueError):
            pass

        df = pd.DataFrame(self.source.data)
        df = df.astype(dtype={"Time": "float64", "Value": "float64"})

        self.source.data = {
            "Time": df["Time"],
            "Value": df["Value"],
            "Color": [get_color(v) for v in df["Time"]],
        }

        # reset callback
        self.source.on_change("data", self.source_updated)


```



However that way may not have been clear what was the purpose of the callback function.

**Comment by RaphaelRosset** [comment]
Just disover that Bokeh TableColumn has an Editor parameter which I could put to NumberEditor(step=0.5) and solve such needs in many cases.
However this would not work in my application where values are not always following a constant step. What I would need is to provide a list of valid values to the NumberEditor and be able to modify that list of value depending on the data record I am visualizing.

**Comment by bryevdv** [comment]
@RaphaelRosset ` self.source.remove_on_change` is a very heavyweight operation that does not get much use/testing. I'm not actually sure I would expect it work for a callback to remove *itself*, either. It's definitely not the first approach I would advise in a case like this. can you try something else, namely conditioning the callback code with a `self.inside_callback` flag or similar, rather than adding/removing the callback itself.

**Comment by RaphaelRosset** [comment]
@bryevdv thanks for the recommendation just updated the code with a flag as follow.
I understand you did not expect this to fix the issue, but just  in case I confirm the bug reported above still occurs avoiding self.source.remove_on_change

```
class AppWindow(pn.Column):
    def __init__(self):
        super().__init__()
        self.update_inside_callback = False
       // copy code from above then


    def source_updated(self, attr, old, new):
            if self.update_inside_callback:
                return
            self.update_inside_callback = True
                
            df = pd.DataFrame(self.source.data)
            df = df.astype(dtype={"Time": "float64", "Value": "float64"})
    
            self.source.data = {
                "Time": df["Time"],
                "Value": df["Value"],
                "Color": [get_color(v) for v in df["Time"]],
            }
    
            self.update_inside_callback = False
```
