### ISSUE TITLE
[BUG] `Bokeh.bokeh.embed_item` fails depending on order of keys in `item`

### ISSUE THREAD

**Issue by burnpanck** [bokeh/bokeh#13115]
### Software versions

Python version      :  3.11.3 (main, Apr 19 2023, 14:26:19) [Clang 14.0.3 (clang-1403.0.22.14.1)]
IPython version     :  8.12.0
Tornado version     :  6.3
Bokeh version       :  3.1.0
BokehJS static path :  /Users/yves/.pyenv/versions/3.11.3/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v19.5.0
npm version         :  9.3.1
Operating system    :  macOS-13.3.1-arm64-arm-64bit

### Browser name and version

Google Chrome Version 113.0.5672.63 (Official Build) (arm64)

### Expected behavior

`Bokeh.bokeh.embed_item(item)` should handle all semantically equivalent `items` equally. In particular, JS/JSON objects assign no semantic meaning to the order of the keys, and thus the behaviour should not depend on the order of the keys.

### Observed behavior

Instead, depending on the order of the keys, `embed_item` either performs the expected action, or causes an `Uncaught (in promise) Error: reference p1028 isn't known`. It appears that the decoding machinery cannot handle "forward-references", in the sense that parts of a document may refer to other parts of a document which haven't been decoded yet at the time the reference is encountered.

### Example code

Take the [`json_item.py`](examples/output/apis/json_item.py) example, and add `sort_keys=True` to the `json.dumps` call in any of the `/plot` / `/plot2` routes. Accessing `127.0.0.1:5000/` of the Flask app will now produce a broken web-page with one or both plots missing (depending on where `sort_keys` is applied), and a corresponding error in the developer console - at least on my version of Chrome.

Complete modified example:
<details>

```Python
import json

from flask import Flask
from jinja2 import Template

from bokeh.embed import json_item
from bokeh.plotting import figure
from bokeh.resources import CDN
from bokeh.sampledata.iris import flowers

app = Flask(__name__)

page = Template("""
<!DOCTYPE html>
<html lang="en">
<head>
  {{ resources }}
</head>

<body>
  <div id="myplot"></div>
  <div id="myplot2"></div>
  <script>
  fetch('/plot')
    .then(function(response) { return response.json(); })
    .then(function(item) { return Bokeh.embed.embed_item(item); })
  </script>
  <script>
  fetch('/plot2')
    .then(function(response) { return response.json(); })
    .then(function(item) { return Bokeh.embed.embed_item(item, "myplot2"); })
  </script>
</body>
""")

colormap = {'setosa': 'red', 'versicolor': 'green', 'virginica': 'blue'}
colors = [colormap[x] for x in flowers['species']]

def make_plot(x, y):
    p = figure(title = "Iris Morphology", sizing_mode="fixed", width=400, height=400)
    p.xaxis.axis_label = x
    p.yaxis.axis_label = y
    p.circle(flowers[x], flowers[y], color=colors, fill_alpha=0.2, size=10)
    return p

@app.route('/')
def root():
    return page.render(resources=CDN.render())

@app.route('/plot')
def plot():
    p = make_plot('petal_width', 'petal_length')
    return json.dumps(json_item(p, "myplot"), sort_keys=True)

@app.route('/plot2')
def plot2():
    p = make_plot('sepal_width', 'sepal_length')
    return json.dumps(json_item(p))

if __name__ == '__main__':
    app.run()
```

</details>

### Stack traceback or browser console output

The full stack-trace of the exception:
```
bokeh-3.1.0.min.js:211 Uncaught (in promise) Error: reference p1028 isn't known
    at p.error (bokeh-3.1.0.min.js:211:4951)
    at p._decode_ref (bokeh-3.1.0.min.js:211:4572)
    at p._decode (bokeh-3.1.0.min.js:211:1046)
    at p._decode_plain_object (bokeh-3.1.0.min.js:211:2340)
    at p._decode (bokeh-3.1.0.min.js:211:1066)
    at p._decode_object_ref (bokeh-3.1.0.min.js:211:4846)
    at p._decode (bokeh-3.1.0.min.js:211:1779)
    at bokeh-3.1.0.min.js:211:2249
    at f (bokeh-3.1.0.min.js:178:450)
    at p._decode_plain_array (bokeh-3.1.0.min.js:211:2237)
```

**Comment by zhaohongbo02** [comment]
I recently encountered this problem, the bokeh version is 3.1.1. Specifically, `center` needs to reference `left` (vertical axis) and `bottom` (horizontal axis). Although `center` is after `left` and `bottom` in the json order, it still reports an error when embedding and decoding. In addition to `Bokeh.embed.embed_item`, are there other ways to embed bokeh graphic data into the front end?

**Comment by zhaohongbo02** [comment]
My current solution is to reorder the attributes in the front-end bokeh chart data in the order of the correct data, and then embed them in the corresponding div.
