### ISSUE TITLE
[BUG] - Running the docs' "Specialized Axis Ticking" example fails due to Node compilation error

### ISSUE THREAD

**Issue by wswope-etiometry** [bokeh/bokeh#13228]
https://docs.bokeh.org/en/latest/docs/user_guide/advanced/extensions/ticking.html

### Software versions

Python version      :  3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.1.1
BokehJS static path :  /home/wswope/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v18.16.0
npm version         :  9.5.1
Operating system    :  Linux-5.15.0-75-generic-x86_64-with-glibc2.31

### Expected behavior

I expected the example to run without error.

### Observed behavior

Tornado returned a 500 response code, and a node-related error message in the console output.

### Example code

- Create a new directory.
- Copy the axis-ticking example code from the docs page to "ticking.py" in the new directory.
- Create, chmod, and run the following setup script in the same directory:

``` 
#!/usr/bin/env bash

cd "$(dirname "$0")"

# setup conda env
CONDA_BASE="$(conda info --base)"
source "${CONDA_BASE}/etc/profile.d/conda.sh"
conda create -n qis_bokeh -y
conda activate qis_bokeh
conda install --satisfied-skip-solve -y bokeh
conda install --satisfied-skip-solve -y nodejs

# run app
bokeh serve --show ticking.py
 ```

### Stack traceback or browser console output

 ```
 2023-06-22 15:08:26,170 Starting Bokeh server version 3.1.1 (running on Tornado 6.2)
2023-06-22 15:08:26,322 User authentication hooks NOT provided (default user enabled)
2023-06-22 15:08:26,324 Bokeh app running at: http://localhost:5006/ticking
2023-06-22 15:08:26,324 Starting Bokeh server with process id: 10623
2023-06-22 15:08:26,583 /home/USER/dev/bokeh_node_bug/ticking.py: call to show() ignored when running scripts with the 'bokeh' command.
2023-06-22 15:08:28,320 Uncaught exception GET /ticking (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/ticking', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/server/views/doc_handler.py", line 56, in get
    page = server_html_page_for_session(session,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/embed/server.py", line 253, in server_html_page_for_session
    bundle = bundle_for_objs_and_resources(None, resources)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/embed/bundle.py", line 211, in bundle_for_objs_and_resources
    ext = bundle_models(models)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 314, in bundle_models
    _bundle_cache[key] = bundle = _bundle_models(custom_models)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 521, in _bundle_models
    custom_impls = _compile_models(custom_models)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 498, in _compile_models
    compiled = nodejs_compile(impl.code, lang=impl.lang, file=impl.file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 114, in nodejs_compile
    output = _run_nodejs([compilejs_script], dict(code=code, lang=lang, file=file, bokehjs_dir=bokehjs_dir))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 449, in _run_nodejs
    return _run(_nodejs_path(), argv, input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 444, in _run
    raise RuntimeError(errout.decode('utf-8'))
RuntimeError: /home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/server/static/js/compiler.js:298875
        return /^[\p{Mc}\p{Me}\p{Mn}]$/u.test(String.fromCodePoint(codePoint));
               ^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid regular expression: /^[\p{Mc}\p{Me}\p{Mn}]$/: Invalid property name in character class
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

 ```

**Comment by bryevdv** [comment]
@wswope-etiometry That example is not a Bokeh server application, i.e. not meant to be run with `bokeh serve`. It is just plain python code that generates a static HTML page as output. It should be run like any other python script: `python ticking.py`

**Comment by wswope-etiometry** [comment]
@bryevdv Thank you for the response and taking the time to look into this!

For context, I ran into this bug in a larger Bokeh server project, and the docs example was the simplest reproduction method I could find. I'm expecting `show(...)` to be a no-op, though it never gets reached because the error appears to get triggered by the `MyFormatter()` instantiation.

The same error persists after tweaking the example to run in server context:

```

from bokeh.models import TickFormatter
from bokeh.plotting import figure, curdoc
from bokeh.util.compiler import TypeScript

CODE = """
import {TickFormatter} from "models/formatters/tick_formatter"

export class MyFormatter extends TickFormatter {
  // accepts a list of numbers (ticks) and returns a list of strings
  doFormat(ticks: string[] | number[]) {
    // format the first tick as-is
    const formatted = [`${ticks[0]}`]

    // format the rest as offsets from the first
    for (let i = 1; i < ticks.length; i++) {
      formatted.push(`+${(Number(ticks[i]) - Number(ticks[0])).toPrecision(2)}`)
    }
    return formatted
  }
}
"""


class MyFormatter(TickFormatter):
    __implementation__ = TypeScript(CODE)


p = figure()
p.circle([1, 2, 3, 4, 6], [5, 7, 3, 2, 4], size=20)

p.xaxis.formatter = MyFormatter()

curdoc().add_root(p)
```

Or am I misunderstanding you, and this usage of the bokeh API is invalid in the bokeh server context?
