### ISSUE TITLE
[BUG] Running the docs' "Specialized Axis Ticking" example fails due to Node compilation error

### ISSUE THREAD

**Issue by wswope-etiometry** [bokeh/bokeh#13234]
This is a tweaked resubmission of #13228, as I am able to replicate the bug in both the Bokeh desktop and server contexts.

### Software versions

Python version : 3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0]
IPython version : (not installed)
Tornado version : 6.2
Bokeh version : 3.1.1
BokehJS static path : /home/wswope/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/server/static
node.js version : v18.16.0
npm version : 9.5.1
Operating system : Linux-5.15.0-75-generic-x86_64-with-glibc2.31

### Expected behavior

I expected the example to run without error.

### Observed behavior

A runtime error is triggered.

### Example code

https://docs.bokeh.org/en/latest/docs/user_guide/advanced/extensions/ticking.html

- Create a new directory.
- Copy the axis-ticking example code from the docs page to "ticking.py" in the new directory.
- Create, chmod, and run the following setup script in the same directory:

```
#!/usr/bin/env bash

cd "$(dirname "$0")"

# setup conda env
CONDA_BASE="$(conda info --base)"
source "${CONDA_BASE}/etc/profile.d/conda.sh"
conda create -n qis_bokeh -y
conda activate qis_bokeh
conda install --satisfied-skip-solve -y bokeh
conda install --satisfied-skip-solve -y nodejs

# run app (normal bokeh desktop context)
python ticking.py
# run app (server context)
bokeh serve --show ticking.py
```

Tweaked example to run in server context (only lines touched were the final line and the imports):
```

from bokeh.models import TickFormatter
from bokeh.plotting import figure, curdoc
from bokeh.util.compiler import TypeScript

CODE = """
import {TickFormatter} from "models/formatters/tick_formatter"

export class MyFormatter extends TickFormatter {
  // accepts a list of numbers (ticks) and returns a list of strings
  doFormat(ticks: string[] | number[]) {
    // format the first tick as-is
    const formatted = [`${ticks[0]}`]

    // format the rest as offsets from the first
    for (let i = 1; i < ticks.length; i++) {
      formatted.push(`+${(Number(ticks[i]) - Number(ticks[0])).toPrecision(2)}`)
    }
    return formatted
  }
}
"""


class MyFormatter(TickFormatter):
    __implementation__ = TypeScript(CODE)


p = figure()
p.circle([1, 2, 3, 4, 6], [5, 7, 3, 2, 4], size=20)

p.xaxis.formatter = MyFormatter()


curdoc().add_root(p)
```

### Stack traceback or browser console output

Error when run in usual Bokeh context:
```
Traceback (most recent call last):
  File "/home/USER/dev/bokeh_node_bug/ticking.py", line 35, in <module>
    show(p)
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/io/showing.py", line 143, in show
    return _show_with_state(obj, state, browser, new, notebook_handle=notebook_handle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/io/showing.py", line 194, in _show_with_state
    _show_file_with_state(obj, state, new, controller)
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/io/showing.py", line 175, in _show_file_with_state
    filename = save(obj, state=state)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/io/saving.py", line 98, in save
    _save_helper(obj, filename, resources, title, template, theme)
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/io/saving.py", line 164, in _save_helper
    html = file_html(obj, resources, title=title, template=template or FILE, theme=theme)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/embed/standalone.py", line 359, in file_html
    bundle = bundle_for_objs_and_resources([doc], resources)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/embed/bundle.py", line 211, in bundle_for_objs_and_resources
    ext = bundle_models(models)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 314, in bundle_models
    _bundle_cache[key] = bundle = _bundle_models(custom_models)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 521, in _bundle_models
    custom_impls = _compile_models(custom_models)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 498, in _compile_models
    compiled = nodejs_compile(impl.code, lang=impl.lang, file=impl.file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 114, in nodejs_compile
    output = _run_nodejs([compilejs_script], dict(code=code, lang=lang, file=file, bokehjs_dir=bokehjs_dir))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 449, in _run_nodejs
    return _run(_nodejs_path(), argv, input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 444, in _run
    raise RuntimeError(errout.decode('utf-8'))
RuntimeError: /home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/server/static/js/compiler.js:298875
        return /^[\p{Mc}\p{Me}\p{Mn}]$/u.test(String.fromCodePoint(codePoint));
               ^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid regular expression: /^[\p{Mc}\p{Me}\p{Mn}]$/: Invalid property name in character class
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

Error when run in server context:
```
2023-06-22 15:08:26,170 Starting Bokeh server version 3.1.1 (running on Tornado 6.2)
2023-06-22 15:08:26,322 User authentication hooks NOT provided (default user enabled)
2023-06-22 15:08:26,324 Bokeh app running at: http://localhost:5006/ticking
2023-06-22 15:08:26,324 Starting Bokeh server with process id: 10623
2023-06-22 15:08:26,583 /home/USER/dev/bokeh_node_bug/ticking.py: call to show() ignored when running scripts with the 'bokeh' command.
2023-06-22 15:08:28,320 Uncaught exception GET /ticking (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/ticking', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
 File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/tornado/web.py", line 1713, in _execute
   result = await result
            ^^^^^^^^^^^^
 File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/server/views/doc_handler.py", line 56, in get
   page = server_html_page_for_session(session,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/embed/server.py", line 253, in server_html_page_for_session
   bundle = bundle_for_objs_and_resources(None, resources)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/embed/bundle.py", line 211, in bundle_for_objs_and_resources
   ext = bundle_models(models)
         ^^^^^^^^^^^^^^^^^^^^^
 File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 314, in bundle_models
   _bundle_cache[key] = bundle = _bundle_models(custom_models)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 521, in _bundle_models
   custom_impls = _compile_models(custom_models)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 498, in _compile_models
   compiled = nodejs_compile(impl.code, lang=impl.lang, file=impl.file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 114, in nodejs_compile
   output = _run_nodejs([compilejs_script], dict(code=code, lang=lang, file=file, bokehjs_dir=bokehjs_dir))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 449, in _run_nodejs
   return _run(_nodejs_path(), argv, input)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/util/compiler.py", line 444, in _run
   raise RuntimeError(errout.decode('utf-8'))
RuntimeError: /home/USER/anaconda3/envs/qis_bokeh/lib/python3.11/site-packages/bokeh/server/static/js/compiler.js:298875
       return /^[\p{Mc}\p{Me}\p{Mn}]$/u.test(String.fromCodePoint(codePoint));
              ^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid regular expression: /^[\p{Mc}\p{Me}\p{Mn}]$/: Invalid property name in character class
   at internalCompileFunction (node:internal/vm:73:18)
   at wrapSafe (node:internal/modules/cjs/loader:1176:20)
   at Module._compile (node:internal/modules/cjs/loader:1218:27)
   at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
   at Module.load (node:internal/modules/cjs/loader:1117:32)
   at Module._load (node:internal/modules/cjs/loader:958:12)
   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
   at node:internal/main/run_main_module:23:47
```

**Comment by bryevdv** [comment]
@mattpap any thoughts on this one?

**Comment by mattpap** [comment]
This appears to be a valid regex on node 18.*:
```
$ node
Welcome to Node.js v18.16.1.
Type ".help" for more information.
> x = /^[\p{Mc}\p{Me}\p{Mn}]$/u
/^[\p{Mc}\p{Me}\p{Mn}]$/u
> 
```
I think that this only can happen if some other version of nodejs is being picked up for extension compilation. Usually the system wide install of nodejs, if available, is very outdated.

**Comment by wswope-etiometry** [comment]
Hello!

@mattpap Your guess appears to have been right on the money. 

I tried to replicate again today, but couldn't. 

I remembered checking `which npm` at the time and confirming that it was pointing to the conda env, so for good measure, I tweaked the run script to:

```
conda install -y bokeh==3.1.1
conda install -y nodejs==18.16.0

echo "$(which npm)"
echo "$(which nodejs)"
```

which output:

```
/home/USER/anaconda3/envs/qis_bokeh/bin/npm
/usr/bin/nodejs
```

Seemed weird, since I do have a system-installed `/usr/bin/npm` as well, but I took a look at my conda path (`/home/USER/anaconda3/envs/qis_bokeh/bin`), and it appears there's no `nodejs` binary there, only `node`.

Whoops. Apologies for my oversight, and thanks for taking a look at this! 

I'll take a look in the next few days to see if I can figure out why `bokeh info` was picking up the conda-installed `node` version, whereas Bokeh's compilation callout wasn't. Very minor issue, but might be worth patching over for the next person who comes along.

**Comment by bryevdv** [comment]
@mattpap presumably we can check the `nodejs` version at runtime as well, what do you think of re-purposing this issue to add a runtime version check and more specific error for too-old versions?

**Comment by wswope-etiometry** [comment]
@bryevdv Funny enough, that's already implemented under bokeh/src/bokeh/util/compiler.py:

https://github.com/bokeh/bokeh/blob/8fa062ac8938a6c064caa2dd50be7013f04fa2f7/src/bokeh/util/compiler.py#L387

I spent over an hour in pdb trying to poke holes in the logic, but couldn't find a single flaw.

I also checked the 3.0-3.3 branches for recent changes to the file that could've been related, and didn't find anything on that front either.

**Comment by mattpap** [comment]
The flaw is with having very old version of nodejs as the lower bound:

https://github.com/bokeh/bokeh/blob/d2030a42cf678b8559a80e8bc4f8b006e78913b2/src/bokeh/util/compiler.py#L99
