### ISSUE TITLE
[BUG] export_png() need webdriver ，No need to pass on the first use

### ISSUE THREAD

**Issue by dyw618** [bokeh/bokeh#13361]
### Software versions

Python version      :  3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.3.2
Bokeh version       :  3.2.1
BokehJS static path :  E:\ProgramFiles\anaconda3\envs\python311\Lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19044-SP0
-----------------------------------------------------------------
selenium                  3.141.0         py311h2bbff1b_1000    https://mirrors.ustc.edu.cn/anaconda/pkgs/main

### Browser name and version

Chrome  116.0.5845.141

### Expected behavior

    x = [1, 2, 3, 4, 5]
    y = [6, 7, 2, 4, 5]
    p = figure(title=None)
    source = ColumnDataSource(data=dict(x=x, y=y))
    p.circle(x='x', y='y', source=source)
    export_png(p, filename="./123.png")

### Observed behavior

Traceback (most recent call last):
  File "D:\python_image\text_image2.py", line 66, in <module>
    test()
  File "D:\python_image\text_image2.py", line 61, in test
    export_png(p, filename="./123.png")
  File "E:\ProgramFiles\anaconda3\envs\python311\Lib\site-packages\bokeh\io\export.py", line 115, in export_png
    image = get_screenshot_as_png(obj, width=width, height=height, driver=webdriver, timeout=timeout, state=state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFiles\anaconda3\envs\python311\Lib\site-packages\bokeh\io\export.py", line 253, in get_screenshot_as_png
    web_driver = driver if driver is not None else webdriver_control.get()
                                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFiles\anaconda3\envs\python311\Lib\site-packages\bokeh\io\webdriver.py", line 138, in get
    self.current = self.create()
                   ^^^^^^^^^^^^^
  File "E:\ProgramFiles\anaconda3\envs\python311\Lib\site-packages\bokeh\io\webdriver.py", line 142, in create
    driver = self._create(kind)
             ^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFiles\anaconda3\envs\python311\Lib\site-packages\bokeh\io\webdriver.py", line 160, in _create
    raise RuntimeError("Neither firefox and geckodriver nor a variant of chromium browser and " \
RuntimeError: Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the former with 'conda install -c conda-forge firefox geckodriver'.

### Example code

```Python
from bokeh.io import export_png
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

    x = [1, 2, 3, 4, 5]
    y = [6, 7, 2, 4, 5]
    p = figure(title=None)
    source = ColumnDataSource(data=dict(x=x, y=y))
    p.circle(x='x', y='y', source=source)
    export_png(p, filename="./123.png")
```

### Stack traceback or browser console output

Traceback (most recent call last):
  File "D:\python_image\text_image2.py", line 66, in <module>
    test()
  File "D:\python_image\text_image2.py", line 61, in test
    export_png(p, filename="./123.png")
  File "E:\ProgramFiles\anaconda3\envs\python311\Lib\site-packages\bokeh\io\export.py", line 115, in export_png
    image = get_screenshot_as_png(obj, width=width, height=height, driver=webdriver, timeout=timeout, state=state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFiles\anaconda3\envs\python311\Lib\site-packages\bokeh\io\export.py", line 253, in get_screenshot_as_png
    web_driver = driver if driver is not None else webdriver_control.get()
                                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFiles\anaconda3\envs\python311\Lib\site-packages\bokeh\io\webdriver.py", line 138, in get
    self.current = self.create()
                   ^^^^^^^^^^^^^
  File "E:\ProgramFiles\anaconda3\envs\python311\Lib\site-packages\bokeh\io\webdriver.py", line 142, in create
    driver = self._create(kind)
             ^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFiles\anaconda3\envs\python311\Lib\site-packages\bokeh\io\webdriver.py", line 160, in _create
    raise RuntimeError("Neither firefox and geckodriver nor a variant of chromium browser and " \
RuntimeError: Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the former with 'conda install -c conda-forge firefox geckodriver'.

**Comment by dyw618** [comment]
When I first used bokeh, export_png does not need to pass webdriver parameters, I don't know what to do。Is it the version issue？

**Comment by bryevdv** [comment]
Hi @DuanYang5 Bokeh attempts to auto-detect the relevant webdriver by looking in various common locations, but ultimately, this is a system configuration matter that is outside our control. Happy to advise on ways try to get things working or set up on your specific system, but that is a support question, not a bug, so this discussion belongs on the community discourse: https://discourse.bokeh.org/
