### ISSUE TITLE
[BUG] DataTable autosize_mode="fit_viewport" raises ReferenceError

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#13460]
### Expected behavior

My expectation is, that all `autosize_mode`s of the `DataTable` can be displayed without an error.

### Observed behavior

The two modes `"fit_viewport"` and `"fit_columns"` both raise a `ReferenceError` shown in the Browser Console.

```
VM188 bokeh-tables-3.3.0.min.js:92
    Uncaught (in promise) ReferenceError: row is not defined
    at getColContentSize (VM188 bokeh-tables-3.3.0.min.js:92:48514)
    at getColAutosizeWidth (VM188 bokeh-tables-3.3.0.min.js:92:47153)
    at SlickGrid.autosizeColumns (VM188 bokeh-tables-3.3.0.min.js:92:44466)
    at M.updateLayout (VM188 bokeh-tables-3.3.0.min.js:55:3085)
    at M._after_render (VM188 bokeh-tables-3.3.0.min.js:55:6623)
    at M.after_render (VM185 bokeh-3.3.0.min.js:560:6522)
    at M.r_after_render (VM185 bokeh-3.3.0.min.js:560:6487)
    at M.render_to (VM185 bokeh-3.3.0.min.js:560:6323)
    at VM185 bokeh-3.3.0.min.js:218:834
    at async u (bokeh-3.3.0.min.js:218:657)
```

### Example code

```Python
from datetime import date
from random import randint

from bokeh.models import ColumnDataSource, DataTable, DateFormatter, TableColumn
from bokeh.io import show, output_notebook
output_notebook()

data = dict(
    dates=[date(2023, 3, i+1) for i in range(3)],
    downloads=[randint(0, 100) for i in range(3)],
)
source = ColumnDataSource(data)

columns = [
    TableColumn(field="dates", title="Date", formatter=DateFormatter()),
    TableColumn(field="downloads", title="Downloads"),
]

data_table_viewport = DataTable(
    source=source,
    columns=columns,
    width=400,
    height=100,
    autosize_mode = "fit_viewport", # same for "fit_columns"
)
show(data_table_viewport)
```
<details>
<summary>Software versions</summary>
Python version      :  3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  3.3.0
BokehJS static path :  /opt/conda/envs/aiva-env/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v18.16.0
npm version         :  9.5.1
Operating system    :  Linux-4.19.0-21-amd64-x86_64-with-glibc2.35

Chrome Version 118.0.5993.71
</details>

**Comment by mosc9575** [comment]
I want to mention that the issue above only appears if the `ColumnDataSource` takes a `dict` as input. If I first create a pandas DataFrame and then create the source from the DataFrame, the code works as expected.

Here is the same example again, but working because of pandas.

```python
import pandas as pd # added

from datetime import date
from random import randint

from bokeh.models import ColumnDataSource, DataTable, DateFormatter, TableColumn
from bokeh.io import show, output_notebook
output_notebook()

data = dict(
    dates=[date(2023, 3, i+1) for i in range(3)],
    downloads=[randint(0, 100) for i in range(3)],
)
source = ColumnDataSource(pd.DataFrame(data)) # adapted

columns = [
    TableColumn(field="dates", title="Date", formatter=DateFormatter()),
    TableColumn(field="downloads", title="Downloads"),
]

data_table_viewport = DataTable(
    source=source,
    columns=columns,
    width=400,
    height=100,
    autosize_mode = "fit_viewport", # same for "fit_columns"
)
show(data_table_viewport)
```

![grafik](https://github.com/bokeh/bokeh/assets/68053396/2cdfa685-1f9b-47cc-a7de-98714a2e23de)


Taking a look into the source object, the difference between these two sources is, that the data is once stored in a numpy array and one in a list. I hope this gives a hint to the solution.

## Update

In some other cases, the pandas conversion doesn't help.

```python
import pandas as pd

from bokeh.io import show, output_notebook
from bokeh.models import ColumnDataSource, TableColumn
from bokeh.models.widgets import DataTable
output_notebook()

data = {
    "column_1": ['a', 'b', 'c'],
    "column_2": [4, 5, 6],
    "column_3": [7, 8, 9],
}

data_table = DataTable(
    source=ColumnDataSource(pd.DataFrame(data)),
    columns=[TableColumn(field=col, title=col) for col in data.keys()],
    width=400,
    height=280,
    autosize_mode="fit_viewport",
)

show(data_table)
```

**Comment by bryevdv** [comment]
@mattpap was this fixed in a PR somewhere? Or should it be moved out of 3.3.1?

**Comment by bryevdv** [comment]
@mattpap any comment on this? I was about to start 3.3.1rc1 then remembered this is still open in the milestone

**Comment by muendlein** [comment]
This does not seem to be an issue anymore (after migration to slickgrid 5.18)

**Comment by mosc9575** [comment]
I tried to run the MRE with the latest commit and I get the following errors:

```
VM244 bokeh-3.10.0.dev4.min.js:305 [bokeh 3.10.0-dev.4] DataTableView(p1036) wasn't built properly
VM242 bokeh-tables-3.10.0.dev4.min.js:93 Uncaught Error: SlickGrid Cannot find stylesheet.
VM244 bokeh-3.10.0.dev4.min.js:305 [bokeh 3.10.0-dev.4] DataTableView(p1054) wasn't built properly
VM242 bokeh-tables-3.10.0.dev4.min.js:93 Uncaught ReferenceError: row is not defined
VM244 bokeh-3.10.0.dev4.min.js:186 [bokeh 3.10.0-dev.4] setting log level to: 'info'
VM242 bokeh-tables-3.10.0.dev4.min.js:93 Uncaught (in promise) ReferenceError: row is not defined
```

**Comment by mattpap** [comment]
> `bokeh-3.10.0.dev4.min.js`

You have a mismatch between your bokeh version and bokehjs. I just started dev5 build, which will contain SlickGrid 5.18 upgrade.

**Comment by mattpap** [comment]
I can confirm this doesn't throw any exceptions anymore. We may want to add a regression test for this though.

**Comment by mosc9575** [comment]
The case using "fit_columns" is still buggy. The numbers for the downloads only become visible after an interaction with the table.

https://github.com/user-attachments/assets/b3dc0bed-3880-4653-a7d3-9bcf09d8494a

**Comment by muendlein** [comment]
@mosc9575 Thank you, this is still a bug, I have created a separate issue for that: https://github.com/bokeh/bokeh/issues/15123

**Comment by muendlein** [comment]
@mosc9575 The additional bug should be resolved now, could you check if this is also the case with your notebook?

**Comment by mosc9575** [comment]
I can confirm that the output is now correctly displayed.
