### ISSUE TITLE
[BUG] v3 vs v2 of bokeh

### ISSUE THREAD

**Issue by hmkim** [bokeh/bokeh#13498]
### Software versions

Python version      :  3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]
IPython version     :  8.7.0
Tornado version     :  6.2
Bokeh version       :  3.0.0
BokehJS static path :  /Users/hyunmink/mambaforge/envs/lab/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v20.9.0
npm version         :  10.1.0
Operating system    :  macOS-13.6-arm64-arm-64bit

### Browser name and version

Firefox, Chrome

### Expected behavior

Visible with v2.4.3

In versions 3.0.0 and later, the plot is not visible.

### Observed behavior

Not seen

### Example code

```Python
https://github.com/aws-samples/amazon-omics-tutorials/blob/main/utils/scripts/timeline.py
```

### Screenshots

v3.0.0 and later
<img width="692" alt="v3 0 0" src="https://github.com/bokeh/bokeh/assets/4966343/23dfd083-be8a-461b-ade2-70908e41b316">

v2.4.3
<img width="1214" alt="v2 4 3" src="https://github.com/bokeh/bokeh/assets/4966343/5769d60c-9885-4ff8-9633-9084a3fc5ba5">

**Comment by bryevdv** [comment]
@hmkim There is a lot going on in the linked code that surely has nothing to do with any issue (CLI arg argparsing, AWS boto calls, etc). We really need a complete [***Minimal*** Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) (emphasis on minimal in this case), so my first suggestion is to pare down the example to code drastically, to just whatever is needed to see the issue (e.g. with synthetic or saved data and no AWS access, etc). At the very least, since there are lots of command line options, you need to provide exact instructions for running the code.

**Comment by hmkim** [comment]
@bryevdv   Thanks for reply. 
[example.zip](https://github.com/bokeh/bokeh/files/13233269/example.zip)
Attached the code & data.

You may also be interested in
https://github.com/bokeh/bokeh/issues/13436

**Comment by bryevdv** [comment]
@hmkim when  try to run your code I get this error (pandas 2.1.1 is installed)
```
Traceback (most recent call last):
  File "/Users/bryan/Desktop/example/test.py", line 107, in <module>
    main()
  File "/Users/bryan/Desktop/example/test.py", line 15, in main
    data = pickle.load(f)
           ^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'
```

**Comment by bryevdv** [comment]
@hmkim are you able to provide more direction on how to run your code?

**Comment by hmkim** [comment]
@bryevdv  Sorry for late reply. 

This issue is caused by the new breaking backwards compatibility with Pandas 1.x, although I don't see this documented in the release notes. The solution is to downgrade pandas to the 1.x series: pip install "pandas<2.0.0"

Anyway, I updated the code. Here are new attached file. 
[example.zip](https://github.com/bokeh/bokeh/files/13392947/example.zip)

**Comment by bryevdv** [comment]
@mattpap I can reproduce the issue with the latest zip file above. As a quick test, if all the sizing modes are changed to "fixed" then the plots do render in some fashion. 

<img width="1263" alt="Screenshot 2023-12-07 at 11 12 02" src="https://github.com/bokeh/bokeh/assets/1078448/3caf432e-454d-4aab-bb95-23febdcaa22a">

Not sure if there is us 3.x usage change that needs to happen or if its just a bug. 

Edit: in fact it renders even if just the first `stretch_both` is changed to `fixed` (but not `stretch_height` — it seems at least one element needs to have a fixed height)
