### ISSUE TITLE
[BUG] Missing SRI hash for version 2.2.2

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#13524]
### Software versions

Python version        :  3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
IPython version       :  8.17.2
Tornado version       :  6.3.3
Bokeh version         :  3.4.0.dev3+12.g8265814f
BokehJS static path   :  /home/jovyan/private/bokeh/src/bokeh/server/static
node.js version       :  v20.5.1
npm version           :  10.2.3
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-4.19.0-21-amd64-x86_64-with-glibc2.35

### Browser name and version

Chrome Version 119.0.6045.106

### Observed behavior

When creating the documentation a ValueError is raised with the message `Missing SRI hash for version 2.2.2`. This error was first raised in the pipeline for the documentation of #13488 and is still part of the latest documentation pipeline.

See also: https://github.com/bokeh/bokeh/actions/runs/6670553617/job/18130816857

This leads to a failing documentation build.

### Example code

```Python
from os import listdir
from os.path import join

from packaging.version import Version as V

from bokeh.resources import get_sri_hashes_for_version

srcdir = '~/bokeh/docs/bokeh/source/'

versions = [x.rstrip(".rst") for x in listdir(join(srcdir, "docs", "releases")) if x.endswith(".rst")]
versions.sort(key=V, reverse=True)

rst = []

for v in versions[1:]:
    try:
        hashes = get_sri_hashes_for_version(v)
    except:
        raise RuntimeError(f"Missing SRI Hash for full release version {v!r}")
```

Replacing the error with a print statement shows all versions without a json file in the `bokeh/src/bokeh/_sri/` folder.

```
Missing SRI Hash for full release version '2.2.2'
Missing SRI Hash for full release version '2.2.0'
Missing SRI Hash for full release version '0.7.1'
Missing SRI Hash for full release version '0.7.0'
Missing SRI Hash for full release version '0.6.1'
Missing SRI Hash for full release version '0.6.0'
Missing SRI Hash for full release version '0.5.2'
Missing SRI Hash for full release version '0.5.1'
Missing SRI Hash for full release version '0.5.0'
Missing SRI Hash for full release version '0.4.4'
Missing SRI Hash for full release version '0.4.2'
Missing SRI Hash for full release version '0.4.1'
Missing SRI Hash for full release version '0.4.0'
Missing SRI Hash for full release version '0.3.0'
Missing SRI Hash for full release version '0.2.0'
Missing SRI Hash for full release version '0.1.0'
```

### Stack traceback or browser console output

This traceback is copied from the mentioned pipeline https://github.com/bokeh/bokeh/actions/runs/6670553617/job/18130816857

```
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/resources.py", line 165, in get_sri_hashes_for_version
    with open(join(ROOT_DIR, "_sri", f"{version}.json")) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/_sri/2.2.2.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 420, in read
    self._read_serial(docnames)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 441, in _read_serial
    self.read_doc(docname)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 498, in read_doc
    publisher.publish()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/parsers.py", line 81, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2355, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/sphinxext/bokeh_releases.py", line 83, in run
    hashes = get_sri_hashes_for_version(v)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/resources.py", line 168, in get_sri_hashes_for_version
    raise ValueError(f"Missing SRI hash for version {version}") from e
ValueError: Missing SRI hash for version 2.2.2
```

**Comment by bryevdv** [comment]
SRI hashes were introduced with 2.3 IIRC. There's a few ways to handle this

* Add a version check in `conf.py` (quick and easy)
* Add empty JSON files for the missing versions (might "work")
* Add actual SRI hashes for the old versions

The last option is probably the "ideal" outcome, but will also probably be fairly tedious for whoever undertakes it.
