### ISSUE TITLE
[BUG] Unexpected attribute 'size' to Circle

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#13525]
### Software versions

Python version        :  3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
IPython version       :  8.17.2
Tornado version       :  6.3.3
Bokeh version         :  3.4.0.dev3+12.g8265814f
BokehJS static path   :  /home/jovyan/private/bokeh/src/bokeh/server/static
node.js version       :  v20.5.1
npm version           :  10.2.3
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-4.19.0-21-amd64-x86_64-with-glibc2.35

### Browser name and version

Chrome Version 119.0.6045.106

### Observed behavior

The model `Circle` doesn't except `size` anymore. This error appears in the building of the documentation since #13283 many times.

The easiest way to reproduce is the Circle.py example in `~/bokeh/examples/reference/models/Circle.py`.

```
import numpy as np

from bokeh.io import curdoc, show
from bokeh.models import Circle, ColumnDataSource, Grid, LinearAxis, Plot

N = 9
x = np.linspace(-2, 2, N)
y = x**2
sizes = np.linspace(10, 20, N)

source = ColumnDataSource(dict(x=x, y=y, sizes=sizes))

plot = Plot(
    title=None, width=300, height=300,
    min_border=0, toolbar_location=None)

glyph = Circle(x="x", y="y", size="sizes", line_color="#3288bd", fill_color="white", line_width=3)
plot.add_glyph(source, glyph)

xaxis = LinearAxis()
plot.add_layout(xaxis, 'below')

yaxis = LinearAxis()
plot.add_layout(yaxis, 'left')

plot.add_layout(Grid(dimension=0, ticker=xaxis.ticker))
plot.add_layout(Grid(dimension=1, ticker=yaxis.ticker))

curdoc().add_root(plot)
```

See this pipeline: https://github.com/bokeh/bokeh/actions/runs/6784549466/job/18447140955

One way to solve is to rename `size` to `radius` and `sizes` to `radii`.

### Stack traceback or browser console output

```
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/sphinxext/bokeh_plot.py", line 174, in run
    (script_tag, js_path, source, docstring, height_hint) = self.process_source(source, path, js_filename)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/sphinxext/bokeh_plot.py", line 237, in process_source
    root, docstring = _evaluate_source(source, path, self.env)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/sphinxext/bokeh_plot.py", line 353, in _evaluate_source
    raise RuntimeError(f"bokeh-plot:: error:\n\n{c.error_detail}\n\nevaluating source:\n\n{source}")
RuntimeError: bokeh-plot:: error:

Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/application/handlers/code_runner.py", line 229, in run
    exec(self._code, module.__dict__)
  File "/home/runner/work/bokeh/bokeh/examples/reference/models/Circle.py", line 17, in <module>
    glyph = Circle(x="x", y="y", size="sizes", line_color="#3288bd", fill_color="white", line_width=3)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/glyphs.py", line 452, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/glyph.py", line 80, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/glyph.py", line 101, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/glyph.py", line 111, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/glyph.py", line 131, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/glyph.py", line 58, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/model/model.py", line 110, in __init__
    super().__init__(**kwargs)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/core/has_props.py", line 305, in __init__
    setattr(self, name, value)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/core/has_props.py", line 343, in __setattr__
    self._raise_attribute_error_with_matches(name, properties)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/core/has_props.py", line 378, in _raise_attribute_error_with_matches
    raise AttributeError(f"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}")
AttributeError: unexpected attribute 'size' to Circle, possible attributes are decorations, fill_alpha, fill_color, hatch_alpha, hatch_color, hatch_extra, hatch_pattern, hatch_scale, hatch_weight, hit_dilation, js_event_callbacks, js_property_callbacks, line_alpha, line_cap, line_color, line_dash, line_dash_offset, line_join, line_width, name, radius, radius_dimension, radius_units, subscribed_events, syncable, tags, x or y


evaluating source:

import numpy as np

from bokeh.io import curdoc, show
from bokeh.models import Circle, ColumnDataSource, Grid, LinearAxis, Plot

N = 9
x = np.linspace(-2, 2, N)
y = x**2
sizes = np.linspace(10, 20, N)

source = ColumnDataSource(dict(x=x, y=y, sizes=sizes))

plot = Plot(
    title=None, width=300, height=300,
    min_border=0, toolbar_location=None)

glyph = Circle(x="x", y="y", size="sizes", line_color="#3288bd", fill_color="white", line_width=3)
plot.add_glyph(source, glyph)

xaxis = LinearAxis()
plot.add_layout(xaxis, 'below')

yaxis = LinearAxis()
plot.add_layout(yaxis, 'left')

plot.add_layout(Grid(dimension=0, ticker=xaxis.ticker))
plot.add_layout(Grid(dimension=1, ticker=yaxis.ticker))

curdoc().add_root(plot)

show(plot)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 420, in read
    self._read_serial(docnames)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 441, in _read_serial
    self.read_doc(docname)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 498, in read_doc
    publisher.publish()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/parsers.py", line 81, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2355, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/domains/__init__.py", line 289, in run
    return super().run()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/sphinxext/bokeh_model.py", line 154, in run
    return self.parse(rst_text, "<bokeh-model>")
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/sphinxext/bokeh_directive.py", line 70, in parse
    nested_parse_with_titles(self.state, result, node)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/util/nodes.py", line 333, in nested_parse_with_titles
    return state.nested_parse(content, content_offset, node, match_titles=1)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2355, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/ext/autodoc/directive.py", line 150, in run
    result = parse_generated_content(self.state, params.result, documenter)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/ext/autodoc/directive.py", line 92, in parse_generated_content
    nested_parse_with_titles(state, content, node)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/util/nodes.py", line 333, in nested_parse_with_titles
    return state.nested_parse(content, content_offset, node, match_titles=1)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2355, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/domains/__init__.py", line 289, in run
    return super().run()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/directives/__init__.py", line 285, in run
    nested_parse_with_titles(self.state, self.content, contentnode, self.content_offset)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/util/nodes.py", line 333, in nested_parse_with_titles
    return state.nested_parse(content, content_offset, node, match_titles=1)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2357, in explicit_markup
    self.explicit_list(blank_finish)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2382, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 316, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2660, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/sphinxext/bokeh_plot.py", line 176, in run
    raise SphinxError(f"Error generating {js_filename}: \n\n{e}")
sphinx.errors.SphinxError: Error generating bokeh-content-ce5005193f5a4ab48fb41207f5faaadf-docs-reference-models-glyphs-circle.js: 

bokeh-plot:: error:
```

**Comment by mattpap** [comment]
These:
```
reading sources... [ 63%] docs/first_steps/first_steps_2
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
reading sources... [ 63%] docs/first_steps/first_steps_3
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
reading sources... [ 63%] docs/first_steps/first_steps_4
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
reading sources... [ 63%] docs/first_steps/first_steps_5
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
reading sources... [ 63%] docs/first_steps/first_steps_6
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'triangle() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='triangle', ...) instead" instead.
BokehDeprecationWarning: 'square() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='square', ...) instead" instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'triangle() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='triangle', ...) instead" instead.
BokehDeprecationWarning: 'square() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='square', ...) instead" instead.
reading sources... [ 64%] docs/first_steps/first_steps_7
reading sources... [ 64%] docs/first_steps/first_steps_8
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
reading sources... [ 64%] docs/first_steps/first_steps_9
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
```
must be updated as well.

**Comment by mattpap** [comment]
Those errors need to be surfaced in docs' CI job. We should have caught that in the original PR.

**Comment by mattpap** [comment]
TODO:
- [x] change `Circle(size=...)` to `Circle(radius=...)`
- [x] fix any remaining deprecations in docs/examples
- [x] resolve unknown column `radius` (see e.g. `periodic_shells` example)
- [x] surface errors in docs' CI job
