### ISSUE TITLE
[BUG] Sphinx 7.2.6 raises ThemeError

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#13548]
### Software versions

Python version        :  3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
IPython version       :  8.18.0
Tornado version       :  6.3.3
Bokeh version         :  3.4.0.dev3+27.g2555a4f2.dirty
BokehJS static path   :  /home/jovyan/private/bokeh/bokehjs/build
node.js version       :  v20.9.0
npm version           :  10.2.4
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-4.19.0-21-amd64-x86_64-with-glibc2.35

### Observed behavior

I tried to build the docs with the latest version of Sphinx after creating a new `bkdev` conda environment.

```
Sphinx==7.2.6
sphinx-copybutton==0.5.2
sphinx-favicon==1.0.1
sphinx_design==0.5.0
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
```

It looks like the Sphinx version is not pinned to <7.x and therefor I got the latest version of the package. Running `make html` raise the error below.

```
Theme error:
An error happened in rendering the page docs/dev_guide.
Reason: ThemeError("Local asset file paths must not contain query strings: '_static/custom.css?v=3.4.0.dev3+27.g2555a4f2.dirty'")
```

This is because of [line 167 in `conf.py`](
https://github.com/bokeh/bokeh/blame/2555a4f2c91c3096b8e7a669a51d727d403b031b/docs/bokeh/source/conf.py#L167)

```
html_css_files = [f"custom.css?v={version}"]
```

which should be changed to 

```
html_css_files = ["custom.css"]
```
.

This will become more important if the next documentation should be build with the latest version of sphinx in a future release.

**Comment by bryevdv** [comment]
The version argument is for cache busting, and is what allows users to correctly pick up the new css file when a new version of the docs is published. I think actually we need to file a bug with Sphinx. 

Otherwise we are going to have to make the css file have an actual different file name like `custom-<version>.css` for every version, which will add more complexity on our end.

**Comment by mosc9575** [comment]
The changes are introduced in Sphinx 7.2.0 in [Raise an error when local asset files contain a `?`](https://github.com/sphinx-doc/sphinx/commit/44a7820cd9183203fe52982840210ee32523414f) and changed a bit in [
Move `_file_checksum()` to `sphinx.builders.html._assets`](https://github.com/sphinx-doc/sphinx/commit/42a654640444e0616557993ef043e0d0e892377d).

So we can use Sphinx before 7.2.0

**Comment by Azaya89** [comment]
I'm also having an error when trying to build the docs locally, although it's of a different type:

```
Running Sphinx v7.2.6
/Users/mac/Documents/development/bokeh/src/bokeh/sphinxext/bokeh_gallery.py:44: RemovedInSphinx80Warning: The alias 'sphinx.util.status_iterator' is deprecated, use 'sphinx.util.display.status_iterator' instead. Check CHANGES for Sphinx API modifications.
  from sphinx.util import ensuredir, status_iterator
/Users/mac/Documents/development/bokeh/src/bokeh/sphinxext/bokeh_plot.py:104: RemovedInSphinx80Warning: The alias 'sphinx.util.status_iterator' is deprecated, use 'sphinx.util.display.status_iterator' instead. Check CHANGES for Sphinx API modifications.
  from sphinx.util import copyfile, ensuredir, status_iterator
/Users/mac/Documents/development/bokeh/src/bokeh/sphinxext/bokeh_sitemap.py:41: RemovedInSphinx80Warning: The alias 'sphinx.util.status_iterator' is deprecated, use 'sphinx.util.display.status_iterator' instead. Check CHANGES for Sphinx API modifications.
  from sphinx.util import status_iterator
creating gallery file entries... [100%] missing_dates.rst
[autosummary] generating autosummary for: docs/dev_guide.rst, docs/dev_guide/bindings.rst, docs/dev_guide/bokehjs.rst, docs/dev_guide/creating_issues.rst, docs/dev_guide/debug_headless_chrome.rst, docs/dev_guide/documentation.rst, docs/dev_guide/env_vars.rst, docs/dev_guide/models.rst, docs/dev_guide/pull_requests.rst, docs/dev_guide/python.rst, ..., docs/user_guide/topics/contour.rst, docs/user_guide/topics/geo.rst, docs/user_guide/topics/graph.rst, docs/user_guide/topics/hex.rst, docs/user_guide/topics/hierarchical.rst, docs/user_guide/topics/images.rst, docs/user_guide/topics/pie.rst, docs/user_guide/topics/stats.rst, docs/user_guide/topics/timeseries.rst, index.rst
BokehDeprecationWarning: 'tile_providers module' was deprecated in Bokeh 3.0.0 and will be removed, use 'add_tile directly' instead.
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://xyzservices.readthedocs.io/en/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 607 source files that are out of date
updating environment: [new config] 607 added, 0 changed, 0 removed
Compilation failed:[  2%] docs/examples/advanced/extensions/putting_together

../../examples/advanced/extensions/putting_together.py:Custom.ts:3:22 - error TS2307: Cannot find module 'models/widgets/sliders/slider' or its corresponding type declarations.

3 import {Slider} from "models/widgets/sliders/slider"
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [html] Error 1
```

**Comment by mosc9575** [comment]
@Azaya89 The path to the Slider looks good to me.

> import {Slider} from "models/widgets/sliders/slider"

Can you check if you have installed `bokehjs` correctly. On Saturday I was able to build the docs after I changed the one line in the `conf.py` as described above. I expect that it should work for you, too.

**Comment by Azaya89** [comment]
> 
> Can you check if you have installed `bokehjs` correctly. On Saturday I was able to build the docs after I changed the one line in the `conf.py` as described above. I expect that it should work for you, too.

Thanks. So, I rebuilt my `bokehjs` dependencies and re-ran `pip install -e .`  However, after running `make clean html serve`, I got a different error message(something to do with the now deprecated Circle glyph):

```
rm -rf build/*
rm -rf source/docs/gallery/*
rm -rf source/docs/examples/*
Running Sphinx v7.2.6
/Users/mac/Documents/development/bokeh/src/bokeh/sphinxext/bokeh_gallery.py:44: RemovedInSphinx80Warning: The alias 'sphinx.util.status_iterator' is deprecated, use 'sphinx.util.display.status_iterator' instead. Check CHANGES for Sphinx API modifications.
  from sphinx.util import ensuredir, status_iterator
/Users/mac/Documents/development/bokeh/src/bokeh/sphinxext/bokeh_plot.py:104: RemovedInSphinx80Warning: The alias 'sphinx.util.status_iterator' is deprecated, use 'sphinx.util.display.status_iterator' instead. Check CHANGES for Sphinx API modifications.
  from sphinx.util import copyfile, ensuredir, status_iterator
/Users/mac/Documents/development/bokeh/src/bokeh/sphinxext/bokeh_sitemap.py:41: RemovedInSphinx80Warning: The alias 'sphinx.util.status_iterator' is deprecated, use 'sphinx.util.display.status_iterator' instead. Check CHANGES for Sphinx API modifications.
  from sphinx.util import status_iterator
making output directory... done
creating gallery file entries... [100%] missing_dates.rst
[autosummary] generating autosummary for: docs/dev_guide.rst, docs/dev_guide/bindings.rst, docs/dev_guide/bokehjs.rst, docs/dev_guide/creating_issues.rst, docs/dev_guide/debug_headless_chrome.rst, docs/dev_guide/documentation.rst, docs/dev_guide/env_vars.rst, docs/dev_guide/models.rst, docs/dev_guide/pull_requests.rst, docs/dev_guide/python.rst, ..., docs/user_guide/topics/contour.rst, docs/user_guide/topics/geo.rst, docs/user_guide/topics/graph.rst, docs/user_guide/topics/hex.rst, docs/user_guide/topics/hierarchical.rst, docs/user_guide/topics/images.rst, docs/user_guide/topics/pie.rst, docs/user_guide/topics/stats.rst, docs/user_guide/topics/timeseries.rst, index.rst
BokehDeprecationWarning: 'tile_providers module' was deprecated in Bokeh 3.0.0 and will be removed, use 'add_tile directly' instead.
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://xyzservices.readthedocs.io/en/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 607 source files that are out of date
updating environment: [new config] 607 added, 0 changed, 0 removed
/Users/mac/Documents/development/bokeh/examples/basic/annotations/band.py:23: FutureWarning: The provided callable <function mean at 0x1038d7a60> is currently using Rolling.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df2 = df.y.rolling(window=300).agg({"y_mean": np.mean, "y_std": np.std})
/Users/mac/Documents/development/bokeh/examples/basic/annotations/band.py:23: FutureWarning: The provided callable <function std at 0x1038d7ba0> is currently using Rolling.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  df2 = df.y.rolling(window=300).agg({"y_mean": np.mean, "y_std": np.std})
WARNING:bokeh.embed.util: docs/examples/interaction/js_callbacks/doc_js_events
You are generating standalone HTML/JS output, but trying to use real Python
callbacks (i.e. with on_change or on_event). This combination cannot work.

Only JavaScript callbacks may be used with standalone output. For more
information on JavaScript callbacks with Bokeh, see:

    https://docs.bokeh.org/en/latest/docs/user_guide/interaction/callbacks.html

Alternatively, to use real Python callbacks, a Bokeh server application may
be used. For more information on building and running Bokeh applications, see:

    https://docs.bokeh.org/en/latest/docs/user_guide/server.html

reading sources... [ 36%] docs/examples/models/glyphs
ERROR:bokeh.core.validation.check:E-1001 (BAD_COLUMN_NAME): Glyph refers to nonexistent column name. This could either be due to a misspelling or typo, or due to an expected column being missing. : text_font='Helvetica' [no close matches] {renderer: GlyphRenderer(id='p30887', ...)}
BokehDeprecationWarning: 'square() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='square', ...) instead" instead.
BokehDeprecationWarning: 'square() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='square', ...) instead" instead.
BokehDeprecationWarning: 'square() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='square', ...) instead" instead.
BokehDeprecationWarning: 'square() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='square', ...) instead" instead.
BokehDeprecationWarning: 'square() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='square', ...) instead" instead.
BokehDeprecationWarning: 'square() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='square', ...) instead" instead.
BokehDeprecationWarning: 'square() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='square', ...) instead" instead.
BokehDeprecationWarning: 'square() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='square', ...) instead" instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'triangle() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='triangle', ...) instead" instead.
BokehDeprecationWarning: 'square() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='square', ...) instead" instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'triangle() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='triangle', ...) instead" instead.
BokehDeprecationWarning: 'square() method' was deprecated in Bokeh 3.3.0 and will be removed, use "scatter(marker='square', ...) instead" instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.3.0 and will be removed, use 'scatter(size=...) instead' instead.
<bokeh-content>:1: ERROR: Unknown target name: "multiple kernel density estimation".
<bokeh-prop>:1: ERROR: Unexpected indentation.
<bokeh-model>:1: WARNING: Block quote ends without a blank line; unexpected unindent.
<bokeh-prop>:1: ERROR: Unexpected indentation.
<bokeh-model>:1: WARNING: Block quote ends without a blank line; unexpected unindent.
copying bokeh-plot files... [100%] bokeh-content-fe9eb6a78d684a5db9fb244c9174eaf7-docs-examples-plotting-histogram.js
adding links to sitemap... 

Sphinx error:
Error generating bokeh-content-40362131fa9044b5b90617c7c8a6f5b7-docs-reference-models-glyphs-circle.js: 

bokeh-plot:: error:

Traceback (most recent call last):
  File "/Users/mac/Documents/development/bokeh/src/bokeh/application/handlers/code_runner.py", line 229, in run
    exec(self._code, module.__dict__)
  File "/Users/mac/Documents/development/bokeh/examples/reference/models/Circle.py", line 17, in <module>
    glyph = Circle(x="x", y="y", size="sizes", line_color="#3288bd", fill_color="white", line_width=3)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Documents/development/bokeh/src/bokeh/models/glyphs.py", line 452, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/mac/Documents/development/bokeh/src/bokeh/models/glyph.py", line 80, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/mac/Documents/development/bokeh/src/bokeh/models/glyph.py", line 101, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/mac/Documents/development/bokeh/src/bokeh/models/glyph.py", line 111, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/mac/Documents/development/bokeh/src/bokeh/models/glyph.py", line 131, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/mac/Documents/development/bokeh/src/bokeh/models/glyph.py", line 58, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/mac/Documents/development/bokeh/src/bokeh/model/model.py", line 110, in __init__
    super().__init__(**kwargs)
  File "/Users/mac/Documents/development/bokeh/src/bokeh/core/has_props.py", line 305, in __init__
    setattr(self, name, value)
  File "/Users/mac/Documents/development/bokeh/src/bokeh/core/has_props.py", line 343, in __setattr__
    self._raise_attribute_error_with_matches(name, properties)
  File "/Users/mac/Documents/development/bokeh/src/bokeh/core/has_props.py", line 378, in _raise_attribute_error_with_matches
    raise AttributeError(f"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}")
AttributeError: unexpected attribute 'size' to Circle, possible attributes are decorations, fill_alpha, fill_color, hatch_alpha, hatch_color, hatch_extra, hatch_pattern, hatch_scale, hatch_weight, hit_dilation, js_event_callbacks, js_property_callbacks, line_alpha, line_cap, line_color, line_dash, line_dash_offset, line_join, line_width, name, radius, radius_dimension, radius_units, subscribed_events, syncable, tags, x or y


evaluating source:

import numpy as np

from bokeh.io import curdoc, show
from bokeh.models import Circle, ColumnDataSource, Grid, LinearAxis, Plot

N = 9
x = np.linspace(-2, 2, N)
y = x**2
sizes = np.linspace(10, 20, N)

source = ColumnDataSource(dict(x=x, y=y, sizes=sizes))

plot = Plot(
    title=None, width=300, height=300,
    min_border=0, toolbar_location=None)

glyph = Circle(x="x", y="y", size="sizes", line_color="#3288bd", fill_color="white", line_width=3)
plot.add_glyph(source, glyph)

xaxis = LinearAxis()
plot.add_layout(xaxis, 'below')

yaxis = LinearAxis()
plot.add_layout(yaxis, 'left')

plot.add_layout(Grid(dimension=0, ticker=xaxis.ticker))
plot.add_layout(Grid(dimension=1, ticker=yaxis.ticker))

curdoc().add_root(plot)

show(plot)

make: *** [html] Error 2
```

Progress, if you ask me :)

**Comment by mosc9575** [comment]
This looks much better now but it is not so easy to build the docs without errors right now.

Here are the steps I needed to do.

1. start at the branch [mattpap/13525_circle_size](https://github.com/bokeh/bokeh/tree/mattpap/13525_circle_size) to avoid your latest error
2. to avoid https://github.com/bokeh/bokeh/issues/13524 add empty json files, if you see an error "Missing SRI hash for version x.x.x" for each missing version
3. edit the `conf.py` to avoid the error of this issue

Hope it works now.

**Comment by bryevdv** [comment]
> AttributeError: unexpected attribute 'size' to Circle, possible attributes are decorations, fill_alpha, fill_color, hatch_alpha, hatch_color, hatch_extra, hatch_pattern, hatch_scale, hatch_weight, hit_dilation, js_event_callbacks, js_property_callbacks, line_alpha, line_cap, line_color, line_dash, line_dash_offset, line_join, line_width, name, radius, radius_dimension, radius_units, subscribed_events, syncable, tags, x or y


This seems like an example that needs updating for the recent scatter/circle work

**Comment by mattpap** [comment]
> This seems like an example that needs updating for the recent scatter/circle work

This and other issues alike are already fixed in PR https://github.com/bokeh/bokeh/pull/13535.

**Comment by bryevdv** [comment]
FYI @mosc9575 a related older sphinx issue: https://github.com/sphinx-doc/sphinx/issues/11133

I think for now, to close this issue, let's just pin the sphinx version to one that works.

**Comment by pradyunsg** [comment]
IIRC, Sphinx 7.1.0+ injects content checksum as query strings on css/JS assets, so doing the cache busting manually should no longer be necessary.

It might be worth checking if making the change suggested by OP results in Sphinx 7.1+ injecting a query string that achieves the same as what you're trying to achieve here.

**Comment by Azaya89** [comment]
> Hope it works now.

Thanks, I have finally gotten it to work through your suggestions.

**Comment by bryevdv** [comment]
👍 In that case we can resolve with @mosc9575 original proposal to update to 
```
html_css_files = ["custom.css"]
```
and, for good measure, setting sphinx 7.1 as a *minimum* version. 

It would be good to quickly check that things are working as expected in our complex docs build.
