### ISSUE TITLE
Problems initializing Models using BokehJS without Python

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#13732]
I have been experimenting using BokehJS without Python in TypeScript projects using webpack, React, etc, and as Jupyter extensions. Here is a demo of a WIP frontend-only Jupyter extension using BokehJS:
[jupyter_bokehjs.webm](https://github.com/bokeh/bokeh/assets/580326/a49bdc39-28c4-4996-9754-55823f3f8700)

Note that I am talking about explicitly creating BokehJS objects in the browser rather than serving Bokeh documents via say Flask and the BokehJS code decoding the JSON received from the server and using `embed`. And I am talking about using BokehJS's TypeScript code rather than just JavaScript which can be achieved more simply using the minified bundles from CDN. I am using the BokehJS 3.4.0 dev/RC NPM packages as they have the dependencies specified which is really helpful.

There is a problem with the design of the class hierarchy of BokehJS for this use case which I would like to fix. The `HasProps` constructor, under certain circumstances, calls `finalize()` here https://github.com/bokeh/bokeh/blob/b0a6b984732421ba4c3766511ce5fb6aa862117b/bokehjs/src/lib/core/has_props.ts#L340
which calls `initialize()`
https://github.com/bokeh/bokeh/blob/b0a6b984732421ba4c3766511ce5fb6aa862117b/bokehjs/src/lib/core/has_props.ts#L366
which is overridden in various derived classes such as `ColumnarDataSource`
https://github.com/bokeh/bokeh/blob/b0a6b984732421ba4c3766511ce5fb6aa862117b/bokehjs/src/lib/models/sources/columnar_data_source.ts#L72-L76
and here initialises two member variables.

So we have a derived class constructor that calls a base class constructor that calls a derived class function to initialise derived class member variables. Calling an overridden function from a base class constructor is considered bad practice as the member variables we are trying to initialise have not necessarily been allocated yet. Here is some simple TypeScript code to illustrate the scenario:
```typescript
abstract class Base {
    constructor() {
        this.initialize()
    }

    initialize(): void {}
}

class Derived extends Base {
    variable: number

    constructor() {
        super()
        console.log("End of Derived.constructor, this.variable =", this.variable)
    }

    override initialize(): void {
        super.initialize()
        this.variable = 23
        console.log("End of Derived.initialize, this.variable =", this.variable)
    }
}
```
In some situations I have tried, this code works as expected. But in others `variable` is set to 23 but the `variable` that clients can access remains `undefined`. This is pretty much a deal-breaker for my various experiments.

In most Bokeh usage this is not a problem as the `HasProps` initialization is deferred if we are decoding a JSON document, by which time we are outside of the object constructors and all member variables have been allocated. When running the BokehJS test suite locally and in CI is does appear to be a problem either. I do not understand this, but it gives me hope that there might be some TS compiler options that give a reliable solution.

I have created a little repo https://github.com/ianthomas23/bokehjs-expts to demonstrate. The `webpack-simple` directory uses the `Derived` and `Base` code from above. It is possible to avoid the problem here by targetting a different ES version as mentioned in the various READMEs. The `webpack-bokehjs` directory is a BokehJS example which you can get part-working by forcing the `CDS` to be initialized again but eventually you hit the problem as `DataRange1d` has similar problematic initialization of member variables. Here it cannot be worked around using a different ES version.

If we had to redesign the code to avoid calling overridden functions in base class constructors, how would we do it?

# Option 1
If a `Derived.initialize` needs to initialize member variables, call it from `Derived.constructor` not `Base.constructor`. To do this we would have to prevent `Base.constructor` from calling it first. The only communication between `Derived` and `Base` here is via constructor arguments, so we'd have to have a `defer_initialization` boolean passed down the constructor hierarchy. This is probably not acceptable as the argument would become part of the public API when it should be an internal implementation detail.

# Option 2
Add a global (?) flag for deferring all initialization which is explicitly set in client code. We would have to temporarily store a sequence of all objects created this way so that when `show` or whatever is called, objects are popped off it and initialized then. This would be fine for single-shot plots but if we are doing clever stuff with callbacks to create new objects we might have to perform the "check and initialize sequence" in a number of places.

# Option 3
Move the initialization of member variables outside of the `initialize()` functions. This effectively means we no longer override `HasProps.initialize()`. Those member variables would  have to be initialized some other way, such as when they are first needed. `DataRange1d` has 8 member variables so maybe we'd have to have a single sentinel boolean for all of them and initialise them together.

# Option 4
Add an extra level of indirection in constructors so that when we construct an object is has the chance to construct its underlying implementation object and initialise it outside of its own constructor. This would mean lots of boilerplate code because the class the client uses, which is really a proxy for the underlying implementation class, would need to expose the same interface. Probably only really possible using some automatic code generation tools and would be pretty invasive.

It would be great if someone else could take a look at this and see if my analysis make sense or if I have made some fundamental error in understanding the situation.

**Comment by mattpap** [comment]
This is a known problem, I think, from the very beginning, though we don't have prior issues open for this. This hasn't been fixed for so long, because of the strong bias towards initialization from JSON, which implies deferred initialization and is handled at the `Document`/deserialization level. For reference, views suffer from the same problem, actually much worse, but given that they aren't initialized by the user, then we can comfortably implement two stage initialization for them, handled by `build_view()` or `build_views()`.

`HasProps.initialize()` has to functions:
* initialize non-properties based off property values
* prepare for `HasProps.connect_signals()`

Both have to be done after properties are initialized, because properties are initialized all at once in `HasProps.constructor`.

Having `HasProps.initialize()` has the additional disadvantage of not being able to use TypeScript's `readonly` modifier on attributes initialized in `initialize()`. It's also a big contributor to why we can't enable [`strictPropertyInitialization`](https://www.typescriptlang.org/tsconfig#strictPropertyInitialization).

This would be very easy to resolve if JavaScript allowed static callable signatures for classes. It kind of supports this, but only for the old-style "classes", not the new-style that use `class` keyword. In this approach we would only initialize properties in constructors (when calling with `new`) and call `initialize()` and `connect_signals()` when calling without `new` (after an object was constructed with `new`). This could potentially be made backwards compatible. We could approximate this with a static method, e.g. `build()`, and constructing objects with e.g. `Plot.build({...properties})`, but it's a very ugly API.

A different and more practical approach I've been considering, is to `initialize()` and `connect_signals()` when attaching a `Document` to a model. This would make both styles of initialization (from JSON and manual) equivalent in their functionality and behavior. `initialize()` would be called exactly once, whereas `connect_signals()` and `disconnect_signals()` would be called on `_doc_attach` and `_doc_detach`.  Not calling `connect_signals()` in constructors would also reduce the need for `initialize()` significantly, e.g. all signals would be defined in constructors and would be readonly.

**Comment by ianthomas23** [comment]
Thanks for the clarification Mateusz. I like the solution in your last paragraph. I would happily work on this, but I understand from the notes of this week's meeting (which unfortunately I couldn't attend as I was on a delayed flight) that you've already started working on it?

**Comment by ianthomas23** [comment]
I've looked at the idea of moving the `initialize()` to `HasProps.attach_document()` and the `connect_signals()` to `_doc_attached` and it fixes the initial problem. But there are multiple layers of problems caused by calling derived-class virtual functions in the base class constructor. For example, `Range1d` has a `reset_start` callback that updates the member variable `_reset_start` defined here:

https://github.com/bokeh/bokeh/blob/04970eaab36ceafc0cd2bd744bcb5c04d5611d1c/bokehjs/src/lib/models/ranges/range1d.ts#L22-L34

But this is called during `HasProps.initialize_props()` from within the `HasProps` constructor and so `self._reset_start` isn't guaranteed to be allocated and when you try to reset the viewport `self._reset_start` is `null`.

**Comment by pastewka** [comment]
https://github.com/bokeh/bokeh/pull/13872

**Comment by amaurylivier** [comment]
I am currently facing the same problem with "@bokeh/bokehjs": "^3.5.1".
I try to import Bokeh in this way :
`import * as Bokeh from '@bokeh/bokehjs'`
Then i create a plot and show it :
```
const p = new Bokeh.Plotting.figure()
p.scatter([0,1,2,3,4,5],[0,1,2,3,4,5])
Bokeh.Plotting.show(p,'#container')
```
I am facing this error :

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'connect')
    at GlyphRendererView.connect (view.js:35:1)
    at GlyphRendererView.connect_signals (glyph_renderer.js:142:1)
    at build_views (build_views.js:34:1)
    at async FigureView._build_renderers (plot_canvas.js:604:1)
    at async FigureView.build_renderer_views (plot_canvas.js:630:1)
    at async FigureView.lazy_initialize (plot_canvas.js:274:1)
    at async _build_view (build_views.js:7:1)
    at async build_view (build_views.js:11:1)
    at async ViewManager.build_view (view_manager.js:102:1)
    at async render_view (standalone.js:46:1)
    at async render_model (standalone.js:56:1)
    at async add_document_standalone (standalone.js:67:1)
    at async Module.show (io.js:54:1)
```


Is there a workaround?

**Comment by bryevdv** [comment]
@AmauryVa please ***never*** post screenshots of code or logs in issues. ***Always*** post only the actual text. Screen shots are not accessible and cannot be copy and pasted from.

**Comment by mattpap** [comment]
This works:
```html
<html>
  <head>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.js"></script>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-api-3.5.1.js"></script>
  </head>
  <body>
    <div id="container"></div>
    <script>
      const p = new Bokeh.Plotting.figure()
      p.scatter([0,1,2,3,4,5], [0,1,2,3,4,5])
      Bokeh.Plotting.show(p, "#container")
    </script>
  </body>
</html>
```
Please provide a complete reproducible example, web browser type and version, etc. Preferably start a new issue with all the details, so we can decide separately if this is a problem and if so, whether this is a variant of this issue or something different.

**Comment by horagong** [comment]
```
import * as Bokeh from '@bokeh/bokehjs';

const p = new Bokeh.Plotting.figure();
p.scatter([0,1,2,3,4,5], [0,1,2,3,4,5]);
Bokeh.Plotting.show(p, "#app");
```

This code doesn’t work as @AmauryVa mentioned. I gave up on the React + BokehJS project because of this issue. The problem is that importing Bokeh via node_modules doesn’t work, but including it using <script src> does. The error message is the same as what was mentioned earlier. I think this issue may be related to the content mentioned above.

**Comment by ianthomas23** [comment]
I have moved this to the 4.0 milestone as I think it likely it will include breaking changes.
