### ISSUE TITLE
[BUG] Visualization of large(r) dataset fails to load even if amount of data being rendered remains the same

### ISSUE THREAD

**Issue by JulianKu** [bokeh/bokeh#13764]
### Software versions

Python version        :  3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]
IPython version       :  8.15.0
Tornado version       :  6.3.3
Bokeh version         :  3.3.4
BokehJS static path   :  $HOME/miniconda3/envs/$ENV_NAME/lib/python3.10/site-packages/bokeh/server/static
node.js version       :  v20.9.0
npm version           :  10.1.0
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-5.15.0-97-generic-x86_64-with-glibc2.31

### Expected behavior

I am running experiments where I am logging time series of multiple processes (here: abstract processes, not computer processes) with several variables each periodically.
My dataset therefore is of size `(n_timesteps, n_processes)` where each variable sometimes has additional dimensions, so that e.g. variable `paths` is of size `(n_timesteps, n_processes, n_waypoints, 2)` but the leading dimensions are always `(n_timesteps, n_processes)`.

Using bokeh, I wrote a visualization that renders a single point in time of a single process using interactive UI elements (here: Slider for time step and Selector for process). Then, making use of custom JS callbacks, the data sources or their views are modified. 
The visualization consists of 3 subplots for some of which the JS callbacks simply modify the attributes of filters on the main CDS (e.g. by setting the indices of an `IndexFilter` or the booleans of a `BooleanFilter`); for other glyphs, “derived” CDS are filled by copying over a single slice of all relevant variables with indexing `[i, j]` for time step `i` and process `p` (e.g. for connected glyphs where filters are not supported).

### Observed behavior

Now, everything works fine up to a certain number of time steps. In the specific case, I am running `60` processes and everything works fine up to around `1000` (**EDIT**: updated number since I noticed that also still works for 1000 steps) time steps. The loading of the HTML takes like 5-10 seconds and after loading, all visualizations and interactions (choosing processes and sliding through time steps) run smoothly.

At 2500 time steps, however, the HTML starts to load, but the page remains blank. The Browser console tells me:
```
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
    at _embed_items (bokeh-3.3.4.js:738:30)
    at Object.embed_items (bokeh-3.3.4.js:733:16)
```

I suspect, that somehow the amount of data reaches a limit after which bokeh cannot handle it any more, even though the amount of data being rendered remains the same. Memory shouldn't be an issue here with about ~1 GB allocated (out of 32 Gb)
Is this something being hard coded in Bokeh? 
I tried Firefox and Chrome to check whether the Browser might be the issue here.

Is there any way to mitigate this problem?

### Example code

**EDIT**: Updated MRE here. "Minimal" might be subjective... I have uploaded the data source files [here](https://cloud.rts.uni-hannover.de/s/zWoi2xEW6Md4g6o) (the `..._1000.npy` is the one that is still rendering fine while the `..._2500.npy` only shows a blank page. 

```Python
import argparse
from collections import OrderedDict
from itertools import cycle
from math import pi as PI
import operator

from bokeh import models as bkm
from bokeh.core.property.validation import validate
from bokeh.io import output_file, save
from bokeh.layouts import layout, column, row
from bokeh.palettes import interp_palette, Dark2_5 as default_palette
from bokeh.plotting import figure, show
from bokeh.settings import settings as bks
from bokeh.transform import dodge, stack
import numpy as np

if __name__ == "__main__":
    
    # Little argumentparser for n_timesteps
    parser = argparse.ArgumentParser(description="Interactive plot for multi-agent navigation")
    parser.add_argument("cds_file", type=str,
                        help="Path to the file containing the data sources for the interactive plot",
                        default="data_sources_full.npy", nargs="?")
    args = parser.parse_args()
    cds_file = args.cds_file
    
    n_envs = 10
    n_agents = 6
    batch_size_single_flat = n_envs * n_agents
    laser_res = 256
    laser_range = 10
    num_waypoints = 3
    num_pathpoints = 100
    fps = 10
    primitive_name_to_idx = OrderedDict(
                                home=0,
                                goal_navigation=1,
                                path_navigation=2,
                                pose_diff=3,
                                measure_on=4,
                                measure_off=5,
                                no_op=6
                            )
    primitives_vis_waypoints = ["path_navigation"]
    idx_vis_waypoints = [primitive_name_to_idx[name] for name in primitives_vis_waypoints]
    primitives_vis_paths = ["home", "goal_navigation", "path_navigation"]
    idx_vis_paths = [primitive_name_to_idx[name] for name in primitives_vis_paths]
    
    cds_data = np.load(cds_file, allow_pickle=True).item()
    n_timesteps = cds_data["agents_source"]["x"].shape[0] // batch_size_single_flat
    max_time = n_timesteps / fps
    omega = cds_data["agents_source"]["omega"]
    active_primitives = cds_data["agents_source"]["primitive_idx"]
    laser_distances = cds_data["laser_source"]["laser_distances"]
    
    # Bokeh plot data sources
    with validate(False):
        lines_source = bkm.ColumnDataSource(data=cds_data["lines_source"])
        objects_source = bkm.ColumnDataSource(data=cds_data["objects_source"])
        agents_source = bkm.ColumnDataSource(data=cds_data["agents_source"])
        waypoints_source = bkm.ColumnDataSource(data=cds_data["waypoints_source"])
        paths_source = bkm.ColumnDataSource(data=cds_data["paths_source"])
        laser_source = bkm.ColumnDataSource(data=cds_data["laser_source"])

    # Bokeh plot filters
    default_env = default_agent = default_timestep = 0
    default_idx = (default_timestep, default_env, default_agent)
    default_flat_idx = default_timestep * batch_size_single_flat + default_env * n_agents + default_agent
    lines_filter = bkm.GroupFilter(column_name="env", group=str(default_env))
    objects_filter = bkm.GroupFilter(column_name="env", group=str(default_env))
    agents_env_filter = bkm.GroupFilter(column_name="env", group=str(default_env))
    agents_agt_filter = bkm.GroupFilter(column_name="agent", group=str(default_agent))
    agents_time_filter = bkm.GroupFilter(column_name="timestep", group=str(default_timestep))
    agents_cw_filter = bkm.BooleanFilter(booleans=(omega < 0).tolist())
    agents_ccw_filter = bkm.BooleanFilter(booleans=(omega > 0).tolist())
    agents_goal_filter = bkm.BooleanFilter(
                        booleans=np.isin(active_primitives,
                                         np.array(
                                             operator.itemgetter("home", "goal_navigation")(primitive_name_to_idx),
                                             dtype=active_primitives.dtype)).tolist())
    laser_start_idx = default_flat_idx * laser_res
    laser_end_idx = (default_flat_idx + 1) * laser_res
    laser_filter = bkm.IndexFilter(
        np.arange(laser_start_idx, laser_end_idx)[laser_distances[laser_start_idx:laser_end_idx] < laser_range])
    waypoints_filter = bkm.IndexFilter(np.arange(default_flat_idx * num_waypoints, 
                                                 (default_flat_idx + 1) * num_waypoints))
    path_filter = bkm.IndexFilter(np.arange(default_flat_idx * num_pathpoints,
                                            (default_flat_idx + 1) * num_pathpoints))
    
    # Derived data sources
    map_source = bkm.ColumnDataSource(data=cds_data["map_source"])
    agents_source_cumul = bkm.ColumnDataSource(data=cds_data["agents_source_cumul"])
    agents_resets_cumul = bkm.ColumnDataSource(data=cds_data["agents_resets_cumul"])
    
    # Filtered data source views
    lines_view = bkm.CDSView(filter=lines_filter)
    objects_view = bkm.CDSView(filter=objects_filter)
    agents_view = bkm.CDSView(filter=agents_env_filter & agents_agt_filter & agents_time_filter)
    agents_view_cw = bkm.CDSView(filter=agents_env_filter & agents_agt_filter & agents_time_filter & \
                                 agents_cw_filter)
    agents_view_ccw = bkm.CDSView(filter=agents_env_filter & agents_agt_filter & agents_time_filter & \
                                  agents_ccw_filter)
    agents_view_goal = bkm.CDSView(filter=agents_env_filter & agents_agt_filter & agents_time_filter & \
                                   agents_goal_filter)
    waypoints_view = bkm.CDSView(filter=waypoints_filter)
    paths_view = bkm.CDSView(filter=path_filter)
    laser_view = bkm.CDSView(filter=laser_filter)
    
    # Create interactive plot
    fig_env = figure(title="Environment", x_axis_label='x', y_axis_label='y',
                     match_aspect=True)
    # Draw environment map
    free_color = "green"
    occupied_color = "red"
    unknown_color = "white"
    map_palette = interp_palette([unknown_color, occupied_color, free_color], 256)
    map_cmapper = bkm.LinearColorMapper(palette=map_palette, low=0, high=255)
    fig_env.image(image="maps", x="maps_origin_x", y="maps_origin_y", dw="maps_dx", dh="maps_dy",
                  origin="bottom_left", anchor="bottom_left",
                  source=map_source, alpha=0.3, color_mapper=map_cmapper)
    colorbar = bkm.ColorBar(title="Map", color_mapper=map_cmapper, scale_alpha=0.3,
                            ticker=bkm.FixedTicker(ticks=[0, 127, 255]),
                            major_label_overrides={0: "Unknown", 127: "Occupied", 255: "Free"})
    fig_env.add_layout(colorbar, "above")
    # Add the static elements to the plot
    #   environment lines
    fig_env.segment('x0', 'y0', 'x1', 'y1', source=lines_source, view=lines_view, legend_label="Walls",
                    color="black", alpha=1., line_width=2)
    #   object positions
    fig_env.circle('x', 'y', radius="radii", source=objects_source, view=objects_view, legend_label="Object",
                   fill_color="orange", fill_alpha=1., line_color=None)

    # Add the dynamic elements to the plot
    #   paths
    fig_env.segment('x0', 'y0', 'x1', 'y1', source=paths_source, view=paths_view, legend_label="Path",
                    color="blue", alpha=0.6, line_width=2)
    #   waypoints
    fig_env.circle('x', 'y', radius=0.4, 
                   source=waypoints_source, view=waypoints_view, legend_label="Waypoint",
                   fill_color="cyan", fill_alpha=0.6, line_color=None)
    #   goal positions
    fig_env.circle('primitive_goal_x', 'primitive_goal_y', radius=0.5, source=agents_source, view=agents_view_goal,
                   legend_label="Goal", line_color="red", fill_color=None, line_width=1,
                   hatch_pattern="criss_cross", hatch_color="red", hatch_alpha=0.6)
    #   agent velocities and angular velocities vectors
    standard_vee = bkm.VeeHead(size=10, line_color="black", line_width=1)
    tiny_vee = bkm.VeeHead(size=5, line_color="black", line_width=1)
    tiny_tee = bkm.TeeHead(size=4, line_color="black", line_width=1)
    vel = fig_env.segment('x', 'y', stack('x', 'vx'), stack('y', 'vy'),
                          source=agents_source, view=agents_view, line_color="black", line_width=1)
    vel.add_decoration(standard_vee, "end")
    angvel_cw = fig_env.arc(x='x', y='y', radius=dodge("radii", 0.25), start_angle="angle",
                            end_angle=stack("angle", "omega"), direction="clock", source=agents_source,
                            view=agents_view_cw, line_color="black", line_width=1)
    angvel_cw.add_decoration(tiny_tee, "start")
    angvel_cw.add_decoration(tiny_tee, "end")
    angvel_ccw = fig_env.arc(x='x', y='y', radius=dodge("radii", 0.25), start_angle="angle",
                             end_angle=stack("angle", "omega"), direction="anticlock", source=agents_source,
                             view=agents_view_ccw, line_color="black", line_width=1)
    angvel_ccw.add_decoration(tiny_tee, "start")
    angvel_ccw.add_decoration(tiny_vee, "end")
    #   agent positions
    fig_env.circle('x', 'y', radius="radii", source=agents_source, view=agents_view, legend_label="Agent", 
                   fill_color="blue", fill_alpha=1., line_color=None)
    #   agent orientation
    fig_env.wedge(x='x', y='y', radius="radii", start_angle="orientation_start", end_angle="orientation_end",
                  source=agents_source, view=agents_view, fill_color="green")
    fig_env.legend.location = "top_right"
    fig_env.legend.click_policy="hide"
    
    # Add info on hover
    info_hover = bkm.HoverTool(
                        tooltips=[
                            ("Time", "@time{(0.00)}"),
                            ("Battery Level", "@battery_level{(0.00)}"), 
                            ("Reward", "@reward{(+0.00)}"),
                            ("Primitive", "@primitive_name{%s}"),
                            ("Info", "@info{%s}")
                        ],
                        formatters={
                            "@primitive_name": "printf",
                            "@info": "printf"
                        },
                        mode="vline"
                    )
    fig_cumul = figure(title="Battery and Reward", x_axis_label="Time", y_axis_label="Battery Level / Reward",
                       x_range=(0, max_time), tools=[info_hover])
    colors = cycle(default_palette)
    bat_color = next(colors)
    battery_line = fig_cumul.line(x="time", y="battery_level", legend_label="Battery Level",
                                  source=agents_source_cumul, line_color=bat_color)
    low_battery_thresh = 0.1
    fig_cumul.hspan(y=low_battery_thresh, legend_label="Low Battery Threshold",
                    line_color=bat_color, line_dash="dashed", line_width=2, line_alpha=0.6)
    reward_line = fig_cumul.line(x="time", y="reward", legend_label="Reward",
                                 source=agents_source_cumul, line_color=next(colors))
    fig_cumul.vspan(x="reset", source=agents_resets_cumul, legend_label="Reset",
                    line_color="black", line_dash="dotted", line_width=2, line_alpha=0.6)
    fig_cumul.hover.renderers = [battery_line, reward_line]
    fig_cumul.legend.location = "top_right"
    fig_cumul.legend.click_policy="hide"

    laser_hover = bkm.HoverTool(
                        tooltips=[
                            ("Angle", "@laser_angles{(0.00)}"),
                            ("Distance", "@laser_distances{(0.00)}")
                        ],
                        mode="mouse"
                    )
    laser_range_ext = laser_range + 1
    fig_laser = figure(title="Laser Scan", x_axis_type=None, y_axis_type=None, match_aspect=True, aspect_ratio=1,
                       tools=[laser_hover])
    # Plot polar axes and labels
    axes_radii = np.arange(laser_range_ext)
    axes_angles = np.linspace(0, 2*PI, 8, endpoint=False)
    axes_end_x = [laser_range * np.cos(a) for a in axes_angles]
    axes_end_y = [laser_range * np.sin(a) for a in axes_angles]
    fig_laser.circle(0, 0, radius=axes_radii[1:], line_color="black", line_width=1, line_alpha=0.5, fill_color=None)
    fig_laser.segment(x0=0, y0=0, x1=axes_end_x, y1=axes_end_y, 
                      line_color="black", line_width=1, line_alpha=0.5)
    distance_label_angle = 0.5 * (axes_angles[0] + axes_angles[1])
    cda = np.cos(distance_label_angle)
    sda = np.sin(distance_label_angle)
    distance_label_offset = 6
    fig_laser.text(cda * axes_radii[1:], sda * axes_radii[1:], 
                   text=[str(r) for r in axes_radii[1:]], text_align="left", text_baseline="middle",   
                   x_offset=cda * distance_label_offset, y_offset=sda * distance_label_offset, anchor="center")
    fig_laser.text(x=[laser_range_ext * np.cos(a) for a in axes_angles], 
                   y=[laser_range_ext * np.sin(a) for a in axes_angles], 
                   text=[str(int(a / PI * 180)) for a in axes_angles],
                   text_align="center", text_baseline="middle", anchor="center")
    # Plot laser scan
    laser_transform = bkm.PolarTransform(radius="laser_distances", angle="laser_angles")
    laser_dots = fig_laser.circle(x=laser_transform.x, y=laser_transform.y, source=laser_source, view=laser_view,
                                  fill_color="blue", fill_alpha=0.7, size=5)
    fig_laser.hover.renderers = [laser_dots]

    # Define widgets
    env_select = bkm.Select(title="Environment", value=str(default_env), options=list(map(str, range(n_envs))))
    agent_select = bkm.Select(title="Agent", value=str(default_agent), options=list(map(str, range(n_agents))))
    timestep_slider = bkm.Slider(start=0, end=n_timesteps-1, value=default_timestep, step=1, title="Timestep")

    # Change group based on selected environment, agent, or timestep via callbacks

    env_callback = bkm.CustomJS(args=dict(lines_source=lines_source, 
                                          objects_source=objects_source,
                                          agents_source=agents_source,
                                          lines_filter=lines_filter, 
                                          objects_filter=objects_filter, 
                                          agents_env_filter=agents_env_filter, 
                                          env_select=env_select), 
                                code="""
                                    const env = env_select.value;
                                    
                                    // Update filters based on selected environment
                                    lines_filter.group = env;
                                    objects_filter.group = env;
                                    agents_env_filter.group = env;
                                    lines_source.change.emit();
                                    objects_source.change.emit();
                                    agents_source.change.emit();
                                    """)
    
    agt_callback = bkm.CustomJS(args=dict(agents_source=agents_source,
                                          agents_agt_filter=agents_agt_filter, 
                                          agent_select=agent_select), 
                                code="""
                                    const agent = agent_select.value;

                                    // Update filter based on selected agent
                                    agents_agt_filter.group = agent;
                                    agents_source.change.emit();
                                    """)
    
    timestep_callback = bkm.CustomJS(args=dict(agents_source=agents_source,
                                               agents_time_filter=agents_time_filter,
                                               timestep_slider=timestep_slider), 
                                     code="""
                                        const timestep = timestep_slider.value;
                                        
                                        // Update filters based on selected timestep
                                        agents_time_filter.group = timestep.toString();
                                        
                                        agents_source.change.emit();
                                        """)
    
    shared_callback = bkm.CustomJS(args=dict(agents_source=agents_source,
                                             agents_source_cumul=agents_source_cumul,
                                             agents_resets_cumul=agents_resets_cumul,
                                             map_source=map_source,
                                             idx_vis_waypoints=idx_vis_waypoints,
                                             idx_vis_paths=idx_vis_paths,
                                             num_waypoints=num_waypoints,
                                             num_pathpoints=num_pathpoints,
                                             waypoints_filter=waypoints_filter,
                                             path_filter=path_filter,
                                             waypoints_source=waypoints_source,
                                             paths_source=paths_source,
                                             laser_source=laser_source,
                                             laser_filter=laser_filter,
                                             laser_res=laser_res,
                                             laser_range=laser_range,
                                             env_select=env_select,
                                             agent_select=agent_select,
                                             timestep_slider=timestep_slider,
                                             n_envs=n_envs, n_agents=n_agents), 
                                   code="""
                                        const timestep = timestep_slider.value;
                                        const env = parseInt(env_select.value);
                                        const agent = parseInt(agent_select.value);
                                        
                                        const data = agents_source.data;
                                        
                                        // Update map based on selected
                                        const batch = n_envs * n_agents;
                                        const flat_idx = timestep * batch + env * n_agents + agent;
                                        var map_data = map_source.data;
                                        const image_size = map_data["maps"][0].length;
                                        map_data["maps"][0] = data["maps"].slice(flat_idx * image_size,
                                                                                 (flat_idx + 1) * image_size);
                                        map_data["maps"][0].shape = data["maps"].shape.slice(-2);
                                        map_data["maps"][0].dimension = 2;
                                        map_data["maps_origin_x"][0] = data["maps_origin_x"].slice(flat_idx, 
                                                                                                   flat_idx + 1);
                                        map_data["maps_origin_y"][0] = data["maps_origin_y"].slice(flat_idx,
                                                                                                   flat_idx + 1);
                                        map_data["maps_dx"][0] = data["maps_dx"].slice(flat_idx, flat_idx + 1);
                                        map_data["maps_dy"][0] = data["maps_dy"].slice(flat_idx, flat_idx + 1);
                                        
                                        // Update waypoints and paths filter based on selected 
                                        // (and resulting active primitive)
                                        const primitive_idx = data["primitive_idx"][flat_idx];
                                        if (idx_vis_waypoints.includes(primitive_idx)) {
                                            waypoints_filter.indices = Array.from({length: num_waypoints},
                                                                                  (_, i) => flat_idx * num_waypoints + 
                                                                                            i);
                                        } else {
                                            waypoints_filter.indices = [];
                                        }
                                        // for paths also filter out all segments where one of the values is NaN
                                        if (idx_vis_paths.includes(primitive_idx)) {
                                            path_filter.indices = Array.from({length: num_pathpoints - 1},
                                                                             (_, i) => flat_idx * (num_pathpoints - 1)
                                                                                        + i);
                                        } else {
                                            path_filter.indices = [];
                                        }
                                        
                                        const laser_data = laser_source.data;
                                        // Update indices, filter for distance < laser_range
                                        laser_filter.indices = Array.from({length: laser_res}, 
                                                                          (_, i) => flat_idx * laser_res + i)
                                                                          .filter(i => laser_data["laser_distances"][i] 
                                                                                        < laser_range);
                                        
                                        // Get indices of all timesteps that are lower than the selected timestep
                                        // and assign corresponding elements of the agents_source 
                                        // to agents_source_cumul (for cumulative plots of battery, reward, and info)
                                        var cumul_data = agents_source_cumul.data;
                                        var cumul_resets = agents_resets_cumul.data;
                                        cumul_data["time"] = [];
                                        cumul_data["battery_level"] = [];
                                        cumul_data["reward"] = [];
                                        cumul_data["info"] = [];
                                        cumul_data["primitive_name"] = [];
                                        cumul_resets["reset"] = [];
                                        const start = env * n_agents + agent;
                                        const step = batch;
                                        const end = (timestep + 1) * step;
                                        var time;
                                        for (var i = start; i < end; i += step) {
                                            time = data["time"][i];
                                            cumul_data["time"].push(time);
                                            cumul_data["battery_level"].push(data["battery_level"][i]);
                                            cumul_data["reward"].push(data["reward"][i]);
                                            cumul_data["info"].push(data["info"][i]);
                                            cumul_data["primitive_name"].push(data["primitive_name"][i]);
                                            if (data["reset"][i]) {
                                                cumul_resets["reset"].push(time);
                                            }
                                        }
                                        
                                        waypoints_source.change.emit();
                                        paths_source.change.emit();
                                        map_source.change.emit();
                                        laser_source.change.emit();
                                        agents_source_cumul.change.emit();
                                        agents_resets_cumul.change.emit();
                                        """)

    env_select.js_on_change("value", env_callback, shared_callback)
    agent_select.js_on_change("value", agt_callback, shared_callback)
    timestep_slider.js_on_change("value", timestep_callback, shared_callback)
    
    # Set up Play/Pause button/toggle JS
    sleep_ms = 1000 // fps
    play_anim = bkm.CustomJS(args=dict(slider=timestep_slider, sleep_ms=sleep_ms, n_timesteps=n_timesteps),
                             code="""
                                // A little lengthy but it works for me, for this problem, in this version.
                                var check_and_iterate = function() {
                                    var slider_val = slider.value;
                                    var toggle_val = cb_obj.active;
                                    if(toggle_val == false) {
                                        cb_obj.label = "► Play";
                                        clearInterval(looop);
                                        } 
                                    else {
                                        slider.value = (slider_val + 1) % n_timesteps;
                                        }
                                }
                                if(cb_obj.active == false){
                                    cb_obj.label = "► Play";
                                    clearInterval(looop);
                                }
                                else {
                                    cb_obj.label = "❚❚ Pause";
                                    var looop = setInterval(check_and_iterate, sleep_ms);
                                };
                                """
                             )
    
    play_button = bkm.Toggle(label="► Play", active=False)
    play_button.js_on_change("active", play_anim)
    
    # Create layout
    grid = layout([[fig_env], [env_select, agent_select, play_button, timestep_slider], [fig_laser, fig_cumul]])
    
    # Export to HTML
    output_file("interactive_plot.html")
    show(grid)
```

### Stack traceback or browser console output

Uncaught (in promise) SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
    at _embed_items (bokeh-3.3.4.js:738:30)
    at Object.embed_items (bokeh-3.3.4.js:733:16)

**Comment by bryevdv** [comment]
@JulianKu We can't begin to speculate without a complete [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by mattpap** [comment]
> Memory shouldn't be an issue here with about ~1 GB allocated (out of 32 Gb). Is this something being hard coded in Bokeh?

It's a web browser limit of some kind (e.g. maximum allocation limit per page). It can be quite arbitrary. As mentioned before, MRE would be really helpful, but a quick solution may be to make sure all your data arrays are numpy's ndarrays. Those are binary encoded and can significantly reduce the size of the overall payload. However, this sill may be too much for a standalone HTML file. In that case you may need to send your data in pure binary format which requires a bokeh server (data is transmitted over a binary websocket) or a remote data source of some kind.

**Comment by mattpap** [comment]
Also related issue https://github.com/bokeh/bokeh/issues/13645.

**Comment by JulianKu** [comment]
I have updated the issue with a reproducible example and provided the required data as `npy` files under a Nextcloud share.

**Comment by JulianKu** [comment]
@mattpap

> but a quick solution may be to make sure all your data arrays are numpy's ndarrays

Base format for all data were PyTorch tensors. Before opening this issue, I already assumed that numpy arrays could be better suited and converted all tensors to numpy arrays (unfortunately not solving it though)

**Comment by bryevdv** [comment]
@JulianKu thinking more on this, for this kind of data size you should probably be looking at things like DataShader. Sending ~gigabytes of data into browser tabs is just not going to be a good time. Holoviews can integrate Bokeh and Datashader together, as far as I know. cc @philippjfr @jbednar

**Comment by JulianKu** [comment]
@bryevdv Thank you for this recommendation.
Do you happen to know whether it is possible with DataShader to sustain the same level of interactivity (widget state dependent data selection) within a single exported HTML file? This aspect is crucial for my work as I will not be able to run any kind of server alongside the visualization...

**Comment by bryevdv** [comment]
No, datashader is server-side rendering.

**Comment by jbednar** [comment]
Datashader is server-side rendering, but it is possible to preserve nearly everything in a static export _except_ rerendering.  Specifically, you can render the plot with hover and selection info embedded into it per pixel, and that info will still be there in the HTML file, even though the original dataset is only on the server. You can even support _some_ zooming capability by rendering at e.g. 4X screen resolution, which will let you zoom in a bit, eventually bottoming out in a pixellated view of the data.  There's no free lunch, of course; if your data is too big for the browser, it boils down to subsampling it (and preserving all points that are in the sample while losing the rest), or aggregating it (as Datashader does, per pixel, and thus preserving the totals and other aggregate info while losing the individual points).

**Comment by JulianKu** [comment]
@jbednar Thank you for clarification.
In this case, I would need to render 2'500 (`n_timesteps`) * 10 (`n_envs`) * 6 (`n_agents`) = 150'000 states into images in order to mimic the non-static aspects of my plot (plus, I would need to upscale the images in order to also sustain some level of zoom). 
Doesn't sound like it will be less memory-intensive, but thank you anyway.
I will see whether I can find a different way of logging this...

**Comment by bryevdv** [comment]
@bokeh/dev I am inclined to close with `noaction` as there is nothing we can do on our end about browser limits.

**Comment by JulianKu** [comment]
I felt like that there had to be a way to make this work, as the actual amount of data being rendered does not change with increasing number of time steps. And since the total dataset should easily fit into RAM, I thought that this should make it work.
However, that was just my initial thought — not knowing much about browser internals etc.
I will close this issue looking — for alternative solutions

**Comment by JulianKu** [comment]
I felt like that there had to be a way to make this work, as the actual amount of data being rendered does not change with increasing number of time steps. And since the total dataset should easily fit into RAM, I thought that this should make it work.
However, that was just my initial thought — not knowing much about browser internals etc.
I will close this issue looking — for alternative solutions
