### ISSUE TITLE
server/image.py example failing on master

### ISSUE THREAD

**Issue by kdodia** [bokeh/bokeh#1385]
As of https://github.com/bokeh/bokeh/commit/f1acdb5b5df26f81a1d663887c4694798e4ce9f4, the [server/image.py](https://github.com/bokeh/bokeh/blob/master/examples/plotting/server/image.py) example fails with the following error:

```
2014-11-10 09:21:05,841:ERROR:bokeh.server:Exception on /bokeh/bb/50bab977-1548-4f63-9e16-19b98c723773/bulkupsert [POST]
Traceback (most recent call last):
  File "/Users/kdodia/miniconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kdodia/miniconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kdodia/miniconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kdodia/miniconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kdodia/miniconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kdodia/miniconda/envs/py2/lib/python2.7/site-packages/bokeh/server/views/bbauth.py", line 25, in wrapper
    return func(docid, *args, **kwargs)
  File "/Users/kdodia/miniconda/envs/py2/lib/python2.7/site-packages/bokeh/server/views/backbone.py", line 125, in bulk_upsert
    clientdoc.load(*data, events='none', dirty=True)
  File "/Users/kdodia/miniconda/envs/py2/lib/python2.7/site-packages/bokeh/document.py", line 253, in load
    props = m.finalize(self._models)
  File "/Users/kdodia/miniconda/envs/py2/lib/python2.7/site-packages/bokeh/plot_object.py", line 169, in finalize
    attrs[name] = prop.from_json(json, models=models)
  File "/Users/kdodia/miniconda/envs/py2/lib/python2.7/site-packages/bokeh/properties.py", line 904, in from_json
    prop = self.instance_type.lookup(name)
  File "/Users/kdodia/miniconda/envs/py2/lib/python2.7/site-packages/bokeh/properties.py", line 535, in lookup
    return lookup_descriptor(cls, name)
  File "/Users/kdodia/miniconda/envs/py2/lib/python2.7/site-packages/bokeh/properties.py", line 498, in lookup_descriptor
    raise KeyError("Property '%s' not found on class '%s'" % (propname, cls))
KeyError: u"Property 'type' not found on class '<class 'bokeh.properties.HasProps'>'"
```

ping @hhuuggoo @mattpap

**Comment by bryevdv** [comment]
Fixed at some point (working in 0b7e50dceae48057f3c88889dab024e3204396d8)
