### ISSUE TITLE
[BUG] ColumnDataSource serialization failed for `int` Masked array with `ValueError` / `TypeError`

### ISSUE THREAD

**Issue by orionlee** [bokeh/bokeh#13904]
### Software versions

Python version        :  3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
IPython version       :  8.12.3
Tornado version       :  6.4
numpy version         :  1.24.4
Bokeh version         :  3.4.1
BokehJS static path   :  C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\Lib\site-packages\bokeh\server\static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Windows-10-10.0.22631-SP0

### Expected behavior

When plotting using a `ColumnDataSource` that has masked integer columns, i.e., `numpy.ma.array` with `int` dtype, the plot should work with missing value handled accordingly.

### Observed behavior

The plot failed with `ValueError: cannot convert float NaN to integer` 

### Example code

```Python
Example in a Jupyter notebook:


import bokeh
from bokeh.io import show, output_notebook
from bokeh.layouts import layout
from bokeh.plotting import figure, ColumnDataSource

import numpy as np


def test_bokeh_server(notebook_url="localhost:8888"):
    def create_interact_ui(doc):
        fig = figure(
            title="Test Bokeh server",
        )

        x = [0, 5, 10]
        y = [4, 6, 8]
        mask = [0, 0, 1]
        
        source = ColumnDataSource(data=dict(
            x=np.ma.array(x, mask=mask),
            y=np.ma.array(y, mask=mask),
            ))
        fig.scatter(source=source, size=30, fill_color="red")
        doc.add_root(layout([
            [fig, ]
        ]))
        
    output_notebook(verbose=False, hide_banner=True)
    show(create_interact_ui, notebook_url=notebook_url)

test_bokeh_server()
```

### Stack traceback or browser console output

Python stacktrace of the above example.

```python
ERROR:bokeh.server.protocol_handler:error handling message
 message: Message 'PULL-DOC-REQ' content: {} 
 error: TypeError('Cannot convert fill_value nan to dtype int32')
Traceback (most recent call last):
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\numpy\ma\core.py", line 467, in _check_fill_value
    fill_value = np.array(fill_value, copy=False, dtype=ndtype)
ValueError: cannot convert float NaN to integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\server\protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\server\session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\server\session.py", line 257, in _handle_pull
    return connection.protocol.create('PULL-DOC-REPLY', message.header['msgid'], self.document)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\protocol\__init__.py", line 131, in create
    return self._messages[msgtype].create(*args, **kwargs)  # type: ignore [attr-defined]
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\protocol\messages\pull_doc_reply.py", line 82, in create
    content = PullDoc(doc=document.to_json())
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\document\document.py", line 752, in to_json
    roots = serializer.encode(self._roots)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 253, in encode
    return self._encode(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 278, in _encode
    return self._encode_list(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 326, in _encode_list
    return [self.encode(item) for item in obj]
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 326, in <listcomp>
    return [self.encode(item) for item in obj]
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 253, in encode
    return self._encode(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 262, in _encode
    return obj.to_serializable(self)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\model\model.py", line 534, in to_serializable
    super_rep = super().to_serializable(serializer)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\has_props.py", line 417, in to_serializable
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\has_props.py", line 417, in <dictcomp>
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 253, in encode
    return self._encode(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 278, in _encode
    return self._encode_list(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 326, in _encode_list
    return [self.encode(item) for item in obj]
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 326, in <listcomp>
    return [self.encode(item) for item in obj]
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 253, in encode
    return self._encode(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 262, in _encode
    return obj.to_serializable(self)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\model\model.py", line 534, in to_serializable
    super_rep = super().to_serializable(serializer)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\has_props.py", line 417, in to_serializable
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\has_props.py", line 417, in <dictcomp>
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 253, in encode
    return self._encode(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 278, in _encode
    return self._encode_list(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 326, in _encode_list
    return [self.encode(item) for item in obj]
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 326, in <listcomp>
    return [self.encode(item) for item in obj]
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 253, in encode
    return self._encode(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 262, in _encode
    return obj.to_serializable(self)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\model\model.py", line 534, in to_serializable
    super_rep = super().to_serializable(serializer)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\has_props.py", line 417, in to_serializable
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\has_props.py", line 417, in <dictcomp>
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 253, in encode
    return self._encode(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 278, in _encode
    return self._encode_list(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 326, in _encode_list
    return [self.encode(item) for item in obj]
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 326, in <listcomp>
    return [self.encode(item) for item in obj]
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 253, in encode
    return self._encode(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 262, in _encode
    return obj.to_serializable(self)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\model\model.py", line 534, in to_serializable
    super_rep = super().to_serializable(serializer)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\has_props.py", line 417, in to_serializable
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\has_props.py", line 417, in <dictcomp>
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 253, in encode
    return self._encode(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 262, in _encode
    return obj.to_serializable(self)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\model\model.py", line 534, in to_serializable
    super_rep = super().to_serializable(serializer)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\has_props.py", line 417, in to_serializable
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\has_props.py", line 417, in <dictcomp>
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 253, in encode
    return self._encode(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 282, in _encode
    return self._encode_dict(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 343, in _encode_dict
    entries=[(self.encode(key), self.encode(val)) for key, val in obj.items()],
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 343, in <listcomp>
    entries=[(self.encode(key), self.encode(val)) for key, val in obj.items()],
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 253, in encode
    return self._encode(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 293, in _encode
    return self._encode_ndarray(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\core\serialization.py", line 427, in _encode_ndarray
    array = transform_array(obj)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\bokeh\util\serialization.py", line 357, in transform_array
    array = array.filled(np.nan)  # type: ignore # filled is untyped
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\numpy\ma\core.py", line 3826, in filled
    fill_value = _check_fill_value(fill_value, self.dtype)
  File "C:\pkg\_winNonPortables\miniforge3\envs\lk_dev\lib\site-packages\numpy\ma\core.py", line 473, in _check_fill_value
    raise TypeError(err_msg % (fill_value, ndtype)) from e
TypeError: Cannot convert fill_value nan to dtype int32
```

**Comment by orionlee** [comment]
The root cause: in the serialization logic that handles `np.ma.MaskedArray`, it assumes the `MaskedArray` is float type that supports `np.nan`:

https://github.com/bokeh/bokeh/blob/c2926ab02cec65fff2aa3379682cb3170e2ca42a/src/bokeh/util/serialization.py#L356-L357


Not sure how best to approach it. I understand the `.fill_value` of a `MaskedArray` is often undesirable (some default large value produced by numpy), and `nan` probably does work best in practice. 
But `nan` does not work for `MaskedArray` of integer types.

**Comment by bryevdv** [comment]
cc @bokeh/dev One option would be to simply document this combination as explicitly unsupported. But affording a configurable sentinel value for "NA" might not be too much work.
