### ISSUE TITLE
[BUG] RangeTool `start_gesture` values besides `none` prevent notebook rendering

### ISSUE THREAD

**Issue by droumis** [bokeh/bokeh#13944]
### Software versions

Python version        :  3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ]
IPython version       :  8.25.0
Tornado version       :  6.4.1
Bokeh version         :  3.5.0.dev8+6.gb702536e.dirty
~~BokehJS static path   :  /Users/droumis/src/bokeh/src/bokeh/server/static~~ (See comment)
node.js version       :  v21.7.1
npm version           :  10.5.0
jupyter_bokeh version :  (not installed)
Operating system      :  macOS-13.5.2-arm64-arm-64bit

### Browser name and version

chrome

### Jupyter notebook / Jupyter Lab version

JupyterLab 4.2.2

### Expected behavior

Plot should appear in notebook regardless of RangeTool `start_gesture` value

### Observed behavior

Plot does not appear in notebook when RangeTool `start_gesture` value is either 'pan' or 'tap'

### Example code

```Python
import numpy as np
from bokeh.layouts import column
from bokeh.models import ColumnDataSource, RangeTool
from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

n_points = 3000
x_values = np.linspace(0, 100, n_points)
y_values = np.random.randn(n_points).cumsum()

source = ColumnDataSource(data=dict(x=x_values, y=y_values))

detailed_plot = figure(
    width=800,
    height=250,
    tools=["xpan", "xzoom_in", "xzoom_out", "reset", "wheel_zoom"],
    toolbar_location="above",
    active_scroll="wheel_zoom",
    background_fill_color="#efefef",
    x_range=(22, 30),
)

detailed_plot.line("x", "y", source=source)

minimap = figure(
    width=detailed_plot.width,
    height=125,
    tools="",
    toolbar_location=None,
    background_fill_color=detailed_plot.background_fill_color,
    title="Drag the middle or edges of the selection box below to change the range above"
)

minimap.line("x", "y", source=source)
minimap.x_range.range_padding = 0
minimap.ygrid.grid_line_color = None

range_tool = RangeTool(x_range=detailed_plot.x_range, y_range=detailed_plot.y_range, start_gesture='none')
range_tool.overlay.fill_color = "navy"
range_tool.overlay.fill_alpha = 0.2
minimap.add_tools(range_tool)

show(column(detailed_plot, minimap))
```

### Screenshots

https://github.com/bokeh/bokeh/assets/6613202/ec684302-5e52-482f-b0ea-27a7ddcc75ea

**Comment by droumis** [comment]
hmmm.. I also don't see an output when I try to set `range_tool.overlay.inverted = True` (another 3.5 feature) so it might be something about my dev environment

**Comment by droumis** [comment]
I think I fixed the path to BokehJS, but it's still not displaying anything in the notebook.

```bash
Python version        :  3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ]
IPython version       :  8.25.0
Tornado version       :  6.4.1
Bokeh version         :  3.5.0.dev8+6.gb702536e.dirty
BokehJS static path   :  /Users/droumis/src/bokeh/bokehjs/build
node.js version       :  v21.7.1
npm version           :  10.5.0
jupyter_bokeh version :  (not installed)
Operating system      :  macOS-13.5.2-arm64-arm-64bit
```

**Comment by droumis** [comment]
ah.. right, BokehJS 3.4.1 is still being used... I'll continue debugging

```
bokeh-3.4.1.min.js:180 Uncaught (in promise) Error: unknown property RangeTool.start_gesture
    at p.property (bokeh-3.4.1.min.js:180:2321)
    at p.initialize_props (bokeh-3.4.1.min.js:180:4489)
    at p._decode_object_ref (bokeh-3.4.1.min.js:213:4647)
    at p._decode (bokeh-3.4.1.min.js:213:1739)
    at bokeh-3.4.1.min.js:213:2209
    at h (bokeh-3.4.1.min.js:179:599)
    at p._decode_plain_array (bokeh-3.4.1.min.js:213:2197)
    at p._decode (bokeh-3.4.1.min.js:213:888)
    at p._decode_plain_object (bokeh-3.4.1.min.js:213:2300)
    at p._decode (bokeh-3.4.1.min.js:213:1026)
```

**Comment by droumis** [comment]
I deleted the bokehjs/build directory and reinstalled with pip -e but I'm still getting 
> bokeh.js:1138 [bokeh 3.4.1] Bokeh/BokehJS version mismatch: new document using Bokeh 3.5.0.dev8+6.gb702536e.dirty and BokehJS 3.4.1


I feel like this has also happened a previous time I've tried to use a dev version of Bokeh to contribute, but I can't seem to find the issue with the solution.

**Comment by droumis** [comment]
OK, setting `export BOKEH_RESOURCES=inline` seems to have done it. IMO, the contributor docs are pretty misleading. I'll try to suggest specific changes or questions elsewhere at some point
