### ISSUE TITLE
[BUG] Example program range_tool.py fails to run: "unexpected attribute 'start_gesture' to RangeTool"

### ISSUE THREAD

**Issue by jllanfranchi** [bokeh/bokeh#14006]
### Software versions

Python version        :  3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
IPython version       :  8.15.0
Tornado version       :  6.3.3
Bokeh version         :  3.4.3
BokehJS static path   :  /home/justinl/miniconda3/envs/py310/lib/python3.10/site-packages/bokeh/server/static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-5.14.0-70.30.1.el9_0.x86_64-x86_64-with-glibc2.34

### Browser name and version

Mozilla Firefox 102.4.0esr

("102.4.0esr (64-bit) / Mozilla Firefox for Fedora / fedora - 1.0")

### Jupyter notebook / Jupyter Lab version

_No response_ (Not applicable)

### Expected behavior

The example program provided in the documentation should run successfully.

### Observed behavior

Python code copied verbatim from https://docs.bokeh.org/en/latest/docs/examples/interaction/tools/range_tool.html then when run it gives

`AttributeError: unexpected attribute 'start_gesture' to RangeTool, possible attributes are description, icon, js_event_callbacks, js_property_callbacks, name, overlay, subscribed_events, syncable, tags, visible, x_interaction, x_range, y_interaction or y_range`

(Note this also occurs using Bokeh 3.5.1)

### Example code

```Python
# Code copied verbatim from https://docs.bokeh.org/en/latest/docs/examples/interaction/tools/range_tool.html

import numpy as np

from bokeh.layouts import column
from bokeh.models import ColumnDataSource, RangeTool
from bokeh.plotting import figure, show
from bokeh.sampledata.stocks import AAPL

dates = np.array(AAPL['date'], dtype=np.datetime64)
source = ColumnDataSource(data=dict(date=dates, close=AAPL['adj_close']))

p = figure(height=300, width=800, tools="xpan", toolbar_location=None,
           x_axis_type="datetime", x_axis_location="above",
           background_fill_color="#efefef", x_range=(dates[1500], dates[2500]))

p.line('date', 'close', source=source)
p.yaxis.axis_label = 'Price'

select = figure(title="Drag the middle and edges of the selection box to change the range above",
                height=130, width=800, y_range=p.y_range,
                x_axis_type="datetime", y_axis_type=None,
                tools="", toolbar_location=None, background_fill_color="#efefef")

range_tool = RangeTool(x_range=p.x_range, start_gesture="pan")
range_tool.overlay.fill_color = "navy"
range_tool.overlay.fill_alpha = 0.2

select.line('date', 'close', source=source)
select.ygrid.grid_line_color = None
select.add_tools(range_tool)

show(column(p, select))
```

### Stack traceback or browser console output

```
Traceback (most recent call last):
  File "/home/username/./range_tool.py", line 39, in <module>
    range_tool = RangeTool(x_range=p.x_range, start_gesture="pan")
  File "/home/username/miniconda3/envs/py310/lib/python3.10/site-packages/bokeh/models/tools.py", line 479, in __init__
    super().__init__(*args, **kwargs)
  File "/home/username/miniconda3/envs/py310/lib/python3.10/site-packages/bokeh/models/tools.py", line 178, in __init__
    super().__init__(*args, **kwargs)
  File "/home/username/miniconda3/envs/py310/lib/python3.10/site-packages/bokeh/model/model.py", line 119, in __init__
    super().__init__(**kwargs)
  File "/home/username/miniconda3/envs/py310/lib/python3.10/site-packages/bokeh/core/has_props.py", line 306, in __init__
    setattr(self, name, value)
  File "/home/username/miniconda3/envs/py310/lib/python3.10/site-packages/bokeh/core/has_props.py", line 344, in __setattr__
    self._raise_attribute_error_with_matches(name, properties)
  File "/home/username/miniconda3/envs/py310/lib/python3.10/site-packages/bokeh/core/has_props.py", line 379, in _raise_attribute_error_with_matches
    raise AttributeError(f"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}")
AttributeError: unexpected attribute 'start_gesture' to RangeTool, possible attributes are description, icon, js_event_callbacks, js_property_callbacks, name, overlay, subscribed_events, syncable, tags, visible, x_interaction, x_range, y_interaction or y_range
```

**Comment by mattpap** [comment]
> Bokeh version : 3.4.3

`RangeTool.start_gesture` was added in bokeh 3.5.0.

> Note this also occurs using Bokeh 3.5.1

Let's make sure you're actually running bokeh 3.5.1. I would add
```py
import bokeh
print(bokeh.__version__)
```
at the beginning of your code to make sure.

**Comment by jllanfranchi** [comment]
Thanks for the quick response! So I uninstalled Bokeh 3.4.3 & re-installed 3.5.1 via pip (then uninstalled & re-installed via conda / conda-forge). Ran the program, and now (however I install Bokeh), the above error doesn't occur. I see `bokeh.__version__='3.5.1'`. However, now I get an entirely white (blank) webpage (nothing seems to render).

I also tried creating a completely new, clean conda environment (python 3.10) & exclusively ran
```conda install bokeh==3.5.1 bokeh_sampledata```
 (note I have defaults set to use conda-forge); same result.

**Comment by bryevdv** [comment]
What is the output in the browser's javascript console? FWIW the example runs as expected for me on OSX

**Comment by mosc9575** [comment]
If the javascript console warns you about a version mismatch, than it could be necessary to close the program and/or browser you are working in. It happened to me, that the old javascript code was in the cache and re-opening the program solved this.

**Comment by jllanfranchi** [comment]
The output is
```
Uncaught ReferenceError: OffscreenCanvas is not defined
    u file:///home/user/range_tool.html:363
    _ file:///home/user/range_tool.html:363
    require file:///home/user/range_tool.html:124
    _ file:///home/user/range_tool.html:362
    require file:///home/user/range_tool.html:124
    _ file:///home/user/range_tool.html:360
    require file:///home/user/range_tool.html:124
    _ file:///home/user/range_tool.html:359
    require file:///home/user/range_tool.html:124
    _ file:///home/user/range_tool.html:354
    require file:///home/user/range_tool.html:124
    _ file:///home/user/range_tool.html:353
    require file:///home/user/range_tool.html:124
    _ file:///home/user/range_tool.html:352
    require file:///home/user/range_tool.html:124
    _ file:///home/user/range_tool.html:260
    require file:///home/user/range_tool.html:124
    _ file:///home/user/range_tool.html:259
    require file:///home/user/range_tool.html:124
    _ file:///home/user/range_tool.html:258
    require file:///home/user/range_tool.html:124
    _ file:///home/user/range_tool.html:176
    require file:///home/user/range_tool.html:124
    <anonymous> file:///home/user/range_tool.html:136
    <anonymous> file:///home/user/range_tool.html:175
    <anonymous> file:///home/user/range_tool.html:49
    <anonymous> file:///home/user/range_tool.html:56
test_range_tool.html:363:57
Uncaught ReferenceError: Bokeh is not defined
    <anonymous> file:///home/user/range_tool.html:741
test_range_tool.html:741:9
    <anonymous> file:///home/user/range_tool.html:741
Uncaught ReferenceError: Bokeh is not defined
    fn file:///home/user/range_tool.html:753
test_range_tool.html:753:11
```
Inspecting the .html produced in a private window, I see the same thing. It is tricky for me to restart my browser right now but I will do so asap @mosc9575 

I did not see OffscreenCanvas defined anywhere in the html, though I saw where it was used (`const n=new OffscreenCanvas(0,0).getContext("2d");`).

Will update when I get a fresh browser session. Will try on another host as well. Thanks again for the input, @bryevdv and @mosc9575

**Comment by mattpap** [comment]
> Uncaught ReferenceError: OffscreenCanvas is not defined

What browser (name, exact version) do you use?

**Comment by jllanfranchi** [comment]
I updated the description above, adding the following: Mozilla Firefox 102.4.0esr (the string in Help states "102.4.0esr (64-bit) / Mozilla Firefox for Fedora / fedora - 1.0").

**Comment by jllanfranchi** [comment]
I re-started Firefox entirely & tried again. Similarly, just a blank white page. JS console output is:

```
Uncaught ReferenceError: OffscreenCanvas is not defined
    u https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:347
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:347
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:346
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:344
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:343
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:338
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:337
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:336
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:244
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:243
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:242
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:160
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    <anonymous> https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:120
    <anonymous> https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:159
    <anonymous> https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:33
    <anonymous> https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:40
bokeh-3.5.1.min.js:347:57
    u https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:347
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:347
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:346
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:344
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:343
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:338
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:337
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:336
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:244
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:243
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:242
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:160
    require https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:108
    <anonymous> https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:120
    <anonymous> https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:159
    <anonymous> https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:33
    <anonymous> https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js:40
Uncaught ReferenceError: Bokeh is not defined
    <anonymous> file:///home/user/test_range_tool.html:17
test_range_tool.html:17:9
Uncaught ReferenceError: Bokeh is not defined
    fn file:///home/user/test_range_tool.html:29
test_range_tool.html:29:11
```

**Comment by jllanfranchi** [comment]
I copied the produced html file to my Windows PC running Chrome & Firefox, and another PC running Ubuntu, and it renders fine in all cases. All computers in question are on the same network, so the external firewall rules shouldn't be an issue; there might be something restricting the the failing Linux PC, though... or a web browser setting, cache something, etc. It's the only one on RedHat (9.0). Doubt that's the issue. I will try a new user profile in the browser in question next.

**Comment by bryevdv** [comment]
Looks like OffscrenCanvas is only available by default starting with FF 105

https://caniuse.com/?search=OffscreenCanvas

(But has been available on e.g. chrome since 2018)

**Comment by jllanfranchi** [comment]
Thank you so much, @bryevdv ! (I created a new user profile in the same Firefox on the same PC, had the same issue, but installed Google Chrome fresh from the web on that PC and the demo code works fine there. So I'll just use Chrome on this PC until I get FF upgraded.)

**Comment by mattpap** [comment]
Bokeh should work fine in a two year old web browser with security updates. It's even worse when it comes to Safari, because `OffscreenCanvas` was implemented there only in 2023.
