### ISSUE TITLE
Tests sometimes fail with `WebSocketTimeoutException` on travis-ci

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1409]
Perhaps too low value for timeout? Traceback:
```
======================================================================
ERROR: test_basic_subscribe (bokeh.server.tests.wsmanager_test.TestSubscribeWebSocket)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/bokeh/bokeh/bokeh/server/tests/wsmanager_test.py", line 33, in test_basic_subscribe
    msg = sock.recv()
  File "/home/travis/miniconda/lib/python2.7/site-packages/websocket/_core.py", line 654, in recv
    opcode, data = self.recv_data()
  File "/home/travis/miniconda/lib/python2.7/site-packages/websocket/_core.py", line 669, in recv_data
    frame = self.recv_frame()
  File "/home/travis/miniconda/lib/python2.7/site-packages/websocket/_core.py", line 744, in recv_frame
    frame_buffer.recv_header(self._recv_strict)
  File "/home/travis/miniconda/lib/python2.7/site-packages/websocket/_core.py", line 255, in recv_header
    header = recv_fn(2)
  File "/home/travis/miniconda/lib/python2.7/site-packages/websocket/_core.py", line 851, in _recv_strict
    bytes = self._recv(shortage)
  File "/home/travis/miniconda/lib/python2.7/site-packages/websocket/_core.py", line 836, in _recv
    raise WebSocketTimeoutException(message)
WebSocketTimeoutException: None
```

**Comment by mattpap** [comment]
This doesn't seem to happen anymore (at least I didn't notice this for a while).

**Comment by bryevdv** [comment]
Me either. I will close this for now. Re-open as necessary.
