### ISSUE TITLE
[BUG] custom data model causing server error (500)

### ISSUE THREAD

**Issue by muendlein** [bokeh/bokeh#14179]
### Software versions

Python version        :  3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
IPython version       :  8.12.0
Tornado version       :  6.2
NumPy version         :  1.24.2
Bokeh version         :  3.6.2
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Windows-10-10.0.19045-SP0

### Expected behavior

Using a custom data model should cause any issues when running a bokeh server and refreshing the page.

### Observed behavior

When refreshing the page in the browser (chrome) after a certain time (ca. 30 seconds) the server will crash hard:
error: `ModuleNotFoundError: No module named 'bokeh_app_5f0445280a0943b48f7b4b629fa8b6d7'`
Example/code is from here: https://docs.bokeh.org/en/latest/docs/examples/plotting/data_models.html

Note: 
- At first everything works as intended, the issue only appears ca. 30 seconds after launching the bokeh server
- Sometimes more than one refresh is required to trigger the error

### Example code

```Python
import numpy as np

from bokeh.core.properties import Float
from bokeh.io import curdoc
from bokeh.model import DataModel
from bokeh.models import ColumnDataSource, CustomJS
from bokeh.plotting import figure, show

doc = curdoc()

class Params(DataModel):
    amp = Float(default=0.1, help="Amplitude")
    freq = Float(default=0.1, help="Frequency")
    phase = Float(default=0, help="Phase")
    offset = Float(default=-5, help="Offset")

params = Params(amp=2, freq=3, phase=0.4, offset=1)

A = params.amp
k = params.freq
phi = params.phase
B = params.offset
x = np.linspace(0, 10, 100)
y = A*np.sin(k*x + phi) + B

source = ColumnDataSource(data=dict(x=x, y=y))

plot = figure(tags=[params], y_range=(-10, 10), title="Data models example")
plot.line("x", "y", source=source, line_width=3, line_alpha=0.6)

callback = CustomJS(args=dict(source=source, params=params), code="""
    const data = source.data
    const A = params.amp
    const k = params.freq
    const phi = params.phase
    const B = params.offset

    const x = source.data.x
    const y = Array.from(x, (x) => B + A*Math.sin(k*x+phi))
    source.data = { x, y }
""")

params.js_on_change("amp", callback)
params.js_on_change("freq", callback)
params.js_on_change("phase", callback)
params.js_on_change("offset", callback)

doc.add_root(plot)
```

**Comment by bryevdv** [comment]
Can reproduce on OSX/Chrome as well.

Here is a more complete stack trace
```
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/foo', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/bryan/anaconda3/envs/bk36-py312/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/bryan/anaconda3/envs/bk36-py312/lib/python3.12/site-packages/bokeh/server/views/doc_handler.py", line 56, in get
    page = server_html_page_for_session(session,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/anaconda3/envs/bk36-py312/lib/python3.12/site-packages/bokeh/embed/server.py", line 278, in server_html_page_for_session
    bundle = bundle_for_objs_and_resources(None, resources)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/anaconda3/envs/bk36-py312/lib/python3.12/site-packages/bokeh/embed/bundle.py", line 192, in bundle_for_objs_and_resources
    extensions = _bundle_extensions(all_objs if objs else None, resources)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/anaconda3/envs/bk36-py312/lib/python3.12/site-packages/bokeh/embed/bundle.py", line 284, in _bundle_extensions
    module = __import__(name)
             ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'bokeh_app_6b11d76feb624875a2a5c4d7f16ee2d9
```

**Comment by bryevdv** [comment]
The proximate problem is that the module object `<class 'bokeh_app_461ff7bd81c24854aa4e7556aba30770.Params'>` is in the `all_objs` set. We could certainly add a defensive filter to this loop
```
    all_objs = objs if objs is not None else HasProps.model_class_reverse_map.values()

    for obj in all_objs:
        if hasattr(obj, "__implementation__"):
            continue
        name = obj.__view_module__.split(".")[0]
        if name == "bokeh":
            continue
        if name in names:
            continue
        names.add(name)
        try:
            module = __import__(name)
```

But I think it is questionable that `HasProps.model_class_reverse_map` would include this module in the first place. @mattpap do you have any quick thoughts whether there is a reason it is included? 

Edit: sorry, I missed the `.Params` in the actual object inside `HasProps.model_class_reverse_map`. It's not the module that is returned but each individual custom model class from every session. I guess I can kind of understand why that might be there, but it also seems a bit unworkable. Will have to think about this.

**Comment by bryevdv** [comment]
just filtering these out does seem to fix the immediate problem
```diff
diff --git a/src/bokeh/embed/bundle.py b/src/bokeh/embed/bundle.py
index 0265528052..a4a842794d 100644
--- a/src/bokeh/embed/bundle.py
+++ b/src/bokeh/embed/bundle.py
@@ -278,10 +278,15 @@ def _bundle_extensions(objs: set[HasProps] | None, resources: Resources) -> list
         name = obj.__view_module__.split(".")[0]
         if name == "bokeh":
             continue
+        if name.startswith("bokeh_app_"):
+            continue
         if name in names:
             continue
         names.add(name)
```
But my follow-on questions:

* Is there some better solution to recording every session's custom models in one global `HasProps` reverse map
  * i.e. is there maybe a different model resolver that could be used in the server case that partitions/keeps track of custom extensions by session somehow?
* We probably need to define a global somewhere for the `bokeh_app_` module prefix and it would probably be good to try to implement some more robust way of truly determining that a module is a "bokeh app module"
* Either way, are these classes currently being cleaned up in any way once sessions close? I kind of suspect maybe not...
