### ISSUE TITLE
[BUG] export_png crashing chrome-for-testing

### ISSUE THREAD

**Issue by Sorcecoder** [bokeh/bokeh#14203]
### Software versions

Python version      :  3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.1.1
BokehJS static path :  /home/sorcecoder/.local/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v20.12.0
npm version         :  10.5.0
Operating system    :  Linux-6.8.0-49-generic-x86_64-with-glibc2.35

### Browser name and version

chrome-for-testing 129.0.6668.70

### Expected behavior

I am trying to get the bokeh plot into an pdf report as an image.
I am running chrome for testing along with my main application in docker.

when I run my python backend via python3 it works and generates images, everything is fine. When I run it in docker I would also expect it to work. But it does not.

### Observed behavior

Currently export_png() crashes the chromedriver and I could not figure out why. Even looked into your code what you are doing over here to maybe contribute something.

I noticed this tinny annoying comment and I am suspecting it could be the cause of my issue:
```
export.py:124     filename = os.fspath(filename) # XXX: Image.save() doesn't fully support PathLike
```
Could this be related?

### Example code

```Python
This is how I setup chrome-for-testing in Dockerfile:

# Download and set up Chrome binary
RUN wget -q https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.70/linux64/chrome-linux64.zip && \
    unzip chrome-linux64.zip \
    && mkdir /usr/bin/google-chrome \
    && mv chrome-linux64/* /usr/bin/google-chrome/ \
    && rm chrome-linux64.zip \
    && cd ..

# Download and set up Chromedriver binary
RUN wget -N https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.70/linux64/chromedriver-linux64.zip \
    && unzip chromedriver-linux64.zip \
    && cd chromedriver-linux64 \
    && mkdir /usr/local/bin/chromedriver \
    && mv chromedriver /usr/local/bin/chromedriver/ \
    && chmod +x /usr/local/bin/chromedriver/chromedriver \
    && cd ..


This is how I use it in python

def generate_plot_image(self, plot, gatewayId: str, plot_type: str) -> str:

        chrome_options = Options()
        chrome_options.add_argument(
            "--no-sandbox"
        )  # Required for some server environments
        chrome_options.add_argument("--headless=new")  # Run in headless mode
        chrome_options.add_argument("--remote-debugging-port=9222")
        chrome_options.add_argument(
            "--disable-dev-shm-usage"
        )  # Overcome limited resource problems

        driver = webdriver.Chrome(
            executable_path="/usr/local/bin/chromedriver/chromedriver",
            options=chrome_options,
        )

        # Create the path
        path = f"/tmp/{gatewayId}/"

        # Create the directory if it doesn't exist
        os.makedirs(path, exist_ok=True)

        filepath = f"{path}/{plot_type}.png"

        export_png(plot, filename=filepath, webdriver=driver)

        return filepath
```

### Stack traceback or browser console output

```
1  | 2024-12-21 11:40:24,230 - ERROR - Exception on /reports/create [POST]
flask_backend-1  | Traceback (most recent call last):
flask_backend-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
flask_backend-1  |     response = self.full_dispatch_request()
flask_backend-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
flask_backend-1  |   File "/app/helper/Reports.py", line 375, in open
flask_backend-1  |     image_path = self.generate_plot_image(
flask_backend-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^
flask_backend-1  |   File "/app/helper/Reports.py", line 609, in generate_plot_image
flask_backend-1  |     driver = webdriver.Chrome(
flask_backend-1  |              ^^^^^^^^^^^^^^^^^
flask_backend-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
flask_backend-1  |     super().__init__(
flask_backend-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
flask_backend-1  |     super().__init__(
flask_backend-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
flask_backend-1  |     self.start_session(capabilities, browser_profile)
flask_backend-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
flask_backend-1  |     response = self.execute(Command.NEW_SESSION, parameters)
flask_backend-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask_backend-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
flask_backend-1  |     self.error_handler.check_response(response)
flask_backend-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
flask_backend-1  |     raise exception_class(message, screen, stacktrace)
flask_backend-1  | selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
flask_backend-1  |   (chrome not reachable)
flask_backend-1  |   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crash
ed.)
```

**Comment by Sorcecoder** [comment]
Okay okay,
for all ya fellows who wanna do screenshots of plots and get into this driver missmatch, chrome chrashing hell etc - I found a way. I resigned to follow my ego and do it "well" by trying to future proof chrome versioning, preinstalling binaries to have less latency etc. and just decided I want to have it working regardless of how long the request take (now just over 10 seconds which I hate, might continue looking into selenium docker-compose images & networking and how to make it usable with export_png in the future, I just want to have my client pay me before the year ends).

Solution:
# 1. bump Selenium to 4.14.0
# 2. Use standard chrome version in docker compose:

```
# Install chrome driver
RUN apt-get update && apt-get install -y wget unzip \
    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt-get install -y ./google-chrome-stable_current_amd64.deb \
    && rm google-chrome-stable_current_amd64.deb \
    && cd ..

```

# 3. Let selenium handle the chromedriver hell on runtime:

```
def generate_plot_image(self, plot, gatewayId: str, plot_type: str) -> str:
        chrome_options = Options()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument(
            "--no-sandbox"
        )  # Required for some server environments
        chrome_options.add_argument(
            "--disable-dev-shm-usage"
        )  # Overcome limited resource problems

        try:
            driver = webdriver.Chrome(options=chrome_options, keep_alive=True)
        except Exception as e:
            raise RuntimeError(f"Failed to initialize Chrome WebDriver: {e}")

        try:
            path = f"/tmp/{gatewayId}/"
            os.makedirs(path, exist_ok=True)

            filepath = f"{path}/{plot_type}.png"
            export_png(plot, filename=filepath, webdriver=driver)

            return filepath
        except Exception as e:
            raise RuntimeError(f"Failed to export plot as PNG: {e}")
        finally:
            driver.quit()
```

And voila I have a running solution.

**Comment by bryevdv** [comment]
Just noting that Bokeh definitely assumes a working webdriver, but does not have any assumptions or opinions about how that gets set up.
