### ISSUE TITLE
Grid Plot with row of all None behaves badly

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1651]
See #1640 for more details.

**Comment by bryevdv** [comment]
This is still true in `0.12.4` master dev, probably for different reasons. Here is code:
```
import numpy as np

from bokeh.models import BoxSelectTool
from bokeh.plotting import figure, show, output_file, gridplot

x = np.linspace(0, 4*np.pi, 100)
y = np.sin(x)

TOOLS = "wheel_zoom,save,box_select,lasso_select"

opts = dict(tools=TOOLS, plot_width=350, plot_height=350)

p1 = figure(title="selection on mouseup", **opts)
p1.circle(x, y, color="navy", size=6, alpha=0.6)

p2 = figure(title="selection on mousemove", **opts)
p2.square(x, y, color="olive", size=6, alpha=0.6)
p2.select_one(BoxSelectTool).select_every_mousemove = True

p3 = figure(title="default highlight", **opts)
p3.circle(x, y, color="firebrick", alpha=0.5, size=6)

p4 = figure(title="custom highlight", **opts)
p4.square(x, y, color="navy", size=6, alpha=0.6,
          nonselection_color="orange", nonselection_alpha=0.6)

output_file("scatter_selection.html", title="scatter_selection.py example")

show(gridplot([[p1, p2], [None, None], [p3, p4]]))  # open a browser
```
And the problem is trying to size the spacers with no neighbors:
```
Traceback (most recent call last):
  File "scatter_selection.py", line 29, in <module>
    show(gridplot([[p1, p2], [None, None], [p3, p4]]))  # open a browser
  File "/Users/bryan/work/bokeh/bokeh/layouts.py", line 380, in gridplot
    item = Spacer(width=neighbor.plot_width, height=neighbor.plot_height)
AttributeError: 'NoneType' object has no attribute 'plot_width'
```

**Comment by bryevdv** [comment]
De-prioritizing again. I can't actually think of a use-case for doing this, so perhaps the correct solution is just a validation warning or error.
