### ISSUE TITLE
selection_update stack trace when doing pan/zoom/select ops

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#1709]
After a minute or two of exploring the `selection_update.py` example with pan/zoom/select I got this stack trace.  I wasn't able to reproduce it, but perhaps it is evident to bokeh devs what may have caused it.

```
$ python selection_update.py 
Using saved session configuration for http://localhost:5006/
To override, pass 'load_from_config=False' to Session
Traceback (most recent call last):
  File "selection_update.py", line 107, in <module>
    cursession().poll_document(curdoc(), 0.05)
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/bokeh/session.py", line 677, in poll_document
    self.load_document(document)
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/bokeh/session.py", line 570, in load_document
    doc.merge(json_objs)
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/bokeh/document.py", line 395, in merge
    self.load(plot_context_json, *other_objects)
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/bokeh/document.py", line 245, in load
    self.execute_callback_queue(all_models-new_models)
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/bokeh/document.py", line 345, in execute_callback_queue
    m._trigger(*cb)
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/bokeh/plot_object.py", line 298, in _trigger
    fn(self, attrname, old, new)
  File "selection_update.py", line 97, in on_selection_change
    ph_source2.data["top"] = -hhist2
TypeError: bad operand type for unary -: 'list'
```

**Comment by bryevdv** [comment]
Somehow this was fixed and the fix got lost. The problem is just these two lines:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/server/selection_update.py#L50
https://github.com/bokeh/bokeh/blob/master/examples/plotting/server/selection_update.py#L64

The comprehensions need to be wrapped in `np.array` or (better) use `np.zeros` so that those two variables are actual numpy arrays. @ijstokes can you submit a PR to fix this?
