### ISSUE TITLE
Exception running an app in bokeh-server

### ISSUE THREAD

**Issue by plakdawa** [bokeh/bokeh#1853]
I am using bokeh updated to the latest version in anaconda:
bokeh                     0.7.1                np19py27_0

I created a dashboard app along the lines of the example in stock_app.py and sliders_applet.py.

The app generates a stack trace shown below. I cannot figure out the cause of the problem. If I take the class and output the html to a file the plots are generated properly (without the widgets) so I am assuming that the issue is not with the data.

The code and data are available at: https://github.com/plakdawa/bokeh-dashboard-broken.

Thanks a lot in advance for any guidance.

|>c:\Anaconda\Scripts\bokeh-server.exe -d --script dashboard.py
adding  to python path
importing dashboard.py
2015-02-09 16:21:10,812:DEBUG:bokeh.server.zmqpub:zmqpub starting: inproc://bokeh_in
2015-02-09 16:21:10,813:DEBUG:bokeh.server.zmqsub:SUB CONNECT: inproc://bokeh_out
2015-02-09 16:21:18,371:INFO:tornado.access:301 GET /dashboard?cloudname=den8 (127.0.0.1) 16.00ms
2015-02-09 16:21:18,476:INFO:bokeh.server.models.docs:num models: 1
2015-02-09 16:21:18,561:DEBUG:_bokeh_app:get_cloudname(): Entered
2015-02-09 16:21:18,562:INFO:_bokeh_app:Request for cloudname den8
2015-02-09 16:21:18,566:DEBUG:_bokeh_app:get_smoketests_data(): Entered
2015-02-09 16:21:18,566:INFO:_bokeh_app:CSV file for smoketests data will be D:\Home\Porus\Scripts\Projects\IAAS\den8.current
2015-02-09 16:21:18,592:DEBUG:_bokeh_app:DashboardApp.create(): Entered
2015-02-09 16:21:18,594:DEBUG:_bokeh_app:DashboardApp.setup_events(): Entered
2015-02-09 16:21:18,595:DEBUG:_bokeh_app:DashboardApp.make_source(): Entered
2015-02-09 16:21:18,595:DEBUG:_bokeh_app:DashboardApp.set_dates(): Entered
2015-02-09 16:21:18,596:DEBUG:_bokeh_app:datetime_min=2015-02-03 07:15:00
2015-02-09 16:21:18,596:DEBUG:_bokeh_app:datetime_max=2015-02-05 18:00:00
2015-02-09 16:21:18,598:DEBUG:_bokeh_app:DashboardApp.make_date_pickers(): Entered
2015-02-09 16:21:18,598:DEBUG:_bokeh_app:DashboardApp.make_smoketests_run_time_plot(): Entered
2015-02-09 16:21:18,608:DEBUG:bokeh.plotting:returning config from flask request
2015-02-09 16:21:18,608:DEBUG:bokeh.plotting:returning config from flask request
2015-02-09 16:21:18,615:DEBUG:_bokeh_app:DashboardApp.make_smoketests_results_plot(): Entered
2015-02-09 16:21:18,621:DEBUG:bokeh.plotting:returning config from flask request
2015-02-09 16:21:18,622:DEBUG:bokeh.plotting:returning config from flask request
2015-02-09 16:21:18,631:DEBUG:_bokeh_app:DashboardApp.make_children(): Entered
2015-02-09 16:21:18,813:INFO:tornado.access:200 GET /dashboard/?cloudname=den8 (127.0.0.1) 440.00ms
2015-02-09 16:21:18,901:INFO:tornado.access:200 GET /bokeh/jsgenerate/HBox/DashboardApp/DashboardApp (127.0.0.1) 9.00ms 2015-02-09 16:21:19,180:INFO:tornado.access:200 GET /bokeh/wsurl/ (127.0.0.1) 1.00ms
2015-02-09 16:21:19,361:ERROR:tornado.application:Uncaught exception GET /bokeh/objinfo/3ae37a5a-e5fa-461c-892b-4aa25ad99d38/bedbc359-aa42-4a12-a271-2069a238a7f2 (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/bokeh/objinfo/3ae37a5a-e5fa-461c-892b-4aa25ad99d38/bedbc359-aa42-4a12-a271-2069a238a7f2', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'localhost:5006', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:5006/dashboard/?cloudname=den8', 'X-Requested-With': 'XMLHttpRequest'})
Traceback (most recent call last):
  File "c:\Anaconda\lib\site-packages\tornado\web.py", line 1309, in _execute
    result = self.prepare()
  File "c:\Anaconda\lib\site-packages\tornado\web.py", line 2498, in prepare
    self.fallback(self.request)
  File "c:\Anaconda\lib\site-packages\tornado\wsgi.py", line 280, in __call__
    WSGIContainer.environ(request), start_response)
  File "c:\Anaconda\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\Anaconda\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "c:\Anaconda\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Anaconda\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Anaconda\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Anaconda\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Anaconda\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Anaconda\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Anaconda\lib\site-packages\bokeh\server\crossdomain.py", line 33, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "c:\Anaconda\lib\site-packages\bokeh\server\views\bbauth.py", line 14, in wrapper
    return func(docid, *args, **kwargs)
  File "c:\Anaconda\lib\site-packages\bokeh\server\views\main.py", line 234, in get_bokeh_info_one_object
    clientdoc = bokeh_app.backbone_storage.get_document(docid)
  File "c:\Anaconda\lib\site-packages\bokeh\server\serverbb.py", line 87, in get_document
    doc = Document(json_objs)
  File "c:\Anaconda\lib\site-packages\bokeh\document.py", line 42, in __init__
    self.load(*json_objs, dirty=False)
  File "c:\Anaconda\lib\site-packages\bokeh\document.py", line 220, in load
    model = cls.load_json(obj_attrs)
  File "c:\Anaconda\lib\site-packages\bokeh\plot_object.py", line 160, in load_json
    instance.update(**attrs)
  File "c:\Anaconda\lib\site-packages\bokeh\plot_object.py", line 273, in update
    setattr(self, k, v)
  File "c:\Anaconda\lib\site-packages\bokeh\properties.py", line 542, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "c:\Anaconda\lib\site-packages\bokeh\properties.py", line 129, in __set__
    raise e
ValueError: Expected a datetime instance, got 1422947700000.0
2015-02-09 16:21:19,361:ERROR:tornado.access:500 GET /bokeh/objinfo/3ae37a5a-e5fa-461c-892b-4aa25ad99d38/bedbc359-aa42-4a12-a271-2069a238a7f2 (127.0.0.1) 171.00ms
2015-02-09 16:21:19,516:DEBUG:bokeh.server.wsmanager:add socket 226b015f-3bf2-4194-9a8e-393ea9f1be2a

**Comment by bryevdv** [comment]
ping @hhuuggoo 

So, I think there may be a problem with the serialization of the `Datetime` property, which is ok, you shouldn't be required to use it. However, I was still not able to get the app to render even after playing with it for a bit. I've attached my diff below that gets past the immediate stack trace, but basically your layout is never getting added. I can maybe spend some time tomorrow, and I have pinged another dev who can hopefully chime in as well. I think this is something silly, we just need to document better. 
```
diff --git a/dashboard.py b/dashboard.py
index 96dabae..2f75c50 100644
--- a/dashboard.py
+++ b/dashboard.py
@@ -19,7 +19,7 @@ logger = logging.getLogger(__name__)
 import os
 import os.path
 import socket
-#import datetime
+import datetime
 #import re
 
 import pandas
@@ -81,7 +81,7 @@ def get_smoketests_data(cloudname):
         ).sort(columns=['Date'])
     except:
         raise ValueError('Failed to get data from CSV file %s' % csv_file)
-    
+
     return df
 
 class DashboardApp(HBox):
@@ -92,8 +92,8 @@ class DashboardApp(HBox):
 
     source = Instance(ColumnDataSource)
 
-    datetime_min = Datetime()
-    datetime_max = Datetime()
+    _datetime_min = None #Datetime()
+    _datetime_max = None #Datetime()
 
     date_picker_lower = Instance(DatePicker)
     date_picker_upper = Instance(DatePicker)
@@ -145,16 +145,16 @@ class DashboardApp(HBox):
     def set_dates(self):
         logger.debug('DashboardApp.set_dates(): Entered')
 
-        self.datetime_min = self.source.data['datetime'][0]
-        logger.debug('datetime_min=%s', self.datetime_min)
-        self.datetime_max = self.source.data['datetime'][-1]
-        logger.debug('datetime_max=%s', self.datetime_max)
+        self._datetime_min = self.source.data['datetime'][0]
+        logger.debug('_datetime_min=%s', self._datetime_min)
+        self._datetime_max = self.source.data['datetime'][-1]
+        logger.debug('_datetime_max=%s', self._datetime_max)
 
     def make_date_pickers(self):
         logger.debug('DashboardApp.make_date_pickers(): Entered')
 
-        min = self.datetime_min.date()
-        max = self.datetime_max.date()
+        min = self._datetime_min
+        max = self._datetime_max
         self.date_picker_lower = DatePicker(
             value=min,
             min_date=min,
@@ -174,8 +174,8 @@ class DashboardApp(HBox):
             plot_width=400, plot_height=400,
             x_axis_type='datetime',
             x_range=Range1d(
-                start=self.datetime_min,
-                end=self.datetime_max
+                start=self._datetime_min,
+                end=self._datetime_max
             )
         )
         f.line(
@@ -194,8 +194,8 @@ class DashboardApp(HBox):
             title=None,
             x_axis_type='datetime',
             x_range=Range1d(
-                start=self.datetime_min,
-                end=self.datetime_max
+                start=self._datetime_min,
+                end=self._datetime_max
             )
         )
         f.line(
@@ -218,12 +218,13 @@ class DashboardApp(HBox):
     def make_children(self):
         logger.debug('DashboardApp.make_children(): Entered')
 
+        self.children = [self.layout_column_inputs, self.layout_column_smoketests]
         self.layout_column_inputs.children = [
-            self.date_picker_lower, 
+            self.date_picker_lower,
             self.date_picker_upper
         ]
         self.layout_column_smoketests.children = [
-            self.smoketests_run_time_plot, 
+            self.smoketests_run_time_plot,
             self.smoketests_results_plot
         ]
 
@@ -231,8 +232,8 @@ class DashboardApp(HBox):
         logger.debug('DashboardApp.setup_events(): Entered')
 
         super(DashboardApp, self).setup_events()
-        if self.datetime_min is None or self.datetime_max is None:
-            return
+        # if self._datetime_min is None or self._datetime_max is None:
+        #     return
         # for w in ['date_picker_lower', 'date_picker_upper']:
         #     getattr(self, w).on_change('value', self, 'date_change')
         if self.date_picker_lower:
@@ -263,6 +264,7 @@ class DashboardApp(HBox):
             self.date_picker_lower.value,
             self.date_picker_upper.value
         )
+        curdoc().add(self)
 
 @bokeh_app.route('/dashboard/')
 @object_page('Dashboard')
```

**Comment by bryevdv** [comment]
This refers to the old (and completely removed) `bokeh-server`, closing as invalid. Please open a new issue for any problems with the new (much better) `bokeh serve`
