### ISSUE TITLE
Our build have now more than 13 mb because recently added hdf5 data

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#1890]
The cause is the recent added test files in https://github.com/bokeh/bokeh/tree/master/bokeh/server/tests/data

This add 10 MB to our builds which represent 75% of the build (w/o this data it has arounf 3MB).

So, is there any possibility to get this data from somewhere else, maybe at installation time?

Or other workaround? It would be nice to solve this issue before the release, but I suppose we can make 0.8.1 if we don't find a nice way to solve it.

@hhuuggoo, but also @bokeh/core

**Comment by mattpap** [comment]
@damianavila, by builds you mean generated pip/conda packages? If so, why do those packages contain tests at all?

**Comment by damianavila** [comment]
>@damianavila, by builds you mean generated pip/conda packages? 

Yep...

>If so, why do those packages contain tests at all?

I guess they are not only for tests, trying to clear them gives you an error starting the server...

```python
(py34devel)[damian@damian-S400CA][bokeh](test)$ ./bokeh-server --backend=memory

    Bokeh Server Configuration
    ==========================
    python version : 3.4.2
    bokeh version  : 0.8.0-rc-1297302-dirty
    listening      : 127.0.0.1:5006
    backend        : memory
    python options : debug:OFF, verbose:OFF, filter-logs:OFF, multi-user:OFF
    js options     : splitjs:OFF, debugjs:OFF
    
Traceback (most recent call last):
  File "./bokeh-server", line 7, in <module>
    bokeh.server.run()
  File "/media/datos/Desarrollos/bokeh/bokeh/server/__init__.py", line 177, in run
    start_server(args)
  File "/media/datos/Desarrollos/bokeh/bokeh/server/__init__.py", line 181, in start_server
    start.start_simple_server(args)
  File "/media/datos/Desarrollos/bokeh/bokeh/server/start.py", line 64, in start_simple_server
    register_blueprint()
  File "/media/datos/Desarrollos/bokeh/bokeh/server/configure.py", line 95, in register_blueprint
    blaze_blueprint = get_mbs_blueprint(config_file=server_settings.blaze_config)
  File "/media/datos/Desarrollos/bokeh/bokeh/server/blaze/__init__.py", line 15, in get_blueprint
    mbs.app.setup_app(config_file=config_file)
  File "/home/damian/miniconda3/envs/py34devel/lib/python3.4/site-packages/mbs/app.py", line 12, in setup_app
    settings.from_pyfile(config_file)
  File "/home/damian/miniconda3/envs/py34devel/lib/python3.4/site-packages/mbs/settings.py", line 54, in from_pyfile
    mod = imp.load_source(name, fname)
  File "/home/damian/miniconda3/envs/py34devel/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/datos/Desarrollos/bokeh/bokeh/server/blaze/config.py", line 31, in <module>
    aapl = resource("hdfstore://%s::__data__" % path)
  File "/home/damian/miniconda3/envs/py34devel/lib/python3.4/site-packages/into/regex.py", line 64, in __call__
    return self.dispatch(s)(s, *args, **kwargs)
  File "/home/damian/miniconda3/envs/py34devel/lib/python3.4/site-packages/into/resource.py", line 106, in resource_split
    return resource(uri, other, *args, **kwargs)
  File "/home/damian/miniconda3/envs/py34devel/lib/python3.4/site-packages/into/regex.py", line 64, in __call__
    return self.dispatch(s)(s, *args, **kwargs)
  File "/home/damian/miniconda3/envs/py34devel/lib/python3.4/site-packages/into/backends/hdfstore.py", line 71, in resource_hdfstore
    f = pd.HDFStore(fn)
  File "/home/damian/miniconda3/envs/py34devel/lib/python3.4/site-packages/pandas/io/pytables.py", line 396, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/damian/miniconda3/envs/py34devel/lib/python3.4/site-packages/pandas/io/pytables.py", line 532, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/damian/miniconda3/envs/py34devel/lib/python3.4/site-packages/tables/file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/damian/miniconda3/envs/py34devel/lib/python3.4/site-packages/tables/file.py", line 791, in __init__
    self._g_new(filename, mode, **params)
  File "hdf5extension.pyx", line 359, in tables.hdf5extension.File._g_new (tables/hdf5extension.c:3756)
  File "/home/damian/miniconda3/envs/py34devel/lib/python3.4/site-packages/tables/utils.py", line 185, in check_file_access
    check_file_access(filename, 'w')
  File "/home/damian/miniconda3/envs/py34devel/lib/python3.4/site-packages/tables/utils.py", line 175, in check_file_access
    raise IOError("``%s`` does not exist" % (parentname,))
OSError: ``/media/datos/Desarrollos/bokeh/bokeh/server/tests/data`` does not exist
```

They seem to be related with a default config of the blaze blueprint, but probably @hhuuggoo can gives us more details...

**Comment by bryevdv** [comment]
So that anyone that cares to can run the tests easily and to make testing built packages easier. Lots of projects ship their unit tests it is fairly common.

**Comment by damianavila** [comment]
I don't have problem to ship the tests... just we need to figure out how to deal with this... because it is needed for the server to start...

**Comment by fpliger** [comment]
what about no shipping test data and add hooks to lazily download it the first time it's needed (on tests and server)? 

It may not be a good idea if this data is needed in serveral other places....

**Comment by hhuuggoo** [comment]
why is 13mb a big deal? is that size a barrier to people?  The default configuration for the blaze part of the bokeh server is a dummy configuration that makes all our examples and tests work.  The reason why the bokeh server isn't breaking for most people is that most people don't have all the blaze dependencies installed - therefore the blaze config isn't loaded.  I'm not sure what we want to do here, there are many options, I could also put try/excepts in the config so that we don't fail if we can't find the dataset (of course that means that tests and some examples won't work)

**Comment by almarklein** [comment]
> what about no shipping test data and add hooks to lazily download it the
> first time it's needed (on tests and server)?

I have good experience with that with other packages. It's also an 
approach that scales nicely as you add more data.

Personally I prefer to keep *any* data out of a main code repository 
except if its small and very much static. An auto-download approach 
allows you to put the data in its own repository.

- Almar

**Comment by bryevdv** [comment]
We already have machinery for `bokeh.sampledata.download()` I am sure it can be improved, but it is there and available to be used. I don't see why we can't have very pointed and specific warning messages around anything that tries to use the data, that give explicit instructions for downloading the data.

**Comment by hhuuggoo** [comment]
I assume travis already downloads sample data?, do we have an s3 bucket we can chuck the files into, and then we just make the assumption that you need sample data before all the tests willl pass?

**Comment by bryevdv** [comment]
All these testes that actually run the server, those are integration tests. We should separate those, completely, from out unit tests anyway. I don't especially care if the integration tests are a little harder to run.

**Comment by bryevdv** [comment]
But to answer the question, yes there is an s3 bucket for `bokeh.sampledata` @mattpap probably has the information for accessing it most at hand.

**Comment by hhuuggoo** [comment]
@bryevdv these tests don't run the server they use the test client

**Comment by bryevdv** [comment]
Will move in to separate bokeh.server package distribution.
