### ISSUE TITLE
`publishing` example from the `embed` directory fails

### ISSUE THREAD

**Issue by knightofni** [bokeh/bokeh#1943]
With an error message that is not particularly helpfull. Using bokeh 0.8.
```
➜  embed  python publishing.py
Using saved session configuration for http://localhost:5006/
To override, pass 'load_from_config=False' to Session
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
Traceback (most recent call last):
  File "publishing.py", line 11, in <module>
    Session().register('testuser', 'testpassword')
  File "/Users/nicolas/anaconda/lib/python2.7/site-packages/bokeh/session.py", line 208, in register
    raise RuntimeError("Unknown Error")
RuntimeError: Unknown Error
```

**Comment by damianavila** [comment]
This is because you need the bokeh-server working... but it is weird because I have this traceback:

```
Using saved session configuration for http://localhost:5006/
To override, pass 'load_from_config=False' to Session
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
/media/datos/Desarrollos/bokeh/bokeh/session.py:318: UserWarning: You need to start the bokeh-server to see this example.
  warnings.warn("You need to start the bokeh-server to see this example.")
Traceback (most recent call last):
  File "publishing.py", line 11, in <module>
    Session().register('testuser', 'testpassword')
  File "/media/datos/Desarrollos/bokeh/bokeh/session.py", line 205, in register
    'api': 'true'
  File "/media/datos/Desarrollos/bokeh/bokeh/session.py", line 319, in execute
    raise e
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

where you can see we warn about the need of the server...

**Comment by damianavila** [comment]
OK, now with the server working I can reproduce your error...

**Comment by knightofni** [comment]
Yeah, i should have mentionned i had the bokeh-server running...

**Comment by damianavila** [comment]
You need to start the bokeh server with the `-m` option... http://bokeh.pydata.org/en/latest/docs/user_guide/server.html#authentication

I forgot about that...:wink: 
We probably need to add that to the README.
