### ISSUE TITLE
Abstract render  - ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by dasfaha** [bokeh/bokeh#2020]
Hi,

I am trying to run the abstract render example but I run into a ValueError. 

Here is the abstractrender.py error I get when I try to run this example.

```
PS C:\Anaconda\Examples\bokeh\plotting\server> python abstractrender.py
Using saved session configuration for http://localhost:5006/                                   
To override, pass 'load_from_config=False' to Session                                          
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost      
INFO:bokeh.session:got read write apikey                                                       
Traceback (most recent call last):                                                             
  File "abstractrender.py", line 9, in <module>                                                
    output_server("abstractrender")                                                            
  File "C:\Anaconda\lib\site-packages\bokeh\plotting.py", line 379, in output_server           
    session.load_document(curdoc())                                                            
  File "C:\Anaconda\lib\site-packages\bokeh\session.py", line 543, in load_document            
    self.gc()                                                                                  
  File "C:\Anaconda\lib\site-packages\bokeh\session.py", line 529, in gc                       
    self.post_json(url)                                                                        
  File "C:\Anaconda\lib\site-packages\bokeh\session.py", line 367, in post_json                
    return self.execute_json('post', url, headers=headers, **kwargs)                           
  File "C:\Anaconda\lib\site-packages\bokeh\session.py", line 335, in execute_json             
    return utils.get_json(resp)                                                                
  File "C:\Anaconda\lib\site-packages\bokeh\utils.py", line 41, in get_json                    
    return response.json()                                                                     
  File "C:\Anaconda\lib\site-packages\requests\models.py", line 799, in json                   
    return json.loads(self.text, **kwargs)                                                     
  File "C:\Anaconda\lib\json\__init__.py", line 338, in loads                                  
    return _default_decoder.decode(s)                                                          
  File "C:\Anaconda\lib\json\decoder.py", line 366, in decode                                  
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                          
  File "C:\Anaconda\lib\json\decoder.py", line 384, in raw_decode                              
    raise ValueError("No JSON object could be decoded")                                        
ValueError: No JSON object could be decoded                                                    
```
With the server running I get the error below:

```
INFO:tornado.access:200 GET /bokeh/userinfo/ (127.0.0.1) 0.00ms
INFO:tornado.access:200 GET /bokeh/getdocapikey/cb249485-bba5-4893-9408-0d00e657b349 (127.0.0.1) 30.00ms
ERROR:bokeh.server:Exception on /bokeh/bb/cb249485-bba5-4893-9408-0d00e657b349/gc [POST]
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Anaconda\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Anaconda\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Anaconda\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Anaconda\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Anaconda\lib\site-packages\bokeh\server\views\bbauth.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\bokeh\server\views\backbone.py", line 33, in gc
    t.load(gc=True)
  File "C:\Anaconda\lib\site-packages\bokeh\server\serverbb.py", line 369, in load
    clientdoc = bokeh_app.backbone_storage.get_document(self.server_docobj.docid)
  File "C:\Anaconda\lib\site-packages\bokeh\server\serverbb.py", line 90, in get_document
    doc = Document(json_objs)
  File "C:\Anaconda\lib\site-packages\bokeh\document.py", line 42, in __init__
    self.load(*json_objs, dirty=False)
  File "C:\Anaconda\lib\site-packages\bokeh\document.py", line 184, in load
    model = cls.load_json(obj_attrs)
  File "C:\Anaconda\lib\site-packages\bokeh\plot_object.py", line 161, in load_json
    instance.update(**attrs)
  File "C:\Anaconda\lib\site-packages\bokeh\plot_object.py", line 274, in update
    setattr(self, k, v)
  File "C:\Anaconda\lib\site-packages\bokeh\properties.py", line 608, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))
AttributeError: unexpected attribute 'discrete_ranges' to ColumnDataSource, possible attributes are column_names, data, name, selected, session or tags
ERROR:tornado.access:500 POST /bokeh/bb/cb249485-bba5-4893-9408-0d00e657b349/gc (127.0.0.1) 100.00ms
```
I am using Bokeh 0.8.1 on Windows 7 with the Anaconda Continuum distribution Python 2.7.

There is a related issue here: https://github.com/bokeh/bokeh/issues/1290

But obviously moving to Bokeh 0.7 hasn't fixed the issue for me.

Thanks,
David

**Comment by bryevdv** [comment]
AR removed / migrated to Datashaderr
