### ISSUE TITLE
stock_applet example crash

### ISSUE THREAD

**Issue by knightofni** [bokeh/bokeh#2032]
I've got the same crash on my local machine (mac os) & my vagrant dev box (ubuntu)

flask_server.py runs, the crash happens when the browser request the page.

#### Installed libs and versions  (same on both machines)

```
bokeh.__version__ : '0.8.1'
flask.__version__ : '0.10.1'
werkzeug.__version__: '0.10.1'
tornado.version : '4.1'
```

#### debug log from flask_server.py
```
(MD_Flask)vagrant@vagrant-ubuntu-trusty-64:~/anaconda/pkgs/bokeh-0.8.1-np19py27_0/Examples/bokeh/app/stock_applet$ python flask_server.py

View this example at: http://localhost:5050

INFO:werkzeug: * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat

View this example at: http://localhost:5050

WARNING:bokeh.session:root_url should end with a /, adding one
Using saved session configuration for http://localhost:5006
To override, pass 'load_from_config=False' to Session
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
INFO:bokeh.session:No documents found, creating new document 'stock_example5cc49585-bf51-4ec6-9435-5c3e1848f513'
INFO:bokeh.session:got read write apikey
INFO:werkzeug:10.0.2.2 - - [05/Mar/2015 09:45:37] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/anaconda/pkgs/bokeh-0.8.1-np19py27_0/Examples/bokeh/app/stock_applet/flask_server.py", line 28, in applet
    applet = make_stock_applet()
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/bokeh/pluginutils.py", line 26, in wrapper
    changed = session.store_document(curdoc())
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/bokeh/session.py", line 583, in store_document
    self.push(*json_objs)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/bokeh/session.py", line 525, in push
    self.post_json(url, data=data)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/bokeh/session.py", line 367, in post_json
    return self.execute_json('post', url, headers=headers, **kwargs)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/bokeh/session.py", line 335, in execute_json
    return utils.get_json(resp)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/bokeh/utils.py", line 41, in get_json
    return response.json()
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/requests/models.py", line 799, in json
    return json.loads(self.text, **kwargs)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
INFO:werkzeug:10.0.2.2 - - [05/Mar/2015 09:45:37] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [05/Mar/2015 09:45:37] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [05/Mar/2015 09:45:37] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [05/Mar/2015 09:45:37] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [05/Mar/2015 09:45:37] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [05/Mar/2015 09:45:37] "GET /?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
INFO:werkzeug:10.0.2.2 - - [05/Mar/2015 09:45:37] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

#### from bokeh-server (run with `bokeh-server --backend memory`)
```
(MD_Flask)vagrant@vagrant-ubuntu-trusty-64:~$ bokeh-server --backend memory

    Bokeh Server Configuration
    ==========================
    python version : 2.7.9
    bokeh version  : 0.8.1
    listening      : 127.0.0.1:5006
    backend        : memory
    python options : debug:OFF, verbose:OFF, filter-logs:OFF, multi-user:OFF
    js options     : splitjs:OFF, debugjs:OFF

/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/bokeh/server/blaze/__init__.py:19: UserWarning: could not import multiuser blaze server No module named blaze.  This is fine if you do not intend to use blaze capabilities in the bokeh server
  warnings.warn(msg)
INFO:tornado.access:200 GET /bokeh/userinfo/ (127.0.0.1) 7.32ms
INFO:tornado.access:200 POST /bokeh/doc/ (127.0.0.1) 3.71ms
INFO:tornado.access:200 GET /bokeh/getdocapikey/63f911e4-42b0-4010-9b8a-dbb391976771 (127.0.0.1) 12.49ms
INFO:tornado.access:200 POST /bokeh/bb/63f911e4-42b0-4010-9b8a-dbb391976771/gc (127.0.0.1) 25.08ms
INFO:tornado.access:200 GET /bokeh/bb/63f911e4-42b0-4010-9b8a-dbb391976771/ (127.0.0.1) 1.72ms
INFO:tornado.access:200 POST /bokeh/63f911e4-42b0-4010-9b8a-dbb391976771/publish (127.0.0.1) 1.85ms
ERROR:bokeh.server:Exception on /bokeh/bb/63f911e4-42b0-4010-9b8a-dbb391976771/bulkupsert [POST]
Traceback (most recent call last):
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/bokeh/server/views/bbauth.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/bokeh/server/views/backbone.py", line 63, in bulk_upsert
    clientdoc.load(*data, events='none', dirty=True)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/bokeh/document.py", line 183, in load
    cls = PlotObject.get_class(obj_type)
  File "/home/vagrant/anaconda/envs/MD_Flask/lib/python2.7/site-packages/bokeh/plot_object.py", line 63, in get_class
    raise KeyError("View model name '%s' not found" % view_model_name)
KeyError: u"View model name 'StockApp' not found"
ERROR:tornado.access:500 POST /bokeh/bb/63f911e4-42b0-4010-9b8a-dbb391976771/bulkupsert (127.0.0.1) 76.07ms
```

**Comment by knightofni** [comment]
Works perfectly, just needs to open the readme...
