### ISSUE TITLE
simpleapp broken

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2119]
```
2015-03-30 16:30:29,043:WARNING:tornado.access:404 GET /bokeh/airports/ (127.0.0.1) 1.69ms
2015-03-30 16:30:33,408:ERROR:bokeh.server:Exception on /bokeh/stocks/ [GET]
Traceback (most recent call last):
  File "/Users/fpliger/anaconda/envs/pybk27/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/fpliger/anaconda/envs/pybk27/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/fpliger/anaconda/envs/pybk27/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/fpliger/anaconda/envs/pybk27/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/fpliger/anaconda/envs/pybk27/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/fpliger/dev/repos/bokeh/bokeh/server/utils/plugins.py", line 57, in wrapper
    obj = func(*args, **kwargs)
  File "/Users/fpliger/dev/repos/bokeh/bokeh/simpleapp.py", line 50, in gen
    app = SimpleApp.create(self.name, [x.clone() for x in self.widgets])
  File "/Users/fpliger/dev/repos/bokeh/bokeh/models/widgets/layouts.py", line 93, in create
    obj.set_output()
  File "/Users/fpliger/dev/repos/bokeh/bokeh/models/widgets/layouts.py", line 191, in set_output
    args = self.args_for_func(func)
  File "/Users/fpliger/dev/repos/bokeh/bokeh/models/widgets/layouts.py", line 186, in args_for_func
    args = arg_filter(func, args)
  File "/Users/fpliger/dev/repos/bokeh/bokeh/util/functions.py", line 24, in arg_filter
    arg_names, vararg_name, keyword_name, defaults = inspect.getargspec(func)
NameError: global name 'inspect' is not defined
2015-03-30 16:30:33,412:ERROR:tornado.access:500 GET /bokeh/stocks/ (127.0.0.1) 39.30ms
```

**Comment by hhuuggoo** [comment]
sorry - I think when I was merging I moved some stuff around to respond to where utils was - I must have forgotten to test after.   I can fix this tonight

**Comment by fpliger** [comment]
thanks @hhuuggoo. It's a simple one line fix (if I'm not overseeing other more complex things). I'll be doing it in a few minutes.
