### ISSUE TITLE
stock_app_simple.py does not respond to 2. change on the dropdown field

### ISSUE THREAD

**Issue by bald** [bokeh/bokeh#2124]
The example stock_app_simple.py does not respond to the 2. change on the dropdown field.
For example a first click on "GOOG" changes the plot, however, a second click on "INTC" does not change anything.
This is the bokeh-server output:

    Traceback (most recent call last):
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
        raise value
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/bokeh/server/views/backbone.py", line 208, in _handle_specific_model_put
        return _handle_specific_model(docid, typename, id, request.method)
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/bokeh/server/crossdomain.py", line 34, in wrapped_function
        resp = make_response(f(*args, **kwargs))
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/bokeh/server/views/backbone.py", line 169, in _handle_specific_model
        return update(docid, typename, id)
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/bokeh/server/views/bbauth.py", line 21, in wrapper
        return func(*args, **kwargs)
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/bokeh/server/views/backbone.py", line 269, in update
        t.load()
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/bokeh/server/serverbb.py", line 376, in load
        clientdoc.load(*temporary_json, events='none', dirty=False)
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/bokeh/document.py", line 197, in load
        m.setup_events()
    File "/home/till/programming/miniconda3/lib/python3.4/site-packages/bokeh/models/widgets/layouts.py", line 143, in setup_events
        for k in self.__dict__.keys():
    RuntimeError: dictionary changed size during iteration

The "old" stock_app.py is working as expected.

**Comment by fpliger** [comment]
closed via https://github.com/bokeh/bokeh/pull/2125
