### ISSUE TITLE
Pandas periods are not recognised

### ISSUE THREAD

**Issue by koldunovn** [bokeh/bokeh#2266]
When I try to use pandas periods (generated with pandas.period_range) as x axis, I get `ms` instead of dates.
Code example:

``` python
import pandas as pd
import numpy as np
from bokeh.plotting import figure, output_notebook, show

dates = index=pd.period_range('1900-01-01','2000-01-01', freq='A')
ts = np.random.randn(100)

p = figure(x_axis_type="datetime")
p.line(dates,ts)
show(p)
```

If I use:

``` python
dates = index=pd.date_range('1900-01-01','2000-01-01', freq='A')
```

I get proper dates.

**Comment by bryevdv** [comment]
As of `0.12.5` this actually results in a validation error:
```
❯ BOKEH_RESOURCES=inline python foo.py
/Users/bryan/work/bokeh/bokeh/models/sources.py:91: BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('x', 101), ('y', 100)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.items())), BokehUserWarning))
/Users/bryan/work/bokeh/bokeh/core/json_encoder.py:73: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access Timestamp as pandas.Timestamp
  if pd and isinstance(obj, pd.tslib.Timestamp):
Traceback (most recent call last):
  File "foo.py", line 10, in <module>
    show(p)
  File "/Users/bryan/work/bokeh/bokeh/io.py", line 288, in show
    return _show_with_state(obj, _state, browser, new, notebook_handle=notebook_handle)
  File "/Users/bryan/work/bokeh/bokeh/io.py", line 322, in _show_with_state
    _show_file_with_state(obj, state, new, controller)
  File "/Users/bryan/work/bokeh/bokeh/io.py", line 327, in _show_file_with_state
    filename = save(obj, state=state)
  File "/Users/bryan/work/bokeh/bokeh/io.py", line 381, in save
    _save_helper(obj, filename, resources, title)
  File "/Users/bryan/work/bokeh/bokeh/io.py", line 436, in _save_helper
    html = file_html(obj, resources, title=title)
  File "/Users/bryan/work/bokeh/bokeh/embed.py", line 423, in file_html
    (docs_json, render_items) = _standalone_docs_json_and_render_items(models)
  File "/Users/bryan/work/bokeh/bokeh/embed.py", line 752, in _standalone_docs_json_and_render_items
    docs_json[k] = v.to_json()
  File "/Users/bryan/work/bokeh/bokeh/document.py", line 734, in to_json
    doc_json = self.to_json_string()
  File "/Users/bryan/work/bokeh/bokeh/document.py", line 763, in to_json_string
    return serialize_json(json, indent=indent)
  File "/Users/bryan/work/bokeh/bokeh/core/json_encoder.py", line 226, in serialize_json
    return json.dumps(obj, cls=BokehJSONEncoder, allow_nan=False, indent=indent, separators=separators, sort_keys=True, **kwargs)
  File "/Users/bryan/anaconda/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/bryan/anaconda/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/bryan/anaconda/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/bryan/work/bokeh/bokeh/core/json_encoder.py", line 149, in default
    return self.transform_python_types(obj)
  File "/Users/bryan/work/bokeh/bokeh/core/json_encoder.py", line 116, in transform_python_types
    return super(BokehJSONEncoder, self).default(obj)
  File "/Users/bryan/anaconda/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Period' is not JSON serializable
```
