### ISSUE TITLE
[ENH]: Better error message for invalid data type

### ISSUE THREAD

**Issue by hargup** [bokeh/bokeh#2353]
I got the following error message when I was trying to plot bar charts:

``` python
Traceback (most recent call last):
  File "calc_graph_gbc.py", line 49, in <module>
    plot = Bar(data, cat=cultures, title="Bar example", xlabel='categories', ylabel='values', width=400, height=400)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/bokeh/charts/builder/bar_builder.py", line 93, in Bar
    xgrid=xgrid, ygrid=ygrid, y_range=y_range, **kw
  File "/home/hargup/anaconda/lib/python2.7/site-packages/bokeh/charts/_builder.py", line 42, in create_and_build
    chart.add_builder(builder)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/bokeh/charts/_chart.py", line 118, in add_builder
    builder.create(self)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/bokeh/charts/_builder.py", line 165, in create
    self._process_data()
  File "/home/hargup/anaconda/lib/python2.7/site-packages/bokeh/charts/builder/bar_builder.py", line 156, in _process_data
    mid = np.array(values) / 2
TypeError: unsupported operand type(s) for /: 'numpy.ndarray' and 'int'
```

A few minutes later I figured out that my values were `strings` instead of numerals. Debugging will be a lot easier if bokeh can provide a more informative error message for such mistakes.

**Comment by bryevdv** [comment]
`bokeh.chart` (including `Bar`) has been moved to https://github.com/bokeh/bkcharts If appropriate this issue should be re-opened there.
