### ISSUE TITLE
test_matrix errors

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#2486]
pinging @Maggie-M 

When I try to run the script I get this:

1- In py3 I have this issue:

```
CREATING NEW ENV py34_conda_update
Traceback (most recent call last):
  File "test_matrix.py", line 260, in <module>
    cleaner(os.path.join(root, "envs", environment))
  File "/home/damian/miniconda3/envs/bokeh/lib/python3.4/posixpath.py", line 89, in join
    "components") from None
TypeError: Can't mix strings and bytes in path components
```

2- I switch to py2 and then:

```
$ python test_matrix.py -v 0.9.1rc.69178283 -p 0.9.1
CREATING NEW ENV py27_conda_clean
Traceback (most recent call last):
  File "test_matrix.py", line 261, in <module>
    conda_creator(environment, envs[environment]["init"])
  File "test_matrix.py", line 74, in conda_creator
    call_wrapper("conda create --yes -n %s %s %s" % (env_name, pkgs, OPTIONS["channel"]), shell=True)
KeyError: 'channel'
```

I fixed with this diff:

```diff
$ git diff
diff --git a/scripts/test_matrix.py b/scripts/test_matrix.py
index a07c7fb..c7f7120 100644
--- a/scripts/test_matrix.py
+++ b/scripts/test_matrix.py
@@ -8,6 +8,7 @@ import textwrap
 
 OPTIONS = {
     "dry-run"  :  False,
+    "channel"  : "bokeh"
 }
```

3- But then when I tried to run it, it tries to install the bokeh package in the current env, not the created one...

```
$ python test_matrix.py -v 0.9.1rc.69178283 -p 0.9.1 --keep
CREATING NEW ENV py27_conda_clean
Fetching package metadata: ..........
Solving package specifications: .
Package plan for installation in environment /home/damian/miniconda3/envs/py27_conda_clean:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    nose-1.3.7                 |           py27_0         194 KB

The following NEW packages will be INSTALLED:

    bokeh:              0.9.0-np19py27_1 
    certifi:            14.05.14-py27_0  
    dateutil:           2.4.1-py27_0     
    flask:              0.10.1-py27_1    
    greenlet:           0.4.7-py27_0     
    itsdangerous:       0.24-py27_0      
    jinja2:             2.7.3-py27_1     
    libsodium:          0.4.5-0          
    markupsafe:         0.23-py27_0      
    mock:               1.0.1-py27_0     
    nose:               1.3.7-py27_0     
    numpy:              1.9.2-py27_0     
    openssl:            1.0.1k-1         
    pandas:             0.16.2-np19py27_0
    pip:                7.0.3-py27_0     
    python:             2.7.10-0         
    python-dateutil:    2.4.2-py27_0     
    pytz:               2015.4-py27_0    
    pyyaml:             3.11-py27_1      
    pyzmq:              14.7.0-py27_0    
    readline:           6.2-2            
    requests:           2.7.0-py27_0     
    setuptools:         17.1.1-py27_0    
    six:                1.9.0-py27_0     
    sqlite:             3.8.4.1-1        
    ssl_match_hostname: 3.4.0.2-py27_0   
    system:             5.8-2            
    tk:                 8.5.18-0         
    tornado:            4.2-py27_0       
    werkzeug:           0.10.4-py27_0    
    yaml:               0.1.6-0          
    zeromq:             4.0.5-0          
    zlib:               1.2.8-0          

Fetching packages ...
nose-1.3.7-py2 100% |#########################################################################################################################| Time: 0:00:00 514.27 kB/s
Extracting packages ...
[      COMPLETE      ]|############################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|############################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate py27_conda_clean
#
# To deactivate this environment, use:
# $ source deactivate
#
/bin/sh: 1: source: not found
Fetching package metadata: ............
Solving package specifications: .
Package plan for installation in environment /home/damian/miniconda3/envs/bokeh_py2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bokeh-0.9.1rc.69178283     |       np19py27_1        15.3 MB

The following NEW packages will be INSTALLED:

    bokeh: 0.9.1rc.69178283-np19py27_1

Fetching packages ...
```

See the `/bin/sh: 1: source: not found`, the failure seems to be there...

**Comment by Maggie-M** [comment]
The first error is a bug I had missed (a later line requires OPTIONS["channel"], but then never does anything with it).  It will be a really quick fix, so I'll make a PR for it now.

The other issue may have something to do with miniconda.  I've only ever used this script with a full anaconda install, so that may be the issue.  I'll take a look at it and see what I can do.
