### ISSUE TITLE
Error with mpl (showing in violin plot)

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#2643]
When trying to run this example

```
import seaborn as sns

from bokeh import mpl
from bokeh.plotting import output_file, show

tips = sns.load_dataset("tips")

sns.set_style("whitegrid")

planets = sns.load_dataset("planets")
ax = sns.violinplot(x="orbital_period", y="method",
                    data=planets[planets.orbital_period < 1000],
                    scale="width", palette="Set3")

output_file("violin.html")

show(mpl.to_bokeh())
```

I ran into this error

```
Traceback (most recent call last):
  File "violin.py", line 29, in <module>
    show(mpl.to_bokeh())
  File "/Users/mmari/Desktop/continuum/bokeh/bokeh/compat/mpl.py", line 77, in to_bokeh
    exporter.run(fig)
  File "/Users/mmari/Desktop/continuum/bokeh/bokeh/compat/mplexporter/exporter.py", line 51, in run
    self.crawl_fig(fig)
  File "/Users/mmari/Desktop/continuum/bokeh/bokeh/compat/mplexporter/exporter.py", line 118, in crawl_fig
    self.crawl_ax(ax)
  File "/Users/mmari/Desktop/continuum/bokeh/bokeh/compat/mplexporter/exporter.py", line 140, in crawl_ax
    self.draw_collection(ax, collection)
  File "/Users/mmari/Desktop/continuum/bokeh/bokeh/compat/bokeh_exporter.py", line 34, in draw_collection
    super(BokehExporter, self).draw_collection(ax, collection, force_pathtrans, force_offsettrans)
  File "/Users/mmari/Desktop/continuum/bokeh/bokeh/compat/mplexporter/exporter.py", line 272, in draw_collection
    mplobj=collection)
  File "/Users/mmari/Desktop/continuum/bokeh/bokeh/compat/mplexporter/renderers/base.py", line 255, in draw_path_collection
    offsets, styles):
  File "/Users/mmari/Desktop/continuum/bokeh/bokeh/compat/mplexporter/renderers/base.py", line 192, in _iter_path_collection
    if not path_transforms:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

However, it works fine if I supply this input

```
ax = sns.violinplot(x="day", y="total_bill", hue="sex",
                    data=tips, palette="Set2", split=True,
                    scale="count", inner="stick")
```

**Comment by squishan** [comment]
I ran into the same error, were you able to find a solution?

**Comment by tp199911** [comment]
This happens because numpy arrays don't play nice with the "if object" idiom, because it does an elementwise check and hence does not give a simple True or False.

My guess is that a list of 3x3 arrays is expected (seeing as by default they create [np.eye(3)]. However, as you can see in https://gist.github.com/tp199911/337f67b62f3aaaeecf8a, an array with shape (n, 3, 3) can be given by matplotlib.collections.Collection.get_transforms (as can be seen e.g. by set_transforms of EllipseCollection).

The easiest solution seems to be to put a check on len(path_transforms), which will work in both the case of a list and a numpy array. I have done so in PR https://github.com/bokeh/bokeh/pull/3029.
