### ISSUE TITLE
bokeh-server hangs instead of exiting if it cannot bind to requested port

### ISSUE THREAD

**Issue by ahmadia** [bokeh/bokeh#3011]
While you folks are overhauling the server, it might be a good idea to have the bokeh-server explicitly fail if it can't bind to its default behavior, since this means you've got another bokeh-server running that will receive your requests (or worse, another process!)

**Comment by bryevdv** [comment]
More information needed, this is definitely what I have ever observed. This is what I see currently:
```
bryan@0199-bryanv (git:feature/text_annotation) .../sphinx/source/docs/user_guide/source_examples $ bokeh-server 

    Bokeh Server Configuration
    ==========================
    python version : 3.4.3
    bokeh version  : 0.10.0-130-g6f0e0f9-dirty
    listening      : 127.0.0.1:5006
    backend        : memory
    python options : debug:OFF, verbose:OFF, filter-logs:OFF, multi-user:OFF
    js options     : debugjs:OFF
    
^Z
[1]+  Stopped                 bokeh-server
bryan@0199-bryanv (git:feature/text_annotation) .../sphinx/source/docs/user_guide/source_examples $ bg
[1]+ bokeh-server &
bryan@0199-bryanv (git:feature/text_annotation) .../sphinx/source/docs/user_guide/source_examples $ bokeh-server 

    Bokeh Server Configuration
    ==========================
    python version : 3.4.3
    bokeh version  : 0.10.0-130-g6f0e0f9-dirty
    listening      : 127.0.0.1:5006
    backend        : memory
    python options : debug:OFF, verbose:OFF, filter-logs:OFF, multi-user:OFF
    js options     : debugjs:OFF
    
Traceback (most recent call last):
  File "/Users/bryan/anaconda/bin/bokeh-server", line 7, in <module>
    bokeh.server.run()
  File "/Users/bryan/work/bokeh/bokeh/server/__init__.py", line 186, in run
    start_server(args)
  File "/Users/bryan/work/bokeh/bokeh/server/__init__.py", line 190, in start_server
    start.start_simple_server(args)
  File "/Users/bryan/work/bokeh/bokeh/server/start.py", line 72, in start_simple_server
    server.listen(server_settings.port, server_settings.ip)
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/tornado/netutil.py", line 187, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
```

**Comment by ahmadia** [comment]
double-checking, this definitely bit me earlier today.

**Comment by ahmadia** [comment]
Oh, it's so much more insidious!

**Comment by ahmadia** [comment]
@bryevdv - supervisord doesn't recognize that this Bokeh process has failed.  On my Mac it's just frozen/hung.  Are you seeing that as well?

**Comment by bryevdv** [comment]
I'm not sure, I don't know much about supervisord (and was not using it above)

**Comment by ahmadia** [comment]
Does the process explicitly exit?

**Comment by bryevdv** [comment]
no it looks like it didn't exit.

**Comment by ahmadia** [comment]
Okay, well, let's call this undesirable behavior that will hopefully be fixed in the server overhaul :)

**Comment by bryevdv** [comment]
ping @havocp

**Comment by havocp** [comment]
This is indeed fixed on the tornado branch.

```
$ bin/bokeh serve --port 100
Traceback (most recent call last):
  File "bin/bokeh", line 6, in <module>
    command.main(sys.argv)
  File "/home/hp/checkout/bokeh/bokeh/command/__init__.py", line 133, in main
    args.func(args)
  File "/home/hp/checkout/bokeh/bokeh/command/__init__.py", line 94, in func
    server = Server(applications, port=self.port)
  File "/home/hp/checkout/bokeh/bokeh/server/server.py", line 38, in __init__
    self._http.bind(self._port)
  File "/home/hp/bin/Anaconda-2.2.0/lib/python2.7/site-packages/tornado/tcpserver.py", line 171, in bind
    backlog=backlog)
  File "/home/hp/bin/Anaconda-2.2.0/lib/python2.7/site-packages/tornado/netutil.py", line 187, in bind_sockets
    sock.bind(sockaddr)
  File "/home/hp/bin/Anaconda-2.2.0/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 13] Permission denied
$
```

**Comment by ahmadia** [comment]
Cool!
