### ISSUE TITLE
glyphs.py server issue - plots appearing twice

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3066]
I'm seeing some weird behavior on `examples/plotting/server/glyphs.py`

I modified the code slightly to only display the scatter plots. Here's the code and at the bottom a very zoomed out version of the screenshot:

````python
# The plot server must be running
# Go to http://localhost:5006/bokeh to view this plot

import numpy as np

from bokeh.plotting import figure, show, output_server, vplot

N = 9

x = np.linspace(-2, 2, N)
y = x**2
sizes = np.linspace(10, 20, N)

xpts = np.array([-.09, -.12, .0, .12, .09])
ypts = np.array([-.1, .02, .1, .02, -.1])

output_server("glyphs")

vplot = vplot()

p = figure(width=200, height=200, title="wedge")
p.wedge(x, y, 15, 0.6, 4.1, radius_units="screen", color="#B3DE69")
vplot.children.append(p)

p = figure(width=200, height=200, title="circle_x")
p.scatter(x, y, marker="circle_x", size=sizes, color="#DD1C77", fill_color=None)
vplot.children.append(p)

p = figure(width=200, height=200, title="triangle")
p.scatter(x, y, marker="triangle", size=sizes, color="#99D594", line_width=2)
vplot.children.append(p)

p = figure(width=200, height=200, title="circle")
p.scatter(x, y, marker="o", size=sizes, color="#80B1D3", line_width=3)
vplot.children.append(p)

p = figure(width=200, height=200, title="cross")
p.scatter(x, y, marker="cross", size=sizes, color="#E6550D", line_width=2)
vplot.children.append(p)

p = figure(width=200, height=200, title="diamond")
p.scatter(x, y, marker="diamond", size=sizes, color="#1C9099", line_width=2)
vplot.children.append(p)

p = figure(width=200, height=200, title="inverted_triangle")
p.scatter(x, y, marker="inverted_triangle", size=sizes, color="#DE2D26")
vplot.children.append(p)

p = figure(width=200, height=200, title="square_x")
p.scatter(x, y, marker="square_x", size=sizes, color="#FDAE6B",
    fill_color=None, line_width=2)
vplot.children.append(p)

p = figure(width=200, height=200, title="asterisk")
p.scatter(x, y, marker="asterisk", size=sizes, color="#F0027F", line_width=2)
vplot.children.append(p)

p = figure(width=200, height=200, title="square_cross")
p.scatter(x, y, marker="square_cross", size=sizes, color="#7FC97F",
    fill_color=None, line_width=2)
vplot.children.append(p)

p = figure(width=200, height=200, title="diamond_cross")
p.scatter(x, y, marker="diamond_cross", size=sizes, color="#386CB0",
    fill_color=None, line_width=2)
vplot.children.append(p)

p = figure(width=200, height=200, title="circle_cross")
p.scatter(x, y, marker="circle_cross", size=sizes, color="#FB8072",
    fill_color=None, line_width=2)
vplot.children.append(p)

show(vplot)  # open a browser
````

<img width="1392" alt="screen shot 2015-11-04 at 7 58 36 pm" src="https://cloud.githubusercontent.com/assets/1796208/10959562/eee93ae0-832e-11e5-8595-f5572d419812.png">

**Comment by birdsarah** [comment]
i should add that i ran this but running a bokeh server `./bin/bokeh serve` and then running `python glyphs.py` from the `examples/plotting/server/` directory.

**Comment by birdsarah** [comment]
if i try running `./bin/bokeh serve examples/plotting/server/glyphs.py` then i get the following error message when I try and load http://localhost:5006/glyphs

````sh
ERROR:bokeh.application.application:Error running application handler <bokeh.application.spellings.script.ScriptHandler object at 0x106f83518>: 'not all arguments converted during string formatting\nFile "script.py", line 51, in complainer:\n" %s() call." % (self._path, name, name, name),' 'Traceback (most recent call last):\n  File "/Users/caged/Dev/bokeh/bokeh/bokeh/application/spellings/script.py", line 81, in modify_document\n    exec(self._code, self._module.__dict__)\n  File "/Users/caged/Dev/bokeh/bokeh/examples/plotting/server/glyphs.py", line 17, in <module>\n    output_server("glyphs")\n  File "/Users/caged/Dev/bokeh/bokeh/bokeh/application/spellings/script.py", line 51, in complainer\n    " %s() call." % (self._path, name, name, name),\nTypeError: not all arguments converted during string formatting\n'
````
