### ISSUE TITLE
Histogram gives ValueError or OverflowError with automatic binning on a  nearly homogenous dataset

### ISSUE THREAD

**Issue by relativistic** [bokeh/bokeh#3124]
I am finding a problem with applying `bokeh.charts.Histogram` on a `DataFrame`, when I do not specify the `bins` argument. This seems to happen when I have a nearly homogenous dataset, but maybe something else is causing the problem. I get one of two errors:

    OverflowError: cannot convert float infinity to integer

and/or

     ValueError: cannot convert float NaN to integer

`bokeh.__version__`  is `'0.10.0'`

Some example code that fails:

```python
import pandas as pd
from bokeh.charts import Histogram
import numpy as np
from bokeh.io import show
from bokeh.plotting import output_file
output_file('foo.html')

# This does not work
values = np.ones(300)

# This works though
# values = np.arange(1, 300)**2

for i in [200, 210, 233, 102, 135, 140, 175, 60, 195, 290, 89, 120]:
    values[i] = 0
values[255] = -2
values[234] = -2
values[160] = -2

df = pd.DataFrame({'values': pd.Series(values)})

hist = Histogram(df, values='values',  legend=True,
                 # bins=20 # If I specify bins, it works
                 )
show(hist)

```

The traceback (run from an ipython terminal) is:

```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    hist = Histogram(df, values='values',  legend=True,
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/builder/histogram_builder.py", line 53, in Histogram
    return create_and_build(HistogramBuilder, data, **kw)
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/_builder.py", line 64, in create_and_build
    chart.add_builder(builder)
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/_chart.py", line 134, in add_builder
    builder.create(self)
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/_builder.py", line 303, in create
    chart.add_renderers(self, renderers)
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/_chart.py", line 129, in add_renderers
    self.renderers += renderers
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/builder/bar_builder.py", line 228, in _yield_renderers
    **group_kwargs)
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/glyphs.py", line 469, in __init__
    super(HistogramGlyph, self).__init__(**kwargs)
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/_models.py", line 61, in __init__
    self.setup()
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/_models.py", line 64, in setup
    self.renderers = [renderer for renderer in self.build_renderers()]
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/glyphs.py", line 478, in build_renderers
    self.bins = Bins(values=self.values, bin_count=self.bin_count)
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/stats.py", line 164, in __init__
    super(Bins, self).__init__(**properties)
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/stats.py", line 23, in __init__
    self._refresh()
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/stats.py", line 29, in _refresh
    self.calculate()
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/charts/stats.py", line 174, in calculate
    binned, bin_edges = pd.cut(self.get_data(), self.bin_count, retbins=True, precision=0)
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pandas/tools/tile.py", line 100, in cut
    bins = np.linspace(mn, mx, bins + 1, endpoint=True)
  File "/Users/<username>/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/function_base.py", line 84, in linspace
    num = int(num)
OverflowError: cannot convert float infinity to integer
```

**Comment by birdsarah** [comment]
ping @rothnic @fpliger

**Comment by rothnic** [comment]
@relativistic Thanks, yeah I need to handle the case when data results in an inner quartile range of 0. I'll have it fixed in the next release.

**Comment by rothnic** [comment]
Closed by the referenced commit.
