### ISSUE TITLE
Error using Bokeh with Flask

### ISSUE THREAD

**Issue by napsternxg** [bokeh/bokeh#3372]
I am trying to render bokeh plots via Flask using the example described in: https://github.com/bokeh/bokeh/tree/master/examples/embed/simple

I am getting the following error:

```
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178] Traceback (most recent call last):
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]   File "/usr/web/cgi-bin/flask_temp/cgi.py", line 3, in <module>
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]     from app import app
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]   File "/usr/web/cgi-bin/flask_temp/app.py", line 8, in <module>
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]     from bokeh.plotting import figure
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]   File "/usr/local/lib/python2.7/dist-packages/bokeh/plotting.py", line 15, in <module>
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]     from .session import Session
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]   File "/usr/local/lib/python2.7/dist-packages/bokeh/session.py", line 30, in <module>
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]     from requests.exceptions import ConnectionError
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]   File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 58, in <module>
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]     from . import utils
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]   File "/usr/local/lib/python2.7/dist-packages/requests/utils.py", line 12, in <module>
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]     import cgi
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]   File "/usr/web/cgi-bin/flask_temp/cgi.py", line 3, in <module>
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178]     from app import app
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178] ImportError: cannot import name app
    [Fri Dec 18 12:13:46 2015] [error] [client 172.17.106.178] Premature end of script headers: cgi.py
```

My other flask apps are running perfectly fine. I believe there is an issue with the Bokeh library. Has anyone else also faced similar issue ?

**Comment by bryevdv** [comment]
Bokeh is currently undergoing some major overhauls in a few areas, it may be that you are simply trying to run things that are incompatible between versions. But there is no way to say without more information. It's always advisable to share as much information about Bokeh versions, platform type, and browser, etc. as possible when submitting issues.

**Comment by bryevdv** [comment]
Also please note the full `0.11` release with have some complete sample web apps and guidance for integrating Bokeh server with them.

**Comment by napsternxg** [comment]
Here are more details:

```
$ uname -a
3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u1 x86_64 GNU/Linux
$ python --version
Python 2.7.3
$ python -c "import bokeh; print bokeh.__version__"
0.10.0
$ python -c "import flask; print flask.__version__"
0.10.1
```

Here is my `cgi.py`
```
$ cat cgi.py                                                                                                                                                                                                                        
#!/usr/bin/python

from app import app
import logging, sys

from wsgiref.handlers import CGIHandler
logging.basicConfig(stream=sys.stderr)
CGIHandler().run(app)
```

And here is my `app.py`
```
$ cat app.py 
import logging
from logging import StreamHandler
from flask import Flask, render_template, request,redirect,url_for
import os
import sys

from bokeh.embed import components
from bokeh.plotting import figure
from bokeh.resources import INLINE
from bokeh.util.string import encode_utf8



app = Flask(__name__)
logger = StreamHandler()
logger.setLevel(logging.DEBUG)
app.logger.addHandler(logger)

@app.route("/")
def home(methods=['GET']):
  return "Flask temporary app"

colors = {
    'Black': '#000000',
    'Red':   '#FF0000',
    'Green': '#00FF00',
    'Blue':  '#0000FF',
}


def getitem(obj, item, default):
    if item not in obj:
        return default
    else:
        return obj[item]

@app.route("/profile")
def polynomial():
    """ Very simple embedding of a polynomial chart"""
    # Grab the inputs arguments from the URL
    # This is automated by the button
    args = request.args

    # Get all the form arguments in the url with defaults
    color = colors[getitem(args, 'color', 'Black')]
    _from = int(getitem(args, '_from', 0))
    to = int(getitem(args, 'to', 10))

    # Create a polynomial line graph
    x = list(range(_from, to + 1))
    fig = figure(title="Polynomial")
    fig.line(x, [i ** 2 for i in x], color=color, line_width=2)

    # Configure resources to include BokehJS inline in the document.
    # For more details see:
    #   http://bokeh.pydata.org/en/latest/docs/reference/resources_embedding.html#bokeh-embed
    js_resources = INLINE.render_js()
    css_resources = INLINE.render_css()

    # For more details see:
    #   http://bokeh.pydata.org/en/latest/docs/user_guide/embedding.html#components
    script, div = components(fig, INLINE)
    html = render_template(
        'profile.html',
        plot_script=script,
        plot_div=div,
        js_resources=js_resources,
        css_resources=css_resources,
        color=color,
        _from=_from,
        to=to
        )
    return encode_utf8(html)

if __name__ == "__main__":
  app.debug = True
  app.run(debug=True)

```

**Comment by napsternxg** [comment]
Just got this issue resolved at Stackoverflow http://stackoverflow.com/questions/34361741/bokeh-error-while-using-with-flask/34362754#34362754.

**Comment by bryevdv** [comment]
I was about to suggest the same thing, glad it was simple to resolve, and thanks for the additional info!

**Comment by napsternxg** [comment]
@bryevdv However, I am now getting the following error:

```
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178] ERROR:app:Exception on /profile [GET]                                                                                                                                                                               
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178] Traceback (most recent call last):                                                                                                                                                                                  
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app                                                                                                                                
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178]     response = self.full_dispatch_request()                                                                                                                                                                         
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request                                                                                                                   
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178]     rv = self.handle_user_exception(e)                                                                                                                                                                              
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception                                                                                                                   
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178]     reraise(exc_type, exc_value, tb)                                                                                                                                                                                
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request                                                                                                                   
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178]     rv = self.dispatch_request()                                                                                                                                                                                    
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request                                                                                                                        
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178]     return self.view_functions[rule.endpoint](**req.view_args)                                                                                                                                                      
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178]   File "/usr/web/cgi-bin/flask_temp/app.py", line 57, in polynomial                                                                                                                                             
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178]     js_resources = INLINE.render_js()                                                                                                                                                                               
[Fri Dec 18 13:36:43 2015] [error] [client 172.17.106.178] AttributeError: 'Resources' object has no attribute 'render_js'                 
```

I know this has been already discussed at the #3186 but there is not solution given there.

**Comment by napsternxg** [comment]
Using the correct example for version `0.10.0` fixed the above issue as well. 
https://github.com/bokeh/bokeh/blob/0.10.0/examples/embed/simple/simple.py
