### ISSUE TITLE
Running BokehTornado server on background thread

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#3476]
I recently created a notebook for datashader which uses bokeh server with an extra route for serving dynamic images:
`https://github.com/ContinuumIO/datashader/blob/master/example/datashader_notebook.ipynb`

To avoid blocking the notebook, I run `server.start()` on a background thread:
```python
def create_app():
    server = Server(Application(), io_loop=IOLoop(), extra_patterns=[(r"/(.*)", GetDataset)], port=5006)
    return server 

import threading

app = create_app()
t = threading.Thread(target=app.start)
t.start()
```
<img width="858" alt="screen shot 2015-12-31 at 11 26 38 am" src="https://cloud.githubusercontent.com/assets/433221/12066811/89bca646-afb3-11e5-9598-67c769df9c3b.png">
The server actually works, but does throws the exception below.

```
ERROR:tornado.application:Exception in callback <functools.partial object at 0x10c5dc3c0>
Traceback (most recent call last):
  File "/Users/bcollins/anaconda/envs/datashader/lib/python2.7/site-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/Users/bcollins/anaconda/envs/datashader/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/bcollins/anaconda/envs/datashader/lib/python2.7/site-packages/tornado/ioloop.py", line 615, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/Users/bcollins/anaconda/envs/datashader/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/bcollins/anaconda/envs/datashader/lib/python2.7/site-packages/tornado/gen.py", line 267, in wrapper
    result = func(*args, **kwargs)
  File "/Users/bcollins/projects/datashader_project/bokeh/bokeh/server/tornado.py", line 298, in _start_async
    self.exit(1)
AttributeError: 'BokehTornado' object has no attribute 'exit'
```

Not sure if I'm abusing the notebook, or whether this is a valid use case and I just need a context manager or somthing.  Looking for ideas on how to remove exception.  Note that the server still responds with images.

**Comment by bryevdv** [comment]
The code in question is this:
```
    @gen.coroutine
    def _start_async(self):
        try:
            atexit.register(self._atexit)
            signal.signal(signal.SIGTERM, self._sigterm)
        except Exception:
            self.exit(1)
```
This is the code that (at startup) registers the shutdown cleanup code. Can you catch/print the exception?  I'm guessing that was supposed to be `sys.exit(1)` but you say things are "working" and changing it to that would probably make them "not working". So maybe we can figure out what that has to be in cases when the server is running in a thread.

**Comment by ChristianTremblay** [comment]
What is the difference between the Server class and the BokehTornado class... both seems to do the server job...

**Comment by bryevdv** [comment]
`BokehTornado` is a subclass of `tornado.web.Application` which can implement at web app by associating views with different endpoints (including websocket upgrades). But, it does't do anything on its own, it needs to be used in conjunction with an HTTP server, e.g. `tornado.httpserver.HTTPServer`. The `bokeh.server.Server` class is a higher level class that coordinates and starts the tornado app and http server together conveniently.

**Comment by ChristianTremblay** [comment]
Thanks for the answer... I tried to implement something similar in my app (on Windows) and it actually don't work. 

I tried with io_loop = None

```
DEBUG:bokeh.server.tornado:Allowed Host headers: ['localhost:5006']
DEBUG:bokeh.server.tornado:These host origins can connect to the websocket: ['localhost:5006']
DEBUG:bokeh.server.tornado:Patterns are: [('/?', <class 'bokeh.server.views.doc_handler.DocHandler'>, {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x00000000091CACF8>, 'bokeh_websocket_path': '/ws'}), ('/ws', <class 'bokeh.server.views.ws.WSHandler'>, {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x00000000091CACF8>, 'bokeh_websocket_path': '/ws'}), ('/autoload.js', <class 'bokeh.server.views.autoload_js_handler.AutoloadJsHandler'>, {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x00000000091CACF8>, 'bokeh_websocket_path': '/ws'}), ('/static/(.*)', <class 'bokeh.server.views.static_handler.StaticHandler'>)]
DEBUG:bokeh.client.connection:Running state NOT_YET_CONNECTED
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\bac0-0.98.13b0-py3.4.egg\BAC0\tasks\BokehServer.py", line 28, in run
    self.process()
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\bac0-0.98.13b0-py3.4.egg\BAC0\tasks\BokehServer.py", line 33, in process
    self.task()
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\bac0-0.98.13b0-py3.4.egg\BAC0\tasks\BokehServer.py", line 36, in task
    self.server.start()
  File "c:\0Programmes\Github\bokeh\bokeh\server\server.py", line 137, in start
    self._tornado.start(start_loop=start_loop)
  File "c:\0Programmes\Github\bokeh\bokeh\server\tornado.py", line 221, in start
    self._loop.start()
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\ioloop.py", line 748, in start
    raise RuntimeError("IOLoop is already running")
RuntimeError: IOLoop is already running

INFO:bokeh.client.connection:Failed to connect to server: HTTPError(599, 'Timeout', None)
DEBUG:bokeh.client.connection:transitioning to state DISCONNECTED
DEBUG:bokeh.client.connection:Stopping client loop in state DISCONNECTED due to True from connected_or_closed
```

I then tried using io_loop = tornado.ioloop.IOLoop()
```
DEBUG:bokeh.server.tornado:Allowed Host headers: ['localhost:5006']
DEBUG:bokeh.server.tornado:These host origins can connect to the websocket: ['localhost:5006']
DEBUG:bokeh.server.tornado:Patterns are: [('/?', <class 'bokeh.server.views.doc_handler.DocHandler'>, {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x000000000935A208>, 'bokeh_websocket_path': '/ws'}), ('/ws', <class 'bokeh.server.views.ws.WSHandler'>, {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x000000000935A208>, 'bokeh_websocket_path': '/ws'}), ('/autoload.js', <class 'bokeh.server.views.autoload_js_handler.AutoloadJsHandler'>, {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x000000000935A208>, 'bokeh_websocket_path': '/ws'}), ('/static/(.*)', <class 'bokeh.server.views.static_handler.StaticHandler'>)]
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x0000000009370840>, <tornado.concurrent.Future object at 0x000000000936AA90>)
Traceback (most recent call last):
  File "c:\0Programmes\Github\bokeh\bokeh\server\tornado.py", line 296, in _start_async
    signal.signal(signal.SIGTERM, self._sigterm)
ValueError: signal only works in main thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\ioloop.py", line 600, in _run_callback
    ret = callback()
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\ioloop.py", line 615, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\gen.py", line 267, in wrapper
    result = func(*args, **kwargs)
  File "c:\0Programmes\Github\bokeh\bokeh\server\tornado.py", line 298, in _start_async
    self.exit(1)
AttributeError: 'BokehTornado' object has no attribute 'exit'
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x0000000009370840>, <tornado.concurrent.Future object at 0x000000000936AA90>)
Traceback (most recent call last):
  File "c:\0Programmes\Github\bokeh\bokeh\server\tornado.py", line 296, in _start_async
    signal.signal(signal.SIGTERM, self._sigterm)
ValueError: signal only works in main thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\ioloop.py", line 600, in _run_callback
    ret = callback()
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\ioloop.py", line 615, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Users\ctremblay.SERVISYS\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\gen.py", line 267, in wrapper
    result = func(*args, **kwargs)
  File "c:\0Programmes\Github\bokeh\bokeh\server\tornado.py", line 298, in _start_async
    self.exit(1)
AttributeError: 'BokehTornado' object has no attribute 'exit'
DEBUG:bokeh.client.connection:Running state NOT_YET_CONNECTED
```

I'll try with a subprocess as you proposed in [issue#3305] (https://github.com/bokeh/bokeh/issues/3305)

**Comment by ChristianTremblay** [comment]
I would prefer to be able to someway, configure the server without using a subprocess.

Having the choice to "fake" an application path (localhost:5506/myapp) for example... instead of using the session-id?=blabla

**Comment by bryevdv** [comment]
That's an interesting use case, but it's definitely not a first priority. To explore it you'd first need to find out if tornado `IOLoops` can be run in separate threads at all. If not, then I'd say it is a non-start (unless your app happens to already be a tornado app and you can share an `IOLoop`) and then if that is possible, it looks like `BokehTornado` would need a mode that doesn't use signals to clean up:
```
Traceback (most recent call last):
  File "c:\0Programmes\Github\bokeh\bokeh\server\tornado.py", line 296, in _start_async
    signal.signal(signal.SIGTERM, self._sigterm)
ValueError: signal only works in main thread
```
since signals can't work outside the main thread. 

Alternatively, another option might be to run `BokehTornado` in the main thread, and the "rest" of your app in a different thread.

**Comment by bryevdv** [comment]
It's also possible in the future that the "keep models up to date and issue notifications" part of the server could be made into a separate API, that could be used independently of the particular `BokehServer`

**Comment by bryevdv** [comment]
This was recently demonstrated on in a complete example on the ML: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/LYmjTXzX43E

**Comment by misterjoa** [comment]
Hello all !

Seems I got a related issue.
Some probable cause may be found in this other issue, and potentially to re-importing some modules when loading tornado in a sub- (not main) thread : https://github.com/eventlet/eventlet/issues/230

I will try to investigate further because I don't want the logic of the bokeh server to be on the main thread which is just used as a orchestrator for many tasks.

Btw Bokeh is really great and the more I investigate the more I like it !!

Cheers,

misterjoa
