### ISSUE TITLE
bokeh-0.11.0 test failures

### ISSUE THREAD

**Issue by jlec** [bokeh/bokeh#3565]
When running ```nosetests -v -e multiuser_auth_test -e usermodel_test``` with bokeh-0.11.0 and nose-1.3.7 I see the following errors:

```python
======================================================================
ERROR: Given values of categorical data, count the records of each unique value.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_cat_list_input() takes exactly 1 argument (0 given)

======================================================================
ERROR: Given values only input, use index for labels.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_values_only_input() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_boxplot_builder.test_array_input
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_array_input() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_histogram_builder.test_series_input
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_series_input() takes exactly 1 argument (0 given)

======================================================================
ERROR: A list of two lists of values in should result in 2 composite glyphs.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_array_input() takes exactly 1 argument (0 given)

======================================================================
ERROR: Make sure array input is derived to a measurement name, value data source.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_array_input_assignment() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_line_builder.test_df_only_input
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_df_only_input() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_scatter_builder.test_list_input
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_list_input() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_builder.test_empty_builder_labels
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_empty_builder_labels() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_builder.test_default_color
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_default_color() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_builder.test_custom_color
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_custom_color() takes exactly 1 argument (0 given)

======================================================================
ERROR: Check known example for how many rows should exist based on columns.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_cat_to_polor() takes exactly 2 arguments (0 given)

======================================================================
ERROR: Check for type of output and columns in output for wedge text source.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_create_wedge_text() takes exactly 1 argument (0 given)

======================================================================
ERROR: Test creating chart data source from array-like list data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_area_base_values() takes exactly 1 argument (0 given)

======================================================================
ERROR: Test creating chart data source from array-like list data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_list() takes exactly 1 argument (0 given)

======================================================================
ERROR: Test creating chart data source from array-like numpy data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_array() takes exactly 1 argument (0 given)

======================================================================
ERROR: Test creating chart data source from existing dataframe.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_pandas() takes exactly 1 argument (0 given)

======================================================================
ERROR: Test creating chart data source from dict of arrays.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_dict() takes exactly 1 argument (0 given)

======================================================================
ERROR: Test creating chart data source from array of dicts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_records() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_data_source.test_groupby
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_groupby() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_data_source.test_derived_selections
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_derived_selections() takes exactly 1 argument (0 given)

======================================================================
ERROR: List of lists for dimension results in column derivation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_derived_cols_from_lists_kw() takes exactly 1 argument (0 given)

======================================================================
ERROR: List of lists for dimension results in column derivation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_derived_cols_from_lists() takes exactly 1 argument (0 given)

======================================================================
ERROR: Wide dataframe columns assigned to y dimension for the chart.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_custom_derived_cols_from_df() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_stats.test_explicit_bin_count
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_explicit_bin_count() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_stats.test_auto_bin_count
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_auto_bin_count() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_stats.test_bin_labeling
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_bin_labeling() takes exactly 1 argument (0 given)

======================================================================
ERROR: bokeh.command.subcommands.tests.test_html.test_no_script
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_no_script() takes exactly 1 argument (0 given)

======================================================================
ERROR: bokeh.command.subcommands.tests.test_html.test_basic_script
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_basic_script() takes exactly 1 argument (0 given)

======================================================================
ERROR: bokeh.command.subcommands.tests.test_html.test_basic_script_with_output_after
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_basic_script_with_output_after() takes exactly 1 argument (0 given)

======================================================================
ERROR: bokeh.command.subcommands.tests.test_html.test_basic_script_with_output_before
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_basic_script_with_output_before() takes exactly 1 argument (0 given)

======================================================================
ERROR: bokeh.command.subcommands.tests.test_json.test_no_script
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_no_script() takes exactly 1 argument (0 given)

======================================================================
ERROR: bokeh.command.subcommands.tests.test_json.test_basic_script
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_basic_script() takes exactly 1 argument (0 given)

======================================================================
ERROR: bokeh.command.subcommands.tests.test_json.test_basic_script_with_output_after
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_basic_script_with_output_after() takes exactly 1 argument (0 given)

======================================================================
ERROR: bokeh.command.subcommands.tests.test_json.test_basic_script_with_output_before
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_basic_script_with_output_before() takes exactly 1 argument (0 given)

======================================================================
ERROR: bokeh.command.subcommands.tests.test_secret.test_run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_run() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_bootstrap.test_no_subcommand
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_no_subcommand() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_bootstrap.test_version
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_version() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_bootstrap.test_version_short
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_version_short() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_util.test_die
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_die() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_callbacks.test_py_callback
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/bokeh-0.11.0/work/bokeh-0.11.0-python2_7/lib/bokeh/models/tests/test_callbacks.py", line 32, in test_py_callback
    cb = CustomJS.from_py_func(cb)
  File "/var/tmp/portage/dev-python/bokeh-0.11.0/work/bokeh-0.11.0-python2_7/lib/bokeh/models/callbacks.py", line 42, in from_py_func
    raise RuntimeError('Using Python functions for CustomJS '
RuntimeError: Using Python functions for CustomJS is currently not supported on Python 2.x

======================================================================
ERROR: bokeh.server.protocol.tests.test_message.test_create_header
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_create_header() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_client_server.test_client_changes_do_not_boomerang
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_client_changes_do_not_boomerang() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_client_server.test_server_changes_do_not_boomerang
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_server_changes_do_not_boomerang() takes exactly 1 argument (0 given)

======================================================================
ERROR: test_client_server.test_unit_spec_changes_do_not_boomerang
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_unit_spec_changes_do_not_boomerang() takes exactly 1 argument (0 given)

----------------------------------------------------------------------
Ran 701 tests in 13.285s

FAILED (errors=45)
```
Happens with py2 and py3.

Any additional info needed?

**Comment by bryevdv** [comment]
Hi @jlec We use `py.test` in our continuous integration testing. I also know we make use of some pytest extensions and features (e.g for selenium tests and also conf files for setup/teardown). It's not clear to me that the tests would or should be expected to run correctly, except as described here:

http://bokeh.pydata.org/en/latest/docs/dev_guide/testing.html

Can you try to run the tests in the accepted way and see if there is any issue? And if there is,  please include platform information as well (I do know some unit tests currently fail on Windows e.g. because they test a numpy type that does not exist on windows... we are still figuring out to to run CI on platforms other than Linux)

**Comment by jlec** [comment]
Alright, py.test runs better.
