### ISSUE TITLE
 deprecated inspect.getargspec make failing tests in Travis CI with Nightly build (Python 3.6)

### ISSUE THREAD

**Issue by ChristianTremblay** [bokeh/bokeh#3595]
Here's an extract from the Travis CI output on my app : 
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/mock/mock.py", line 1297, in patched
    arg = patching.__enter__()
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/mock/mock.py", line 1353, in __enter__
    self.target = self.getter()
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/mock/mock.py", line 1520, in <lambda>
    getter = lambda: _importer(target)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/mock/mock.py", line 1206, in _importer
    thing = __import__(import_path)
  File "/home/travis/build/ChristianTremblay/BAC0/BAC0/__init__.py", line 3, in <module>
    from . import core
  File "/home/travis/build/ChristianTremblay/BAC0/BAC0/core/__init__.py", line 6, in <module>
    from . import devices
  File "/home/travis/build/ChristianTremblay/BAC0/BAC0/core/devices/__init__.py", line 3, in <module>
    from . import Device
  File "/home/travis/build/ChristianTremblay/BAC0/BAC0/core/devices/Device.py", line 16, in <module>
    from ...tasks.BokehRenderer import BokehPlot
  File "/home/travis/build/ChristianTremblay/BAC0/BAC0/tasks/BokehRenderer.py", line 12, in <module>
    from bokeh.plotting import Figure
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/bokeh/plotting/__init__.py", line 3, in <module>
    from ..document import Document; Document
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/bokeh/document.py", line 20, in <module>
    from .model import Model
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/bokeh/model.py", line 14, in <module>
    from .util.callback_manager import CallbackManager
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/bokeh/util/callback_manager.py", line 7, in <module>
    from inspect import formatargspec, getargspec, isfunction, ismethod
ImportError: cannot import name 'getargspec'
```

**Comment by bryevdv** [comment]
Wow thanks for the heads up. I will admit 3.6 was not really on my radar yet.

**Comment by bryevdv** [comment]
According to this comment in the python.org tracker, `inspect.getargspec` has been restored:

https://bugs.python.org/issue25486#msg258007

So, closing this for now.
