### ISSUE TITLE
Problem in exception for BokehTornado?

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#3666]
I'm getting the following error in a notebook that I'd be happy to share privately, but I _think_ the problem being reported isn't specific to the notebook:

```
ERROR:tornado.application:Exception in callback <functools.partial object at 0x10bcbf418>
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "//anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 615, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "//anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "//anaconda/lib/python2.7/site-packages/tornado/gen.py", line 267, in wrapper
    result = func(*args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/bokeh/server/tornado.py", line 315, in _start_async
    self.exit(1)
AttributeError: 'BokehTornado' object has no attribute 'exit'
```

The error is from bokeh 0.11, but the same line is in the current github master:  https://github.com/bokeh/bokeh/blob/master/bokeh/server/tornado.py#L326 
That line contains a call to self.exit(), but there isn't such a method for this class.  Maybe it was supposed to be sys.exit()?  Of course, how the code ever got to this point may be an error in the notebook code, but this exception handling doesn't seem correct as written.

**Comment by birdsarah** [comment]
not sure @jbednar, I agree with you that there isn't a self.exit() and I can't see it in the parent classes. ping @havocp @bryevdv

**Comment by havocp** [comment]
I think if just remove the try/catch with the self.exit in the catch block, which would reveal the actual exception thrown here. at that point said exception could be fixed (possibly by removing this entire sigterm setup, possibly by silently ignoring a failure to set it up, I'm not sure)

**Comment by bryevdv** [comment]
code has changed since this issue
