### ISSUE TITLE
Bokeh Spectrogram Demo is broken

### ISSUE THREAD

**Issue by ghyde** [bokeh/bokeh#3667]
When I run the spectrogram demo (located in examples/embed/spectrogram/spectrogram.py) and visit `localhost:5000`, I get the following error:

> 127.0.0.1 - - [15/Jan/2016 12:54:51] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/user/anaconda/lib/python2.7/site-packages/flask/app.py", line 1836, in \_\_call\_\_
    return self.wsgi_app(environ, start_response)
  File "/Users/user/anaconda/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/user/anaconda/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/user/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/user/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/user/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/user/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/user/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions\[rule.endpoint\](\*\*req.view_args)
  File "/Users/user/github/bokeh/examples/embed/spectrogram/spectrogram.py", line 38, in root
    freq_slider, gain_slider, spectrum, signal, spec, eq = make_spectrogram()
  File "/Users/user/github/bokeh/examples/embed/spectrogram/spectrogram.py", line 127, in make_spectrogram
    border_fill_color= "#d4e7e4", name='spectrogram', \*\*plot_kw)
  File "/Users/user/anaconda/lib/python2.7/site-packages/bokeh/plotting.py", line 243, in figure
    fig = Figure(\*\*kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/bokeh/plotting.py", line 56, in \_\_init\_\_
    super(Figure, self).\_\_init\_\_(\*arg, \*\*kw)
  File "/Users/user/anaconda/lib/python2.7/site-packages/bokeh/models/plots.py", line 86, in \_\_init\_\_
    super(Plot, self).\_\_init\_\_(\*\*kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/bokeh/plot_object.py", line 90, in \_\_init\_\_
    super(PlotObject, self).\_\_init\_\_(\*\*kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/bokeh/properties.py", line 364, in \_\_init\_\_
    setattr(self, name, value)
  File "/Users/user/anaconda/lib/python2.7/site-packages/bokeh/properties.py", line 378, in \_\_setattr\_\_
    (name, self.\_\_class\_\_.\_\_name\_\_, text, nice_join(matches)))
AttributeError: unexpected attribute 'border_fill_color' to Figure, similar attributes are border_fill

It appears the attribute `border_fill_color` was renamed to `border_fill`.

**Comment by bryevdv** [comment]
> It appears the attribute border_fill_color was renamed to border_fill.

The other way around, actually. I think you must be using an older version of Bokeh?

**Comment by bryevdv** [comment]
Just to double check, confirmed with current `master`. You can check out a branch appropriate to your version, or update to a newer version of Bokeh, to see this example.

**Comment by ghyde** [comment]
For future posterity, I was running 0.10.0-py27_0. It's working now with 0.11.0-py27_1.

If you're using `conda`, execute `conda update bokeh` to update to the latest version.
