### ISSUE TITLE
Using Motor to fetch data from MongoDB

### ISSUE THREAD

**Issue by jdugge** [bokeh/bokeh#3732]
This is related to #3702.

We need to fetch data from a MongoDB according to the current view range of the plot. For this, we use a `x_range.on_change` callback function that issues a call to the MongoDB. This works fine when using the `pymongo` library.

However, since fetching the data can take a while, it's necessary to make the process non-blocking (`pymongo` is blocking). The obvious way to do that for MongoDB access from Bokeh is to use the [Motor library](http://motor.readthedocs.org/en/stable/), since it's non-blocking and also uses the Tornado framework.

I've been able to come up with a simple example with an `update_data` function that fetches the data and populates the plot right after it is created. However, immediately after that, I get a `RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes`, and all future invocations of the `update_data` function fail to update the plot (even though they successfully fetch the data from the database).

How can I get Motor to play nice with Bokeh? Or am I on the wrong track and should be using a different approach for getting data on demand from my MongoDB?

---

Here's a small script that generates a database with some test data on a MongoDB server:

``` python
import numpy as np
import pandas as pd
import pymongo
import datetime

index = pd.date_range('2000-01-01', '2000-12-31', freq='h')
ylist = np.linspace(0, 365, index.size) + np.random.rand(index.size)
data = [{'dt': idx, 'y': y} for idx, y in zip(index, ylist)]

client = pymongo.MongoClient()
db = client['testdb']
coll = db['testcoll']

_ = coll.insert(data)
```

And here's my `motor_example.py` script that can be served using `bokeh serve motor_example.py`:

``` python
import bokeh.plotting
import datetime
import motor
from tornado import gen

client = motor.MotorClient()
db = client['testdb']
coll = db['testcoll']


@gen.coroutine
def update_data(start, end):
    cursor = coll.find({'dt': {'$gte': start, '$lt': end}}, {'_id': 0})
    data = yield cursor.to_list(length=10000)
    x = [dp['dt'] for dp in data]
    y = [dp['y'] for dp in data]
    ds.data = {
        'x': x,
        'y': y
    }


def my_callback_function(param, old, new):
    start = datetime.datetime.utcfromtimestamp(p.x_range.start/1000)
    end = datetime.datetime.utcfromtimestamp(p.x_range.end/1000)
    update_data(start, end)


start = datetime.datetime(2000, 6, 1)
end = datetime.datetime(2000, 7, 31)

p = bokeh.plotting.figure(x_axis_type='datetime', x_range=[start, end], y_range=[0,1000])
l = p.line(x=[], y=[])
ds = l.data_source

print 'Initial data update'
update_data(start, end)

p.x_range.on_change('end', my_callback_function)

bokeh.plotting.curdoc().add_root(p)
```

which generates the following error message:

```
c:\Data\Bokeh>bokeh serve motor_example.py
DEBUG:bokeh.server.tornado:Allowed Host headers: ['localhost:5006']
DEBUG:bokeh.server.tornado:These host origins can connect to the websocket: ['localhost:5006']
DEBUG:bokeh.server.tornado:Patterns are: [('/motor_example/?', <class 'bokeh.server.views.doc_handler.DocHandler'>, {'application_context': <bokeh.ser
ver.application_context.ApplicationContext object at 0x000000000A467A20>, 'bokeh_websocket_path': '/motor_example/ws'}), ('/motor_example/ws', <class
'bokeh.server.views.ws.WSHandler'>, {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x000000000A467A20>, 'bokeh
_websocket_path': '/motor_example/ws'}), ('/motor_example/autoload.js', <class 'bokeh.server.views.autoload_js_handler.AutoloadJsHandler'>, {'applicat
ion_context': <bokeh.server.application_context.ApplicationContext object at 0x000000000A467A20>, 'bokeh_websocket_path': '/motor_example/ws'}), ('/st
atic/(.*)', <class 'bokeh.server.views.static_handler.StaticHandler'>)]
INFO:bokeh.command.subcommands.serve:Starting Bokeh server on port 5006 with applications at paths ['/motor_example']
Initial data update
INFO:tornado.access:200 GET /motor_example (::1) 237.00ms
INFO:tornado.access:304 GET /static/css/bokeh.min.css?v=486d3195473d3e39ad36f2888fefe389 (::1) 137.00ms
INFO:tornado.access:304 GET /static/js/bokeh.min.js?v=b0e2720e424bae5562ceecc6d83c2044 (::1) 1.00ms
INFO:tornado.access:304 GET /static/js/bokeh-widgets.min.js?v=8e88133dddc48883a815d4278dd80f9a (::1) 2.00ms
INFO:tornado.access:304 GET /static/js/bokeh-compiler.min.js?v=34cb81b761c2c28f1955c7bb98dab3a9 (::1) 2.00ms
INFO:tornado.access:304 GET /static/css/bokeh-widgets.min.css?v=0bbd11cf0fab2f648f3918c073bc9c3d (::1) 1.00ms
ERROR:tornado.application:Future exception was never retrieved: Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\tornado\gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "c:\Data\Bokeh\motor_example.py", line 19, in update_data
    'y': y
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\core\properties.py", line 714, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\core\properties.py", line 456, in __set__
    self._real_set(obj, old, value)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\core\properties.py", line 446, in _real_set
    self._trigger(obj, old, value)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\core\properties.py", line 397, in _trigger
    obj.trigger(self.name, old, value)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\model.py", line 106, in trigger
    super(Model, self).trigger(attr, old, new)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\util\callback_manager.py", line 104, in trigger
    self._document._notify_change(self, attr, old, new)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\document.py", line 508, in _notify_change
    self._trigger_on_change(ModelChangedEvent(self, model, attr, old, new, serializable_new))
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\document.py", line 495, in _trigger_on_change
    self._with_self_as_curdoc(invoke_callbacks)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\document.py", line 479, in _with_self_as_curdoc
    return f()
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\document.py", line 494, in invoke_callbacks
    cb(event)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\document.py", line 463, in <lambda>
    self._callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\document.py", line 56, in dispatch
    super(ModelChangedEvent, self).dispatch(receiver)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\document.py", line 44, in dispatch
    receiver._document_patched(self)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\bokeh\server\session.py", line 167, in _document_patched
    raise RuntimeError("_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes")
RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes
INFO:bokeh.server.views.ws:WebSocket connection opened
DEBUG:bokeh.server.views.ws:Receiver created for Protocol(u'1.0')
DEBUG:bokeh.server.views.ws:ServerHandler created for Protocol(u'1.0')
INFO:bokeh.server.views.ws:ServerConnection created
DEBUG:bokeh.server.session:Sending pull-doc-reply from session 'vlwxK06s3YFU97abRL9XhxQsZVKQK3LAh4u3chNcuJrO'
DEBUG:bokeh.server.tornado:[pid 16372] 1 clients connected
``
```

**Comment by jdugge** [comment]
As suggested by @havocp in #3702, I adjusted the code to use a `add_next_tick_callback`, and now fetching the data on range updates works.

However, the calls to `update_db` still pile up while scrolling and fetching is in progress, so after the scrolling is done, you can see old calls being executed. Something still seems to be blocking the thread.


```python
import bokeh.plotting
import datetime
import motor
from tornado import gen

client = motor.MotorClient()
db = client['testdb']
coll = db['testcoll']


@gen.coroutine
def update_data():
    global in_progress
    global ds
    start = datetime.datetime.utcfromtimestamp(p.x_range.start/1000)
    end = datetime.datetime.utcfromtimestamp(p.x_range.end/1000)
    cursor = coll.find({'dt': {'$gte': start, '$lt': end}}, {'_id': 0})
    data = yield cursor.to_list(length=10000)
    x = [dp['dt'] for dp in data]
    y = [dp['y'] for dp in data]
    ds.data = {
        'x': x,
        'y': y
    }
    in_progress = False


def my_callback_function(param, old, new):
    global in_progress
    print in_progress
    if in_progress:
        print "In progress, doing nothing"
    else:
        in_progress = True
        print "Adding callback"
        doc.add_next_tick_callback(update_data)    


start = datetime.datetime(2000, 6, 1)
end = datetime.datetime(2000, 7, 31)

p = bokeh.plotting.figure(x_axis_type='datetime', x_range=[start, end], y_range=[0,1000])
l = p.line(x=[], y=[])
ds = l.data_source

print 'Initial data update'
in_progress = False
update_data()

p.x_range.on_change('end', my_callback_function)

doc = bokeh.plotting.curdoc()
doc.add_root(p)
```

**Comment by havocp** [comment]
a sampling profiler would probably show the blocking call taking up most of the time

**Comment by havocp** [comment]
Another thing to try is to use a timeout rather than next tick, to throttle loads from mongo to some reasonable frequency. That might give you a better chance to keep up with incoming events.

Potentially we could also be throttling on the client side.

It's possible that simply parsing the events is already too slow to keep up - if you have a no-op callback and do zero work, does it still backlog? If so I think there isn't much you can do other than run the server on a faster CPU.

The 'real' solution here in some abstract architectural sense is backpressure - for example Java has an initiative to add this at http://www.reactive-streams.org/
But very few languages or frameworks support this because people often just throttle things until it works and call that good enough. Tornado doesn't have any builtin backpressure support for example as far as I know, it just creates huge buffers (gets more and more backlogged).

We could probably roll our own equivalent on the websocket for events - have the client only send a certain number of events until the server asks for more. But, anyway. Not helpful for you in the short term, just talking about ways Bokeh could improve in this area.

**Comment by bryevdv** [comment]
I think this would be a great demonstration but I have no hope that anyone personally on the core team will be able to develop it any time in the near future. In the mean time there are examples of async updates e.g. the Dask cluster monitor
