### ISSUE TITLE
High level chart Bar UnicodeEncodeError

### ISSUE THREAD

**Issue by danaki** [bokeh/bokeh#3781]
Test case:

```
    df = {
      'field1': {
        0: u'Dreili\u0146i',
        1: u'Zasulauks',
        2: u'Jaunciems',
        3: u'Vec\u0101\u0137i',
        4: u'Zolit\u016bde'
      },
      'field2': {
        0: 1393.4975669099756,
        1: 940.10734463276833,
        2: 616.83713611329665,
        3: 1674.2025627044709,
        4: 1068.1402252322382
        }}

    p = Bar(df, 'field1', values='field2')
```

Produces exception:

```
Traceback (most recent call last):
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/Users/yuri/work/ssguru/web/public/flats.py", line 41, in bar_price_mean_by_district
    ylabel="Mean price")
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/bokeh/charts/builders/bar_builder.py", line 311, in Bar
    chart = create_and_build(BarBuilder, data, **kw)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/bokeh/charts/builder.py", line 67, in create_and_build
    chart.add_builder(builder)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/bokeh/charts/chart.py", line 149, in add_builder
    builder.create(self)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/bokeh/charts/builder.py", line 518, in create
    chart.add_renderers(self, renderers)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/bokeh/charts/chart.py", line 144, in add_renderers
    self.renderers += renderers
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/bokeh/core/property_containers.py", line 18, in wrapper
    result = func(*args, **kwargs)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/bokeh/core/property_containers.py", line 77, in __iadd__
    return super(PropertyValueList, self).__iadd__(y)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/bokeh/charts/builders/bar_builder.py", line 204, in yield_renderers
    x_label=self._get_label(group['label']),
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/bokeh/charts/builder.py", line 487, in _get_label
    return str(raw_label)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
```

Possibly other high level charts affected

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/18)
