### ISSUE TITLE
Server examples not working on the RPI 2

### ISSUE THREAD

**Issue by multimedial** [bokeh/bokeh#3961]
The server examples for bokeh are not running on the raspberry pi, no matter what. It seems as if the requests for updating the data get timed out.

`pi@raspberrypi:~ bokeh serve bokeh_single_plot.py --host 192.168.178.16:80
2016-02-29 16:00:25,431 Starting Bokeh server version 0.12.0dev1
2016-02-29 16:00:25,434 Allowed Host headers: ['192.168.178.16:80']
2016-02-29 16:00:25,435 These host origins can connect to the websocket: ['localhost:5006', '192.168.178.16:80']
2016-02-29 16:00:25,436 Patterns are: [('/bokeh_single_plot/?', <class 'bokeh.server.views.doc_handler.DocHandler'>, {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x72821530>, 'bokeh_websocket_path': '/bokeh_single_plot/ws'}), ('/bokeh_single_plot/ws', <class 'bokeh.server.views.ws.WSHandler'>, {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x72821530>, 'bokeh_websocket_path': '/bokeh_single_plot/ws'}), ('/bokeh_single_plot/autoload.js', <class 'bokeh.server.views.autoload_js_handler.AutoloadJsHandler'>, {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x72821530>, 'bokeh_websocket_path': '/bokeh_single_plot/ws'}), ('/static/(.*)', <class 'bokeh.server.views.static_handler.StaticHandler'>)]
2016-02-29 16:00:25,457 Starting Bokeh server on port 5006 with applications at paths ['/bokeh_single_plot']
2016-02-29 16:00:40,473 [pid 5076] 0 clients connected
2016-02-29 16:00:40,475 [pid 5076]   /bokeh_single_plot has 0 sessions with 0 unused
2016-02-29 16:00:55,471 [pid 5076] 0 clients connected
2016-02-29 16:00:55,473 [pid 5076]   /bokeh_single_plot has 0 sessions with 0 unused
2016-02-29 16:01:10,280 404 GET /Kemper (127.0.0.1) 6.83ms
2016-02-29 16:01:10,458 [pid 5076] 0 clients connected
2016-02-29 16:01:10,459 [pid 5076]   /bokeh_single_plot has 0 sessions with 0 unused
2016-02-29 16:01:19,159 Running state NOT_YET_CONNECTED
2016-02-29 16:01:39,185 Failed to connect to server: HTTPError(599, 'Timeout', None)
2016-02-29 16:01:39,188 transitioning to state DISCONNECTED
2016-02-29 16:01:39,190 Stopping client loop in state DISCONNECTED due to True from connected_or_closed
2016-02-29 16:01:39,196 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x72821050>: Cannot push session document because we failed to connect to the server (to start the server, try the 'bokeh serve' command)
File "session.py", line 269, in push:
raise IOError("Cannot push session document because we failed to connect to the server (to start the server, try the 'bokeh serve' command)") Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bokeh/application/handlers/code_runner.py", line 71, in run
    exec(self._code, module.__dict__)
  File "/home/pi/bokeh_single_plot.py", line 41, in <module>
    session = push_session(curdoc())
  File "/usr/local/lib/python2.7/dist-packages/bokeh/client/session.py", line 63, in push_session
    session.push(document)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/client/session.py", line 269, in push
    raise IOError("Cannot push session document because we failed to connect to the server (to start the server, try the 'bokeh serve' command)")
IOError: Cannot push session document because we failed to connect to the server (to start the server, try the 'bokeh serve' command)

2016-02-29 16:01:39,321 200 GET /bokeh_single_plot (127.0.0.1) 20503.33ms
2016-02-29 16:01:39,328 [pid 5076] 0 clients connected
2016-02-29 16:01:39,330 [pid 5076]   /bokeh_single_plot has 1 sessions with 1 unused
2016-02-29 16:01:39,337 404 GET /ws?bokeh-protocol-version=1.0&bokeh-session-id=f6yb1MzJQCiqbsfDhJ5TpR1UnSR3bh58hZKWckTQMXJS (::1) 2.88ms
2016-02-29 16:01:39,570 WebSocket connection opened
2016-02-29 16:01:39,572 Receiver created for Protocol(u'1.0')
2016-02-29 16:01:39,574 ServerHandler created for Protocol(u'1.0')
2016-02-29 16:01:39,576 ServerConnection created
2016-02-29 16:01:39,599 Sending pull-doc-reply from session 'vOVYbRtBaqd5mv3oHLUAtNy0DzTZOCyAFVlBU518BHRN'
2016-02-29 16:01:40,458 [pid 5076] 1 clients connected
2016-02-29 16:01:40,460 [pid 5076]   /bokeh_single_plot has 1 sessions with 0 unused
2016-02-29 16:01:55,463 [pid 5076] 1 clients connected`

**Comment by bryevdv** [comment]
@multimedial as you can see, that log message is generated by a tiny `try: except:` around a call to the `tornado.webdsocket.websocket_connect`.  

https://github.com/bokeh/bokeh/blob/0f4206dcecc8584aac0d0c1241391476467125c2/bokeh/client/connection.py#L320-L324

Whatever is happening, seems to be happening inside tornado. Unfortunately I'm not sure what we can do about it. We do not have any RasbPi to test with, and even if we did, it's not something we could integrated into our Continuous Testing framework. If someone with experience (and resources) wants to try and figure out if there is something different to do that would make this work on RasbPi, we would definitely welcome a PR.

**Comment by multimedial** [comment]
Hi, thanks for having looked into this. 
I am supposed to write a plotting application which displays realtime data, yet I am screwed because of this bug :-(

**Comment by bryevdv** [comment]
@multimedial do you think you can try to do some more investigation? Perhaps you might be able to ask around on the Tornado community if people have experiences using web sockets and tornado on RasbPi? As I said at least at a glance this appears to be un upstream issue. There might be a workaround but the best people to ask seem to be the Tornado folks.

**Comment by mattpap** [comment]
599 error code indicates network connectivity issue (it's an internal Tornado's code). Did you make sure the `192. ...` address is visible to bokeh server?

**Comment by multimedial** [comment]
I will see what I can do, I like bokeh very much and it would solve me a lot of issues, but I am also under a tight deadline which just got even tighter becuse of this.

I found a workaround, at least to my problem. You provide an example in the docs where the values are being pulled by the browser from the server (the timeout example with the button), and not pushed from the server to the browser (as in the plain vanilla timeout example).

**Comment by multimedial** [comment]
Yes, the address is visible, as I am getting the starting page.

**Comment by mattpap** [comment]
@multimedial, can you try adding `--allow-websocket-origin 192. ...` (keep the host argument as-is)? This should help routing websockets.

**Comment by bryevdv** [comment]
I am going to re-open this so we can collect any information learned. I'd definitely like to be able to offer any guidance to people wanting to use the server on RasbPi, if we can.

**Comment by bryevdv** [comment]
`--allow-websocket-origin` should not be needed (it's really useful for the case where you want to embed an `autoload_server` tag, e.g. and the origin is the main page hosting site (which is different from the host  that page connects to that is running the server). But, I do agree that you should try this. If it solves the issue then there is a bug, I think.

**Comment by mattpap** [comment]
@bryevdv, I was about to ask for the difference with `--host`, because the documentation isn't too helpful in this case. Thought the log says it accepts websockets from `192. ...`, so my suggestion should unhelpful.

**Comment by multimedial** [comment]
Hi guys, 

my fault. It was an issue with the installed software. I reinstalled the Debian Jessie image on the SD card of the raspberry and did a new install of bokeh, and now everything seems to be working fine. 

My apologies.

**Comment by bryevdv** [comment]
No apologies needed, glad it is working for you!

**Comment by multimedial** [comment]
Sorry, but I got to reopen this. This IS indeed an issue, I can reproduce it even on my new install.

The problem lies in the bokeh.client, especially in code like: 
```

session = push_session(curdoc())

def update(step):
        p1.data_source.data["y"] = random.randint(0,10)

curdoc().add_periodic_callback(update, 1000)

session.loop_until_closed()
```

**Comment by multimedial** [comment]
I am confused - this snippet here is taken from timeout.py, which works: 

callbacks = [make_callback(i) for i in range(N)]
```

# open a session to keep our local document in sync with server
session = push_session(curdoc())

for callback in callbacks:
    curdoc().add_timeout_callback(callback, callback.interval)

curdoc().add_timeout_callback(sys.exit, (N+4)*100)

session.show(p) # open the document in a browser

session.loop_until_closed() # run forever
```

yet this one does not (my code): 

```
session = push_session(curdoc())

def update(step):
        p1.data_source.data["y"] = random.randint(0,10)

curdoc().add_timeout_callback(update, 1000)

session.loop_until_closed()
```

This one exhibits the problem that bokeh.client cannot connect to the server. I am confused as to why this is, as they seem to be very similar.

**Comment by multimedial** [comment]
Bryan, this might be related, I see the same 
"DEBUG:bokeh.client.connection:Running state NOT_YET_CONNECTED"

https://github.com/bokeh/bokeh/issues/3476

**Comment by multimedial** [comment]
This might be related: https://github.com/tornadoweb/tornado/issues/1414

**Comment by bryevdv** [comment]
@multimedial statements like 
```
session = push_session(curdoc())
```
are not needed in apps served with `bokeh serve`, they are only needed when you want to update something from a *different* python process. Perhaps this is the problem you are experiencing?

**Comment by multimedial** [comment]
I want do update a served document with new data from the database. According to the documentation, I am supposed to push the new data using push_session()?

Is there any other way for bokeh to push new data to an already served document (=update a document in the browser with new data being collected in the meantime)?

Thank you for your patience. I had to abandon bokeh and develop an alternative (using D3.js + Rikshaw right now), but bokeh would be much, much nicer if it would work.

**Comment by bryevdv** [comment]
I would suggest the easiest path is to have the bokeh app (inside the Bokeh server) pull data directly from the data base, if that is an option. Alternatively if the data is available through some REST API you could potentially use an `AjaxDataSource` and not worry about a Bokeh server at all.

It is definitely possible to have other processes update bokeh sessions "from outside" but it is also definitely more involved. See https://github.com/bokeh/bokeh-demos/tree/master/happiness for a more complete example.

**Comment by bryevdv** [comment]
I also forgot to mention the periodic callback itself can certainly connect to the data base to pull in new data, and that should be simple as well. In any event, in the interest of cleaning up our tracker I'm going to close this for now. For "support" type questions we are sending people to the mailing list. Of course, if there is a bug or feature request please open any new issues needed.
