### ISSUE TITLE
"bokeh server notebook.ipynb" and "bokeh html notebook,ipynb" fails

### ISSUE THREAD

**Issue by leemorgan-mobile** [bokeh/bokeh#4208]
calls base class in code_runner which treats ipynb as .py

**Comment by bryevdv** [comment]
@leemorgan-mobile more information is needed (as was described in the issue template). For instance what version of Bokeh are you running?  The ability to run the `bokeh` command on a Jupyter notebook is a recent addition, it may simply that your version bokeh is not up to date? If not, please provide a notebook that reproduces the problem for us to investigate.

**Comment by bryevdv** [comment]
Marking as `discussion` until more information is received.

**Comment by leemorgan-mobile** [comment]
0.11.1
py 2.7.6

```
$cat nokeh.ipynb 
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "import sys\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import bokeh"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'0.11.1'"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "bokeh.__version__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'2.7.6 (default, Jun 22 2015, 17:58:13) \\n[GCC 4.8.2]'"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "sys.version"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}

```

**Comment by bryevdv** [comment]
The code is supposed to run through `code_runner` the problem appears to be some encoding handling problem specific to Python 2:
```
(py27bk0111)bryan@0199-bryanv  /tmp $ bokeh serve foo.ipynb 
Error loading /private/tmp/foo.ipynb:

Invalid syntax in "foo.ipynb" on line 0:
None
Traceback (most recent call last):
  File "/Users/bryan/anaconda/envs/py27bk0111/lib/python2.7/site-packages/bokeh/application/handlers/code_runner.py", line 23, in __init__
    nodes = ast.parse(source, path)
  File "/Users/bryan/anaconda/envs/py27bk0111/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "/private/tmp/foo.ipynb", line 0
SyntaxError: encoding declaration in Unicode string
```

**Comment by bryevdv** [comment]
For future reference, it is also always useful and appropriate to include tracebacks like the one above as well. In general, please err on the side of providing too much information.

**Comment by bryevdv** [comment]
Running notebooks via `bokeh serve` is not a commonly used feature, and python 2 will eventually be dropped at some point, so spending time on this does not make sense.
