### ISSUE TITLE
Unable to update a line plot in realtime

### ISSUE THREAD

**Issue by VeenitShah** [bokeh/bokeh#4316]
Hi All,

I'm trying to update a line plot based on real time values that I get from a stream. Currently, I've not hooked up my code to the stream. I'm mimicking the behavior by using `shuffle` from `random`. Please find the code. It's mostly from the docs at but I've made a few changes - 

```
from random import shuffle
from bokeh.client import push_session
from bokeh.plotting import figure, curdoc

x = [1,2,3]
y = [10,20,30]
p = figure()
r2 = p.line(x, y, color="navy", line_width=4)

# open a session to keep our local document in sync with server
session = push_session(curdoc())

def update():
    global y
    r2.data_source.data["y"] = shuffle(y)

curdoc().add_periodic_callback(update, 50)

session.show() # open the document in a browser

session.loop_until_closed() # run forever
```

I get the below error in the bokeh server logs - 

```
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/bokeh/server/protocol/server_handler.py", line 38, in handle
    work = yield handler(message, connection)
  File "//anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "//anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "//anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "//anaconda/lib/python2.7/site-packages/bokeh/server/session.py", line 42, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "//anaconda/lib/python2.7/site-packages/bokeh/server/session.py", line 182, in _handle_pull
    return connection.protocol.create('PULL-DOC-REPLY', message.header['msgid'], self.document)
  File "//anaconda/lib/python2.7/site-packages/bokeh/server/protocol/__init__.py", line 46, in create
    return self._messages[msgtype].create(*args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/bokeh/server/protocol/messages/pull_doc_reply.py", line 32, in create
    content = { 'doc' : document.to_json() }
  File "//anaconda/lib/python2.7/site-packages/bokeh/document.py", line 717, in to_json
    doc_json = self.to_json_string()
  File "//anaconda/lib/python2.7/site-packages/bokeh/document.py", line 705, in to_json_string
    'references' : self._references_json(root_references)
  File "//anaconda/lib/python2.7/site-packages/bokeh/document.py", line 516, in _references_json
    ref['attributes'] = r._to_json_like(include_defaults=False)
  File "//anaconda/lib/python2.7/site-packages/bokeh/models/sources.py", line 175, in _to_json_like
    attrs['data'] = transform_column_source_data(attrs['data'])
  File "//anaconda/lib/python2.7/site-packages/bokeh/util/serialization.py", line 129, in transform_column_source_data
    data_copy[key] = traverse_data(data[key])
  File "//anaconda/lib/python2.7/site-packages/bokeh/util/serialization.py", line 100, in traverse_data
    if is_numpy and not any(isinstance(el, (list, tuple)) for el in datum):
TypeError: 'NoneType' object is not iterable
```

**Comment by birdsarah** [comment]
@VeenitShah, I've answered this question on the mailing list, which is the appropriate place for this kind of question.

**Comment by VeenitShah** [comment]
And I thought it had something to do with Bokeh! Damn!
Thank you @birdsarah 👍

**Comment by bryevdv** [comment]
@VeenitShah in order to keep our GH tracker manageable we attempt to reserve it for feature requests and bug reports only, and leave general support to the mailing list. Thanks.
