### ISSUE TITLE
Test failures and error on py 3.4 with bokeh 0.11.1

### ISSUE THREAD

**Issue by bsipocz** [bokeh/bokeh#4450]
I had some problem with an old notebook of mine when running it on py3 (still works with py2). However running the tests also shows various errors and failures. I wonder whether this is something trivially wrong in my setup?

Doing the same exercise on py2.7 passes the tests (though the numbers don't add up the number of items collected) except it also returns the same InternalError. 

```
bsipocz@tegla2:~$ python3 -c 'import bokeh; bokeh.test();'
============================= test session starts ==============================
platform darwin -- Python 3.4.4, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /sw/lib/python3.4/site-packages/bokeh, inifile: 
plugins: cov-2.2.0, html-1.8.0, selenium-1.2.1, variables-1.4, xdist-1.14
collected 652 items / 6 errors 

application/handlers/tests/test_code.py ....
application/handlers/tests/test_directory.py ....
application/handlers/tests/test_function.py ..
application/handlers/tests/test_notebook.py .
application/handlers/tests/test_script.py .
application/handlers/tests/test_server_lifecycle.py ........
application/tests/test_application.py ...
charts/builders/tests/test_bar_builder.py ...
charts/builders/tests/test_boxplot_builder.py .
charts/builders/tests/test_histogram_builder.py .
charts/builders/tests/test_line_builder.py ...
charts/builders/tests/test_scatter_builder.py .
charts/tests/test_attributes.py ......
charts/tests/test_builder.py ...
charts/tests/test_chart_utils.py ........
charts/tests/test_comp_glyphs.py .......
charts/tests/test_data_source.py ..........
charts/tests/test_stats.py ...
command/subcommands/tests/test_html.py ........
command/subcommands/tests/test_info.py ......
command/subcommands/tests/test_json.py ........
command/subcommands/tests/test_sampledata.py .....
command/subcommands/tests/test_secret.py .....
command/subcommands/tests/test_serve.py .....
command/subcommands/tests/test_subcommands_package.py ...
command/tests/test_bootstrap.py ...
command/tests/test_command_package.py .
command/tests/test_util.py ..
core/tests/test_json_encoder.py .............
core/tests/test_properties.py ...................................................................
core/tests/test_query.py .........
models/tests/test_annotations.py .........
models/tests/test_callbacks.py .F
models/tests/test_glyphs.py ..................................................................................................
models/tests/test_ranges.py ...............
models/tests/test_renderers.py ..
models/tests/test_sources.py ............
plotting/tests/test_figure.py ..............
server/protocol/messages/tests/test_patch_doc.py ...
server/protocol/messages/tests/test_pull_doc.py ...
server/protocol/messages/tests/test_push_doc.py ..
server/protocol/tests/test_message.py .
server/protocol/tests/test_receiver.py ..
server/protocol/tests/test_versions.py ..
server/tests/test_server.py ....................
server/tests/test_tornado.py .......
tests/test_bokeh_init.py ...
tests/test_client_server.py .FFFFFFFFFFFFFFFFFFFFFFFFF
tests/test_colors.py ....................
tests/test_document.py .........................................
tests/test_driving.py ......
tests/test_layouts.py ......
tests/test_main_module.py F
tests/test_objects.py ................................................
tests/test_resources.py .............FF....
tests/test_server.py FF
tests/test_themes.py ..F...F.......
tests/test_widgets.py ......
util/tests/test_callback_manager.py ....................
util/tests/test_dependencies.py .
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/main.py", line 94, in wrap_session
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/main.py", line 125, in _main
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/main.py", line 150, in pytest_runtestloop
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 253, in _wrapped_call
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 278, in get_result
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/runner.py", line 66, in pytest_runtest_protocol
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/runner.py", line 76, in runtestprotocol
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/runner.py", line 122, in call_and_report
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/pytest_selenium/pytest_selenium.py", line 137, in pytest_runtest_makereport
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 278, in get_result
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/skipping.py", line 219, in pytest_runtest_makereport
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 278, in get_result
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/runner.py", line 229, in pytest_runtest_makereport
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/python.py", line 752, in repr_failure
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/python.py", line 745, in _repr_failure_py
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/main.py", line 408, in _repr_failure_py
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/_code/code.py", line 418, in getrepr
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/_code/code.py", line 598, in repr_excinfo
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/_code/code.py", line 590, in repr_traceback
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/_code/code.py", line 557, in repr_traceback_entry
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/_code/code.py", line 171, in path
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/_pytest/_code/code.py", line 38, in path
INTERNALERROR>   File "/sw/lib/python3.4/site-packages/py/_path/local.py", line 155, in __init__
INTERNALERROR>   File "/sw/lib/python3.4/posixpath.py", line 361, in abspath
INTERNALERROR> OSError: [Errno 24] Too many open files

====== 33 failed, 576 passed, 1 pytest-warnings, 6 error in 8.89 seconds =======

bsipocz@tegla2:~$ python3 -c 'import bokeh; print(bokeh.__version__);'
0.11.1
```

**Comment by birdsarah** [comment]
This is a wierd quirk that I'm not sure we've documented on the testing page. Set `ulimit -n 1024` and the tests should pass. A short PR to the testing docs under the developer guide would be much appreciated.

**Comment by birdsarah** [comment]
http://bokeh.pydata.org/en/dev/docs/dev_guide/testing.html

**Comment by bsipocz** [comment]
Thanks. Failures are now down to 2:

```
bsipocz@tegla2:~$ python3 -c 'import bokeh; bokeh.test();'
================================================================================ test session starts ================================================================================
platform darwin -- Python 3.4.4, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /sw/lib/python3.4/site-packages/bokeh, inifile: 
plugins: cov-2.2.0, html-1.8.0, selenium-1.2.1, variables-1.4, xdist-1.14
collected 736 items 

application/handlers/tests/test_code.py ....
application/handlers/tests/test_directory.py ....
application/handlers/tests/test_function.py ..
application/handlers/tests/test_notebook.py .
application/handlers/tests/test_script.py .
application/handlers/tests/test_server_lifecycle.py ........
application/tests/test_application.py ...
charts/builders/tests/test_bar_builder.py ...
charts/builders/tests/test_boxplot_builder.py .
charts/builders/tests/test_histogram_builder.py .
charts/builders/tests/test_line_builder.py ...
charts/builders/tests/test_scatter_builder.py .
charts/tests/test_attributes.py ......
charts/tests/test_builder.py ...
charts/tests/test_chart.py ..........
charts/tests/test_chart_utils.py ........
charts/tests/test_comp_glyphs.py .......
charts/tests/test_data_source.py ..........
charts/tests/test_stats.py ...
command/subcommands/tests/test_html.py ........
command/subcommands/tests/test_info.py ......
command/subcommands/tests/test_json.py ........
command/subcommands/tests/test_sampledata.py .....
command/subcommands/tests/test_secret.py .....
command/subcommands/tests/test_serve.py .....
command/subcommands/tests/test_subcommands_package.py ...
command/tests/test_bootstrap.py ...
command/tests/test_command_package.py .
command/tests/test_subcommand.py ......
command/tests/test_util.py ..
core/tests/test_json_encoder.py .............
core/tests/test_properties.py ...................................................................
core/tests/test_query.py .........
core/tests/test_state.py .......
models/tests/test_annotations.py .........
models/tests/test_callbacks.py .F
models/tests/test_glyphs.py ..................................................................................................
models/tests/test_plots.py .......
models/tests/test_ranges.py ...............
models/tests/test_renderers.py ..
models/tests/test_sources.py ............
plotting/tests/test_figure.py ..............
server/protocol/messages/tests/test_patch_doc.py ...
server/protocol/messages/tests/test_pull_doc.py ...
server/protocol/messages/tests/test_push_doc.py ..
server/protocol/tests/test_message.py .
server/protocol/tests/test_receiver.py ..
server/protocol/tests/test_versions.py ..
server/tests/test_server.py ....................
server/tests/test_tornado.py .......
tests/test_bokeh_init.py ...
tests/test_client_server.py ..........................
tests/test_colors.py ....................
tests/test_document.py .........................................
tests/test_driving.py ......
tests/test_embed.py ....................
tests/test_io.py ..................................
tests/test_layouts.py ......
tests/test_main_module.py F
tests/test_objects.py ................................................
tests/test_resources.py ...................
tests/test_server.py ..
tests/test_themes.py ..............
tests/test_widgets.py ......
util/tests/test_callback_manager.py ....................
util/tests/test_dependencies.py ....
util/tests/test_serialization.py .....
util/tests/test_session_id.py ..........
util/tests/test_string.py .
util/tests/test_testing.py .
util/tests/test_tornado.py .......................

===================================================================================== FAILURES ======================================================================================
_________________________________________________________________________________ test_py_callback __________________________________________________________________________________

    @mark.skipif(sys.version_info < (3, ), reason='requires Python 3')
    def test_py_callback():
    
        slider = Slider()
        foo = None  # fool pyflakes
    
        def cb(x=slider):
            foo()
>       cb = CustomJS.from_py_func(cb)

models/tests/test_callbacks.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'bokeh.models.callbacks.CustomJS'>, func = <function test_py_callback.<locals>.cb at 0x10fd63730>

    @classmethod
    def from_py_func(cls, func):
        """ Create a CustomJS instance from a Python function. The
            function is translated to Python using PyScript.
            """
        if not isinstance(func, FunctionType):
            raise ValueError('CustomJS.from_py_func needs function object.')
        try:
            from flexx.pyscript import py2js
        except ImportError:
            if sys.version_info < (3, ):
                raise RuntimeError('Using Python functions for CustomJS '
                                    'is currently not supported on Python 2.x')
            else:
>               raise RuntimeError('To use Python functions for CustomJS, you need Flexx '
                                   '("conda install -c bokeh flexx" or "pip install flexx")')
E               RuntimeError: To use Python functions for CustomJS, you need Flexx ("conda install -c bokeh flexx" or "pip install flexx")

models/callbacks.py:45: RuntimeError
_________________________________________________________________________________ test_main_module __________________________________________________________________________________

    def test_main_module():
        """ Test the __main__.py that allow doing "python -m bokeh"
        """
        cmd = [sys.executable, '-m', 'bokeh', '--version']
>       v = subprocess.check_output(cmd, stderr=subprocess.STDOUT).decode().strip()

tests/test_main_module.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

timeout = None, popenargs = (['/sw/bin/python3', '-m', 'bokeh', '--version'],), kwargs = {'stderr': -2}, inputdata = None, process = <subprocess.Popen object at 0x10da80da0>
output = b'Fatal Python error: Py_Initialize: can\'t initialize sys standard streams\nTraceback (most recent call last):\n  Fil... in <module>\n  File "/sw/lib/python3.4/tokenize.py", line 27, in <module>\nImportError: cannot import name \'open\'\n'
unused_err = None, retcode = -6

    def check_output(*popenargs, timeout=None, **kwargs):
        r"""Run command with arguments and return its output.
    
        If the exit code was non-zero it raises a CalledProcessError.  The
        CalledProcessError object will have the return code in the returncode
        attribute and output in the output attribute.
    
        The arguments are the same as for the Popen constructor.  Example:
    
        >>> check_output(["ls", "-l", "/dev/null"])
        b'crw-rw-rw- 1 root root 1, 3 Oct 18  2007 /dev/null\n'
    
        The stdout argument is not allowed as it is used internally.
        To capture standard error in the result, use stderr=STDOUT.
    
        >>> check_output(["/bin/sh", "-c",
        ...               "ls -l non_existent_file ; exit 0"],
        ...              stderr=STDOUT)
        b'ls: non_existent_file: No such file or directory\n'
    
        There is an additional optional argument, "input", allowing you to
        pass a string to the subprocess's stdin.  If you use this argument
        you may not also use the Popen constructor's "stdin" argument, as
        it too will be used internally.  Example:
    
        >>> check_output(["sed", "-e", "s/foo/bar/"],
        ...              input=b"when in the course of fooman events\n")
        b'when in the course of barman events\n'
    
        If universal_newlines=True is passed, the return value will be a
        string rather than bytes.
        """
        if 'stdout' in kwargs:
            raise ValueError('stdout argument not allowed, it will be overridden.')
        if 'input' in kwargs:
            if 'stdin' in kwargs:
                raise ValueError('stdin and input arguments may not both be used.')
            inputdata = kwargs['input']
            del kwargs['input']
            kwargs['stdin'] = PIPE
        else:
            inputdata = None
        with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
            try:
                output, unused_err = process.communicate(inputdata, timeout=timeout)
            except TimeoutExpired:
                process.kill()
                output, unused_err = process.communicate()
                raise TimeoutExpired(process.args, timeout, output=output)
            except:
                process.kill()
                process.wait()
                raise
            retcode = process.poll()
            if retcode:
>               raise CalledProcessError(retcode, process.args, output=output)
E               subprocess.CalledProcessError: Command '['/sw/bin/python3', '-m', 'bokeh', '--version']' returned non-zero exit status -6

../../subprocess.py:620: CalledProcessError
============================================================= 2 failed, 734 passed, 1 pytest-warnings in 11.49 seconds ==============================================================
```

**Comment by birdsarah** [comment]
The first one you just need to follow the error message and install flexx.

The second one, I'm not sure what's going on. Not sure if this guide I've been working on would be helpful to you: https://bokeh-cookbook.github.io/blog/2016/06/05/setting-up-your-dev-environment/

It could be that `bokeh.test()` got broken at some point - @bryevdv - is it time to move to having just one way of running the tests. We don't exersize `bokeh.test()` so it wouldn't surprise me if it got broken.

**Comment by bsipocz** [comment]
@birdsarah - Yes, I've notice the first one after I've already sent the comment. However it's a bit weird this doesn't come up with py2. (flexx doesn't seemed to be installed there either, but I once had the dev environment set up for py2 (I can double check the details tomorrow)).

Anyway what is the preferred way of running the tests? As I said I started this digging down due to some errors with my code, so if there are any other sort of diagnosis I'm happy to run it.

**Comment by birdsarah** [comment]
Flexx isn't available for py2 I think.

**Comment by bryevdv** [comment]
I don't think that's right, there was a big deal that @almarklein made "python" CustomJS callbacks work for python 2

**Comment by bsipocz** [comment]
It seems also on pypi that flexx is supported on py2.

**Comment by almarklein** [comment]
Yes, Flexx works on Python 2.7 (and is tested for it in CI).

**Comment by bryevdv** [comment]
I think `bokeh.test()` is going away, so closing this.
