### ISSUE TITLE
Unable to update ColumnDataSource with nan values

### ISSUE THREAD

**Issue by phumke** [bokeh/bokeh#4472]
I'm calculating a running average, which includes generation of nan's for the first x number of elements.  The first time I load this data into the ColumnDataSource it correctly displays the data along with the running average.  However trying to update the ColumnDataSource with new data causes a JSON serialization error to be thrown.

Workaround would be to replace nan's with a valid float value - but I'd prefer to let the graph hide the nan portions like it does originally.

Am I doing something wrong or is there a better way to handle nan data?

Here's code to reproduce the issue:

```
import pandas
import numpy as np
from bokeh.plotting import Figure
from bokeh.models import ColumnDataSource, HBox, VBox, VBoxForm
from bokeh.models.widgets import Button
from bokeh.io import curdoc

def update():
    df = get_data()
    calc_rolling_mean(df)
    update_chart_data(df)

def get_data():
    dates = pandas.date_range(start = '2016-01-01', end = '2016-01-10')
    values = np.random.randn(10)
    return pandas.DataFrame(data = {'test_date': dates, 'test_value': values})

def calc_rolling_mean(df):
    df['test_value_mean'] = pandas.rolling_mean(df['test_value'], 5)

def update_chart_data(df):
    global source

    #print('------------>')
    #print(source.data)
    #print(df)

    dfd = df.to_dict('list')
    source.data = dfd

    #print('<------------')

source = ColumnDataSource()

plot = Figure(plot_height=600, plot_width=1000, title="Test", x_axis_type="datetime")
plot.circle(x="test_date", y="test_value", source=source, color="blue")
plot.line(x='test_date', y='test_value_mean', source=source, color="red")

change_it = Button(label="click to add more nans", type="success")
change_it.on_click(update)

curdoc().add_root(HBox(VBoxForm(change_it), plot))

#print('Restarted')
update()
```

Here's the long stack trace:

```
Traceback (most recent call last):
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\server\protocol\server_handler.py", line 38, in handle
    work = yield handler(message, connection)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\server\session.py", line 42, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\server\session.py", line 212, in _handle_patch
    message.apply_to_document(self.document)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\server\protocol\messages\patch_doc.py", line 80, in apply_to_document
    doc.apply_json_patch(self.content)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\document.py", line 841, in apply_json_patch
    patched_obj.set_from_json(attr, value, models=references)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\core\properties.py", line 733, in set_from_json
    prop.set_from_json(self, json, models)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\core\properties.py", line 371, in set_from_json
    models)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\core\properties.py", line 323, in set_from_json
    return self.__set__(obj, json)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\core\properties.py", line 456, in __set__
    self._real_set(obj, old, value)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\core\properties.py", line 446, in _real_set
    self._trigger(obj, old, value)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\core\properties.py", line 397, in _trigger
    obj.trigger(self.name, old, value)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\model.py", line 106, in trigger
    super(Model, self).trigger(attr, old, new)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\util\callback_manager.py", line 105, in trigger
    self._document._with_self_as_curdoc(invoke)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\document.py", line 479, in _with_self_as_curdoc
    return f()
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\util\callback_manager.py", line 102, in invoke
    callback(attr, old, new)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\models\widgets\buttons.py", line 56, in <lambda>
    self.on_change('clicks', lambda attr, old, new: handler())
  File "C:\Users\phumke\Documents\lmcia-dat\trunk\projects\_Sandbox\Python\web_apps\apd_dw_to_bokeh\apd\main_for_debug_report_2.py", line 14, in update
    update_chart_data(df)
  File "C:\Users\phumke\Documents\lmcia-dat\trunk\projects\_Sandbox\Python\web_apps\apd_dw_to_bokeh\apd\main_for_debug_report_2.py", line 41, in update_chart_data
    source.data = dfd
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\core\properties.py", line 714, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\core\properties.py", line 456, in __set__
    self._real_set(obj, old, value)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\core\properties.py", line 446, in _real_set
    self._trigger(obj, old, value)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\core\properties.py", line 397, in _trigger
    obj.trigger(self.name, old, value)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\model.py", line 106, in trigger
    super(Model, self).trigger(attr, old, new)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\util\callback_manager.py", line 104, in trigger
    self._document._notify_change(self, attr, old, new)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\document.py", line 508, in _notify_change
    self._trigger_on_change(ModelChangedEvent(self, model, attr, old, new, serializable_new))
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\document.py", line 495, in _trigger_on_change
    self._with_self_as_curdoc(invoke_callbacks)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\document.py", line 479, in _with_self_as_curdoc
    return f()
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\document.py", line 494, in invoke_callbacks
    cb(event)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\document.py", line 463, in <lambda>
    self._callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\document.py", line 56, in dispatch
    super(ModelChangedEvent, self).dispatch(receiver)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\document.py", line 44, in dispatch
    receiver._document_patched(self)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\server\session.py", line 177, in _document_patched
    self._pending_writes.append(connection.send_patch_document(event))
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\server\connection.py", line 42, in send_patch_document
    msg = self.protocol.create('PATCH-DOC', [event])
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\server\protocol\__init__.py", line 46, in create
    return self._messages[msgtype].create(*args, **kwargs)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\server\protocol\messages\patch_doc.py", line 35, in create
    patch_json = document.create_json_patch_string(events)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\document.py", line 806, in create_json_patch_string
    return serialize_json(json)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\site-packages\bokeh\core\json_encoder.py", line 86, in serialize_json
    return json.dumps(obj, cls=encoder, allow_nan=False, **kwargs)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\phumke\AppData\Local\Continuum\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
```

I'm using Anaconda 3, and Bokeh 0.11.0.

**Comment by HuntJSparra** [comment]
Your code worked fine for me, but if I understand you correctly I had the same issue a few days ago.

What is going on is that under the hood Bokeh (usually) converts numpy nan values to the string 'NaN' because JSON cannot actually accept NaN values. Unfortunately this replacement only occurs when the code is initially launched and converted to JS. Meaning that when your update loop runs after that, the values will not be converted. You should see this if you print the df's values in the initial load (reading 'NaN' for the nan values) and then print again after clicking the button (reading numpy.nan values).

I was able to work around the issue using the bellow to convert the numpy nans to strings before setting the df's data value:
```
def replace_nans (data):
    for key in data:
        data[key] = ['NaN' if pd.isnull(value) else value for value in data[key]]
    return data
```

Returns the data dictionary with all numpy nans converted to valid string 'NaN's

**Comment by phumke** [comment]
Oh bummer the code doesn't reproduce the issue for you!  Maybe I'll also take a stab at updating to one of the dev releases and seeing if I still see the same behavior.

Thank you for the workaround.  Let me give that a try and see if that will also resolve the issue.

From the perspective of the bokeh serialization code, is the one time serialization of NaN's the desired behavior?  If not, I could dig a little bit into the code and look into adding support for NaN's in later update loops.

**Comment by crashMOGWAI** [comment]
I ran into the same issue as well, and just used a df.fillna() to fill nulls before updating. Believe you'll always hit this error if you are trying to push an update with np.NaN values directly to the source. This is still an issue as of 0.12.3 release.

**Comment by bryevdv** [comment]
This was presumably fixed when the base64 encoding work happened. The original code (slightly updated for layout changes):
```
import pandas
import numpy as np
from bokeh.plotting import Figure
from bokeh.models import ColumnDataSource, HBox, VBox, WidgetBox
from bokeh.models.widgets import Button
from bokeh.io import curdoc

def update():
    df = get_data()
    calc_rolling_mean(df)
    update_chart_data(df)

def get_data():
    dates = pandas.date_range(start = '2016-01-01', end = '2016-01-10')
    values = np.random.randn(10)
    return pandas.DataFrame(data = {'test_date': dates, 'test_value': values})

def calc_rolling_mean(df):
    df['test_value_mean'] = pandas.rolling_mean(df['test_value'], 5)

def update_chart_data(df):
    global source

    #print('------------>')
    #print(source.data)
    #print(df)

    dfd = df.to_dict('list')
    source.data = dfd

    #print('<------------')

source = ColumnDataSource()

plot = Figure(plot_height=600, plot_width=1000, title="Test", x_axis_type="datetime")
plot.circle(x="test_date", y="test_value", source=source, color="blue")
plot.line(x='test_date', y='test_value_mean', source=source, color="red")

change_it = Button(label="click to add more nans", button_type="success")
change_it.on_click(update)

curdoc().add_root(HBox(WidgetBox(change_it), plot))

#print('Restarted')
update()
```
no longer raises any errors (and appears to work as expected AFAIC)
