### ISSUE TITLE
Problems running examples/plotting/file/graphs.py on python34

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4536]
I had my py34 examples run fail due to graphs.py, but py27 passed. When I ran the example locally, I consistently got the following error: 

``` console
(bokeh_34)➜  file git:(birdsarah/4384_new_layout_functions) ✗ python graphs.py
Traceback (most recent call last):
  File "graphs.py", line 43, in <module>
    colorings = [ [ color_map[zeta] for zeta in solution ] for solution in solutions ]
  File "graphs.py", line 43, in <listcomp>
    colorings = [ [ color_map[zeta] for zeta in solution ] for solution in solutions ]
  File "graphs.py", line 43, in <listcomp>
    colorings = [ [ color_map[zeta] for zeta in solution ] for solution in solutions ]
KeyError: 1/4 - sqrt(3)*I/4 + sqrt(6 + 6*sqrt(3)*I)/4
```

The following diff, allowed it to run, and the output looked correct:

``` diff
diff --git a/examples/plotting/file/graphs.py b/examples/plotting/file/graphs.py
index 6003ed6..690a08a 100644
--- a/examples/plotting/file/graphs.py
+++ b/examples/plotting/file/graphs.py
@@ -40,7 +40,7 @@ colors = symbols('red,green,blue')
 roots_of_unity = roots(Dummy()**3 - 1, multiple=True)
 color_map = dict(zip(roots_of_unity, colors))
 solutions = solve(Fx, *Vx)
-colorings = [ [ color_map[zeta] for zeta in solution ] for solution in solutions ]
+colorings = [ [ color_map.get(zeta) for zeta in solution ] for solution in solutions ]

 n, ncols = len(colorings), 2
 gs = GridSpec((n + 1)//ncols, 1 + ncols)
```

I'm not sure what's going on, maybe I've got something screwy in my environment, not sure, but thought I'd mention it. ping @mattpap.

**Comment by mattpap** [comment]
@birdsarah, I overlooked this issue. Is this still reproducible?

**Comment by birdsarah** [comment]
Yes, it is reproduce-able - I just checked again for me.

However, I probably should have closed this issue as the above diff was made (I think by me) on master - https://github.com/bokeh/bokeh/pull/4605/files.

**Comment by bryevdv** [comment]
@birdsarah can you report your version of sympy? For me updating to `1.0` fixed this issue.
