### ISSUE TITLE
JS tests reporting as failed even when they all passed

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4539]
I've been seeing this a fair amount over the last few days. The js test is failing even though all the js tests passed. Here's what that output looks like:

``` console
  Jitter transform module

    Jitter with uniform

      ✓ should average the fixed values (57ms)

    Jitter with normal

      ✓ should average the fixed values (48ms)

  Paragraph.View render

    ✓ should set the margin to 0

  Tabs.Model

    ✓ should have children matching tabs.child after initialization

    ✓ should return children from get_layoutable_children

    ✓ get_constraints should return constraints from children

    ✓ get_edit_variables should return edit_variables from children

    ✓ get_constraints should return constraints from children

  Widget.Model

    ✓ should should return 8 constraints

  621 passing (10s)

  8 pending

INFO:tests.plugins.file_server:Shutting down the webserver

F

=================================== FAILURES ===================================

___________________________ TestBokehJS.test_bokehjs ___________________________

self = <tests.test_bokehjs.TestBokehJS testMethod=test_bokehjs>

    def test_bokehjs(self):

        os.chdir('bokehjs')

        proc = subprocess.Popen([join('node_modules', '.bin', 'gulp'), "test"],

                                stdout=subprocess.PIPE)

        result = proc.wait()

        msg = proc.stdout.read().decode('utf-8', errors='ignore')

        print(msg)

        if result != 0:

>           assert False

E           AssertionError: assert False

../tests/test_bokehjs.py:21: AssertionError

====================== 970 tests deselected by "-m 'js'" =======================

================== 1 failed, 970 deselected in 30.65 seconds ===================

The command "if [[ -z "$TRAVIS_TAG" && "$GROUP" == unit ]]; then py.test -s -m js; fi" exited with 1.
```

Something is causing the python test that runs the bokehjs to think the test failed. Here's the full log for that run: https://travis-ci.org/bokeh/bokeh/jobs/138147284#L2311

**Comment by birdsarah** [comment]
Some other runs that had the same problem, just to get a flavor of frequency:
* https://travis-ci.org/bokeh/bokeh/jobs/138157537

**Comment by bryevdv** [comment]
So in my observation, every time this has happened there has been an *error* (not a failure) in the JS tests, way up near the top

<img width="1013" alt="screen shot 2016-06-18 at 11 32 28 am" src="https://cloud.githubusercontent.com/assets/1078448/16172179/83b16672-3548-11e6-8455-c5916ad43f8c.png">

It goes away on a re-run so maybe a race or some phantomJS specific thing? It seems that gulp should be reporting errors, in any case.

**Comment by birdsarah** [comment]
more  fail capture

<img width="1032" alt="screen shot 2016-06-19 at 4 05 25 am" src="https://cloud.githubusercontent.com/assets/1796208/16176948/1601426a-35d3-11e6-9dcb-ddb5da54651a.png">

**Comment by birdsarah** [comment]
some from running locally

```console
------------------------------------------------------------------------------------------------------ Captured stderr call ------------------------------------------------------------------------------------------------------
Bokeh: Bokeh does not support Polygons with holes in, only exterior ring used.
Bokeh: MultiPoint not supported in Bokeh
Bokeh: Bokeh does not support Polygons with holes in, only exterior ring used.
GMapPlot.title: python is missing some properties found in CoffeeScript
    GMapPlot.title.text_align: coffee defaults to "left" but python has no such property
    GMapPlot.title.text_baseline: coffee defaults to "bottom" but python has no such property
Bokeh: LogTickFormatter not configured with a ticker, using default base of 10 (labels will be incorrect if ticker base is not 10)
Python/Coffee matching defaults problems: 0
Bokeh: unrecognized side: 'null'



==========


      ✓ get_width_height should return a constrained height if plot is portrait oriented
    Plot.Model
[02:53:36] 'test' errored after 11 s
[02:53:36] Error in plugin 'gulp-mocha'
Message:
    unknown edit variable
Details:
    domain: [object Object]
    domainThrown: true
Stack:
Error: unknown edit variable
  at Solver.suggestValue (/Users/caged/Dev/bokeh/bokeh/bokehjs/src/vendor/kiwi/kiwi.js:1549:23)
  at Solver.suggest_value (/Users/caged/Dev/bokeh/bokeh/bokehjs/src/coffee/core/layout/solver.coffee:52:13)
  at PlotView.LayoutDOMView.render (/Users/caged/Dev/bokeh/bokeh/bokehjs/src/coffee/models/layouts/layout_dom.coffee:72:9)
  at PlotView.render (/Users/caged/Dev/bokeh/bokeh/bokehjs/src/coffee/models/plots/plot.coffee:27:5)
  at PlotView.<anonymous> (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/backbone/backbone.js:328:18)
  at PlotView.<anonymous> (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/underscore/underscore.js:890:21)
  at triggerEvents (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/backbone/backbone.js:368:57)
  at triggerApi (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/backbone/backbone.js:356:19)
  at eventsApi (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/backbone/backbone.js:155:16)
  at Solver.Events.trigger (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/backbone/backbone.js:346:5)
  at Document._resize (/Users/caged/Dev/bokeh/bokeh/bokehjs/src/coffee/document.coffee:143:14)
  at Document.resize (/Users/caged/Dev/bokeh/bokeh/bokehjs/src/coffee/document.coffee:106:6)
  at proxy (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/jquery/dist/jquery.js:497:14)
  at [object Object]._onTimeout (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/underscore/underscore.js:768:19)
  at Timer.listOnTimeout (timers.js:92:15)

      ✓ should have _horizontal set to true by default
    

--------------



      ✓ get_width_height should return a constrained width if plot is landscape oriented
[02:57:22] 'test:models' errored after 6.32 s
[02:57:22] Error in plugin 'gulp-mocha'
Message:
    unknown edit variable
Details:
    domain: [object Object]
    domainThrown: true
Stack:
Error: unknown edit variable
  at Solver.suggestValue (/Users/caged/Dev/bokeh/bokeh/bokehjs/src/vendor/kiwi/kiwi.js:1549:23)
  at Solver.suggest_value (/Users/caged/Dev/bokeh/bokeh/bokehjs/src/coffee/core/layout/solver.coffee:52:13)
  at PlotView.LayoutDOMView.render (/Users/caged/Dev/bokeh/bokeh/bokehjs/src/coffee/models/layouts/layout_dom.coffee:72:9)
  at PlotView.render (/Users/caged/Dev/bokeh/bokeh/bokehjs/src/coffee/models/plots/plot.coffee:27:5)
  at PlotView.<anonymous> (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/backbone/backbone.js:328:18)
  at PlotView.<anonymous> (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/underscore/underscore.js:890:21)
  at triggerEvents (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/backbone/backbone.js:368:57)
  at triggerApi (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/backbone/backbone.js:356:19)
  at eventsApi (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/backbone/backbone.js:155:16)
  at Solver.Events.trigger (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/backbone/backbone.js:346:5)
  at Document._resize (/Users/caged/Dev/bokeh/bokeh/bokehjs/src/coffee/document.coffee:143:14)
  at Document.resize (/Users/caged/Dev/bokeh/bokeh/bokehjs/src/coffee/document.coffee:106:6)
  at proxy (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/jquery/dist/jquery.js:497:14)
  at [object Object]._onTimeout (/Users/caged/Dev/bokeh/bokeh/bokehjs/node_modules/underscore/underscore.js:768:19)
  at Timer.listOnTimeout (timers.js:92:15)

      ✓ get_width_height should return a constrained height if plot is portrait oriented
    Plot.Model
      ✓ should have _horizontal set to true by default
 


---------------
```

**Comment by birdsarah** [comment]
#4638 tried to make some improvements

It seems to be a glitch in stubbing the solver, and I would say a race condition given that it doesn't always happen. It seemed to happen more when the fixed mode performance improvement was added - which may be because there's less initialization time.

It's often plot_canvas.update_constraints that's triggering the call to update_solver; but not always.

**Comment by mattpap** [comment]
Looking at the following failure:
```
     1) "after each" hook
      - get_width should return the width from the aspect ratio

  PlotCanvas
    2) "before each" hook
    3) "after each" hook for "should set the sizing_mode to box by default"


  543 passing (9s)
  18 pending
  3 failing

  1) Plot PlotView "after each" hook:
     Uncaught Error: unknown edit variable
    at Solver.suggestValue (src/vendor/kiwi/kiwi.js:1549:23)
    at Solver.exports.Solver.Solver.suggest_value (build/js/tree/core/layout/solver.js:77:28)
    at PlotView.exports.LayoutDOMView.LayoutDOMView.render (build/js/tree/models/layouts/layout_dom.js:106:15)
    at PlotView.exports.PlotView.PlotView.render (build/js/tree/models/plots/plot.js:35:35)
    at PlotView.<anonymous> (build/js/tree/models/layouts/layout_dom.js:72:34)
    at PlotView.<anonymous> (build/js/tree/core/events.js:199:22)
    at PlotView.<anonymous> (node_modules/underscore/underscore.js:890:21)
    at triggerEvents (build/js/tree/core/events.js:241:43)
    at triggerApi (build/js/tree/core/events.js:227:13)
    at eventsApi (build/js/tree/core/events.js:44:18)
    at Solver.exports.Events.trigger (build/js/tree/core/events.js:216:5)
    at Document.exports.Document.Document._resize (build/js/tree/document.js:200:29)
    at Document.exports.Document.Document.resize (build/js/tree/document.js:158:14)
    at Timeout._onTimeout (node_modules/underscore/underscore.js:768:19)
  

  2) Plot "before each" hook:
     TypeError: Cannot read property 'call' of undefined
  

  3) PlotCanvas "after each" hook for "should set the sizing_mode to box by default":
     TypeError: CanvasView.prototype.get_ctx.restore is not a function
    at Object.unstub_canvas (test/utils.coffee:45:34)
    at Context.<anonymous> (test/models/plots/plot_canvas.coffee:34:11)
  



  4) "before each" hook
```
my assessment is that this is a test (or test infrastructure) failure and not an inherent problem with layout code. What's happening here is that layout is being modified for the purpose of testing before and after each test. Those modifications don't take into account that certain event chains may be triggered in bokehjs, especially delayed event chains. Solver (or whatever) is being unstubbed too early and then events depending on the "stubbed"  state are being evaluated and must fail. In this particular case, `Document.resize()` is being called too late or "after each" too early. btw. Don't get fooled by the order of "after" and "before", because there are multiple nested "befores" and "afters" in `test/models/plots/plot.coffee`.

How to fix this? My first thought is to ditch all this sinon stub sorcery. That should be done anyway, but it won't fully fix the problem. A test shouldn't be considered as finished until all event chains finished without uncaught exceptions. I'm not sure how to achieve this. If this was only about backbone events, this would be fairly easy, but we also have to include browser events.
