### ISSUE TITLE
Tests from remotedata are failing in master (py27 env)

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#472]
pinging @hhuuggoo because it is related with remote data merged PR

```
======================================================================
ERROR: test_line_downsample (bokeh.server.tests.remotedata_tests.RemoteDataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/datos/Desarrollos/bokeh/bokeh/server/tests/remotedata_tests.py", line 46, in test_line_downsample
    result = result.json()
  File "/media/datos/virtualenvs/bokeh-dev/local/lib/python2.7/site-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
-------------------- >> begin captured stdout << ---------------------

Starting Bokeh plot server on port 5006...
View http://127.0.0.1:5006/bokeh to see plots

found config for http://localhost:5006/
{}
loading it!
if you don't wish to load this config, please pass load_from_config=False

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
bokeh.server.server_backends: ERROR: No module named arraymanagement.client
Traceback (most recent call last):
  File "/media/datos/Desarrollos/bokeh/bokeh/server/server_backends.py", line 412, in __init__
    from arraymanagement.client import ArrayClient
ImportError: No module named arraymanagement.client
bokeh.server.server_backends: INFO: error importing arraymanagement
bokeh.server.server_backends: INFO: install arraymanagement from https://github.com/continuumio/ArrayManagement
bokeh.server.server_backends: INFO: or procede without remote data capabilities
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /bokeh/ping HTTP/1.1" 200 4
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /bokeh/data2/defaultuser/defaultuser/AAPL.hdf5?downsample_function=line1d&downsample_parameters=%5B%22close%22%2C+%22date%22%2C+%5B%22close%22%2C+%22open%22%2C+%22date%22%5D%2C+%5B1325386800000.0%2C+1357009200000.0%5D%2C+10%5D HTTP/1.1" 404 233
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_list (bokeh.server.tests.remotedata_tests.RemoteDataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/datos/Desarrollos/bokeh/bokeh/server/tests/remotedata_tests.py", line 24, in test_list
    sources = s.list_data()
  File "/media/datos/Desarrollos/bokeh/bokeh/serverconfig.py", line 168, in list_data
    result = utils.get_json(result)
  File "/media/datos/Desarrollos/bokeh/bokeh/utils.py", line 14, in get_json
    return request.json()
  File "/media/datos/virtualenvs/bokeh-dev/local/lib/python2.7/site-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
-------------------- >> begin captured stdout << ---------------------

Starting Bokeh plot server on port 5006...
View http://127.0.0.1:5006/bokeh to see plots

found config for http://localhost:5006/
{}
loading it!
if you don't wish to load this config, please pass load_from_config=False

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
bokeh.server.server_backends: ERROR: No module named arraymanagement.client
Traceback (most recent call last):
  File "/media/datos/Desarrollos/bokeh/bokeh/server/server_backends.py", line 412, in __init__
    from arraymanagement.client import ArrayClient
ImportError: No module named arraymanagement.client
bokeh.server.server_backends: INFO: error importing arraymanagement
bokeh.server.server_backends: INFO: install arraymanagement from https://github.com/continuumio/ArrayManagement
bokeh.server.server_backends: INFO: or procede without remote data capabilities
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /bokeh/ping HTTP/1.1" 200 4
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
bokeh.server: ERROR: Exception on /bokeh/data/defaultuser [GET]
Traceback (most recent call last):
  File "/media/datos/virtualenvs/bokeh-dev/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/datos/virtualenvs/bokeh-dev/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/datos/virtualenvs/bokeh-dev/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/media/datos/virtualenvs/bokeh-dev/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/datos/virtualenvs/bokeh-dev/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/datos/Desarrollos/bokeh/bokeh/server/views/data.py", line 15, in list_sources
    username)
  File "/media/datos/Desarrollos/bokeh/bokeh/server/server_backends.py", line 422, in list_data_sources
    return self.client[username].descendant_urls(ignore_groups=True)
AttributeError: 'HDF5DataBackend' object has no attribute 'client'
requests.packages.urllib3.connectionpool: DEBUG: "GET /bokeh/data/defaultuser HTTP/1.1" 500 291
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 164 tests in 2.500s

FAILED (errors=2)
```

**Comment by richwu** [comment]
If this has been fixed, why I got this problem by 0.8.1 again? Anything missed by rolling to the new version?

**Comment by bryevdv** [comment]
This test was passing for the 0.8.1 release on all platforms, for py2/py3. Can you be more specific about the problem you are seeing? Can you provide a minimal example to reproduce the problem?

**Comment by richwu** [comment]
Hi Bryan,
I'm testing the base examples, animated.py for bokeh-server plotting. I've
upgrade the bokeh installation to 0.8.1 thru conda. And I cleaned/re-cloned
the github bokeh repo entirely for client side example code.

I tested the code both on localhost bokeh-server and remote host

The following is my
/home/amdevu/work/work_env/anaconda_pydev/bin/python
/home/amdevu/work/work_dir/py_work/
github.com/bokeh/examples/plotting/server/animated.py
No handlers could be found for logger "bokeh.session"
Using saved session configuration for http://192.168.1.120:5006
To override, pass 'load_from_config=False' to Session
Traceback (most recent call last):
  File "/home/amdevu/work/work_dir/py_work/
github.com/bokeh/examples/plotting/server/animated.py", line 22, in <module>
    output_server("animated",url='http://192.168.1.120:5006')
  File "/home/amdevu/work/work_dir/py_work/github.com/bokeh/bokeh/io.py",
line 157, in output_server
    docname, session=session, url=url, name=name, clear=clear
  File "/home/amdevu/work/work_dir/py_work/github.com/bokeh/bokeh/state.py",
line 223, in output_server
    self._session.load_document(self._document)
  File "/home/amdevu/work/work_dir/py_work/github.com/bokeh/bokeh/session.py",
line 543, in load_document
    self.gc()
  File "/home/amdevu/work/work_dir/py_work/github.com/bokeh/bokeh/session.py",
line 529, in gc
    self.post_json(url)
  File "/home/amdevu/work/work_dir/py_work/github.com/bokeh/bokeh/session.py",
line 367, in post_json
    return self.execute_json('post', url, headers=headers, **kwargs)
  File "/home/amdevu/work/work_dir/py_work/github.com/bokeh/bokeh/session.py",
line 335, in execute_json
    return utils.get_json(resp)
  File "/home/amdevu/work/work_dir/py_work/github.com/bokeh/bokeh/utils.py",
line 42, in get_json
    return response.json()
  File
"/home/amdevu/work/work_env/anaconda_pydev/lib/python2.7/site-packages/requests/models.py",
line 799, in json
    return json.loads(self.text, **kwargs)
  File
"/home/amdevu/work/work_env/anaconda_pydev/lib/python2.7/json/__init__.py",
line 338, in loads
    return _default_decoder.decode(s)
  File
"/home/amdevu/work/work_env/anaconda_pydev/lib/python2.7/json/decoder.py",
line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File
"/home/amdevu/work/work_env/anaconda_pydev/lib/python2.7/json/decoder.py",
line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Process finished with exit code 1

Regards
Richard

**Comment by damianavila** [comment]
Do you see this in 0.8.0 too? or in 0.7.1? BTW, this seems not related with the previous remote data test failing, it should be probably migrated to a new issue...
