### ISSUE TITLE
first example in quickstart missing output_file

### ISSUE THREAD

**Issue by jdimatteo** [bokeh/bokeh#4727]
The first quickstart example results in an error due to a missing output_file, e.g.

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bokeh/io.py", line 302, in show
    return _show_with_state(obj, _state, browser, new)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/io.py", line 320, in _show_with_state
    _show_file_with_state(obj, state, new, controller)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/io.py", line 325, in _show_file_with_state
    filename = save(obj, state=state)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/io.py", line 381, in save
    filename, resources, title = _get_save_args(state, filename, resources, title)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/io.py", line 413, in _get_save_args
    raise RuntimeError("save() called but no filename was supplied or detected, and output_file(...) was never called, nothing saved")
RuntimeError: save() called but no filename was supplied or detected, and output_file(...) was never called, nothing saved
```

**Comment by T3am5hark** [comment]
The first example in the "Getting Started" guide on the side also produces same error...

http://bokeh.pydata.org/en/latest/docs/user_guide/quickstart.html#getting-started
