### ISSUE TITLE
Error plotting dates before 1970 (on Windows?)

### ISSUE THREAD

**Issue by cgmorton** [bokeh/bokeh#4880]
When I try to generate a time series figure with dates before 1970 on a Windows, I get an "OverflowError: mktime argument out of range".  I'm using Bokeh 0.12.0 installed from conda with Python 2.7 on Windows 7.  Based on a little searching on [stackoverflow](http://stackoverflow.com/questions/2518706/python-mktime-overflow-error) it sounds like this might just be a problem with Windows.

The following scripts should generate the error:

```
import datetime as dt
import random
from bokeh.plotting import figure, show

# Dates before 1970 cause an error
f = figure(x_axis_type='datetime')
f.line(
    [dt.date(year, 1, 1) for year in range(1969, 2000)],
    random.sample(range(1, 100), len(dates)))
show(f)
```

If I change the mktime call line in json_encoder.py from:

```
return time.mktime(obj.timetuple()) * 1000.
```

to:

```
epoch_delta = dt.datetime(obj.year, obj.month, obj.day) - dt.datetime(1970, 1, 1)
return epoch_delta.total_seconds() * 1000.
```

the problem goes away for me, but I'm not confident enough in that solution to make a pull request!

Here's the full traceback:

```
Traceback (most recent call last):
  File "bokeh_1970.py", line 20, in <module>
    show(f)
  File "C:\Miniconda2\lib\site-packages\bokeh\io.py", line 302, in show
    return _show_with_state(obj, _state, browser, new)
  File "C:\Miniconda2\lib\site-packages\bokeh\io.py", line 320, in _show_with_state
    _show_file_with_state(obj, state, new, controller)
  File "C:\Miniconda2\lib\site-packages\bokeh\io.py", line 325, in _show_file_with_state
    filename = save(obj, state=state)
  File "C:\Miniconda2\lib\site-packages\bokeh\io.py", line 382, in save
    _save_helper(obj, filename, resources, title, validate)
  File "C:\Miniconda2\lib\site-packages\bokeh\io.py", line 448, in _save_helper
    html = standalone_html_page_for_models(obj, resources, title)
  File "C:\Miniconda2\lib\site-packages\bokeh\embed.py", line 603, in standalone_html_page_for_model
s
    return file_html(models, resources, title)
  File "C:\Miniconda2\lib\site-packages\bokeh\embed.py", line 314, in file_html
    (docs_json, render_items) = _standalone_docs_json_and_render_items(models)
  File "C:\Miniconda2\lib\site-packages\bokeh\embed.py", line 575, in _standalone_docs_json_and_rend
er_items
    docs_json[k] = v.to_json()
  File "C:\Miniconda2\lib\site-packages\bokeh\document.py", line 794, in to_json
    doc_json = self.to_json_string()
  File "C:\Miniconda2\lib\site-packages\bokeh\document.py", line 787, in to_json_string
    return serialize_json(json, indent=indent)
  File "C:\Miniconda2\lib\site-packages\bokeh\core\json_encoder.py", line 99, in serialize_json
    return json.dumps(obj, cls=encoder, allow_nan=False, indent=indent, separators=separators, sort_
keys=True, **kwargs)
  File "C:\Miniconda2\lib\json\__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\Miniconda2\lib\json\encoder.py", line 209, in encode
    chunks = list(chunks)
  File "C:\Miniconda2\lib\json\encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "C:\Miniconda2\lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\Miniconda2\lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\Miniconda2\lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\Miniconda2\lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\Miniconda2\lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\Miniconda2\lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\Miniconda2\lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\Miniconda2\lib\json\encoder.py", line 442, in _iterencode
    o = _default(o)
  File "C:\Miniconda2\lib\site-packages\bokeh\core\json_encoder.py", line 83, in default
    return self.transform_python_types(obj)
  File "C:\Miniconda2\lib\site-packages\bokeh\core\json_encoder.py", line 49, in transform_python_ty
pes
    return time.mktime(obj.timetuple()) * 1000.
OverflowError: mktime argument out of range
```

**Comment by mattpap** [comment]
This code works on Linux. Nevertheless, the documentation of `mktime()` states that the earliest date that can be represented is platform dependent, so this is definitively a bug on bokeh-side.

**Comment by bryevdv** [comment]
An equivalent to the suggested fix was implemented recently. Tested on windows, is now working:

<img width="932" alt="screen shot 2017-06-21 at 22 31 21" src="https://user-images.githubusercontent.com/1078448/27416194-73059e6e-56d1-11e7-8ff7-12fe8398025a.png">
