### ISSUE TITLE
Limit imports of client/server code to only when necessary

### ISSUE THREAD

**Issue by budiaji** [bokeh/bokeh#5060]
Hi,

I try to import a module Bar module using

```
from bokeh.charts import Bar
```

then I got SyntaxError

```
Traceback (most recent call last):
  File "bokeh_func.py", line 2, in <module>
    from bokeh.charts import Bar 
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/__init__.py", line 10, in <module>
    from ..plotting.helpers import DEFAULT_PALETTE
  File "/usr/local/lib/python2.7/dist-packages/bokeh/plotting/__init__.py", line 7, in <module>
    from ..io import curdoc; curdoc
  File "/usr/local/lib/python2.7/dist-packages/bokeh/io.py", line 29, in <module>
    from .core.state import State
  File "/usr/local/lib/python2.7/dist-packages/bokeh/core/state.py", line 46, in <module>
    from ..client import DEFAULT_SESSION_ID
  File "/usr/local/lib/python2.7/dist-packages/bokeh/client/__init__.py", line 6, in <module>
    from .session import ClientSession, pull_session, push_session, show_session, DEFAULT_SESSION_ID
  File "/usr/local/lib/python2.7/dist-packages/bokeh/client/session.py", line 10, in <module>
    from ._connection import ClientConnection
  File "/usr/local/lib/python2.7/dist-packages/bokeh/client/_connection.py", line 11, in <module>
    from tornado import gen, locks
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1243, in <module>
    import tornado.platform.asyncio
  File "/usr/local/lib/python2.7/dist-packages/tornado/platform/asyncio.py", line 33, in <module>
    import asyncio # type: ignore
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
```

There is asyncio installed on my system. When I uninstalled asyncio, there is no error.

Bokeh info

```
Python version      :  2.7.6 (default, Jun 22 2015, 17:58:13) 
IPython version     :  1.2.1
Bokeh version       :  0.12.1
BokehJS static path :  /usr/local/lib/python2.7/dist-packages/bokeh/server/static
```

**Comment by mattpap** [comment]
@budiaji, how did you end up with asyncio package on Python 2.7? asyncio is a Python 3.3 package, so a syntax error like the reporter one is not unexpected. Apparently pip can install asyncio without hickup on 2.7. For 2.7 you may want to check out https://pypi.python.org/pypi/trollius (if that's necessary at all).

**Comment by bryevdv** [comment]
Right, this is an upstream issue. The error is coming from within tornado, not Bokeh. It's seems that it is looking for any system `asyncio` and aliasing it as `tornado.platform.asyncio`, with the results you are seeing. I echo @mattpap's question: what is this `asyncio` that you are installing on python 2.7?

About the only thing I think we could do is move the `bokeh.client` imports from the top-level to inside the functions where they are actually used. That's only an "accidental" fix for your situation, and also only "works" if you don't also use Bokeh server. But it seems like a good idea to try and avoid bringing in tornado and everything unless its actually needed, so I'd be +1 for moving those imports in any case. @bokeh/dev ?

**Comment by bryevdv** [comment]
OK there was no response from the OP, but I think the idea of structuring to limit imports of heavy server related things to only when they are actually used is a good one, so I have updated this issue.
