### ISSUE TITLE
Bokeh Line Plot with Web GL fails in Internet explorer 11

### ISSUE THREAD

**Issue by renzop** [bokeh/bokeh#5117]
Using bokeh 0.12.2 plotting line plot with webgl=True does not render the plot in ie11. But Works in chrome.  

Error message show in the browser:
"ValueError: Type undefined not allowed for texture"

-- Same behaviour with the bokeh examples (except there is no error message in the browser window nor in the console)
http://bokeh.pydata.org/en/latest/docs/user_guide/webgl.html#

Python version      :  2.7.9 (default, Feb 10 2015, 03:28:08) 
IPython version     :  4.2.0
Bokeh version       :  0.12.2

Bokehplots are embedded with the components function.

**Comment by pierluigi-failla** [comment]
Same issue with `webgl=True`, here is the error:

`ValueError: ValueError:Type undefined not allowed for texture
   at i.prototype.set_data (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js:140:31351)
   at t (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js:14:21448)
   at e.prototype.init (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js:15:35)
   at t (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js:14:18473)
   at e (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js:14:22611)
   at e.prototype.initialize (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js:13:325)
   at a (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js:4:1121)
   at e (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js:4:3118)
   at e (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js:12:31954)
   at e (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js:13:19814)
`
the same code works properly within Chrome and not in iExplore 11.

**Comment by mattpap** [comment]
@pierluigi-failla, can you repost the stacktrace using unminified resources? (`BOKEH_MINIFIED=false python some.py` or whatever is the equivalent on windows).

**Comment by pierluigi-failla** [comment]
Sorry, my bad! Here is the unminified version:

`ValueError: ValueError:Type undefined not allowed for texture
   at Texture2D.prototype.set_data (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.js:49435:139)
   at DashAtlas (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.js:15716:5)
   at LineGLGlyph.prototype.init (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.js:15846:5)
   at BaseGLGlyph (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.js:15552:5)
   at LineGLGlyph (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.js:15797:5)
   at GlyphView.prototype.initialize (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.js:12576:11)
   at View (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.js:879:3)
   at BokehView (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.js:1053:5)
   at GlyphView (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.js:12562:5)
   at LineView (https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.js:13699:5)
`

Just to add a bit of information, I created the `script` and `div` using `components` (in python) then I embedded it in an html page. Loading the page in Chrome works pretty fine, while IE is giving the above error.

**Comment by bryevdv** [comment]
As of 2.2 this example rendered successfully on IE with legacy resources, e.g `CDN.legacy = True`. 

Also noting that in light of MS recent announcement, all IE support will be dropped completely sometime in the next year.
