### ISSUE TITLE
ggplot compat doesn't work with >0.9.4

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5208]
running `examples/compat/ggplot_point.py` with a version higher than 0.9.4 (which are available on conda-forge) gives following error:

``` sh
(bokeh_34) ➜  compat git:(birdsarah/5076_yield_tests) python ggplot_point.py      
/Users/caged/Dev/bokeh/bokeh/bokeh/core/compat/bokeh_renderer.py:260: UserWarning: Path marker shapes currently not handled, defaulting to Circle
  warnings.warn("Path marker shapes currently not handled, defaulting to Circle")
Traceback (most recent call last):
  File "ggplot_point.py", line 16, in <module>
    show(mpl.to_bokeh())
  File "/Users/caged/Dev/bokeh/bokeh/bokeh/core/compat/mpl.py", line 55, in to_bokeh
    exporter.run(fig)
  File "/Users/caged/Dev/bokeh/bokeh/bokeh/core/compat/mplexporter/exporter.py", line 51, in run
    self.crawl_fig(fig)
  File "/Users/caged/Dev/bokeh/bokeh/bokeh/core/compat/mplexporter/exporter.py", line 118, in crawl_fig
    self.crawl_ax(ax)
  File "/Users/caged/Dev/bokeh/bokeh/bokeh/core/compat/mplexporter/exporter.py", line 140, in crawl_ax
    self.draw_collection(ax, collection)
 45 test:                                                                                               
  File "/Users/caged/Dev/bokeh/bokeh/bokeh/core/compat/bokeh_exporter.py", line 34, in draw_collection
    super(BokehExporter, self).draw_collection(ax, collection, force_pathtrans, force_offsettrans)
  File "/Users/caged/Dev/bokeh/bokeh/bokeh/core/compat/mplexporter/exporter.py", line 272, in draw_collection
    mplobj=collection)
  File "/Users/caged/Dev/bokeh/bokeh/bokeh/core/compat/bokeh_renderer.py", line 282, in draw_path_collection
    marker.line_color = convert_color(tuple(map(tuple,style['edgecolor']))[0])
IndexError: tuple index out of range
```

There maybe other additional errors that our examples don't pick up.

**Comment by birdsarah** [comment]
Should compat be in bokeh core or in a seperate package so it can be maintained at its own pace?

**Comment by Ron024** [comment]
I am also having the same issue creating a plot with seaborn 0.7.1, matplotlib 1.5.3, and bokeh 0.12.4.

**Comment by bryevdv** [comment]
Unfortunately MPL compat is about to be deprecated entirely. We do not have the resources or ability to maintain it.
