### ISSUE TITLE
import_optional isn't robust to all import failures

### ISSUE THREAD

**Issue by dhirschfeld** [bokeh/bokeh#5242]
In my IIS web app trying to import IPython raises a ValueError.

`import_requires` only protects against an ImportError so trying to import `bokeh` results in an exception which crashes the application

```
Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "c:\python\envs\py-dev\lib\site-packages\wfastcgi.py", line 779, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "c:\python\envs\py-dev\lib\site-packages\wfastcgi.py", line 621, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv('WSGI_HANDLER'))
  File "c:\python\envs\py-dev\lib\site-packages\wfastcgi.py", line 589, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
  File ".\quantweb.py", line 42, in <module>
    app = create_app()
  File ".\quantweb.py", line 8, in create_app
    from frontend import frontend
  File ".\frontend.py", line 4, in <module>
    from utils import handle_exception
  File ".\utils.py", line 3, in <module>
    import bokeh.plotting as plt
  File "C:\dev\code\bokeh\bokeh\plotting\__init__.py", line 2, in <module>
    from ..document import Document; Document
  File "C:\dev\code\bokeh\bokeh\document.py", line 36, in <module>
    from .model import Model
  File "C:\dev\code\bokeh\bokeh\model.py", line 13, in <module>
    from .core.properties import Any, HasProps, List, MetaHasProps, String
  File "C:\dev\code\bokeh\bokeh\core\properties.py", line 78, in <module>
    IPython = import_optional('IPython')
  File "C:\dev\code\bokeh\bokeh\util\dependencies.py", line 19, in import_optional
    return import_module(mod_name)
  File "c:\python\envs\py-dev\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\python\envs\py-dev\lib\site-packages\IPython\__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "c:\python\envs\py-dev\lib\site-packages\IPython\terminal\embed.py", line 16, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "c:\python\envs\py-dev\lib\site-packages\IPython\core\interactiveshell.py", line 62, in <module>
    from IPython.utils import io
  File "c:\python\envs\py-dev\lib\site-packages\IPython\utils\io.py", line 92, in <module>
    stdin = IOStream(sys.stdin, fallback=devnull)
  File "c:\python\envs\py-dev\lib\site-packages\IPython\utils\io.py", line 41, in __init__
    for meth in filter(clone, dir(stream)):
  File "c:\python\envs\py-dev\lib\site-packages\IPython\utils\io.py", line 40, in clone
    return not hasattr(self, meth) and not meth.startswith('_')
  File "c:\python\envs\py-dev\lib\site-packages\IPython\utils\io.py", line 79, in closed
    return self.stream.closed
ValueError: underlying buffer has been detached


StdOut: 

StdErr: 
```

**Comment by mattpap** [comment]
> ValueError: underlying buffer has been detached

Is this a known issue? Is this somehow fixable? This may need a follow up with IPython team, so that they limit or don't do computations at import time.

**Comment by dhirschfeld** [comment]
It *is* likely a bug in ipython but I'm not sure if it has been reported upstream. Nevertheless, if bokeh is importing ipython then bokeh needs to be robust to it throwing a ValueError (or any other error) on import.  IMHO since the import is entirely optional bokeh shouldn't crash hard because of a bug in ipython.

Without this patch the latest bokeh is entirely unusable for my usecase. With this patch I may not get whatever functionality ipython provided but the rest of bokeh functions perfectly well

I agree that silently swallowing exceptions is generally a very bad idea as it can hide the source of later problems however I see that more as an argument to issue a warning rather than to let bokeh crash hard.

I've updated the PR to issue a warning on an optional import which raises an exception.
