### ISSUE TITLE
Extensions cannot use own `.eco` templates as compiler won't compile them

### ISSUE THREAD

**Issue by djpugh** [bokeh/bokeh#5279]
As mentioned in #5258, when creating an extension, the template cannot be a separate implementation and compiled, instead it must be updated in the JS/Coffescript implementation of the extension.
e.g.:

```
 ionslidertemplate = require "models/widgets/slidertemplate"
 
 # This model will actually need to render things, so we must provide
 # view. The LayoutDOM model has a view already, so we will start with that
 class IonRangeSliderView extends InputWidget.View
   tagName: "div"
   template: ionslidertemplate
```
And in the `initialize` function:
```
 html = @template(@model.attributes)
 # replace div slider to input slider
 html = html.replace('<div class="slider "','<input type="text" class="slider "')
 html = html.replace('<div class="bk-slider-horizontal">','<div class="bk-slider-horizontal bk-ion-slider">')
```
v0.12.2

It would be really helpful if these could be implemented in a `.eco` file to use as the template directly.

**Comment by djpugh** [comment]
@bryevdv as mentioned in #5258 this doesn't seem to be working yet - I'm getting errors from `bokeh/utils/compile.py`:
```
Traceback (most recent call last):
  File ".\extensions_example_widget_plot.py", line 419, in <module>
    show(layout)
  File "D:\Code\bokeh\bokeh\io.py", line 314, in show
    return _show_with_state(obj, _state, browser, new, notebook_handle=notebook_handle)
  File "D:\Code\bokeh\bokeh\io.py", line 332, in _show_with_state
    _show_file_with_state(obj, state, new, controller)
  File "D:\Code\bokeh\bokeh\io.py", line 337, in _show_file_with_state
    filename = save(obj, state=state)
  File "D:\Code\bokeh\bokeh\io.py", line 396, in save
    _save_helper(obj, filename, resources, title, validate)
  File "D:\Code\bokeh\bokeh\io.py", line 461, in _save_helper
    html = standalone_html_page_for_models(obj, resources, title)
  File "D:\Code\bokeh\bokeh\embed.py", line 594, in standalone_html_page_for_models
    return file_html(models, resources, title)
  File "D:\Code\bokeh\bokeh\embed.py", line 307, in file_html
    bundle = _bundle_for_objs_and_resources(models, resources)
  File "D:\Code\bokeh\bokeh\embed.py", line 204, in _bundle_for_objs_and_resources
    bokeh_js = js_resources.render_js()
  File "D:\Code\bokeh\bokeh\resources.py", line 395, in render_js
    return JS_RESOURCES.render(js_raw=self.js_raw, js_files=self.js_files)
  File "D:\Code\bokeh\bokeh\resources.py", line 388, in js_raw
    custom_models = gen_custom_models_static()
  File "D:\Code\bokeh\bokeh\util\compiler.py", line 316, in gen_custom_models_static
    deps_map = resolve_deps(compiled.deps, model.path)
  File "D:\Code\bokeh\bokeh\util\compiler.py", line 312, in resolve_deps
    return resolve_modules(missing, root)
  File "D:\Code\bokeh\bokeh\util\compiler.py", line 293, in resolve_modules
    code = compiled.code
  File "D:\Code\bokeh\bokeh\util\compiler.py", line 84, in __getattr__
    return self[key]
KeyError: 'code'
```

Debugging that error a bit it looks as if the eco template is not generating any code in bokeh\utils\compiler.py:nodejs_compile - I'm just going to try stepping through the python code to check nothing weird is happening there

I don't think it's anything in my template as using the stock slider template it also generates no compiled code, so will error here (Line 289-294 of bokeh\utils\compiler.py):
```
                if impl.lang == "less":
                    code = _style_template % dict(css=json.dumps(compiled.code))
                    deps = []
                else:
                    code = compiled.code
                    deps = compiled.deps
```

**Comment by djpugh** [comment]
Was fixed, I forgot to rebuild `bokehjs`!
