### ISSUE TITLE
Literal code blocks not working for extensions 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5387]
See the example in this issue comment: https://github.com/bokeh/bokeh/issues/1671#issuecomment-254338617

It is required to use `CoffeeScript` it seems like it was auto-detected before. 

ping @mattpap

**Comment by mattpap** [comment]
@bryevdv, I don't see anything in this comment that says that it's required to use `CoffeeScript` wrapper. Did you verify this doesn't work?

**Comment by bryevdv** [comment]
@mattpap sorry yes that example does actually work, but this one does not (just tested):
```
from bokeh.io import output_file, show
from bokeh.models import TickFormatter
from bokeh.plotting import figure

JS_CODE = """
import TickFormatter "models/formatters/tick_formatter"

export class MyFormatter extends TickFormatter.Model
  type: "MyFormatter"

  # TickFormatters should implement this method, which accepts a lisst
  # of numbers (ticks) and returns a list of strings
  doFormat: (ticks) ->
    # format the first tick as-is
    formatted = ["#{ticks[0]}"]

    # format the remaining ticks as a difference from the first
    for i in [1...ticks.length]
       formatted.push("+#{(ticks[i]-ticks[0]).toPrecision(2)}")

    return formatted
"""

class MyFormatter(TickFormatter):

    __implementation__ = JS_CODE

p = figure()
p.circle([1,2,3,4,6], [5,7,3,2,4])

p.xaxis.formatter = MyFormatter()

show(p)
```

**Comment by mattpap** [comment]
> `import TickFormatter "models/formatters/tick_formatter"`

`import {TickFormatter} from "models/formatters/tick_formatter"`

**Comment by mattpap** [comment]
Or maybe you meat `import * as TickFormatter from "models/formatters/tick_formatter`, to show that you can't import `TickFormatter.Model` (or `View`) anymore. I'm not sure which, thus it would be nice to get the intent along with code.

**Comment by bryevdv** [comment]
ping @birdsarah OK I think this was a false alarm we can close?

**Comment by birdsarah** [comment]
```python
from bokeh.io import output_file, show
from bokeh.models import TickFormatter
from bokeh.plotting import figure

JS_CODE = """
import {TickFormatter} "models/formatters/tick_formatter"

export class MyFormatter extends TickFormatter.Model
  type: "MyFormatter"

  # TickFormatters should implement this method, which accepts a lisst
  # of numbers (ticks) and returns a list of strings
  doFormat: (ticks) ->
    # format the first tick as-is
    formatted = ["#{ticks[0]}"]

    # format the remaining ticks as a difference from the first
    for i in [1...ticks.length]
       formatted.push("+#{(ticks[i]-ticks[0]).toPrecision(2)}")

    return formatted
"""

class MyFormatter(TickFormatter):

    __implementation__ = JS_CODE

p = figure()
p.circle([1,2,3,4,6], [5,7,3,2,4])

p.xaxis.formatter = MyFormatter()

show(p)
```

I changed the import, maybe incorrectly, getting this error when I try and run it

```console
	Traceback (most recent call last):
  File "test.py", line 33, in <module>
    show(p)
  File "/Users/sbird/Dev/bokeh/bokeh/bokeh/io.py", line 314, in show
    return _show_with_state(obj, _state, browser, new, notebook_handle=notebook_handle)
  File "/Users/sbird/Dev/bokeh/bokeh/bokeh/io.py", line 332, in _show_with_state
    _show_file_with_state(obj, state, new, controller)
  File "/Users/sbird/Dev/bokeh/bokeh/bokeh/io.py", line 337, in _show_file_with_state
    filename = save(obj, state=state)
  File "/Users/sbird/Dev/bokeh/bokeh/bokeh/io.py", line 396, in save
    _save_helper(obj, filename, resources, title, validate)
  File "/Users/sbird/Dev/bokeh/bokeh/bokeh/io.py", line 461, in _save_helper
    html = standalone_html_page_for_models(obj, resources, title)
  File "/Users/sbird/Dev/bokeh/bokeh/bokeh/embed.py", line 594, in standalone_html_page_for_models
    return file_html(models, resources, title)
  File "/Users/sbird/Dev/bokeh/bokeh/bokeh/embed.py", line 307, in file_html
    bundle = _bundle_for_objs_and_resources(models, resources)
  File "/Users/sbird/Dev/bokeh/bokeh/bokeh/embed.py", line 204, in _bundle_for_objs_and_resources
    bokeh_js = js_resources.render_js()
  File "/Users/sbird/Dev/bokeh/bokeh/bokeh/resources.py", line 395, in render_js
    return JS_RESOURCES.render(js_raw=self.js_raw, js_files=self.js_files)
  File "/Users/sbird/Dev/bokeh/bokeh/bokeh/resources.py", line 388, in js_raw
    custom_models = gen_custom_models_static()
  File "/Users/sbird/Dev/bokeh/bokeh/bokeh/util/compiler.py", line 273, in gen_custom_models_static
    raise CompilationError(compiled.error)
bokeh.util.compiler.CompilationError: /Users/sbird/Dev/bokeh/bokeh/test.py:MyFormatter:2:24:unexpected string
```

**Comment by birdsarah** [comment]
I have also tried

```coffee
import {TickFormatter} "models/formatters/tick_formatter"

export class MyFormatter extends TickFormatter
```

At the top of the implementation with the same error.

**Comment by mattpap** [comment]
@birdsarah, I wrote it my earlier comment, it should be:
```
import {TickFormatter} from "models/formatters/tick_formatter"
```

**Comment by birdsarah** [comment]
😥 I'm finally there. Thanks @mattpap. *from* turned out to be useful.

```python
from bokeh.io import output_file, show
from bokeh.models import TickFormatter
from bokeh.plotting import figure

JS_CODE = """
import {TickFormatter} from "models/formatters/tick_formatter"

export class MyFormatter extends TickFormatter
  type: "MyFormatter"

  # TickFormatters should implement this method, which accepts a lisst
  # of numbers (ticks) and returns a list of strings
  doFormat: (ticks) ->
    # format the first tick as-is
    formatted = ["#{ticks[0]}"]

    # format the remaining ticks as a difference from the first
    for i in [1...ticks.length]
       formatted.push("+#{(ticks[i]-ticks[0]).toPrecision(2)}")

    return formatted
"""

class MyFormatter(TickFormatter):

    __implementation__ = JS_CODE

p = figure()
p.circle([1,2,3,4,6], [5,7,3,2,4])

p.xaxis.formatter = MyFormatter()

show(p)
```
