### ISSUE TITLE
ValueError when running Bokeh in Toree notebook

### ISSUE THREAD

**Issue by jannepeltola** [bokeh/bokeh#5509]
Hi,

I'm running bokeh 0.12.3 in a notebook using the latest master branch of the Apache Toree PySpark kernel and Jupyter 4.2.3 on Python 3.4.3.

All calls to `output_notebook()` crash with:

```Traceback (most recent call last):
  File "/tmp/kernel-PySpark-5ffeccb6-e6c4-484f-9934-bee5df76feb0/pyspark_runner.py", line 189, in <module>
    eval(compiled_code)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/bokeh/io.py", line 178, in output_notebook
    load_notebook(resources, verbose, hide_banner, load_timeout)
  File "/usr/local/lib/python2.7/site-packages/bokeh/util/notebook.py", line 33, in load_notebook
    publish_display_data({'text/html': html})
  File "/usr/local/lib/python2.7/site-packages/bokeh/util/notebook.py", line 104, in publish_display_data
    displaypub.publish_display_data(source, data)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/display.py", line 119, in publish_display_data
    InteractiveShell.instance().display_pub.publish(
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 499, in __init__
    self.init_io()
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 658, in init_io
    io.stdout = io.IOStream(sys.stdout)
  File "/usr/local/lib/python2.7/site-packages/IPython/utils/io.py", line 34, in __init__
    raise ValueError("fallback required, but not specified")
ValueError: fallback required, but not specified
```

I couldn't find anything in existing issues or Google. Happy to provide further information.

**Comment by jannepeltola** [comment]
Actually, I found out that this is an issue with Toree itself. Looks like magics are currently broken in their master branch. You can close the issue.
