### ISSUE TITLE
Can't run unit tests without pytest-selenium

### ISSUE THREAD

**Issue by pitrou** [bokeh/bokeh#5520]
This is bothersome as pytest-selenium doesn't seem installable here:
```
$ pip install pytest pytest-selenium
Requirement already satisfied (use --upgrade to upgrade): pytest in /home/antoine/miniconda3/envs/bokeh27/lib/python2.7/site-packages
Collecting pytest-selenium
  Using cached pytest_selenium-1.7.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.29 in /home/antoine/miniconda3/envs/bokeh27/lib/python2.7/site-packages (from pytest)
Collecting pytest-html>=1.7 (from pytest-selenium)
  Using cached pytest_html-1.12.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from pytest-selenium)
Collecting selenium>=3.0.0 (from pytest-selenium)
  Using cached selenium-3.0.2-py2.py3-none-any.whl
Collecting pytest-variables (from pytest-selenium)
  Using cached pytest_variables-1.4-py2-none-any.whl
Collecting pytest-base-url (from pytest-selenium)
  Using cached pytest_base_url-1.2.0-py2.py3-none-any.whl
Collecting ansi2html>=1.1.1 (from pytest-html>=1.7->pytest-selenium)
  Using cached ansi2html-1.1.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from ansi2html>=1.1.1->pytest-html>=1.7->pytest-selenium)
Building wheels for collected packages: ansi2html
  Running setup.py bdist_wheel for ansi2html ... error
  Complete output from command /home/antoine/miniconda3/envs/bokeh27/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lBrz2R/ansi2html/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpyvTEegpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/ansi2html
  copying ansi2html/converter.py -> build/lib/ansi2html
  copying ansi2html/__init__.py -> build/lib/ansi2html
  copying ansi2html/util.py -> build/lib/ansi2html
  copying ansi2html/style.py -> build/lib/ansi2html
  running egg_info
  writing requirements to ansi2html.egg-info/requires.txt
  writing ansi2html.egg-info/PKG-INFO
  writing top-level names to ansi2html.egg-info/top_level.txt
  writing dependency_links to ansi2html.egg-info/dependency_links.txt
  writing entry points to ansi2html.egg-info/entry_points.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'ansi2html.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found under directory 'tests'
  writing manifest file 'ansi2html.egg-info/SOURCES.txt'
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-lBrz2R/ansi2html/setup.py", line 115, in <module>
      """
    File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
      return orig.install.run(self)
    File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/command/install.py", line 575, in run
      self.run_command(cmd_name)
    File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/dist.py", line 971, in run_command
      cmd_obj.ensure_finalized()
    File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
      self.finalize_options()
    File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
      self.set_undefined_options('install',('install_layout','install_layout'))
    File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/cmd.py", line 302, in set_undefined_options
      getattr(src_cmd_obj, src_option))
    File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
      raise AttributeError, attr
  AttributeError: install_layout
  
  ----------------------------------------
  Failed building wheel for ansi2html
  Running setup.py clean for ansi2html
Failed to build ansi2html
Installing collected packages: ansi2html, pytest-html, selenium, pytest-variables, pytest-base-url, pytest-selenium
  Running setup.py install for ansi2html ... error
    Complete output from command /home/antoine/miniconda3/envs/bokeh27/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lBrz2R/ansi2html/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gtEVbS-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/ansi2html
    copying ansi2html/converter.py -> build/lib/ansi2html
    copying ansi2html/__init__.py -> build/lib/ansi2html
    copying ansi2html/util.py -> build/lib/ansi2html
    copying ansi2html/style.py -> build/lib/ansi2html
    running egg_info
    writing requirements to ansi2html.egg-info/requires.txt
    writing ansi2html.egg-info/PKG-INFO
    writing top-level names to ansi2html.egg-info/top_level.txt
    writing dependency_links to ansi2html.egg-info/dependency_links.txt
    writing entry points to ansi2html.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'ansi2html.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    writing manifest file 'ansi2html.egg-info/SOURCES.txt'
    running install_lib
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lBrz2R/ansi2html/setup.py", line 115, in <module>
        """
      File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/command/install.py", line 575, in run
        self.run_command(cmd_name)
      File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/dist.py", line 971, in run_command
        cmd_obj.ensure_finalized()
      File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
        self.set_undefined_options('install',('install_layout','install_layout'))
      File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/cmd.py", line 302, in set_undefined_options
        getattr(src_cmd_obj, src_option))
      File "/home/antoine/miniconda3/envs/bokeh27/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
        raise AttributeError, attr
    AttributeError: install_layout
    
    ----------------------------------------
Command "/home/antoine/miniconda3/envs/bokeh27/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lBrz2R/ansi2html/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gtEVbS-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-lBrz2R/ansi2html/
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by bryevdv** [comment]
We don't have any control over whether `pytest-selenium` is pip-installable or not. This is why we invested in making sure all dev dependencies are conda installable from the `bokeh` channel. I would definitely state that `conda` environments are preferred and recommended for Bokeh development for this reason. 

I'm also not aware of any way to specify "optional" dependencies to `pytest`. If you know of an easy  way to make the tests work locally without `pytest-selenium` but run correctly with `pytest-selenium` on TravisCI, please feel free to re-open with that information and we can re-label as a `task`

**Comment by pitrou** [comment]
You can have a different py.test configuration per directory so, assuming the selenium tests are in a specific directory, that should work:
http://docs.pytest.org/en/latest/customize.html?highlight=configuration

**Comment by bryevdv** [comment]
Doesn't seem to help. I removed the `addOpts` line with `--driver` from the top level `setup.cfg` and moved it to a new `setup.cfg` in `tests/integration` and it still fails even if you tell pytest to not run integration tests:
```
$ py.test -m 'not (examples or js or integration or quality)'                     (mattpap/2274_interactive_legends✱)
=========================================================== test session starts ===========================================================
platform darwin -- Python 3.4.4, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /Users/bryan/work/bokeh, inifile: setup.cfg
plugins: cov-1.8.1, html-1.7, rerunfailures-1.0.1, variables-1.3, xdist-1.14
collected 1009 items / 1 errors

================================================================= ERRORS ==================================================================
____________________________________ ERROR collecting tests/integration/interaction/test_wheel_zoom.py ____________________________________
tests/integration/integration_tests_plugin.py:50: in pytest_generate_tests
    if metafunc.config.option.driver == "SauceLabs":
E   AttributeError: 'CmdOptions' object has no attribute 'driver'
========================================================= pytest-warning summary ==========================================================
WC1 None pytest_funcarg__cov: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
WC1 /Users/bryan/work/bokeh/bokeh/util/tests/test_options.py cannot collect test class 'TestOpts' because it has a __init__ constructor
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================== 186 tests deselected ===========================================================
======================================= 186 deselected, 2 pytest-warnings, 1 error in 6.87 seconds ========================================
```
AFAICT pytest evals all the `setup.cfg` files first, even if the tests are not subsequently run.
