### ISSUE TITLE
Error updating using Conda

### ISSUE THREAD

**Issue by neeljpatel** [bokeh/bokeh#5702]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

**>>conda update bokeh**
Fetching package metadata ...An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 231, in install
    index = common.get_index_trap(**index_args)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 627, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 25, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 290, in fetch_index
    for url in urls]
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 68, in func
    res = f(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
    resp = session.get(url + filename, headers=headers, proxies=session.proxies)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Anaconda\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in
 urlopen
    chunked=chunked)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in
 _make_request
    self._validate_conn(conn)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in
 _validate_conn
    conn.connect()
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connection.py", line 330, in con
nect
    cert = self.sock.getpeercert()
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 324,
 in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 171,
 in get_subj_alt_name
    ext = cert.extensions.get_extension_for_class(
AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**>>conda info**
Warning: could not import binstar_client ('args' object has no attribute 'site')Current conda in
stall:

             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.3.5
       python version : 2.7.10.final.0
     requests version : 2.12.4
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : C:\Users\npatel\.condarc
         offline mode : False
    is foreign system : False

**Comment by mattpap** [comment]
@neeljpatel, can you update conda to the most recent version (`conda update conda` in the root environment) and retry?

**Comment by neeljpatel** [comment]
@mattpap I was able to fix the issue after (randomly) attempting to update pip. I'm guessing conda is using pip, so this seemed to fix the issue. Thanks!
