### ISSUE TITLE
Missing template in flask_embed.py and tornado_embed.py

### ISSUE THREAD

**Issue by Juanlu001** [bokeh/bokeh#5742]
The `flask_embed.py` and `tornado_embed.py` examples are not self-contained in that they need an `embed.html` template. Running `flask_embed.py` as it appears in the repository leads to the following error:

```
$ python flask_embed.py 
Opening Flask app with embedded Bokeh application on http://localhost:8080/
[2017-01-16 21:29:37,150] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask_embed.py", line 43, in bkapp_page
    return render_template("embed.html", script=script)
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: embed.html
```

And putting `examples/embed/simple/templates/embed.html` under `templates/` yields this:

```
$ python flask_embed.py   
Opening Flask app with embedded Bokeh application on http://localhost:8080/
[2017-01-16 21:30:38,094] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask_embed.py", line 43, in bkapp_page
    return render_template("embed.html", script=script)
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/tmp/templates/embed.html", line 9, in top-level template code
    {{ js_resources|indent(4)|safe }}
  File "/home/juanlu/.miniconda3/envs/py35/lib/python3.5/site-packages/jinja2/filters.py", line 453, in do_indent
    rv = (u'\n' + indention).join(s.splitlines())
jinja2.exceptions.UndefinedError: 'js_resources' is undefined
```

**Comment by bryevdv** [comment]
Ack, I think it did not get picked up during the last release because of a `.gitignore` excluding HTML files. And it's since been deleted in my local tree. The other `embed.html` is not appropriate for this context, I will add a suitable one to master soon.

**Comment by bryevdv** [comment]
In the mean time, the template just needs a place for 
```
{{ script }}
```
as can be seen by the render call:
```
self.write(template.render(script=script))
```
I'm actually putting out several fires at the moment, if you have the ability to make a small PR adding a simple but interesting `embed.html` with a `{{ script }}` placeholder, it would be very valuable and appreciated.

**Comment by bryevdv** [comment]
@Juanlu001 are you interested in submitting a PR to resolve this issue as described above?

**Comment by Juanlu001** [comment]
@bryevdv I am indeed, but won't be able to work on this earlier than next weekend I fear!

**Comment by bryevdv** [comment]
Great! I just wanted to make sure you had the opportunity to, if you wanted to, before anyone else worked on it. :)

**Comment by bryevdv** [comment]
FYI I needed to show this to someone, so I created this right quick:
```
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>The HTML5 Herald</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">

  <link rel="stylesheet" href="css/styles.css?v=1.0">

  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->
</head>

<body>
  <div>HERE IS SOME CUSTOM STUFF</div>
  {{ script|safe }}
</body>
</html>
```
It would great if this could be made a little more interesting or visually appealing!

**Comment by bryevdv** [comment]
I went ahead and added this, thanks for pointing it out @Juanlu001

**Comment by Juanlu001** [comment]
Thanks @bryevdv, didn't have time to work on this in the end. Glad it's fixed!
