### ISSUE TITLE
Extension example breaking docs build

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5785]
Building docs on master with 
```
BOKEH_DOCS_CDN=local make SPHINXOPTS=-v clean html serve
```
results in
```
Traceback (most recent call last):
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/Sphinx-1.5-py3.4.egg/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/Sphinx-1.5-py3.4.egg/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/Sphinx-1.5-py3.4.egg/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/Sphinx-1.5-py3.4.egg/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/Sphinx-1.5-py3.4.egg/sphinx/environment/__init__.py", line 549, in update
    self._read_serial(docnames, app)
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/Sphinx-1.5-py3.4.egg/sphinx/environment/__init__.py", line 569, in _read_serial
    self.read_doc(docname, app)
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/Sphinx-1.5-py3.4.egg/sphinx/environment/__init__.py", line 677, in read_doc
    pub.publish()
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/Sphinx-1.5-py3.4.egg/sphinx/io.py", line 55, in read
    self.parse()
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_plot.py", line 164, in parse
    (script, js, js_path, source) = _process_script(source, filename, env.bokeh_plot_auxdir, js_name)
  File "/Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_plot.py", line 125, in _process_script
    js, script = autoload_static(d.roots[0], resources, script_path)
  File "/Users/bryan/work/bokeh/bokeh/embed.py", line 341, in autoload_static
    js_raw = resources.js_raw + [script],
  File "/Users/bryan/work/bokeh/bokeh/resources.py", line 388, in js_raw
    custom_models = gen_custom_models_static()
  File "/Users/bryan/work/bokeh/bokeh/util/compiler.py", line 371, in gen_custom_models_static
    deps_map = resolve_deps(compiled.deps, model.path)
  File "/Users/bryan/work/bokeh/bokeh/util/compiler.py", line 367, in resolve_deps
    return resolve_modules(missing, root)
  File "/Users/bryan/work/bokeh/bokeh/util/compiler.py", line 360, in resolve_modules
    raise RuntimeError("no such module: %s" % module)
RuntimeError: no such module: core/util/callback

Exception occurred:
  File "/Users/bryan/work/bokeh/bokeh/util/compiler.py", line 360, in resolve_modules
    raise RuntimeError("no such module: %s" % module)
RuntimeError: no such module: core/util/callback
```

**Comment by bryevdv** [comment]
This problem seems to have gone away of its own accord at some point. Closing for now.
