### ISSUE TITLE
UnicodeDecodeError when non-ascii characters are present at document's title

### ISSUE THREAD

**Issue by fraserpal** [bokeh/bokeh#5843]
Hi! when deploying an script with Bokeh Server the following error happens:
```
PS C:\Users\407334\pad-s100> bokeh serve plot5.py
2017-02-03 12:45:08,223 Starting Bokeh server version 0.12.4
2017-02-03 12:45:15,502 Starting Bokeh server on port 5006 with applications at paths ['/plot5']
2017-02-03 12:45:15,503 Starting Bokeh server with process id: 8020
2017-02-03 12:45:42,720 Uncaught exception GET /plot5 (::1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/plot5', version='HTTP/1.1', remote_ip='::1
', headers={'Accept-Language': 'es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'Host': 'local
host:5006', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Win
dows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'If
-None-Match': '"504521635d297c857659d8dfa9d1e954279f82a8"', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\lib\site-packages\tornado\web.py", line 1469, in _execute
    result = yield result
  File "C:\Program Files\Anaconda2\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Program Files\Anaconda2\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "C:\Program Files\Anaconda2\lib\site-packages\tornado\gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "C:\Program Files\Anaconda2\lib\site-packages\bokeh\server\views\doc_handler.py", line 34, in get
    template_variables=session.document.template_variables)
  File "C:\Program Files\Anaconda2\lib\site-packages\bokeh\embed.py", line 634, in server_html_page_for_session
    websocket_url=websocket_url, template_variables=template_variables)
  File "C:\Program Files\Anaconda2\lib\site-packages\bokeh\embed.py", line 481, in _html_page_for_render_items
    html = template.render(template_variables_full)
  File "C:\Program Files\Anaconda2\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Program Files\Anaconda2\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Anaconda2\lib\site-packages\bokeh\core\_templates\file.html", line 41, in top-level template co
de
    {{ plot_script|indent(8) }}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 30: ordinal not in range(128)
2017-02-03 12:45:42,780 500 GET /plot5 (::1) 24564.00ms
2017-02-03 12:49:13,460 404 GET /plot4 (::1) 0.00ms
```
I do not know if this is a bug.  What I do to solve it is just to only use ASCII characters in the title:
```
# No error arises
curdoc().title = "Serie-100: Monitorizacion Bloque-Motor"
# Error arises
curdoc().title = "Serie-100: Monitorización Bloque-Motor"
```

**Comment by bryevdv** [comment]
This error is actually coming from Jinja, not Bokeh. Does anyone know if there are special measures needed to include unicode characters in Jinja templates? @bokeh/dev

**Comment by birdsarah** [comment]
Does this help? http://jinja.pocoo.org/docs/dev/api/#unicode

**Comment by kdheepak** [comment]
@fraserpal Can you try the following and see if it works?

```python
curdoc().title = u"Serie-100: Monitorización Bloque-Motor"
```

**Comment by bryevdv** [comment]
ping @fraserpal is this on python 2 or 3? Can you try explicitly specifying a unicode string as @kdheepak suggested?

**Comment by bryevdv** [comment]
@fraserpal can you provide any of the additional info requested?

**Comment by fraserpal** [comment]
Hi Bryan! I cannot give additional info since I have not worked in the
issue any more. Sorry!

2017-06-09 0:22 GMT+02:00 Bryan Van de Ven <notifications@github.com>:

**Comment by kdheepak** [comment]
@bryevdv If it helps, it seems to be Python 2 from the traceback and I tried explicitly specifying a unicode string and it worked when I posted that comment.

**Comment by bryevdv** [comment]
Yes this was a usage error all along. In python 2, unicode strings need to be made explicitly as @kdheepak suggested (things work fine in that case)
