### ISSUE TITLE
When building docs, `make clean all` fails

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#5949]
```
# Sphinx version: 1.5.2
# Python version: 3.5.3 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.5
# Last messages:
#   copying bokeh-plot files... [ 95%] bokeh-plot-f8b4b7f438d656782dafcac3d395149d.js
#   copying bokeh-plot files... [ 96%] bokeh-plot-fa138cfbd93d5d9b3cb8698afabc04cb.js
#   copying bokeh-plot files... [ 96%] bokeh-plot-fa2156d0bf67a2299cc88a41f85c175e.js
#   copying bokeh-plot files... [ 97%] bokeh-plot-fa243db8565c61a322329ebaeec8f7c3.js
#   copying bokeh-plot files... [ 97%] bokeh-plot-fbef5a55095a57bd7ec69880b9e491c1.js
#   copying bokeh-plot files... [ 98%] bokeh-plot-fbffcff58bf2df95017e1a6470add3f2.js
#   copying bokeh-plot files... [ 98%] bokeh-plot-fc686a29565cec5272ecc418812f2401.js
#   copying bokeh-plot files... [ 99%] bokeh-plot-ff7d4e4a58f23d8a18428273c04d26ea.js
#   copying bokeh-plot files... [100%] bokeh-plot-ff7edabe052448ba50e8fd7ac647ccaa.js
#   
# Loaded extensions:
#   bokeh.sphinxext.bokeh_jinja (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/bokeh_jinja.py
#   bokeh.sphinxext.bokeh_palette (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/bokeh_palette.py
#   bokeh.sphinxext.bokeh_autodoc (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/bokeh_autodoc.py
#   sphinx.ext.napoleon (1.5.2) from /Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.autosummary (1.5.2) from /Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/ext/autosummary/__init__.py
#   bokeh.sphinxext.bokeh_prop (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/bokeh_prop.py
#   bokeh.sphinxext.collapsible_code_block (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/collapsible_code_block.py
#   bokeh.sphinxext.bokeh_model (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/bokeh_model.py
#   bokeh.sphinxext.bokeh_index_toctree (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/bokeh_index_toctree.py
#   bokeh.sphinxext.bokeh_enum (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/bokeh_enum.py
#   sphinx.ext.intersphinx (1.5.2) from /Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (1.5.2) from /Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/ext/viewcode.py
#   bokeh.sphinxext.bokeh_github (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/bokeh_github.py
#   alabaster (0.7.9) from /Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/alabaster/__init__.py
#   bokeh.sphinxext.bokeh_palette_group (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/bokeh_palette_group.py
#   sphinx.ext.autodoc (1.5.2) from /Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/ext/autodoc.py
#   bokeh.sphinxext.bokeh_plot (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/bokeh_plot.py
#   bokeh.sphinxext.bokeh_sitemap (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/bokeh_sitemap.py
#   bokeh.sphinxext.bokeh_gallery (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/bokeh_gallery.py
#   sphinx.ext.ifconfig (1.5.2) from /Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/ext/ifconfig.py
#   bokeh.sphinxext.bokeh_options (unknown version) from /Users/jsignell/GitHub/ContinuumIO/bokeh/bokeh/sphinxext/bokeh_options.py
Traceback (most recent call last):
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 556, in update
    self._read_serial(docnames, app)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 576, in _read_serial
    self.read_doc(docname, app)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 684, in read_doc
    pub.publish()
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/io.py", line 55, in read
    self.parse()
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2320, in explicit_markup
    self.explicit_list(blank_finish)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2350, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 318, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2623, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 1659, in run
    documenter.generate(more_content=self.content)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 1004, in generate
    self.document_members(all_members)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 926, in document_members
    check_module=members_check_module and not isattr)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 1004, in generate
    self.document_members(all_members)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 885, in document_members
    members_check_module, members = self.get_object_members(want_all)
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 780, in get_object_members
    if isenumclass(self.object):
  File "/Users/jsignell/conda/envs/bokeh-dev/lib/python3.5/site-packages/sphinx/util/inspect.py", line 107, in isenumclass
    return issubclass(x, enum.Enum)
TypeError: issubclass() arg 1 must be a class

**Comment by bryevdv** [comment]
FWIW I can't repro this with python 3.6 and Sphinx 1.5.1

**Comment by timsnyder** [comment]
Hey @jsignell!   Are you still running into this or did you get past it?   Are you using a conda environment for your development?  If so, could you attach the output of `conda env export`?

**Comment by jsignell** [comment]
@timsnyder I just fell back to sphinx 1.5.1 and was able to build the docs using `make clean html`

**Comment by bryevdv** [comment]
I can repro this after updating to sphinx 1.5.4

**Comment by bryevdv** [comment]
This appears to be because Sphinx added support for Python enumerations, and is confusing our project `enum` objects for python enums to document I'd say this is a bug in Sphinx and that their `isenumclass` functions are improperly assuming that the things to test are always classes.

**Comment by bryevdv** [comment]
PR submitted to sphinx: https://github.com/sphinx-doc/sphinx/pull/3732

**Comment by bryevdv** [comment]
I'm going to close this as upstream. If I head back about a workaround for existing versions of sphinx, I will re-open. Or if our CI starts failing. Currently CI uses a working version of sphinx

**Comment by bryevdv** [comment]
Noting that the fix PR has been merged upstream, so the solution will eventually be use Sphinx > 1.5.4 (I never heard back about a workaround)
