### ISSUE TITLE
mpl_plot.py example not working

### ISSUE THREAD

**Issue by tommycarstensen** [bokeh/bokeh#6026]
I just ran this example:
https://github.com/bokeh/bokeh/blob/0.12.4/examples/compat/mpl_plot.py

With Python3.6, Bokeh0.12.4 and latest pip install of matplotlib. I got the traceback below:

```
Traceback (most recent call last):
  File "mpl_plot.py", line 19, in <module>
    show(mpl.to_bokeh())
  File "/Users/tc9/lib/python3.6/site-packages/bokeh/core/compat/mpl.py", line 57, in to_bokeh
    exporter.run(fig)
  File "/Users/tc9/lib/python3.6/site-packages/bokeh/core/compat/mplexporter/exporter.py", line 51, in run
    self.crawl_fig(fig)
  File "/Users/tc9/lib/python3.6/site-packages/bokeh/core/compat/mplexporter/exporter.py", line 118, in crawl_fig
    self.crawl_ax(ax)
  File "/Users/tc9/lib/python3.6/site-packages/bokeh/core/compat/mplexporter/exporter.py", line 125, in crawl_ax
    self.draw_line(ax, line)
  File "/Users/tc9/lib/python3.6/site-packages/bokeh/core/compat/mplexporter/exporter.py", line 198, in draw_line
    mplobj=line)
  File "/Users/tc9/lib/python3.6/site-packages/bokeh/core/compat/mplexporter/renderers/base.py", line 155, in draw_marked_line
    self.draw_line(data, coordinates, linestyle, label, mplobj)
  File "/Users/tc9/lib/python3.6/site-packages/bokeh/core/compat/bokeh_renderer.py", line 201, in draw_line
    line.line_dash = [] if style['dasharray'] is "none" else [int(i) for i in style['dasharray'].split(",")]  # str2list(int)
  File "/Users/tc9/lib/python3.6/site-packages/bokeh/core/compat/bokeh_renderer.py", line 201, in <listcomp>
    line.line_dash = [] if style['dasharray'] is "none" else [int(i) for i in style['dasharray'].split(",")]  # str2list(int)
ValueError: invalid literal for int() with base 10: '9.6'
```

**Comment by bryevdv** [comment]
@tommycarstensen unfortunately we have had to admit that we do not have the resources or the capability as a team to maintain MPL compat. It is being deprecated entirely with the `0.12.5` release this week. I hope in the future if there is a well-defined JSON protocol for MPL then this capability can be restored in a separate community maintained project.
