### ISSUE TITLE
JS client tests failing

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6151]
Failing on multiple previously passing builds. 

Possibly an updated dependency, not certain yet.  

```
12:32
1) Client should be able to connect:
   Error: Server exited before test promise was resolved
    at ChildProcess.<anonymous> (test/client.coffee:60:20)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

2) Client should pass request string to connection:
   Error: Server exited before test promise was resolved
    at ChildProcess.<anonymous> (test/client.coffee:60:20)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

3) Client should be able to connect:
   Error: Server exited before test promise was resolved
    at ChildProcess.<anonymous> (test/client.coffee:60:20)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

4) Client should get server info:
   Error: Server exited before test promise was resolved
    at ChildProcess.<anonymous> (test/client.coffee:60:20)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

5) Client should sync a document between two connections:
   Error: Server exited before test promise was resolved
    at ChildProcess.<anonymous> (test/client.coffee:60:20)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

**Comment by canavandl** [comment]
* doesn't appear to be a npm-only dep issue

**Comment by bryevdv** [comment]
It was failing for me locally with 4.4.2 maybe I had that upgraded without realizing?

**Comment by bryevdv** [comment]
Though, passing CI jobs have 4.4.2 maybe some local issue on my machine

**Comment by canavandl** [comment]
Based on local testing, it appears it's a tornado + Python 3.5 issue.

Tornado 4.4.2 (the same as the Travis builds) gives the above errors.
Tornado 4.5 gives the JS errors:

<img width="691" alt="screen shot 2017-04-17 at 4 18 54 pm" src="https://cloud.githubusercontent.com/assets/2198981/25101188/a139a9a4-2389-11e7-99d4-860b2564eb9e.png">

**Comment by canavandl** [comment]
so it appears that a bokeh server process isn't resolving any requests. Running 'bokeh serve' then curling `http://localhost:5006/` just hangs.

**Comment by canavandl** [comment]
`bokeh/command/subcommands/test/test/test_serve.test_actual_port_printed_out` fails due to a timeout.

**Comment by canavandl** [comment]
the gulp tests spawn and orphan a bunch of bokeh server processes:

<img width="732" alt="screen shot 2017-04-17 at 4 30 12 pm" src="https://cloud.githubusercontent.com/assets/2198981/25101580/388e14d8-238b-11e7-9b95-5105ea96c5df.png">

why are they are non-standard ports?

**Comment by bryevdv** [comment]
I don't recall, @havocp might remember more

**Comment by havocp** [comment]
I usually try to make ports dynamic so the tests don't fail because a port is in use and tests can run in parallel, but I don't remember specific details about the gulp tests.

**Comment by canavandl** [comment]
The tests are failing due to #6152

**Comment by bryevdv** [comment]
closing as a dupe of #6152
