### ISSUE TITLE
Bokeh scatter based on pandas dataframe - Works on python 3, Crashes on python 2.7

### ISSUE THREAD

**Issue by shepp-hub** [bokeh/bokeh#6218]
Bokeh crashed on me when I tried forming a scatter plot from a pandas dataframe,
[In the stackoverflow question I opened](http://stackoverflow.com/questions/43698677/bokeh-crashes-when-plotting-dataframe-to-scatter) I've been notified the exact same code works under python 3, I tried it and it did.

I'm using Ubuntu 16.04, Bokeh 0.12.5, Python 2.7.12 (on which it crashed) and Python 3.5.2 (on which it worked perfectly).

[Here's the serialized pandas dataframe](http://termbin.com/s7sq)
Here's the code:
```
from bokeh.charts import Scatter, output_file,show 
import json
from pandas import DataFrame
df=DataFrame.from_dict(json.load(open('out.json')))
p=Scatter(df)
output_file('scatter_test.html')
show(p)
```
Instead of a scatter plot it crashes with the following traceback:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    p=Scatter(df)
  File "/home/guy/.local/lib/python2.7/site-packages/bokeh/charts/builders/scatter_builder.py", line 65, in Scatter
    return create_and_build(ScatterBuilder, data, **kws)
  File "/home/guy/.local/lib/python2.7/site-packages/bokeh/charts/builder.py", line 56, in create_and_build
    chart.add_builder(builder)
  File "/home/guy/.local/lib/python2.7/site-packages/bokeh/charts/chart.py", line 153, in add_builder
    builder.create(self)
  File "/home/guy/.local/lib/python2.7/site-packages/bokeh/charts/builder.py", line 512, in create
    chart.add_renderers(self, renderers)
  File "/home/guy/.local/lib/python2.7/site-packages/bokeh/charts/chart.py", line 148, in add_renderers
    self.renderers += renderers
  File "/home/guy/.local/lib/python2.7/site-packages/bokeh/core/property/containers.py", line 76, in wrapper
    result = func(self, *args, **kwargs)
  File "/home/guy/.local/lib/python2.7/site-packages/bokeh/core/property/containers.py", line 172, in __iadd__
    return super(PropertyValueList, self).__iadd__(y)
  File "/home/guy/.local/lib/python2.7/site-packages/bokeh/charts/builders/scatter_builder.py", line 95, in yield_renderers
    marker=group['marker'])
  File "/home/guy/.local/lib/python2.7/site-packages/bokeh/charts/glyphs.py", line 130, in __init__
    super(PointGlyph, self).__init__(**kwargs)
  File "/home/guy/.local/lib/python2.7/site-packages/bokeh/charts/models.py", line 84, in __init__
    self.setup()
  File "/home/guy/.local/lib/python2.7/site-packages/bokeh/charts/models.py", line 90, in setup
    self.refresh()
  File "/home/guy/.local/lib/python2.7/site-packages/bokeh/charts/models.py", line 99, in refresh
    data = self.build_source()
  File "/home/guy/.local/lib/python2.7/site-packages/bokeh/charts/glyphs.py", line 57, in build_source
    str_labels = [str(label) for label in labels]
TypeError: 'NoneType' object is not iterable
```
The python 3 version works just fine.

**Comment by shepp-hub** [comment]
Also, If there's a way to sidestep this issue and make it run on python 2.7 I'd love to know. I use bokeh in a large python2 project and I don't feel like looking for a different plotting library right now just to get around it.

**Comment by bryevdv** [comment]
First, `bokeh.charts` is being moved to a separate repo for community maintenance. Please log all `bokeh.charts` against https://github.com/bokeh/bkcharts in the future, and not this repo (I am closing this issue here, accordingly)

This code works for me:

```
from bokeh.charts import Scatter, output_file,show
import json
from pandas import DataFrame
df=DataFrame.from_dict(json.load(open('out.json')))
p=Scatter(df,
    x="Fraction of deaths caused by G20: Parkinson disease",
    y="Fraction of deaths caused by I64: Stroke")
output_file('scatter_test.html')
show(p)
```

I am not sure if this is intentional or not. All the examples demonstrate supplying `x` and `y` as I have done above. I am not sure if your code (without them) is expected or intended to work. 

Finally, for a scatter this simple I would suggesting using the `bokeh.plotting` API instead of `bokeh.charts` it is older, more stable, and better maintained.
