### ISSUE TITLE
Server Embed Examples Do Not Work

### ISSUE THREAD

**Issue by covelloz** [bokeh/bokeh#6293]
Pretty sure the code in the server embed examples are broken.
Let me know if you have the same issue.
Particularly the flask_embed.py and tornado_embed.py.

>$python
>Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
>[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
quit()
>$ git clone https://github.com/bokeh/bokeh.git
>$ cd bokeh/examples/howto/server_embed/
>$ python flask_embed.py

**output:**
```
Opening Flask app with embedded Bokeh application on http://localhost:8080/
Created new window in existing browser session.
[2017-05-15 22:12:36,429] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/xdzzz/Software/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xdzzz/Software/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xdzzz/Software/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/xdzzz/Software/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/xdzzz/Software/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xdzzz/Software/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask_embed.py", line 64, in bkapp_page
    script = autoload_server(url='http://localhost:5006/bkapp')
TypeError: autoload_server() missing 1 required positional argument: 'model'
ERROR:tornado.access:500 GET / (::1) 9.28m
```s

**Comment by bryevdv** [comment]
They aren't broken, but they are updated and newer in master than the latest release. The disused parameter models was removed after the last release. You can 

* run bokeh off master / dev builds, or
* run examples corresponding to the actual version you have installed
