### ISSUE TITLE
Dropdown widget cannot append to children layout in jupyter notebook (Firefox not Chrome)

### ISSUE THREAD

**Issue by nicain** [bokeh/bokeh#6468]
https://gist.github.com/nicain/bb7f16ee7b8d1e479e39f6bac3bcd423

bokeh (0.12.6)
tornado (4.5.1)
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
notebook (5.0.0)
firefox (52.0 64-bit)

This code should append  button widgets to the bottom of a layout, with either a Dropdown menu or just a regular button.  This works as a bokeh server, but when embedded in a jupyter notebook, the dropdown menu button fails to append any new buttons below it.

<del>There is not output to the console or the std out as well. </del>

After about a minute, the following Error traceback output appeared in the cell:
```
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7f8e11d22838>
Traceback (most recent call last):
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 604, in _run_callback
    ret = callback()
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 619, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/tornado.py", line 343, in cleanup_sessions
    yield app.cleanup_sessions(self._unused_session_linger_milliseconds)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/application_context.py", line 253, in cleanup_sessions
    yield self._discard_session(session, should_discard_ignoring_block)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/application_context.py", line 226, in _discard_session
    yield session.with_document_locked(do_discard)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/session.py", line 48, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/session.py", line 151, in with_document_locked
    return func(*args, **kwargs)
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/application_context.py", line 221, in do_discard
    session.destroy()
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/session.py", line 116, in destroy
    self._document.remove_on_change(self)
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/document.py", line 601, in remove_on_change
    del self._callbacks[callback]
KeyError: <bokeh.server.session.ServerSession object at 0x7f8e11db3d10>
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7f8e11cc0208>
Traceback (most recent call last):
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 604, in _run_callback
    ret = callback()
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 619, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/tornado.py", line 343, in cleanup_sessions
    yield app.cleanup_sessions(self._unused_session_linger_milliseconds)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/application_context.py", line 253, in cleanup_sessions
    yield self._discard_session(session, should_discard_ignoring_block)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/application_context.py", line 226, in _discard_session
    yield session.with_document_locked(do_discard)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/local1/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/session.py", line 48, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/session.py", line 151, in with_document_locked
    return func(*args, **kwargs)
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/application_context.py", line 221, in do_discard
    session.destroy()
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/server/session.py", line 116, in destroy
    self._document.remove_on_change(self)
  File "/local1/anaconda2/lib/python2.7/site-packages/bokeh/document.py", line 601, in remove_on_change
    del self._callbacks[callback]
KeyError: <bokeh.server.session.ServerSession object at 0x7f8e11db3d10>
```

**Comment by nicain** [comment]
Probably unrelated, but on another application I am working on, I occasionally see the following in the console (Firefox Developer Edition) when trying to use the dropdown widget:

ReferenceError: event is not defined[Learn More]  bokeh-widgets.min.js:2:2848
	["models/widgets/dropdown"]</i.DropdownView</t.prototype.render/</<

**Comment by nicain** [comment]
Just confirmed that this is not an issue with Chrome 58, but remains an issue on Firefox 54.0

**Comment by mattpap** [comment]
> `ReferenceError: event is not defined`

This is a regression introduced in 0.12.6.

**Comment by bryevdv** [comment]
This is working with dropdown with recent FF and `0.12.10` dev 

<img width="777" alt="screen shot 2017-10-13 at 19 13 33" src="https://user-images.githubusercontent.com/1078448/31570571-bd01d500-b04a-11e7-926e-54f974c0346b.png">
