### ISSUE TITLE
Tile Sources cannot be shared between app sessions

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#6590]
Bokeh: 0.12.4+
Datashader: 0.4.0+
Browser: Firefox

Running a bokeh server using datashader and streaming (using a periodic callback) works as expected with Safari and Chrome on OS X 10.12.5 but does not work on Firefox. On Firefox the first image loads but then there are no updates. Firefox shows the following error in the console.

```
TypeError: invalid arguments bokeh.min.js:27:12591
	Bokeh</<["models/glyphs/image_rgba"]</r.ImageRGBAView</e.prototype._set_data http://localhost:5006/static/js/bokeh.min.js:27:12591
	Bokeh</<["models/glyphs/glyph"]</r.GlyphView</r.prototype.set_data http://localhost:5006/static/js/bokeh.min.js:27:2575
	Bokeh</<["models/renderers/glyph_renderer"]</r.GlyphRendererView</e.prototype.set_data http://localhost:5006/static/js/bokeh.min.js:31:27491
	Bokeh</<["models/renderers/glyph_renderer"]</r.GlyphRendererView</e.prototype.connect_signals/< http://localhost:5006/static/js/bokeh.min.js:31:26642
	Bokeh</<["core/signaling"]</u</t.prototype.emit http://localhost:5006/static/js/bokeh.min.js:2:26078
	Bokeh</<["models/sources/column_data_source"]</r.ColumnDataSource</e.prototype.stream http://localhost:5006/static/js/bokeh.min.js:32:13704
	Bokeh</<.document</r.Document</t.prototype.apply_json_patch http://localhost:5006/static/js/bokeh.min.js:22:20953
	Bokeh</<.client</i</t.prototype._handle_patch http://localhost:5006/static/js/bokeh.min.js:1:10794
	PATCH-DOC/< http://localhost:5006/static/js/bokeh.min.js:1:2839
	Bokeh</<.client</o</t.prototype._for_session http://localhost:5006/static/js/bokeh.min.js:1:3716
	PATCH-DOC http://localhost:5006/static/js/bokeh.min.js:1:2805
	Bokeh</<.client</o</t.prototype._steady_state_handler http://localhost:5006/static/js/bokeh.min.js:1:9603
	Bokeh</<.client</o</t.prototype._awaiting_ack_handler/this._current_handler</< http://localhost:5006/static/js/bokeh.min.js:1:9262
	Bokeh</<.client</o</t.prototype._on_message_unchecked http://localhost:5006/static/js/bokeh.min.js:1:8228
	Bokeh</<.client</o</t.prototype._on_message http://localhost:5006/static/js/bokeh.min.js:1:7440
	Bokeh</<.client</o</t.prototype.connect/</</t.socket.onmessage http://localhost:5006/static/js/bokeh.min.js:1:446
```
 No error is shown in the terminal.

[Firefox Stream Error.zip](https://github.com/bokeh/bokeh/files/1129670/Firefox.Stream.Error.zip)

**Comment by bryevdv** [comment]
@hsparra is this still an issue?

**Comment by hsparra** [comment]
@bryevdv, the plot still does not update in Chrome. The JS console shows the following

```
Uncaught TypeError: Cannot read property 'handle' of null
    at t.r.ClientConnection.t._steady_state_handler (connection.js:286)
    at t._current_handler (connection.js:267)
    at t.r.ClientConnection.t._on_message (connection.js:222)
    at WebSocket.t.socket.onmessage (connection.js:63)
```

The little timer below the plot is updating.

**Comment by bryevdv** [comment]
@hsparra did you open FF second,  after another browser? If I make sure its the first browser, it works. Otherwise, I see this in the shell console:
```
2017-10-13 15:51:51,533 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x11341a160>: Models must be owned by only a single document, WMTSTileSource(id='95176d77-9eae-4b0a-960b-7cd9763a146a', ...) is already in a doc
File "model.py", line 553, in _attach_document:
raise RuntimeError("Models must be owned by only a single document, %r is already in a doc" % (self)) Traceback (most recent call last):
  File "/Users/bryan/work/bokeh/bokeh/application/handlers/code_runner.py", line 125, in run
    exec(self._code, module.__dict__)
  File "/Users/bryan/Desktop/taxi-stream_copy.py", line 126, in <module>
    curdoc().add_root(layout)
  File "/Users/bryan/work/bokeh/bokeh/document/document.py", line 243, in add_root
    self._pop_all_models_freeze()
  File "/Users/bryan/work/bokeh/bokeh/document/document.py", line 923, in _pop_all_models_freeze
    self._recompute_all_models()
  File "/Users/bryan/work/bokeh/bokeh/document/document.py", line 946, in _recompute_all_models
    a._attach_document(self)
  File "/Users/bryan/work/bokeh/bokeh/model.py", line 553, in _attach_document
    raise RuntimeError("Models must be owned by only a single document, %r is already in a doc" % (self))
RuntimeError: Models must be owned by only a single document, WMTSTileSource(id='95176d77-9eae-4b0a-960b-7cd9763a146a', ...) is already in a doc
```

The problem is that the built in tile sources always return the *same object*, which is problematic. You cannot reuse the actual same object across sessions. So we probably need to make some way to return new copies instead of just having fixed objects in `tile_providers.py` 

As a workaround, you can just make new tile sources yourself. I.e. copy and paste the code from `tile_providers.py` to create *new, different* tile sources the can be used by each session.

**Comment by jbednar** [comment]
This has bitten me too.  Should we consider removing the built-in tile sources, i.e. force people to instantiate them before use?

**Comment by hsparra** [comment]
I still get this error in FF.
```

**Comment by hsparra** [comment]
Safari JS console does show two errors:
```

**Comment by bryevdv** [comment]
@hsparra it’s working for me in FF if I make sure it’s the very first browser to open the app 

@jbednar I’d prefer to make the effort to implement the class as module pattern  and have properties that return new copies every time

**Comment by bryevdv** [comment]
@hsparra or put another way: an app that uses built on tile sources only works *once* (in any browser)

**Comment by bryevdv** [comment]
@hsparra I'm not sure. I ran the code and it worked as is in both Safari and FF (after restarting to deal with tile issue)

**Comment by bryevdv** [comment]
At this point I'd say let's leave this issue for the tile object problem and you can open a new issue after you take a new look at the code.
