### ISSUE TITLE
ImportError: cannot import name 'export_png'

### ISSUE THREAD

**Issue by lhaeberle** [bokeh/bokeh#6664]
Trying to export Bokeh plots to *png with Bokeh version 0.12.6 and CentOS Linux release 7.3.1611 (Core)leads to

```
Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x7f931868aef0>: cannot import name 'export_png'
File "sensor_t.py", line 370, in <module>:
from bokeh.io import export_png Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 81, in run
    exec(self._code, module.__dict__)
  File "/home/wwwAppRunner/test_dir/sensor_t.py", line 370, in <module>
    from bokeh.io import export_png
ImportError: cannot import name 'export_png'
```
The code slice around line 370 looks like this:

```
360 # show all the stuff above
361 curdoc().add_root(headline)
362 curdoc().add_root(gp)
363 curdoc().title = 'Sensor°°°'  # browser tap title
364 
365 # Add a periodic callback to be run every 500 milliseconds
366 curdoc().add_periodic_callback(update, 500)
367 
368 ######### start TEST EXPORT IMAGE ###################
369  
370 from bokeh.io import export_png
371 from bokeh.document import without_document_lock
372 
373 @without_document_lock
374 def make_image():
375     try:
376         print('trying...')
377         export_png(gp, filename='image.png')
378 
379     except Exception as e:
380         print('image print failed... ', e)
381 
382 
383 # add a periodic callback to create a png image
384 curdoc().add_periodic_callback(make_image, 5000)
```
Any idea which dependencies I probably miss?

**Comment by bryevdv** [comment]
This is not a missing dependency, `export_png` is part of Bokeh itself, as can be seen by examining the `0.12.6` release tag:

https://github.com/bokeh/bokeh/blob/0.12.6/bokeh/io.py#L643

The error you are getting is saying that `export_png` cannot be imported from `bokeh.io` which can only mean that you either have installation/packaged corruption of some sort, or that you are actually importing from an older version of Bokeh without realizing it (maybe conda env or virtualenv mixup)
