### ISSUE TITLE
cant draw histogram from pandas dataframe

### ISSUE THREAD

**Issue by ajanaliz** [bokeh/bokeh#6989]
I wrote the following function that takes in an numpy 2-d matrix + a list of indexes that have to be drawn.

```def draw(matrix, indices):
    from bokeh.charts import Histogram, output_file, show
    from bokeh.layouts import row
    import pandas as pd
    import numpy as np

    mat = matrix[indices, :]
    mat = np.transpose(mat)
    mat = np.array(mat,np.string_)
    df = pd.DataFrame(mat)

    hist = Histogram(df, values='mpg', label='cyl', color='cyl', legend='top_right',
                     title="MPG Histogram by Cylinder Count", plot_width=400)
    output_file('hist.html')
    show(hist)
```

when i run this code:
```
matrix = np.load("asd.npy")
index = [4, 5, 12]

draw(matrix=matrix, indices=index)

```
this is the error i get:
```Traceback (most recent call last):
  File "C:/Users/J/PycharmProjects/stockprediction/bokehtest.py", line 27, in <module>
    draw(matrix=matrix, indices=index)
  File "C:/Users/J/PycharmProjects/stockprediction/bokehtest.py", line 19, in draw
    title="MPG Histogram by Cylinder Count", plot_width=400)
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\charts\builders\histogram_builder.py", line 107, in Histogram
    return create_and_build(HistogramBuilder, data, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\charts\builder.py", line 51, in create_and_build
    builder = builder_class(*data, **builder_kws)
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\charts\builder.py", line 272, in __init__
    attributes = self._setup_attrs(data, kws)
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\charts\builder.py", line 304, in _setup_attrs
    source = ColumnDataSource(data.df)
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\models\sources.py", line 109, in __init__
    self.column_names[:] = list(raw_data.keys())
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\core\property\containers.py", line 77, in wrapper
    self._notify_owners(old)
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\core\property\containers.py", line 104, in _notify_owners
    prop._notify_mutated(owner, old, hint)
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\core\property\descriptors.py", line 810, in _notify_mutated
    value = self.property.prepare_value(obj, self.name, value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\core\property\bases.py", line 265, in prepare_value
    raise e
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\core\property\bases.py", line 258, in prepare_value
    self.validate(value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\core\properties.py", line 1171, in validate
    raise ValueError("expected an element of %s, got seq with invalid items %r" % (self, invalid))
ValueError: expected an element of List(String), got seq with invalid items [0, 1, 2]```

**Comment by ajanaliz** [comment]
I printed the df in the draw function and this is the output:
```0          0.0  0.0  0.0
1          0.0  0.0  0.0
2          0.0  0.0  0.0
3          0.0  0.0  0.0
4          0.0  0.0  0.0
5          0.0  0.0  0.0
6          0.0  0.0  0.0
7          0.0  0.0  0.0
8          0.0  0.0  0.0
9          0.0  0.0  0.0
10         0.0  0.0  0.0
11         0.0  0.0  0.0
12         0.0  0.0  0.0
13         0.0  0.0  0.0
14         0.0  0.0  0.0
15         0.0  0.0  0.0
16         0.0  0.0  0.0
17         0.0  0.0  0.0
18         0.0  0.0  0.0
19         0.0  0.0  0.0
20         0.0  0.0  0.0
21         0.0  0.0  0.0
22         0.0  0.0  0.0
23         0.0  0.0  0.0
24         0.0  0.0  0.0
25         0.0  0.0  0.0
26         0.0  0.0  0.0
27         0.0  0.0  0.0
28         0.0  0.0  0.0
29         0.0  0.0  0.0
..         ...  ...  ...
218        0.0  0.0  0.0
219        0.0  0.0  0.0
220        0.0  0.0  0.0
221        0.0  0.0  0.0
222        0.0  0.0  0.0
223        0.0  0.0  0.0
224        0.0  0.0  0.0
225        0.0  0.0  0.0
226        0.0  0.0  0.0
227        0.0  0.0  0.0
228  1776388.0  0.0  0.0
229        0.0  0.0  0.0
230        0.0  0.0  0.0
231        0.0  0.0  0.0
232        0.0  0.0  0.0
233        0.0  0.0  0.0
234        0.0  0.0  0.0
235        0.0  0.0  0.0
236        0.0  0.0  0.0
237        0.0  0.0  0.0
238        0.0  0.0  0.0
239        0.0  0.0  0.0
240        0.0  0.0  0.0
241  1776388.0  0.0  0.0
242        0.0  0.0  0.0
243        0.0  0.0  0.0
244        0.0  0.0  0.0
245        0.0  0.0  0.0
246        0.0  0.0  0.0
247        0.0  0.0  0.0

[248 rows x 3 columns]```

**Comment by ajanaliz** [comment]
it is a very sparce matrix

**Comment by bryevdv** [comment]
The old `bokeh.charts` (including `Histogram`) have been moved to a separate project [`bkcharts`](https://github.com/bokeh/bkcharts). You could file this issue there, but please know that `bkcharts` is ***currently unmaintained***, so it is unlikely any response will occur. You can look to HoloViews for a very high level API built to on Bokeh that is actively maintained, or use the `bokeh.plotting` API

Any follow on support questions should go to the mailing list as described in the issue tracker:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by bryevdv** [comment]
The old `bokeh.charts` (including `Histogram`) have been moved to a separate project [`bkcharts`](https://github.com/bokeh/bkcharts). You could file this issue there, but please know that `bkcharts` is ***currently unmaintained***, so it is unlikely any response will occur. You can look to HoloViews for a very high level API built to on Bokeh that is actively maintained, or use the `bokeh.plotting` API

Any follow on support questions should go to the mailing list as described in the issue tracker:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
