### ISSUE TITLE
Zooming performance regression in 0.12.11rc

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#7255]
I was just playing around with the bokeh 0.12.11rc2 release and noticed a pretty large performance regression when zooming on a number of linked plots when compared to bokeh 0.12.10.

You can see a comparison of the same grid plot generated using bokeh 0.12.10 and 0.12.11rc2 here:

[0.12.10](http://assets.holoviews.org/tmp/test_0.12.10.html)

[0.12.11rc2](http://assets.holoviews.org/tmp/test_0.12.11rc2.html)

The 0.12.11rc2 version will appear to do nothing for a while, but eventually it does zoom with a lot of stutter.

**Comment by bryevdv** [comment]
please try rc3, I can't recall what PRs are newer than rc2

cc @mattpap

**Comment by bryevdv** [comment]
As a point of comparison, `models/file/iris_splom.py` is acceptably responsive on master/rc3

**Comment by philippjfr** [comment]
I just tried it, still seeing the same issue unfortunately, here is the profiling output when I trigger a plot reset:

0.12.10 (executes in about 150ms):

<img width="1061" alt="screen shot 2017-11-27 at 6 19 09 pm" src="https://user-images.githubusercontent.com/1550771/33282117-8e1604c8-d39f-11e7-955c-2dffcd8deb4f.png">

0.12.11rc3 (executes in about 7 seconds):

<img width="1219" alt="screen shot 2017-11-27 at 6 16 49 pm" src="https://user-images.githubusercontent.com/1550771/33282161-acbb3916-d39f-11e7-9b82-51d62931358f.png">

**Comment by mattpap** [comment]
I suspect this is an effect of PR #7197. Instead of rendering affected plots or at most all plots, all plots are rendered for each plot (combinatorial explosion).

**Comment by bryevdv** [comment]
what happens for you with `iris_splom.py`? It is also a 4x4 grid

**Comment by philippjfr** [comment]
I can confirm that Iris_splom also seems reasonably responsive with bokeh 0.12.11rc3. It does seem a bit slower, but I could just be imagining that. Perhaps those points are just very quick to redraw, even if it happens a bunch of times and the combination of point, multi_line and quad glyphs in my example is just much slower? Simply guessing here though.

**Comment by bryevdv** [comment]
@mattpap I think we should make an effort to improve this for `0.12.11` do you agree?

**Comment by mattpap** [comment]
@bryevdv, definitively. I'm working on this.

**Comment by mattpap** [comment]
@philippjfr, can you share the source code? I would make it easier for me to work on this.

**Comment by philippjfr** [comment]
It's built using HoloViews, you'd have to install holoviews 1.9.x using ``conda install -c conda-forge holoviews`` and then to reproduce the plot you can run:

```python
from bokeh.sampledata.iris import flowers
from holoviews.operation import gridmatrix
import holoviews as hv

hv.extension("bokeh")

iris_ds = hv.Dataset(flowers)
density_grid = gridmatrix(iris_ds, diagonal_type=hv.Distribution, chart_type=hv.Bivariate)
point_grid = gridmatrix(iris_ds, chart_type=hv.Points)

grid = density_grid * point_grid
hv.renderer('bokeh').save(grid, 'test_0.12.11')
```

**Comment by mattpap** [comment]
@philippjfr, I got this error:
```
Traceback (most recent call last):
  File "some126.py", line 12, in <module>
    hv.renderer('bokeh').save(grid, 'test_0.12.11')
  File "/home/mateusz/miniconda/envs/bokeh-py3/lib/python3.6/site-packages/holoviews/plotting/renderer.py", line 470, in save
    plot = self_or_cls.get_plot(obj)
  File "/home/mateusz/miniconda/envs/bokeh-py3/lib/python3.6/site-packages/holoviews/plotting/bokeh/renderer.py", line 116, in get_plot
    plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer)
  File "/home/mateusz/miniconda/envs/bokeh-py3/lib/python3.6/site-packages/holoviews/plotting/renderer.py", line 180, in get_plot
    plot.update(0)
  File "/home/mateusz/miniconda/envs/bokeh-py3/lib/python3.6/site-packages/holoviews/plotting/plot.py", line 485, in update
    return self.initialize_plot()
  File "/home/mateusz/miniconda/envs/bokeh-py3/lib/python3.6/site-packages/holoviews/plotting/bokeh/plot.py", line 424, in initialize_plot
    plot = self._make_axes(plot)
  File "/home/mateusz/miniconda/envs/bokeh-py3/lib/python3.6/site-packages/holoviews/plotting/bokeh/plot.py", line 442, in _make_axes
    width, height = self.renderer.get_size(plot)
  File "/home/mateusz/miniconda/envs/bokeh-py3/lib/python3.6/site-packages/holoviews/plotting/bokeh/renderer.py", line 285, in get_size
    return compute_plot_size(plot)
  File "/home/mateusz/miniconda/envs/bokeh-py3/lib/python3.6/site-packages/holoviews/plotting/bokeh/util.py", line 160, in compute_plot_size
    widths, heights = zip(*[compute_plot_size(child) for child in plot.children])
  File "/home/mateusz/miniconda/envs/bokeh-py3/lib/python3.6/site-packages/holoviews/plotting/bokeh/util.py", line 160, in <listcomp>
    widths, heights = zip(*[compute_plot_size(child) for child in plot.children])
  File "/home/mateusz/miniconda/envs/bokeh-py3/lib/python3.6/site-packages/holoviews/plotting/bokeh/util.py", line 153, in compute_plot_size
    if not plot.children: return 0, 0
AttributeError: 'ToolbarBox' object has no attribute 'children'
```
when running your code. In bokeh 0.12.11 `ToolbarBox` is a `LayoutDOM` and so has no `children` property. In general one shouldn't assume that a layout will have explicit children (that works only for boxes).

**Comment by mattpap** [comment]
Anyway, that was on a side note. I figured out the performance issue regardless.

**Comment by philippjfr** [comment]
Ah, damn, I patched that and forgot about it. Good to hear you figured it out regardless.

**Comment by mattpap** [comment]
@philippjfr, PR #7257.

**Comment by bryevdv** [comment]
@philippjfr can you evaluate with the PR and report back?
