### ISSUE TITLE
Connection errors when sending large amounts of data to browser via a bokeh server

### ISSUE THREAD

**Issue by Belloco** [bokeh/bokeh#7374]
Recently I came across a problem with sending lots of data to a bokeh server, between 20 - 50 MB. The command I used was 
```
bokeh serve data_visualisation --show --args -i path_to_large_file
```
What would happen is that my plot would render, and then almost instantly a timeout would occur so no communication between the browser and server was possible:

```
2018-01-05 10:19:58,280 200 GET /data_visualisation (::1) 9227.38ms
2018-01-05 10:19:58,455 101 GET /data_visualisation/ws?bokeh-protocol-version=1.0&bokeh-session-id=jbQmzoBZbYDBDUdi5Ix6QShbAJtAMGPhmKvC1SWjOuwA (::1) 0.87ms
2018-01-05 10:19:58,455 WebSocket connection opened
2018-01-05 10:19:58,456 ServerConnection created
2018-01-05 10:21:28,512 WebSocket connection closed: code=None, reason=None
```

In the browser console, the following errors where shown:
```
[bokeh] Lost websocket 0 connection, 1006 ()  connection.js:221
[bokeh] Websocket connection 0 disconnected, will not attempt to reconnect connection.js:105 
```

The problem was solved by editing tornado.py by changing the rule on line 221
```super(BokehTornado, self).__init__(all_patterns)```
 to 
``` super(BokehTornado, self).__init__(all_patterns, websocket_max_message_size=50 * 1024 * 1024) ```

By default, the maximum socket message size is 10MiB for the used version of Tornado, and would disconnect for this reason. A more meaningful error message or the possibility to change this value in bokeh would be appreciated.

#### Software version info
bokeh==0.12.13
Tornado==4.5.2
python==3.6.3
MacOS High Sierra (10.13.2)
Any browser (Chrome (63.0.3239.84) / Safari / Firefox)

**Comment by bryevdv** [comment]
@Belloco unfortunately it is not possible to provide a better error message. Those messages originate from the browser, and Tornado respectively, not Bokeh. Bokeh only sees that the connection is closed, it does not get any information about *why* it was closed. 

However, if it is possible to expose `websocket_max_message_size` as a user configurable option that that's certainly reasonable. However it is not completely trivial, as that option appears to be new to Tornado 4.5 and Bokeh support tornado >=4.4 so there will have to be some kind of version handling. Are you interested in helping work up a PR for this?

**Comment by Belloco** [comment]
@bryevdv I'm not really interested in helping work up a PR. I mainly wanted to make sure that if other people encountered this problem, they wouldn't have to search as long as I did :)

**Comment by bryevdv** [comment]
@Belloco FWIW open source software depends crucially on spreading the workload to more people. Since you seem capable of doing this work, I do hope you might reconsider. Thanks for the detailed report in any case.

**Comment by AzraelDD** [comment]
THANK YOU so much for posting this solution! This was a huge problem for me, but by chance I stumbled across this post.

**Comment by timothydmorton** [comment]
I'll second the thanks for this solution, which has allowed me a temporary workaround to this problem.  If anyone is able to work up a PR to help fix this as a configurable option in a future version that would be awesome.

**Comment by kkgadiraju** [comment]
Has anyone found a solution to this issue yet? Or is switching to datashader the only solution for now?

**Comment by jbednar** [comment]
Seems like switching to datashader is only one solution, and that the more direct solution is to change the tornado setting as outlined above.

**Comment by bryevdv** [comment]
I'm working on a PR for this right now.

**Comment by FunnyGoofy** [comment]
is this problem solved? thanks

**Comment by bryevdv** [comment]
`--websocket-max-message-size` is available in 0.13.0

**Comment by FunnyGoofy** [comment]
thanks a lot, after updated to 0.13.0, the error is gone

**Comment by FunnyGoofy** [comment]
if I try to select item from combox and call on_change(). console says: WARNING: bokeh.server.views.ws:Failed sending message as connection was closed

**Comment by bryevdv** [comment]
`--websocket-max-message-size` is an option you have to set yourself. Tornado recently introduced a max default web socket message size. All we can do is expose the parameter to override it, which we have done.

**Comment by FunnyGoofy** [comment]
I overwrote it like:
`super(BokehTornado, self).__init__(all_patterns,
                                           websocket_max_message_size=50 * 1024 * 1024,
                                           **kwargs)`

but, when I switch item from combox and update plot, I got error like this one. 

`pydev debugger: starting

 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:bokeh.server.util:Host wildcard '*' will allow connections originating from multiple (or possibly all) hostnames or IPs. Use non-wildcard values to restrict access explicitly
127.0.0.1 - - [11/Jul/2018 08:36:13] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Jul/2018 08:36:13] "GET / HTTP/1.1" 200 -
Backend TkAgg is interactive backend. Turning interactive mode on.
Exception ignored in: <generator object using_format at 0x0D5DF6F0>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x168E73C0>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x0D9C1EA0>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x14F23540>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x14F23660>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x168E7F30>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x168E7CF0>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x168E7330>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x14EFD150>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x14F233C0>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x14F30810>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
ERROR:bokeh.server.protocol_handler:error handling message Message 'PATCH-DOC' (revision 1): KeyError('JobNumber',)
`

Am I not sure if my problem is associated with [https://github.com/bokeh/bokeh/issues/4000](url)


Thanks a lot

**Comment by FunnyGoofy** [comment]
index.js:2 Uncaught Error: reference {"id":"e66b0946-da61-4478-bacb-8620a2dc7314","subtype":"Figure","type":"Plot"} isn't known (not in Document?)
    at o (index.js:2)
    at index.js:2
    at o (index.js:2)
    at Function.P._resolve_refs (index.js:2)
    at P.apply_json_patch (index.js:2)
    at t._handle_patch (index.js:2)
    at t.handle (index.js:2)
    at t._steady_state_handler (index.js:2)
    at t.ACK.t.msgtype._current_handler (index.js:2)
    at t._on_message (index.js:2)
o @ index.js:2
(anonymous) @ index.js:2
o @ index.js:2
P._resolve_refs @ index.js:2
P.apply_json_patch @ index.js:2
t._handle_patch @ index.js:2
t.handle @ index.js:2
t._steady_state_handler @ index.js:2
ACK.t.msgtype._current_handler @ index.js:2
t._on_message @ index.js:2
i.socket.onmessage @ index.js:2
index.js:2 Uncaught Error: reference {"id":"8527ef3f-1366-4cb1-acaa-d3d2d200fd42","type":"ColumnDataSource"} isn't known (not in Document?)
    at o (index.js:2)
    at index.js:2
    at o (index.js:2)
    at Function.P._resolve_refs (index.js:2)
    at P.apply_json_patch (index.js:2)
    at t._handle_patch (index.js:2)
    at t.handle (index.js:2)
    at t._steady_state_handler (index.js:2)
    at t.ACK.t.msgtype._current_handler (index.js:2)
    at t._on_message (index.js:2)
o @ index.js:2
(anonymous) @ index.js:2
o @ index.js:2
P._resolve_refs @ index.js:2
P.apply_json_patch @ index.js:2
t._handle_patch @ index.js:2
t.handle @ index.js:2
t._steady_state_handler @ index.js:2
ACK.t.msgtype._current_handler @ index.js:2
t._on_message @ index.js:2
i.socket.onmessage @ index.js:2
index.js:2 Uncaught Error: reference {"id":"e66b0946-da61-4478-bacb-8620a2dc7314","subtype":"Figure","type":"Plot"} isn't known (not in Document?)
    at o (index.js:2)
    at index.js:2
    at o (index.js:2)
    at index.js:2
    at o (index.js:2)
    at Function.P._resolve_refs (index.js:2)
    at Function.P._initialize_references_json (index.js:2)
    at P.apply_json_patch (index.js:2)
    at t._handle_patch (index.js:2)
    at t.handle (index.js:2)
o @ index.js:2
(anonymous) @ index.js:2
o @ index.js:2
(anonymous) @ index.js:2
o @ index.js:2
P._resolve_refs @ index.js:2
P._initialize_references_json @ index.js:2
P.apply_json_patch @ index.js:2
t._handle_patch @ index.js:2
t.handle @ index.js:2
t._steady_state_handler @ index.js:2
ACK.t.msgtype._current_handler @ index.js:2
t._on_message @ index.js:2
i.socket.onmessage @ index.js:2
index.js:2 Uncaught Error: reference {"id":"8527ef3f-1366-4cb1-acaa-d3d2d200fd42","type":"ColumnDataSource"} isn't known (not in Document?)
    at o (index.js:2)
    at index.js:2
    at o (index.js:2)
    at index.js:2
    at o (index.js:2)
    at Function.P._resolve_refs (index.js:2)
    at Function.P._initialize_references_json (index.js:2)
    at P.apply_json_patch (index.js:2)
    at t._handle_patch (index.js:2)
    at t.handle (index.js:2)
o @ index.js:2
(anonymous) @ index.js:2
o @ index.js:2
(anonymous) @ index.js:2
o @ index.js:2
P._resolve_refs @ index.js:2
P._initialize_references_json @ index.js:2
P.apply_json_patch @ index.js:2
t._handle_patch @ index.js:2
t.handle @ index.js:2
t._steady_state_handler @ index.js:2
ACK.t.msgtype._current_handler @ index.js:2
t._on_message @ index.js:2
i.socket.onmessage @ index.js:2
index.js:2 [bokeh] Unhandled ERROR reply to E4BBA5A52E434533941535A733849379: KeyError('JobNumber',)
t._handle_error @ index.js:2
t.handle @ index.js:2
t._steady_state_handler @ index.js:2
ACK.t.msgtype._current_handler @ index.js:2
t._on_message @ index.js:2
i.socket.onmessage @ index.js:2``

**Comment by FunnyGoofy** [comment]
`index.js:2 Uncaught Error: reference {"id":"8527ef3f-1366-4cb1-acaa-d3d2d200fd42","type":"ColumnDataSource"} isn't known (not in Document?)
    at o (index.js:2)
    at index.js:2
    at o (index.js:2)
    at index.js:2
    at o (index.js:2)
    at Function.P._resolve_refs (index.js:2)
    at Function.P._initialize_references_json (index.js:2)
    at P.apply_json_patch (index.js:2)
    at t._handle_patch (index.js:2)
    at t.handle (index.js:2)`


it looks like error from columnDataSource

**Comment by FunnyGoofy** [comment]
I previously use Bokeh 0.12.16, not the issue like this. Currently, I update the Bokeh and use 0.13.0. this issue appears. I just wonder if this issue is from Bokeh new release. thanks a lot.

**Comment by bryevdv** [comment]
@FunnyGoofy your issues have nothing do do with this issue. I am deleting your comments because it is unhelpful and confusing to have unrelated messages mixed in together. Please start with the mailing list to see if there needs to be a new issue made.

**Comment by bryevdv** [comment]
@FunnyGoofy 50 is an incredibly tiny value. The units of `websocket_max_message_size` are *bytes* (as documented) so setting to 50 means that any message larger then 50 bytes will cause the connection to be terminated. You want to set to a very large value.

**Comment by FunnyGoofy** [comment]
thanks,  any clue about this issue.

On Wed, Jul 11, 2018 at 10:18 AM, Bryan Van de Ven <notifications@github.com
