### ISSUE TITLE
'import distributed' prevents bokeh server exceptions from printing

### ISSUE THREAD

**Issue by timothydmorton** [bokeh/bokeh#7394]
Cross-posting this issue here:

https://github.com/dask/distributed/issues/1683

**Comment by bryevdv** [comment]
I'm not sure what `dask/distributed` is doing, but it's nothing we have control over. Standard Bokeh does what is expected:
```
~/tmp master
(base) ❯ bokeh serve --show foo.py
2018-01-10 14:47:24,258 Starting Bokeh server version 0.12.14dev2-11-g43b602f3b (running on Tornado 4.5.2)
2018-01-10 14:47:24,262 Bokeh app running at: http://localhost:5006/foo
2018-01-10 14:47:24,262 Starting Bokeh server with process id: 23696
2018-01-10 14:47:24,831 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x10aaa42e8>: division by zero
File "foo.py", line 1, in <module>:
1/0 Traceback (most recent call last):
  File "/Users/bryanv/work/bokeh/bokeh/application/handlers/code_runner.py", line 173, in run
    exec(self._code, module.__dict__)
  File "/Users/bryanv/tmp/foo.py", line 1, in <module>
    1/0
ZeroDivisionError: division by zero

2018-01-10 14:47:24,842 200 GET /foo (::1) 13.30ms
2018-01-10 14:47:24,864 200 GET /static/js/bokeh.min.js?v=d44b7afa1d7c0a2ce0be5a728b29b2af (::1) 9.59ms
2018-01-10 14:47:24,866 200 GET /static/js/bokeh-widgets.min.js?v=ddfbfcf21aae66600332f22c4c7755db (::1) 1.33ms
2018-01-10 14:47:24,867 200 GET /static/js/bokeh-tables.min.js?v=bfab33dd4540637410893e302f50fb01 (::1) 1.08ms
2018-01-10 14:47:24,869 200 GET /static/js/bokeh-gl.min.js?v=8222155951e614b8094084d3fce38fe9 (::1) 1.00ms
2018-01-10 14:47:25,013 101 GET /foo/ws?bokeh-protocol-version=1.0&bokeh-session-id=hr4k01UJsZAY1seimN4boVSBl50eWA3N1gCzszhs9hSA (::1) 0.73ms
2018-01-10 14:47:25,013 WebSocket connection opened
2018-01-10 14:47:25,013 ServerConnection created
^C
Interrupted, shutting down
```
