### ISSUE TITLE
Support passing a pandas.Series as x_range for Figure

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7401]
Bokeh 0.12.14dev3

Currently, running this code (taken from https://stackoverflow.com/questions/48152251/unable-to-create-charts-using-bokeh/48170111):
```python
import pandas as pd
from bokeh.plotting import figure, show

car = pd.DataFrame([l.split() for l in """Jan 1808
Feb 1251
Mar 3023""".splitlines()], columns=['Month', 'Sales'])

p = figure(title="Bokeh Scatter Plot Example", x_axis_label='Month',
           y_axis_label='Sales', x_range=car['Month'])

p.circle(car['Month'], car['Sales'], size=5, alpha=0.5)

show(p)
```
results in 
```python
Traceback (most recent call last):
  File "/home/p-himik/dev/git/bokeh/test.py", line 29, in <module>
    y_axis_label='Sales', x_range=car['Month'])
  File "/home/p-himik/dev/git/bokeh/bokeh/plotting/figure.py", line 793, in figure
    return Figure(**kwargs)
  File "/home/p-himik/dev/git/bokeh/bokeh/plotting/figure.py", line 140, in __init__
    self.x_range = _get_range(opts.x_range)
  File "/home/p-himik/dev/git/bokeh/bokeh/plotting/helpers.py", line 355, in _get_range
    raise ValueError("Unrecognized range input: '%s'" % str(range_input))
ValueError: Unrecognized range input: '0    Jan
1    Feb
2    Mar
Name: Month, dtype: object'
```

The workaround is to replace `x_range=car['Month']` with `x_range=list(car['Month'])`.

**Comment by bryevdv** [comment]
Probably reasonable to just check for a `Series` and cast to list internally
