### ISSUE TITLE
Issue with rapid page reloads with Tornado 5

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#7619]
Seeing this on rapid page reloads:
```
2018-03-12 09:05:56,504 200 GET /gapminder (::1) 134.13ms
2018-03-12 09:05:56,506 Sending pull-doc-reply from session 'c13X3Xet3szgUeNWFMzrL86pmFq77b8q04pGAUD8WUFJ'
2018-03-12 09:05:56,513 Failed sending message as connection was closed
2018-03-12 09:05:56,514 WebSocket connection closed: code=None, reason=None
2018-03-12 09:05:56,604 Future exception was never retrieved
future: <Future finished exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/Users/bryanv/anaconda/envs/15dev1/lib/python3.6/site-packages/tornado/websocket.py", line 808, in wrapper
    yield fut
  File "/Users/bryanv/anaconda/envs/15dev1/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bryanv/anaconda/envs/15dev1/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/bryanv/anaconda/envs/15dev1/lib/python3.6/site-packages/tornado/websocket.py", line 810, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
```

Seemed to happen between `0.12.14` and `0.12.15dev1`

**Comment by bryevdv** [comment]
Was hoping it might just be a Tornado 5 related issue but it seems to be any Tornado version. Will do a more careful bisection later today.

**Comment by bryevdv** [comment]
Actually upon further inspection this seems like it might only happen with Tornado 5 after all. @bdarnell  do you have any ideas or tips for debugging?

**Comment by bdarnell** [comment]
The type of exception raised by `write_message` changed in 5.0 - it is now always `WebSocketClosedError`, while it used to be a mix of `WebSocketClosedError` and `StreamClosedError` (mostly the latter). Are you catching `StreamClosedError` but not `WebSocketClosedError`? 

These "Future exception was never retrieved" messages also got more common in 5.0 with the move to asyncio. You may need to use `yield` or `await` when calling `write_message` to avoid this. This isn't ideal, but I'm not sure what to do about it. We jump through some hoops to silence these messages in other places but it looks like we missed WSH.write_message.

**Comment by bryevdv** [comment]
We only catch `WebSocketClosedError`. Looking at our WS handler subclass, I see this:

```
   @gen.coroutine
    def write_message(self, message, binary=False, locked=True):
        def write_message_unlocked():
            future = super(WSHandler, self).write_message(message, binary)
            # don't yield this future or we're blocking on ourselves!
            raise gen.Return(future)
        if locked:
            with (yield self.write_lock.acquire()):
                write_message_unlocked()
        else:
            write_message_unlocked()
```
And changing to this seems to fix things:
```
    @gen.coroutine
    def write_message(self, message, binary=False, locked=True):
        if locked:
            with (yield self.write_lock.acquire()):
                yield super(WSHandler, self).write_message(message, binary)
        else:
            yield super(WSHandler, self).write_message(message, binary)

    def on_close(self):
```

I'm not sure about the previous comment (I assume from @havocp) not to yield or else we block ourselves, tho.

**Comment by bryevdv** [comment]
Well, with that change and Tornado 4, I see this on reloads: 
```
Handler or its work threw an exception: StreamClosedError('Stream is closed',): Message 'PULL-DOC-REQ' (revision 1)
Traceback (most recent call last):
  File "/Users/bryanv/work/bokeh/bokeh/server/views/ws.py", line 150, in on_message
    yield self._schedule(work)
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/bryanv/work/bokeh/bokeh/server/views/ws.py", line 226, in _schedule
    yield self.send_message(work)
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/bryanv/work/bokeh/bokeh/server/views/ws.py", line 176, in send_message
    yield message.send(self)
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/bryanv/work/bokeh/bokeh/protocol/message.py", line 235, in send
    yield conn.write_message(self.metadata_json, locked=False)
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/bryanv/work/bokeh/bokeh/server/views/ws.py", line 192, in write_message
    yield super(WSHandler, self).write_message(message, binary)
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
tornado.iostream.StreamClosedError: Stream is closed
```

I'll try to see if there is a place to catch both exceptions.

**Comment by bryevdv** [comment]
This diff seems to function with both Tornado 4 and 5: 
```
diff --git a/bokeh/server/views/ws.py b/bokeh/server/views/ws.py
index f524962cc..c643d9b0a 100644
--- a/bokeh/server/views/ws.py
+++ b/bokeh/server/views/ws.py
@@ -11,7 +11,7 @@ import codecs
 from six.moves.urllib.parse import urlparse

 from tornado import gen, locks
-from tornado.websocket import WebSocketHandler, WebSocketClosedError
+from tornado.websocket import StreamClosedError, WebSocketHandler, WebSocketClosedError

 from ..protocol_handler import ProtocolHandler
 from ...protocol import Protocol
@@ -174,7 +174,7 @@ class WSHandler(WebSocketHandler):
         '''
         try:
             yield message.send(self)
-        except WebSocketClosedError:
+        except (WebSocketClosedError, StreamClosedError):
             # on_close() is / will be called anyway
             log.warn("Failed sending message as connection was closed")
         raise gen.Return(None)
@@ -185,15 +185,11 @@ class WSHandler(WebSocketHandler):
         write lock before writing.

         '''
-        def write_message_unlocked():
-            future = super(WSHandler, self).write_message(message, binary)
-            # don't yield this future or we're blocking on ourselves!
-            raise gen.Return(future)
         if locked:
             with (yield self.write_lock.acquire()):
-                write_message_unlocked()
+                yield super(WSHandler, self).write_message(message, binary)
         else:
-            write_message_unlocked()
+            yield super(WSHandler, self).write_message(message, binary)

     def on_close(self):
         ''' Clean up when the connection is closed.
```

Comments welcome!

**Comment by bdarnell** [comment]
That looks good to me. It's not clear to me what purpose `write_message_unlocked` was serving or what that comment was about.

**Comment by bryevdv** [comment]
@bdarnell thanks as always for the help and feedback. I think `write_message_unlocked` was just to encapsulate the two lines of code when previously raising `gen.Return(future)`. Are there any considerations at to be aware of at all doing a `yield` vs raising `gen.Return`? I'll work up a PR today, hoping there's a way to simulate this kind if disconnect so I can put it under test.

**Comment by bdarnell** [comment]
> Are there any considerations at to be aware of at all doing a yield vs raising gen.Return?

There was no yield in `write_message_unlocked`, so the `raise gen.Return(future)` was exactly equivalent to `return future` and the whole thing was equivalent to `super().write_message`. The change is just that now you're waiting on the Future and before you were simply discarding it.

**Comment by bryevdv** [comment]
Well, with this change things seem to work locally, but some tests now hang:
```
tests/examples/test_examples.py::test_server_examples[/Users/bryanv/work/bokeh/examples/app/image_blur.py-example5]
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:bokeh.client.connection:Running state NOT_YET_CONNECTED
DEBUG:bokeh.client.connection:transitioning to state CONNECTED_BEFORE_ACK
DEBUG:bokeh.client.connection:Running state CONNECTED_BEFORE_ACK
DEBUG:bokeh.client.connection:Received message Message 'ACK' (revision 1)
DEBUG:bokeh.client.connection:Received Message 'ACK' (revision 1)
DEBUG:bokeh.client.connection:transitioning to state CONNECTED_AFTER_ACK
DEBUG:bokeh.client.connection:Stopping client loop in state CONNECTED_AFTER_ACK due to True from connected_or_closed
DEBUG:bokeh.client.connection:Sent Message 'PUSH-DOC' (revision 1) [1411212 bytes]
DEBUG:bokeh.client.connection:Stopping client loop in state WAITING_FOR_REPLY due to True from have_send_result_or_disconnected
DEBUG:bokeh.client.connection:Running state WAITING_FOR_REPLY
DEBUG:bokeh.client.connection:Received message Message 'PATCH-DOC' (revision 1)
DEBUG:bokeh.client.connection:Running state WAITING_FOR_REPLY
DEBUG:bokeh.client.connection:Received message Message 'PATCH-DOC' (revision 1)
DEBUG:bokeh.client.connection:Running state WAITING_FOR_REPLY
DEBUG:bokeh.client.connection:Received message Message 'PATCH-DOC' (revision 1)
DEBUG:bokeh.client.connection:Running state WAITING_FOR_REPLY
```
@havocp do you remember the context of your comment about blocking?

**Comment by bryevdv** [comment]
Also @bdarnell you did mention:

> . You may need to use yield or await when calling write_message to avoid this. This isn't ideal, but I'm not sure what to do about it. 

Are there any other avenues to try?

**Comment by bryevdv** [comment]
OK after a little more digging and reproducing in a local test run: we are re-using the same session id in our server example test infrastructure. This seems like it can trigger the "closed connection" condition that's the same as a too-fast browser reload. I don't think this is a real problem in general, but it seems like it confuses our test harness causing the hang. Using a unique session id per example test passed the tests locally, trying now in the PR
