### ISSUE TITLE
"Cannot connect to browser" When Running Example Tests

### ISSUE THREAD

**Issue by nathanielatom** [bokeh/bokeh#7899]
After following the [dev guide setup instructions](http://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#devguide-setup) in a fresh conda environment using the current bokeh master branch, I'm getting "Cannot connect to browser" errors (from node) when running the example tests.

<details><summary>Relevant Versions</summary>
<p>

macOS 10.12.6

```
# installed with gui/dmg
which chrome
chrome: aliased to /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
chrome --version     
Google Chrome 66.0.3359.170

# installed with brew
which chromium
/usr/local/bin/chromium
chromium --version
Chromium 68.0.3429.0
chromedriver --version                                                   
ChromeDriver 2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef)

bokeh info
Python version      :  3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
IPython version     :  6.4.0
Bokeh version       :  0.12.16rc1-dirty
BokehJS static path :  /Users/Atom/Documents/floss/bokeh/bokeh/server/static
node.js version     :  v8.11.1
npm version         :  6.0.1

pytest --version
This is pytest version 3.5.1, imported from /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest.py
setuptools registered plugins:
  pytest-xdist-1.22.2 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/xdist/plugin.py
  pytest-xdist-1.22.2 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/xdist/looponfail.py
  pytest-variables-1.7.1 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_variables/plugin.py
  pytest-selenium-1.12.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_selenium/drivers/browserstack.py
  pytest-selenium-1.12.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_selenium/drivers/chrome.py
  pytest-selenium-1.12.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_selenium/drivers/crossbrowsertesting.py
  pytest-selenium-1.12.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_selenium/drivers/edge.py
  pytest-selenium-1.12.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_selenium/drivers/firefox.py
  pytest-selenium-1.12.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_selenium/drivers/internet_explorer.py
  pytest-selenium-1.12.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_selenium/drivers/phantomjs.py
  pytest-selenium-1.12.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_selenium/drivers/remote.py
  pytest-selenium-1.12.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_selenium/drivers/safari.py
  pytest-selenium-1.12.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_selenium/drivers/saucelabs.py
  pytest-selenium-1.12.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_selenium/pytest_selenium.py
  pytest-selenium-1.12.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_selenium/safety.py
  pytest-selenium-1.12.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_selenium/drivers/testingbot.py
  pytest-metadata-1.7.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_metadata/plugin.py
  pytest-html-1.17.0 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_html/plugin.py
  pytest-forked-0.2 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_forked/__init__.py
  pytest-cov-2.5.1 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_cov/plugin.py
  pytest-base-url-1.4.1 at /Users/Atom/.miniconda/envs/bokeh/lib/python3.6/site-packages/pytest_base_url/plugin.py
```
</p>
</details>

#### Complete, minimal, self-contained example code that reproduces the issue

<details><summary>Full Pytest Output</summary>
<p>

The same behaviour is observed when running 
```
NODE_PATH="$HOME/Documents/floss/bokeh/bokehjs/node_modules" node /Users/Atom/Documents/floss/bokeh/tests/plugins/chrome_screenshot.js file:///Users/Atom/Documents/floss/bokeh/examples/custom/font-awesome/font-awesome.html /Users/Atom/Documents/floss/bokeh/examples/custom/font-awesome/.tests/font-awesome-0.12.16rc1-local.png 100 15000 1000 1000
```
directly.

```
py.test -m examples --report-path=examples.html -n 5 -x
============================================================= test session starts =============================================================
platform darwin -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
sensitiveurl: .*
rootdir: /Users/Atom/Documents/floss/bokeh, inifile: setup.cfg
plugins: xdist-1.22.2, variables-1.7.1, selenium-1.12.0, metadata-1.7.0, html-1.17.0, forked-0.2, cov-2.5.1, base-url-1.4.1
gw0 [331] / gw1 [331] / gw2 [331] / gw3 [331] / gw4 [331]
scheduling tests via LoadScheduling
F
================================================================== FAILURES ===================================================================
_________________ test_js_examples[/Users/Atom/Documents/floss/bokeh/bokehjs/examples/categorical/categorical.html-example4] __________________
[gw4] darwin -- Python 3.6.5 /Users/Atom/.miniconda/envs/bokeh/bin/python

js_example = '/Users/Atom/Documents/floss/bokeh/bokehjs/examples/categorical/categorical.html'
example = Example('bokehjs/examples/categorical/categorical.html', js), report = None

    @pytest.mark.examples
    def test_js_examples(js_example, example, report):
        if example.is_skip:
            pytest.skip("skipping %s" % example.relpath)
    
        if example.no_js:
            if not pytest.config.option.no_js:
                warn("skipping bokehjs for %s" % example.relpath)
        else:
>           _assert_snapshot(example, "file://%s" % example.path, 'js')

tests/examples/test_examples.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/examples/test_examples.py:171: in _assert_snapshot
    result = get_screenshot(url, screenshot_path, local_wait, global_wait, width, height)
tests/plugins/screenshot.py:43: in get_screenshot
    return _get_screenshot(_get_chrome(), url, screenshot_path, local_wait, global_wait, width, height)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

engine = ['node', '/Users/Atom/Documents/floss/bokeh/tests/plugins/chrome_screenshot.js']
url = 'file:///Users/Atom/Documents/floss/bokeh/bokehjs/examples/categorical/categorical.html'
screenshot_path = '/Users/Atom/Documents/floss/bokeh/bokehjs/examples/categorical/.tests/categorical-0.12.16rc1-local.png', local_wait = 100
global_wait = 15000, width = 1000, height = 1000

    def _get_screenshot(engine, url, screenshot_path, local_wait, global_wait, width, height):
        """
        wait is in milliseconds
        """
        cmd = engine + [url, screenshot_path, str(local_wait), str(global_wait), str(width), str(height)]
        trace("Running command: %s" % " ".join(cmd))
    
        env = os.environ.copy()
        env["NODE_PATH"] = join(TOP_PATH, 'bokehjs', 'node_modules')
    
        try:
            proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env)
            proc.wait()
        except OSError as e:
            fail("Failed to run: %s" % " ".join(cmd))
            fail(str(e))
            sys.exit(1)
    
        if proc.returncode != 0:
            output = proc.stderr.read().decode("utf-8")
            fail(output)
>           sys.exit(1)
E           SystemExit: 1

tests/plugins/screenshot.py:37: SystemExit
------------------------------------------------------------ Captured stdout call -------------------------------------------------------------
[FAIL] Cannot connect to browser:  { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! xdist.dsession.Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================== 1 failed in 12.89 seconds ==========================================================
```
</p>
</details>

The `examples.log` is empty.

There's nothing that mentions chrome in the test documentation, but since the script's called `chrome_screenshot.js` and it's mentioned in #6594 it seems relevant, so I included my chrome / chromium versions above.

I'm not sure whether it's using chrome or chromium or how it might be using these though. 
Connecting to headless chrome/chromium through python-selenium works fine for me.

**Comment by mattpap** [comment]
Both chrome and chromium should work, but so far only chrome works reliably for me (on Linux; this may have been resolved in more recent versions of chromium). Examples tests require a headless browser running ahead of time, so you need to run `google-chrome --headless --remote-debugging-port=9222 &` yourself. For communication with chrome we use chrome devtools/debug protocol, which is different from selenium.

**Comment by bryevdv** [comment]
I had the same issue on OSX, the only way I was able to resolve things and run locally was to install and run chrome via these instructions:

https://objectpartners.com/2017/04/13/how-to-install-and-use-headless-chrome-on-osx/

So I'd regard this as an upstream issue that's out of our hands, accordingly I will close this.
