### ISSUE TITLE
Bokeh GMapOptions error

### ISSUE THREAD

**Issue by anujnimkar** [bokeh/bokeh#7985]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh version - 0.12.16
Python - 3.5
OS - Windows 10
Browser - IE, Chrome, Firefox
Other relevant packages - GMapOptions, gmap
#### Description of expected behavior and the observed behavior
I'm fairly new to Bokeh so please excuse me for my lack of knowledge/experience with bokeh. I am trying to create a geographic visualization using bokeh and then integrate my bokeh server app into flask to deploy it on a VPS. When run independently my code produces the necessary visualization but, gives an error in the command line. The error is occuring at the gmap call. I tried looking this error up and found a few relevant results all of which pointed to bugs in the Bokeh library. Where I am really getting stuck is, at the point of deployment of this visualization either independently as a bokeh server app or by integrating it with Flask because of this error. Any help on this is greatly appreciated. Thanks!

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks
```
from bokeh.io import curdoc
from bokeh.models import GMapOptions
from bokeh.plotting import gmap
map_options = GMapOptions(lat=37.686293, lng=-97.3614409, map_type="roadmap", zoom=13)
p = gmap(google_api_key="My Google Maps API Key", map_options=map_options, title="Resolutions Clients", plot_width=1000, plot_height=600)
curdoc().add_root(p)
```


```
#### Stack traceback and/or browser JavaScript console output
C:\Users\Administrator\PycharmProjects\FlaskApp>bokeh serve --show test.py
2018-06-11 14:20:52,449 Starting Bokeh server version 0.12.16 (running on Tornad
o 5.0.2)
2018-06-11 14:20:52,463 Bokeh app running at: http://localhost:5006/test
2018-06-11 14:20:52,464 Starting Bokeh server with process id: 9972
2018-06-11 14:20:52,816 200 GET /test (::1) 161.02ms
2018-06-11 14:20:53,072 101 GET /test/ws?bokeh-protocol-version=1.0&bokeh-sessio
n-id=YwriVJupgcBKp7IEeFdj5R95PJG2lxe6g82SFqbObcDA (::1) 1.00ms
2018-06-11 14:20:53,072 WebSocket connection opened
2018-06-11 14:20:53,072 ServerConnection created
2018-06-11 14:20:53,120 error handling message Message 'PATCH-DOC' (revision 1):
 TypeError("__init__() missing 2 required positional arguments: 'google_api_key'
 and 'map_options'",)

**Comment by bryevdv** [comment]
@anujnimkar just to be clear, when I ran the code, I saw the error message, but everything still worked as expected. Are you saying that things are different for you, or not working?

**Comment by anujnimkar** [comment]
@bryevdv First of all, thanks for your quick response. Really appreciate it!
If I am to run my app independently, it runs fine even with this command line error. But where I am getting stuck is when I try to deploy this app to something like Heroku. Because of this error, my deployment is failing.

**Comment by bryevdv** [comment]
Sorry I am not especially familiar with Heroku, do you mean their process monitors examine the logs and if they see "error" in it somewhere, abort or something? That seems like a strange, but not something we have aloof control over if it is true We should leave this issue on GH to fix the spurious message on the Bokeh side, but in the mean time I'd suggest posting to the mailing list or SO with a more Heroku-specific question about how to make Heroku not fall just because of spurious log messages.  Otherwise the only immediate suggestion I have is to try to raise the Bokeh log level to critical (not sure if that will suppress the message) or try to route all bokeh log output to `/dev/null`

**Comment by anujnimkar** [comment]
@bryevdv , I'm not sure if their process monitors examine the logs and fail on seeing error. I tested out the deployment for a simple Helloworld app, and it succeeded. It fails when I introduce my Bokeh GMaps though, so my guess is that it could be failing because of the error message, please correct me if I'm wrong here. Here are the logs for both,

Successful Deployment
```
C:\Users\Administrator\TestApp>git push heroku master
Counting objects: 11, done.
Delta compression using up to 16 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (11/11), 4.31 KiB | 0 bytes/s, done.
Total 11 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python app detected
remote: -----> Installing python-3.6.5
remote: -----> Installing pip
remote: -----> Installing dependencies with Pipenv 11.8.2.
remote:        Installing dependencies from Pipfile.lock (2899d6).
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 60.8M
remote: -----> Launching...
remote:        Released v3
remote:        https://fast-tor-15097.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.

Warning: Your console font probably doesn't support Unicode. If you experience s
trange characters in the output, consider switching to a TrueType font such as C
onsolas!
To https://git.heroku.com/fast-tor-15097.git
 * [new branch]      master -> master

C:\Users\Administrator\TestApp>heroku ps:scale web=1
Scaling dynos... done, now running web at 1:Free


```

Failed Deployment
```
C:\Users\Administrator\TherasoftApp>git push heroku master
Counting objects: 11, done.
Delta compression using up to 16 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (11/11), 6.06 KiB | 0 bytes/s, done.
Total 11 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python app detected
remote: -----> Installing python-3.6.5
remote: -----> Installing pip
remote: -----> Installing dependencies with Pipenv 11.8.2.
remote:        Your Pipfile.lock (2899d6) is out of date. Expected: (b9622b).
remote:        Aborting deploy.
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to powerful-depths-14139.
remote:

Warning: Your console font probably doesn't support Unicode. If you experience s
trange characters in the output, consider switching to a TrueType font such as C
onsolas!
To https://git.heroku.com/powerful-depths-14139.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/powerful-depths-14139
.git'
```

**Comment by anujnimkar** [comment]
Also, when I try to integrate the bokeh server app with Flask, to try another route for deployment (via VPS like Digital Ocean), the integration fails for the same reason,

```
FLASK_APP = app.py
FLASK_ENV = development
FLASK_DEBUG = 0
In folder C:/Users/Administrator/PycharmProjects/FlaskApp
C:\Users\Administrator\PycharmProjects\ButtonTest\venv\Scripts\python.exe -m flask run
 * Serving Flask app "app.py"
 * Environment: development
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ButtonTest\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\PycharmProjects\ButtonTest\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\PycharmProjects\ButtonTest\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Administrator\PycharmProjects\ButtonTest\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\Administrator\PycharmProjects\ButtonTest\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\PycharmProjects\ButtonTest\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Administrator\PycharmProjects\FlaskApp\app.py", line 12, in index
    session = pull_session(url = "http://localhost:5006/Button_test_update_version2")
  File "C:\Users\Administrator\PycharmProjects\ButtonTest\venv\lib\site-packages\bokeh\client\session.py", line 113, in pull_session
    session.pull()
  File "C:\Users\Administrator\PycharmProjects\ButtonTest\venv\lib\site-packages\bokeh\client\session.py", line 349, in pull
    self._connection.pull_doc(doc)
  File "C:\Users\Administrator\PycharmProjects\ButtonTest\venv\lib\site-packages\bokeh\client\connection.py", line 165, in pull_doc
    reply.push_to_document(document)
  File "C:\Users\Administrator\PycharmProjects\ButtonTest\venv\lib\site-packages\bokeh\protocol\messages\pull_doc_reply.py", line 57, in push_to_document
    doc.replace_with_json(self.content['doc'])
  File "C:\Users\Administrator\PycharmProjects\ButtonTest\venv\lib\site-packages\bokeh\document\document.py", line 714, in replace_with_json
    replacement = self.from_json(json)
  File "C:\Users\Administrator\PycharmProjects\ButtonTest\venv\lib\site-packages\bokeh\document\document.py", line 484, in from_json
    references = instantiate_references_json(references_json)
  File "C:\Users\Administrator\PycharmProjects\ButtonTest\venv\lib\site-packages\bokeh\document\util.py", line 66, in instantiate_references_json
    instance = cls(id=obj_id, _block_events=True)
TypeError: __init__() missing 2 required positional arguments: 'google_api_key' and 'map_options'
127.0.0.1 - - [11/Jun/2018 16:16:16] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [11/Jun/2018 16:16:16] "GET / HTTP/1.1" 500 -


```

**Comment by anujnimkar** [comment]
@bryevdv, my bad, the compilation was failing because of a change in the Pipfile. Thanks though for taking the time to respond!

**Comment by bryevdv** [comment]
@anujnimkar I don't mean to be overly critical, but you are going about things in a way that is very confusing and not helpful for the maintainers. You have asked different versions of this question, with lots of unrelated details here, on SO, and the mailing lists. That makes it very hard for maintainers to focus on and solve the actual core problem. 

None of the Flask code is relevant to this discussion at all. I empathize that that is your immediate problem and that you want it to work, but is distracting and unhelpful noise in this context. 

To re-focus the discussion here, the *only* thing that Bokeh needs to fix is that this MRE generates a TypeError:
```
from bokeh.io import curdoc
from bokeh.models import GMapOptions
from bokeh.plotting import gmap, figure

map_options = GMapOptions(lat=30.2861, lng=-97.7394, map_type="roadmap", zoom=13)
p = gmap(google_api_key="API KEY", map_options=map_options)

curdoc().add_root(p)
```

**Comment by bryevdv** [comment]
FWIW the basic issue is partly at least that the client seems to be sending patch updates immediately back to the server for the document it just rendered, and I don't think that should be happening at all. Making that not happen should incidentally fix this as well.

**Comment by bryevdv** [comment]
OK, digging further, I partially I see what's happening. There are some values that are modified on the client on construction, and these should (and are) getting patched back. But there is something weird and specific going on with gmap plots, possibly because it is a subtype.

**Comment by anujnimkar** [comment]
Hey @bryevdv , thanks for narrowing the issue down to the bokeh server code. I initially thought that since, the code was running independently on bokeh server (although displaying the PATCH-DOC error), I was missing out something on the Flask side, also thanks for pointing out the autoload_static in Flask code, I'm using server_session, now.

**Comment by anujnimkar** [comment]
@bryevdv,
'That accidentally is harmless (but wasteful) in the case of Plot but for GMapPlot there is some interaction with the subclassing that is causing the extra subclass attrs to not be sent back. Making it not send the unnecessary patching at all should incidentally fix this as well.'

I don't really follow what you mean here, can you let me know how I should make it not send the unnecessary patching at all. 

Thanks!

**Comment by bryevdv** [comment]
> can you let me know how I should make it not send the unnecessary patching at all.

That message for other core devs. If there is a bug in the low level protocol, there's nothing any user will be able to do about it. As it turns out, I was mistaken about this hypothesis, though.

**Comment by anujnimkar** [comment]
Okay, do you think there is a way for me to get through this and be able to deploy my app successfully, any options that you can suggest I should try out?

Thanks,
Anuj

**Comment by bryevdv** [comment]
@anujnimkar The PR is merged and will be in the next release. At that point, the `TypeError` you were seeing will not happen anymore. Anything past that is a usage/support question and should be take outside GitHub

**Comment by anujnimkar** [comment]
@bryevdv  Okay. Is there a way for me to know when the next release will be out(a rough estimate will help)?

Thanks,
Anuj

**Comment by bryevdv** [comment]
Hopefully this week.
