### ISSUE TITLE
Small documentation error for BoxSelectTool

### ISSUE THREAD

**Issue by kevinsa5** [bokeh/bokeh#8000]
The documentation for `BoxSelectTool` says that to constrain selection to a single axis, you pass `width` or `height` as a string in a single-element list, but this is incorrect.  Passing just the string itself works.  Relevant docs section [here](http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#specifying-tools)

```
(venv) kevin@onion-run:~/iplot$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bokeh
>>> print bokeh.__version__
0.12.16
>>> 
>>> from bokeh.models import BoxSelectTool
>>> from bokeh.plotting import figure
>>> 
>>> plot = figure(tools="pan,wheel_zoom,box_zoom,reset")
>>> plot.add_tools(BoxSelectTool(dimensions=["width"]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kevin/iplot/venv/local/lib/python2.7/site-packages/bokeh/model.py", line 219, in __init__
    super(Model, self).__init__(**kwargs)
  File "/home/kevin/iplot/venv/local/lib/python2.7/site-packages/bokeh/core/has_props.py", line 236, in __init__
    setattr(self, name, value)
  File "/home/kevin/iplot/venv/local/lib/python2.7/site-packages/bokeh/core/has_props.py", line 263, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "/home/kevin/iplot/venv/local/lib/python2.7/site-packages/bokeh/core/property/descriptors.py", line 503, in __set__
    self._internal_set(obj, value, setter=setter)
  File "/home/kevin/iplot/venv/local/lib/python2.7/site-packages/bokeh/core/property/descriptors.py", line 724, in _internal_set
    value = self.property.prepare_value(obj, self.name, value)
  File "/home/kevin/iplot/venv/local/lib/python2.7/site-packages/bokeh/core/property/bases.py", line 278, in prepare_value
    raise e
ValueError: expected a value of type basestring, got ['width'] of type list
>>> plot.add_tools(BoxSelectTool(dimensions="width"))
>>> 

```

**Comment by bryevdv** [comment]
@kevinsa5 are you interested in submitting a PR to fix this up?
