### ISSUE TITLE
patch_app.py is broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8232]
Bisection reveals https://github.com/bokeh/bokeh/pull/8224

running the app repeatedly shows
```
2018-09-10 19:07:29,992 Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x1202aa6a8>, <Future finished exception=ValueError('assignment destination is read-only',)>)
Traceback (most recent call last):
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/bryanv/work/bokeh/bokeh/util/tornado.py", line 95, in on_done
    log.error("".join(format_exception(*future.exc_info())))
AttributeError: '_asyncio.Future' object has no attribute 'exc_info'
```
which is also actually a secondary issue causing the exception to not be reported correctly.

**Comment by bryevdv** [comment]
Issue is that `np.frombuffer` returns a readonly view. PR incoming with both fixes (for traceback as well)
