### ISSUE TITLE
`bokeh.sampledata.gapminder` not found

### ISSUE THREAD

**Issue by noppelmax** [bokeh/bokeh#8432]
I wanted to run the gapminder example from this repo. I made a git clone of the current master branch changed the gapminder directory and started the bokeh server. It seems like the `bokeh.sampledata.gapminder` could not be found. See log. I only get a white browser window and error messages in the console. Do you have any idea what i could try?

I tried the current master branch: Commit 7093b5f8b5327dcc5f96c711e156fddba2d8b4e7

My bokeh version 
```
max@sam ~/g/b/e/a/gapminder (master)> bokeh --version
0.13.0
```
```
max@sam ~/g/b/e/a/gapminder (master)> python3 --version
Python 3.5.2
```
```
max@sam ~/g/b/e/a/gapminder (master)> uname -a
Linux sam 4.15.0-38-generic #41~16.04.1-Ubuntu SMP Wed Oct 10 20:16:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
max@sam ~/g/b/e/a/gapminder (master)> firefox --version
Mozilla Firefox 63.0
```

Error output was:
```
max@sam ~/g/b/e/a/gapminder (master)> bokeh serve --show main.py 
/home/max/.local/lib/python3.5/site-packages/bokeh/command/util.py:91: UserWarning: 
It looks like you might be running the main.py of a directory app directly.
If this is the case, to enable the features of directory style apps, you must
call "bokeh serve" on the directory instead. For example:

    bokeh serve my_app_dir/

If this is not the case, renaming main.py will supress this warning.

  warnings.warn(DIRSTYLE_MAIN_WARNING)
2018-11-14 23:18:38,729 Starting Bokeh server version 0.13.0 (running on Tornado 5.1.1)
2018-11-14 23:18:38,731 Bokeh app running at: http://localhost:5006/main
2018-11-14 23:18:38,731 Starting Bokeh server with process id: 17874
2018-11-14 23:18:39,023 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x7fc3fd72a518>: bokeh sample data directory does not exist, please execute bokeh.sampledata.download()
File "sampledata.py", line 113, in external_data_dir:
raise RuntimeError('bokeh sample data directory does not exist, please execute bokeh.sampledata.download()') Traceback (most recent call last):
  File "/home/max/.local/lib/python3.5/site-packages/bokeh/application/handlers/code_runner.py", line 163, in run
    exec(self._code, module.__dict__)
  File "/home/max/git/bokeh/examples/app/gapminder/main.py", line 14, in <module>
    fertility_df, life_expectancy_df, population_df_size, regions_df, years, regions_list = process_data()
  File "/home/max/git/bokeh/examples/app/gapminder/data.py", line 5, in process_data
    from bokeh.sampledata.gapminder import fertility, life_expectancy, population, regions
  File "/home/max/.local/lib/python3.5/site-packages/bokeh/sampledata/gapminder.py", line 62, in <module>
    fertility       = external_csv('gapminder', 'gapminder_fertility.csv', index_col='Country', encoding='utf-8')
  File "/home/max/.local/lib/python3.5/site-packages/bokeh/util/sampledata.py", line 91, in external_csv
    return pd.read_csv(external_path(name), **kw)
  File "/home/max/.local/lib/python3.5/site-packages/bokeh/util/sampledata.py", line 126, in external_path
    data_dir = external_data_dir()
  File "/home/max/.local/lib/python3.5/site-packages/bokeh/util/sampledata.py", line 113, in external_data_dir
    raise RuntimeError('bokeh sample data directory does not exist, please execute bokeh.sampledata.download()')
RuntimeError: bokeh sample data directory does not exist, please execute bokeh.sampledata.download()
 
2018-11-14 23:18:39,033 200 GET /main (127.0.0.1) 65.75ms
2018-11-14 23:18:39,234 404 GET /favicon.ico (127.0.0.1) 0.49ms
2018-11-14 23:18:39,282 101 GET /main/ws?bokeh-protocol-version=1.0&bokeh-session-id=hdaE7bYUmPdSVsConlw2Lwo9rPcLOeOnps7w8klw3K7M (127.0.0.1) 0.65ms
2018-11-14 23:18:39,282 WebSocket connection opened
2018-11-14 23:18:39,283 ServerConnection created
^C
Interrupted, shutting down


```

**Comment by jbednar** [comment]
Have you run `bokeh.sampledata.download()` as the message above suggests?

**Comment by noppelmax** [comment]
I found why the index.html is not show at least: I have to run it on the directory instead of the main.py file. 

Ill try to run bokeh.sampledata.download(). Do i have to write it into the code?

**Comment by jbednar** [comment]
That command downloads the data into `~/.bokeh/data/`, and you only have to run it once ever unless you delete that directory.

**Comment by jbednar** [comment]
And running bokeh serve on the main.py file isn't an error, it just means that you will fail to use the template defined in that directory.  Should still work either way.

**Comment by noppelmax** [comment]
Ok. I think i got it.

```
max@sam ~/g/b/e/app (master)> python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bokeh.sampledata
>>> bokeh.sampledata.download()
Creating /home/max/.bokeh directory
Creating /home/max/.bokeh/data directory
Using data directory: /home/max/.bokeh/data
Downloading: CGM.csv (1589982 bytes)
   1589982 [100.00%]
Downloading: US_Counties.zip (3182088 bytes)
   3182088 [100.00%]
Unpacking: US_Counties.csv
Downloading: us_cities.json (713565 bytes)
    713565 [100.00%]
Downloading: unemployment09.csv (253301 bytes)
    253301 [100.00%]
.
.
.
```

**Comment by noppelmax** [comment]
I spend two hours on finding out i have to run the command on the directory. Maybe we could write a section on how to use templates in the docs?

**Comment by noppelmax** [comment]
Thanks for your help @jbednar

**Comment by jbednar** [comment]
The error message above does say you probably want to run it on the directory...

**Comment by mattpap** [comment]
Simpler approach is to use `bokeh sampledata` console command, as described in bokeh's [quickstart](https://bokeh.pydata.org/en/latest/docs/user_guide/quickstart.html#sample-data).

**Comment by noppelmax** [comment]
Yes, you are right. But i named my file in my project bokehUI.py so this warning is not shown. I only tried gapminder to find out how the template stuff works.

```
max@sam ~/g/b/e/a/gapminder (master)> bokeh serve --show test.py 
2018-11-14 23:53:37,897 Starting Bokeh server version 0.13.0 (running on Tornado 5.1.1)
2018-11-14 23:53:37,899 Bokeh app running at: http://localhost:5006/test
2018-11-14 23:53:37,899 Starting Bokeh server with process id: 20041
2018-11-14 23:53:38,387 200 GET /test (127.0.0.1) 220.45ms
2018-11-14 23:53:38,560 404 GET /favicon.ico (127.0.0.1) 0.51ms
2018-11-14 23:53:38,612 101 GET /test/ws?bokeh-protocol-version=1.0&bokeh-session-id=MLU1n5c9jqK8tBuyAsvmADFS46Zk2JnfHeSoAh1Pfymn (127.0.0.1) 0.90ms
2018-11-14 23:53:38,613 WebSocket connection opened
2018-11-14 23:53:38,613 ServerConnection created
^C
Interrupted, shutting down
```

**Comment by noppelmax** [comment]
Anyway, we could close this issue. Thank you!
