### ISSUE TITLE
Whisker does not accept explicit negative values

### ISSUE THREAD

**Issue by phausamann** [bokeh/bokeh#8484]
#### Version info

Windows 10 x64
python 3.6.5
bokeh 1.0.2

#### Description

Annotations such as `Whisker` do not accept explicit negative values:

    from bokeh.models import Whisker
    Whisker(base=0, lower=-1, upper=1)

raises

	Traceback (most recent call last):
	  ...
	  File "C:\Users\peter\Anaconda3\lib\site-packages\bokeh\model.py", line 261, in __init__
		super(Model, self).__init__(**kwargs)
	  File "C:\Users\peter\Anaconda3\lib\site-packages\bokeh\core\has_props.py", line 254, in __init__
		setattr(self, name, value)
	  File "C:\Users\peter\Anaconda3\lib\site-packages\bokeh\core\has_props.py", line 281, in __setattr__
		super(HasProps, self).__setattr__(name, value)
	  File "C:\Users\peter\Anaconda3\lib\site-packages\bokeh\core\property\descriptors.py", line 1090, in __set__
		super(UnitsSpecPropertyDescriptor, self).__set__(obj, value, setter)
	  File "C:\Users\peter\Anaconda3\lib\site-packages\bokeh\core\property\descriptors.py", line 546, in __set__
		self._internal_set(obj, value, setter=setter)
	  File "C:\Users\peter\Anaconda3\lib\site-packages\bokeh\core\property\descriptors.py", line 767, in _internal_set
		value = self.property.prepare_value(obj, self.name, value)
	  File "C:\Users\peter\Anaconda3\lib\site-packages\bokeh\core\property\dataspec.py", line 397, in prepare_value
		raise ValueError("Distances must be positive or None!")
	ValueError: Distances must be positive or None!

However,

    Whisker(base=0, lower=0, upper=1)

and

    from bokeh.models import ColumnDataSource
    source = ColumnDataSource({'base': [0], 'lower': [-1], 'upper': [1]})
    Whisker(base='base', lower='lower', upper='upper', source=source)

work as expected.

**Comment by bryevdv** [comment]
Seems like a Python API issue. It is hopefully just a matter of using the more general `NumberSpec` rather than `DistanceSpec` on the Python side. 

@phausamann If you are interested in trying things out (you might be able to get to it sooner than us), the place to edit is here:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/annotations.py#L1071-L1081

If that works, we'd be happy to accept a PR

**Comment by phausamann** [comment]
Thanks @bryevdv, that seems easy enough for a first issue to tackle, I'll give it a try.
