### ISSUE TITLE
Make bokehjs importable in nodejs

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#8700]
Currently it fails with:
```
$ NODE_PATH=node_modules/bokehjs/build/js/lib/ node
> require("bokehjs")
ReferenceError: window is not defined
    at Object.<anonymous> (/home/mateusz/tmp/bokeh/node_modules/hammerjs/hammer.js:2643:4)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```
This would allow to use bokehjs to create JSON representation (or HTML files in general) on the backend, for consumption by bokehjs in a web browser. Note that making bokehjs node importable and making it a node module (npm package), e.g. for consumption by webpack, are different things. The later is already possible with some configuration.

**Comment by bryevdv** [comment]
An example of doing this for users to refer to would magnify the value of this change
