### ISSUE TITLE
[BUG] ValueError: Out of range float values are not JSON compliant: nan

### ISSUE THREAD

**Issue by tony-bony** [bokeh/bokeh#9024]
**ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)**
```
Python version      :  2.7.15 (default, Oct  4 2018, 22:42:40) 
IPython version     :  5.8.0
Tornado version     :  4.5.3
Bokeh version       :  1.2.0
BokehJS static path :  /usr/local/lib/python2.7/site-packages/bokeh/server/static
node.js version     :  v10.15.1
npm version         :  6.7.0
```
OS: Mac OS X Yosemite 10.10.5
Browser: Google Chrome  75.0.3770.100 (Official Build) (64-bit)

**Description of expected behavior and the observed behavior**
Expected behavior: NaN values should be accepted and handled by the CustomJS callback
Observed behavior: NaN are accepted in ColumnDataSource but are not accepted in `CustomJS`
```
Traceback (most recent call last):
  File "/Users/User/Documents/workspace/test_js_on_change.py", line 15, in <module>
    show(p)
  File "/usr/local/lib/python2.7/site-packages/bokeh/io/showing.py", line 145, in show
    return _show_with_state(obj, state, browser, new, notebook_handle=notebook_handle)
  File "/usr/local/lib/python2.7/site-packages/bokeh/io/showing.py", line 183, in _show_with_state
    _show_file_with_state(obj, state, new, controller)
  File "/usr/local/lib/python2.7/site-packages/bokeh/io/showing.py", line 166, in _show_file_with_state
    filename = save(obj, state=state)
  File "/usr/local/lib/python2.7/site-packages/bokeh/io/saving.py", line 86, in save
    _save_helper(obj, filename, resources, title, template)
  File "/usr/local/lib/python2.7/site-packages/bokeh/io/saving.py", line 148, in _save_helper
    html = file_html(obj, resources, title=title, template=template)
  File "/usr/local/lib/python2.7/site-packages/bokeh/embed/standalone.py", line 308, in file_html
    (docs_json, render_items) = standalone_docs_json_and_render_items(models, suppress_callback_warning=suppress_callback_warning)
  File "/usr/local/lib/python2.7/site-packages/bokeh/embed/util.py", line 297, in standalone_docs_json_and_render_items
    docs_json[docid] = doc.to_json()
  File "/usr/local/lib/python2.7/site-packages/bokeh/document/document.py", line 845, in to_json
    doc_json = self.to_json_string()
  File "/usr/local/lib/python2.7/site-packages/bokeh/document/document.py", line 874, in to_json_string
    return serialize_json(json, indent=indent)
  File "/usr/local/lib/python2.7/site-packages/bokeh/core/json_encoder.py", line 161, in serialize_json
    return json.dumps(obj, cls=BokehJSONEncoder, allow_nan=False, indent=indent, separators=separators, sort_keys=True, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 323, in _iterencode_list
    yield buf + _floatstr(value)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 254, in floatstr
    repr(o))
ValueError: Out of range float values are not JSON compliant: nan
```

**Complete, minimal, self-contained example code that reproduces the issue**
```py
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, CustomJS

p = figure()

size = [10.0, float('nan'), 20.0]
source = ColumnDataSource(dict(x = [1, 3, 2], 
                               y = [2, 1, 4], 
                               size = size))

p.circle(x = 'x',
         y = 'y', 
         size = 'size', 
         source = source)

source.selected.js_on_change('indices', CustomJS(args = dict(size = size), 
                                                 code = "console.log(size)"))
show(p)
```

The actual example code below uses LogColorMapper and draws a **grey** patch if value is missing (if nan is provided):
```py
from bokeh.plotting import figure, show
from bokeh.models import LogColorMapper, ColumnDataSource, CustomJS
from bokeh.transform import transform

p = figure(plot_width=400, plot_height=400)

one_nan = [0.0, float('nan'), 1.0]
source = ColumnDataSource(dict(xs = [[1, 3, 2], [3, 4, 6], [4, 5, 6]], ys = [[2, 1, 4], [4, 7, 8], [2, 4, 2]], one_nan = one_nan))
log_color_mapper = LogColorMapper(palette = ['red', 'green', 'blue', 'cyan'], low = 0, high = 2)

p.patches('xs', 'ys', fill_color = transform('one_nan', log_color_mapper), source = source)

source.selected.js_on_change('indices', CustomJS(args = dict(one_nan = one_nan), 
                                                 code = "console.log(one_nan)"))

show(p)
```

**Comment by bryevdv** [comment]
NaN values are not JSON serializable. I personally regard this as a bad decision/mistake on the part of the JSON specification, but nonetheless, it's the reality we have to contend with, and there's nothing we can do about it. Bokeh can serialize NaN values in floating point NumPy arrays, because those are not serialized using JSON. Accordingly, your only option is to put any data that might contain NaNs in to NumPy arrays.

**Comment by tony-bony** [comment]
OK. Thanks. 
I still think it's just a little effort (possibly 2 lines of code) to include this conversion to NumPy array in Bokeh CustomJS code, just for the user convenience and for compatibility with ColumnDataSource (too much discrepancies in handling data in Bokeh)

**Comment by bryevdv** [comment]
> I still think it's just a little effort (possibly 2 lines of code) to include this conversion to NumPy array in Bokeh CustomJS code, 
 
The data in your example is in a `ColumnDataSource` and automatically converting is not a good idea for several reasons:

* anyone expecting to be able to change the underlying data from an earlier reference, after putting it into a CDS, would, get a very nasty surprise
* Everyone who doesn't want/need this conversion would be forced to pay a potentially expensive and unnecessary operation 100% of the time
* In my experience almost anyone dealing with NaNs is already using NumPy arrays
