### ISSUE TITLE
[BUG] Incompatible definitions of `VBar.width` in Bokeh and BokehJS

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#9033]
In Bokeh:
```python
class VBar(Glyph):
	[...]
    width = NumberSpec(help="""
    The widths of the vertical bars.
    """)
	[...]
```

In BokehJS:
```typescript
export namespace VBar {
  export type Attrs = p.AttrsOf<Props>

  export type Props = Box.Props & {
    x: p.CoordinateSpec
    bottom: p.CoordinateSpec
    width: p.DistanceSpec
    top: p.CoordinateSpec
  }

  export type Visuals = Box.Visuals
}
```

`NumberSpec` doesn't specify any units but `DistanceSpec` does.
It leads to this error:
```
bokeh.js:525 [bokeh] Unhandled ERROR reply to 151506C3B5744752B7B2865BACFCFDF8: ValueError("expected an element of either String, Dict(Enum('expr', 'field', 'value', 'transform'), Either(String, Instance(Transform), Instance(Expression), Float)) or Float, got {'field': 'chr_width', 'units': 'data'}")
ClientSession._handle_error @ bokeh.js:525
ClientSession.handle @ bokeh.js:472
ClientConnection._steady_state_handler @ bokeh.js:417
_current_handler @ bokeh.js:397
ClientConnection._on_message @ bokeh.js:359
_this.socket.onmessage @ bokeh.js:216
```
And on the Python side (not logged but sent to the UI for some reason?):
```
Traceback (most recent call last):
File "/.../lib/python3.7/site-packages/bokeh/server/protocol_handler.py", line 100, in handle
    work = yield handler(message, connection)
File "/.../lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
File "/.../lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
File "/.../lib/python3.7/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
File "/.../lib/python3.7/site-packages/bokeh/server/session.py", line 257, in _handle_patch
    message.apply_to_document(self.document, self)
File "/.../lib/python3.7/site-packages/bokeh/protocol/messages/patch_doc.py", line 107, in apply_to_document
    doc.apply_json_patch(self.content, setter)
File "/.../lib/python3.7/site-packages/bokeh/document/document.py", line 379, in apply_json_patch
    initialize_references_json(references_json, references, setter)
File "/.../lib/python3.7/site-packages/bokeh/document/util.py", line 90, in initialize_references_json
    instance.update_from_json(obj_attrs, models=references, setter=setter)
File "/.../lib/python3.7/site-packages/bokeh/core/has_props.py", line 405, in update_from_json
    self.set_from_json(k, v, models, setter)
File "/.../lib/python3.7/site-packages/bokeh/core/has_props.py", line 347, in set_from_json
    descriptor.set_from_json(self, json, models, setter)
File "/.../lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 1028, in set_from_json
    super(DataSpecPropertyDescriptor, self).set_from_json(obj, json, models, setter)
File "/.../lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 618, in set_from_json
    models, setter)
File "/.../lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 327, in set_from_json
    self._internal_set(obj, json, setter=setter)
File "/.../lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 766, in _internal_set
    value = self.property.prepare_value(obj, self.name, value)
File "/.../lib/python3.7/site-packages/bokeh/core/property/bases.py", line 327, in prepare_value
    raise e
File "/.../lib/python3.7/site-packages/bokeh/core/property/bases.py", line 320, in prepare_value
    self.validate(value)
File "/.../lib/python3.7/site-packages/bokeh/core/property/either.py", line 116, in validate
    raise ValueError(msg)
ValueError: expected an element of either String, Dict(Enum('expr', 'field', 'value', 'transform'), Either(String, Instance(Transform), Instance(Expression), Float)) or Float, got {'field': 'chr_width', 'units': 'data'}
```

**Comment by bryevdv** [comment]
AFAIK the actual implementation in `box.ts` does not take any units into account. So the options woudl be:

* change BokehJS to `NumberSpec` (done)
* change Python to `DistanceSpec` (and change the BokehJS implementation to respect units, may be non-trivial wrt hit-testing and spatial indexing)

**Comment by p-himik** [comment]
BTW same thing with `HBar.height`. Maybe with other properties as well - didn't dwell deeper.

Just some thinking out loud:
Is it feasible to write some kind of test for this? Probably not since it's hard to know about TS from Python and vice versa. Maybe both Bokeh and BokehJS could benefit from some static description of the data that models accept?

**Comment by bryevdv** [comment]
> Is it feasible to write some kind of test for this?

Yes and no. We already have a test that compares all the default values. This have been critically important, since early on we would have discrepancies between Python JS and that caused huge headaches. We do also have a [`spec.py`](https://github.com/bokeh/bokeh/blob/master/scripts/spec.py) that will dump an extremely detailed specification based on the Python modes, including all the (Bokeh) types, base classes, help strings etc. We could potentially use this to do a deeper comparison than just default values. The main obstacle I see at present is that the BokehJS type system is not as rich as the Python side. 

This also gets into questions about what should be  the "ground truth" for the specification, which is something we should think about long term, i.e. 

* Python could be the ultimate source of truth, with the output of `spec.py` being  something other languages can use to build bindings from
* BokehJS could be ground truth, and we could make a tool to generate a spec from it, and then all languages (including Python) could validate their bindings against it
* Could even go down the code-get route for Python, i.e. `bokeh.models` could be generated based on the BokehJS spec... that's definitely a longer term idea.

For the present, I think it would be good to find a way to start auditing property types that can be compared directly (e.g. DataSpecs in  particular) as a start and immediate improvement.

**Comment by bryevdv** [comment]
we should make a follow on issue about the broader concerns, but the immediate fix (updating JS to specify `NumberSpec`) should not wait on that.
