### ISSUE TITLE
[BUG] Cannot import FileInput widget when running a Bokeh Server

### ISSUE THREAD

**Issue by GuillaumeHarel** [bokeh/bokeh#9130]
Hello,

I have just updated my bokeh library from 1.2.0 to 1.3.0 using conda in order to use the new InputFile widget. The update ran fine according to the console.
However, when I run my usual bokeh server with the new widget, I come across an import error for the InputFile widget. This error does not occure if I directly run my script in my IDE (no bokeh server).

Here is all the software/system version info :
Python : 3.7 (Anaconda)
Bokeh : 1.3.0

OS : Win 10 64 bits
Browser : Mozilla Firefox

As mentionned, I did the bokeh update using conda. 

Below is the single line of code that trigger an Import Error :
**trials.py**
```
from bokeh.models.widgets import FileInput
```
This returns the following error in the console :

C:\Users\ghare\PycharmProjects>bokeh serve --show untitled3/trials.py
2019-07-30 22:10:08,226 Starting Bokeh server version 1.1.0 (running on Tornado 6.0.2)
2019-07-30 22:10:08,237 Bokeh app running at: http://localhost:5006/trials
2019-07-30 22:10:08,237 Starting Bokeh server with process id: 7052
2019-07-30 22:10:09,157 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x000001A5DA9F2390>: cannot import name 'FileInput' from 'bokeh.models.widgets' (C:\Users\ghare\Anaconda3\lib\site-packages\bokeh\models\widgets\__init__.py)
File "trials.py", line 1, in <module>:
from bokeh.models.widgets import FileInput Traceback (most recent call last):
  File "C:\Users\ghare\Anaconda3\lib\site-packages\bokeh\application\handlers\code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "C:\Users\ghare\PycharmProjects\untitled3\trials.py", line 1, in <module>
    from bokeh.models.widgets import FileInput
ImportError: cannot import name 'FileInput' from 'bokeh.models.widgets' (C:\Users\ghare\Anaconda3\lib\site-packages\bokeh\models\widgets\__init__.py)

I precise that I also try to run directly the short example below without running a bokeh server and it works perfectly fine

```
from bokeh.io import output_file, show
from bokeh.models.widgets import FileInput
print('done')
output_file("file_input.html")

file_input = FileInput()

show(file_input)
```
This is the first issue I open, I hope I provided enough info. Otherwise, please tell me what I additional info I should give you.

Thanks for your help.

**Comment by philippjfr** [comment]
If you look at your logging output you will see that it seems to be picking up a different version of bokeh:

```
2019-07-30 22:10:08,226 Starting Bokeh server version 1.1.0 (running on Tornado 6.0.2)
```

Are you sure you have activated the correct environment?

**Comment by GuillaumeHarel** [comment]
Hum you're right about the wrong version of bokeh.

However I did actually activate the right environnement before updating. As mentionned, it is also working fine while working on the same project in pycharm (same env) but not running a bokeh server.

Below is the actual list of package for my environnement (webscrapping):

```
(webscrapper) C:\Windows\system32>conda list
# packages in environment at C:\Users\ghare\Anaconda3\envs\webscrapper:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0
attrs                     19.1.0                   py37_1
backcall                  0.1.0                    py37_0
beautifulsoup4            4.7.1                    py37_1
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
bokeh                     1.3.0                    py37_0
ca-certificates           2019.5.15                     0
certifi                   2019.6.16                py37_1
cffi                      1.12.3           py37h7a1dbc1_0
colorama                  0.4.1                    py37_0
cryptography              2.7              py37h7a1dbc1_0
cycler                    0.10.0                   py37_0
decorator                 4.4.0                    py37_1
defusedxml                0.6.0                      py_0
entrypoints               0.3                      py37_0
freetype                  2.9.1                ha9979f8_1
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
intel-openmp              2019.4                      245
ipykernel                 5.1.1            py37h39e3cac_0
ipython                   7.6.1            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.0                      py_0
jedi                      0.13.3                   py37_0
jinja2                    2.10.1                   py37_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.0.1                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.1                      py_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.5.0                      py_0
kiwisolver                1.1.0            py37ha925a31_0
libiconv                  1.15                 h1df5818_7
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libtiff                   4.0.10               hb898794_2
libxml2                   2.9.9                h464c3ec_0
libxslt                   1.1.33               h579f668_0
lxml                      4.3.3            py37h1350720_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37he774522_0
matplotlib                3.0.3            py37hc8f65d3_0
mistune                   0.8.4            py37he774522_0
mkl                       2019.4                      245
mkl-service               2.0.2            py37he774522_0
mkl_fft                   1.0.12           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
msys2-conda-epoch         20160418                      1
nbconvert                 5.5.0                      py_0
nbformat                  4.4.0                    py37_0
notebook                  6.0.0                    py37_0
numpy                     1.16.4           py37h19fb1c0_0
numpy-base                1.16.4           py37hc3f5095_0
olefile                   0.46                     py37_0
openssl                   1.1.1c               he774522_1
packaging                 19.0                     py37_0
pandas                    0.24.2           py37ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.5.0                      py_0
patsy                     0.5.1                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    6.1.0            py37hdc69c19_0
pip                       19.1.1                   py37_0
prometheus_client         0.7.1                      py_0
prompt_toolkit            2.0.9                    py37_0
pycparser                 2.19                     py37_0
pygments                  2.4.2                      py_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.4.0                      py_0
pyqt                      5.9.2            py37h6538335_2
pyrsistent                0.14.11          py37he774522_0
pysocks                   1.7.0                    py37_0
python                    3.7.3                h8c8aaf0_1
python-dateutil           2.8.0                    py37_0
pytz                      2019.1                     py_0
pywinpty                  0.5.5                 py37_1000
pyyaml                    5.1.1            py37he774522_0
pyzmq                     18.0.0           py37ha925a31_0
qt                        5.9.7            vc14h73c81de_0
qtconsole                 4.5.2                      py_0
scipy                     1.3.0            py37h29ff71c_0
seaborn                   0.9.0                    py37_0
selenium                  3.141.0          py37he774522_0
send2trash                1.5.0                    py37_0
setuptools                41.0.1                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.12.0                   py37_0
soupsieve                 1.8                      py37_0
sqlite                    3.29.0               he774522_0
statsmodels               0.10.0           py37h8c2d366_0
terminado                 0.8.2                    py37_0
testpath                  0.4.2                    py37_0
tk                        8.6.8                hfa6e2cd_0
tornado                   6.0.3            py37he774522_0
traitlets                 4.3.2                    py37_0
urllib3                   1.25.3                   py37_0
vc                        14.1                 h21ff451_3    anaconda
vs2015_runtime            15.5.2                        3    anaconda
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
wheel                     0.33.4                   py37_0
widgetsnbextension        3.5.0                    py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
xlrd                      1.2.0                    py37_0
xlsxwriter                1.1.8                      py_0    anaconda
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.1                h33f27b4_3
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0

```

I don't know why the Bokeh server version is 1.1.0 but this explains the Import Error for FileInput :)
