### ISSUE TITLE
[BUG] Bokeh server document lock bug

### ISSUE THREAD

**Issue by LegitStack** [bokeh/bokeh#9161]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

This runs in a docker container.
OS: Centos 7
bokeh==1.2.0
panel==0.6.0
jinja2==2.10.1
tornado==6.0.2
flask==1.0.2
param==1.9.1
Testing in chrome

#### Description application setup

We have a bokeh server running and a flask app manages routes to various pages, one of them being this bokeh server. (see code below)

#### Description of expected behavior and the observed behavior

We believe this error eluded us for a while since we don't usually perform the following behavior:
When running the bokeh app the first time everything works well. But when refreshing the page and running it again we get an error about there being a document lock. (see error below)

#### minimal, example code:

flask app:
```
from bokeh.embed import server_document
...
@app.route('/bokeh/test')
def bokeh__test():
    resp = {
        'script': server_document(
            url='http://localhost:6001/test',
            #arguments={'user_id': ... , }
            ),
        'template': 'Flask',}
    return render_template('report/bokeh.html', **resp)
...
```

bokeh.html
```
{% extends "base.html" %}
{% block content %}
  {{ script|safe }}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}
```

reports/test/main.ipynb
```
from this_project import BaseReport 
import panel as pn
import holoviews as hv
from bokeh.models import NumeralTickFormatter
hv.extension('bokeh')
pn.extension()
...
report = BaseReport(title='test', ...)
report.serve()
```

this_project/base_report.py (this is the class that has bokeh code in it)
```
import panel as pn
from bokeh.models import CustomJS
from bokeh.models.widgets import PreText
...
class BaseReport(param.Parameterized):
    run = param.Action(lambda x: x.param.trigger('run'), label='Run')

    def __init__(self, datasets, title='Report Title', ..., **params):
        ...
        run_button = pn.widgets.Button(button_type='primary', name='RUN',)
        ...

    def serve(self):
        gspec = pn.GridSpec(sizing_mode='stretch_both')
        title_bar = pn.Column(pn.Row(self.actions, align='center')),
        widgets = self.widget_list
        gspec[0, 0:12] = title_bar
        gspec[1:39, 0:12] = pn.Row(
            pn.WidgetBox(*widgets),
            pn.Column(self.output))
        return gspec.servable()
```

#### Stack traceback and/or browser JavaScript console output

```
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f6d82484160>>, <Future finished exception=RuntimeError('_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes')>)
Traceback (most recent call last):
  File "/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/conda/lib/python3.7/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/conda/lib/python3.7/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/conda/lib/python3.7/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/conda/lib/python3.7/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/conda/lib/python3.7/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/conda/lib/python3.7/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/conda/lib/python3.7/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/conda/lib/python3.7/site-packages/param/parameterized.py", line 1219, in inner
    return fn(*args, **kwargs)
  File "/conda/lib/python3.7/site-packages/param/parameterized.py", line 2572, in set_param
    return self_or_cls.param.set_param(*args,**kwargs)
  File "/conda/lib/python3.7/site-packages/param/parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "/conda/lib/python3.7/site-packages/param/parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "/conda/lib/python3.7/site-packages/panel/param.py", line 340, in action
    value(self.object)
  File "/app/insight/core/report.py", line 44, in <lambda>
    run = param.Action(lambda x: x.param.trigger('run'), label='Run')
  File "/conda/lib/python3.7/site-packages/param/parameterized.py", line 1422, in trigger
    self_.set_param(**params)
  File "/conda/lib/python3.7/site-packages/param/parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "/conda/lib/python3.7/site-packages/param/parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "/conda/lib/python3.7/site-packages/panel/param.py", line 587, in update_pane
    self._update_pane()
  File "/conda/lib/python3.7/site-packages/panel/param.py", line 537, in _update_pane
    new_object = self._eval_function(self.object)
  File "/conda/lib/python3.7/site-packages/panel/param.py", line 534, in _eval_function
    return function(*args, **kwargs)
  File "/conda/lib/python3.7/site-packages/param/parameterized.py", line 318, in _depends
    return func(*args,**kw)
  File "/app/insight/core/report.py", line 179, in output
    self.get_data()
  File "/app/insight/core/report.py", line 146, in get_data
    item.get_data()
  File "/app/insight/core/datasets.py", line 79, in get_data
    self.data = self.execute_query()
  File "/app/insight/core/datasets.py", line 39, in data
    self.source.data = ColumnDataSource(data).data
  File "/conda/lib/python3.7/site-packages/bokeh/core/has_props.py", line 280, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "/conda/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 973, in __set__
    self._internal_set(obj, value, hint=hint, setter=setter)
  File "/conda/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 769, in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
  File "/conda/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 838, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/conda/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 915, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/conda/lib/python3.7/site-packages/bokeh/model.py", line 704, in trigger
    super(Model, self).trigger(attr, old, new, hint=hint, setter=setter)
  File "/conda/lib/python3.7/site-packages/bokeh/util/callback_manager.py", line 161, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "/conda/lib/python3.7/site-packages/bokeh/document/document.py", line 1005, in _notify_change
    self._trigger_on_change(event)
  File "/conda/lib/python3.7/site-packages/bokeh/document/document.py", line 1100, in _trigger_on_change
    self._with_self_as_curdoc(invoke_callbacks)
  File "/conda/lib/python3.7/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/conda/lib/python3.7/site-packages/bokeh/document/document.py", line 1099, in invoke_callbacks
    cb(event)
  File "/conda/lib/python3.7/site-packages/bokeh/document/document.py", line 669, in <lambda>
    self._callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "/conda/lib/python3.7/site-packages/bokeh/document/events.py", line 244, in dispatch
    super(ModelChangedEvent, self).dispatch(receiver)
  File "/conda/lib/python3.7/site-packages/bokeh/document/events.py", line 126, in dispatch
    receiver._document_patched(self)
  File "/conda/lib/python3.7/site-packages/bokeh/server/session.py", line 214, in _document_patched
    raise RuntimeError("_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes")
RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes
```

#### Screenshots or screencasts of the bug in action

Click Run:
![image](https://user-images.githubusercontent.com/5642485/62973594-8f36e780-bdd3-11e9-9540-cdfc321e9e16.png)
Refresh page
Click Run:
![image](https://user-images.githubusercontent.com/5642485/62973695-d02efc00-bdd3-11e9-9b60-f054ef78bc74.png)
Spins forever, and gives errors in the logs

#### Speculation:

Is this a problem with how flask is talking to bokeh through server_document? Should a new session_id be created for each connection or something like that?

**Comment by bryevdv** [comment]
Hi @LegitStack this error message indicates a usage error. Additionally, Panel is not part of the Bokeh project. This discussion would be more suitable to have on the Project Discourse, so please repost there:

https://discourse.bokeh.org
