### ISSUE TITLE
[BUG] Parameter hover_line_width throws attribute error for segment glyph

### ISSUE THREAD

**Issue by hklarner** [bokeh/bokeh#9197]
#### software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
- bokeh 3.1.4
- python3.6
- ubuntu
- chrome

#### Description of expected behavior and the observed behavior
I want to create a segment that changes its line width when hovered over. I use the parameter `hover_line_width`. I get an attribute error "unexpected attribute", see below.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure, output_file, save
from bokeh.models import HoverTool

p = figure()
r = p.segment(x0=[1,2], y0=[2,3], x1=[10,20], y1=[20,30], line_width=3, hover_line_width=6)
p.add_tools(HoverTool(renderers=[r]))

output_file("hover.html")
save(p)
```

#### Stack traceback and/or browser JavaScript console output
Traceback (most recent call last):
  File "...", line 257, in <module>
    debug()
  File "...", line 248, in debug
    r = p.segment(x0=[1,2], y0=[2,3], x1=[10,20], y1=[20,30], line_width=3, hover_line_width=6)
  File "fakesource", line 7, in segment
  File "/usr/local/lib/python3.6/dist-packages/bokeh/plotting/helpers.py", line 857, in func
    glyph = _make_glyph(glyphclass, kwargs, glyph_ca)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/plotting/helpers.py", line 398, in _make_glyph
    return glyphclass(**kws)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/model.py", line 307, in __init__
    super(Model, self).__init__(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/core/has_props.py", line 253, in __init__
    setattr(self, name, value)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/core/has_props.py", line 288, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))
AttributeError: unexpected attribute 'hover_line_width' to Segment, similar attributes are line_width

**Comment by bryevdv** [comment]
Thanks for the report @hklarner

**Comment by bryevdv** [comment]
This was fixed at some point:

<img width="603" alt="Image" src="https://github.com/user-attachments/assets/59e117c0-af00-43c2-bdba-eddafe0fb5be" />
