### ISSUE TITLE
Unable to build BokehJS on OSX

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9315]
cc @mattpap 

```
[09:30:10] failed: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
[09:30:10]     at Hash.update (internal/crypto/hash.js:58:11)
[09:30:10]     at Linker.new_module (/Users/bryan/work/bokeh/bokehjs/src/compiler/linker.ts:532:46)
[09:30:10]     at Linker.resolve (/Users/bryan/work/bokeh/bokehjs/src/compiler/linker.ts:623:27)
[09:30:10]     at Linker.link (/Users/bryan/work/bokeh/bokehjs/src/compiler/linker.ts:236:28)
[09:30:10]     at /Users/bryan/work/bokeh/bokehjs/make/tasks/compiler.ts:31:27
[09:30:10]     at Generator.next (<anonymous>)
[09:30:10]     at /Users/bryan/work/bokeh/bokehjs/make/tasks/compiler.ts:8:71
[09:30:10]     at new Promise (<anonymous>)
[09:30:10]     at __awaiter (/Users/bryan/work/bokeh/bokehjs/make/tasks/compiler.ts:4:12)
[09:30:10]     at Task.task_1.task [as fn] (/Users/bryan/work/bokeh/bokehjs/make/tasks/compiler.ts:19:52)
```

Have blown away `node_modules` and re-installed, did not help. These appear to be the exact same versions used on successful TravisCI builds:
```
~/work/bokeh/bokehjs master 14s
(base) ❯ npm --version
6.12.0

~/work/bokeh/bokehjs master
(base) ❯ conda list nodejs
# packages in environment at /Users/bryan/anaconda:
#
# Name                    Version                   Build  Channel
nodejs                    10.13.0              h0a44026_0
```

**Comment by bryevdv** [comment]
needed a `node make clean`
