### ISSUE TITLE
TypeError: Symbol.asyncIterator is not defined

### ISSUE THREAD

**Issue by kassbohm** [bokeh/bokeh#9429]
Installed Bokeh 1.4.0 using "pip3 install bokeh" using Python 3.6.8 on Linux Mint 19.1.

Trying to use Latex-Labels as in the [example](https://docs.bokeh.org/en/latest/docs/user_guide/extensions_gallery/latex.html) from the extension gallery, I get the following error message:

```
Compilation failed:

TypeError: Symbol.asyncIterator is not defined.
    at __asyncValues (/usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:149:19)
    at /usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:168:36
    at Generator.next (<anonymous>:null:null)
    at /usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:144:75
    at new Promise (<anonymous>:null:null)
    at __awaiter (/usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:130:16)
    at read_stdin (/usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:162:16)
    at /usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:205:48
    at Generator.next (<anonymous>:null:null)
    at /usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:144:75
    at new Promise (<anonymous>:null:null)
    at __awaiter (/usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:130:16)
    at compile (/usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:194:16)
    at /usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:244:33
    at Generator.next (<anonymous>:null:null)
    at /usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:144:75
    at new Promise (<anonymous>:null:null)
    at __awaiter (/usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:130:16)
    at main (/usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:211:16)
    at Object._ (/usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:252:5)
    at require (/usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:88:23)
    at P (/usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:96:16)
    at /usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:126:1
    at parent_require (/usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:32:19)
    at Object.<anonymous> (/usr/local/lib/python3.6/dist-packages/bokeh/server/static/js/compiler.js:33:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by mattpap** [comment]
What version of nodejs do you have (`bokeh info`)?

**Comment by kassbohm** [comment]
Python version      :  3.6.8 (default, Oct  7 2019, 12:59:55)
IPython version     :  (not installed)
Tornado version     :  6.0.3
Bokeh version       :  1.4.0
BokehJS static path :  
/usr/local/lib/python3.6/dist-packages/bokeh/server/static
**node.js version     :  v8.10.0**
npm version         :  3.5.2

**Comment by mattpap** [comment]
You will need to upgrade to node >= 10 (if you use conda, you can install it with `conda install nodejs`). We forgot to check if node 8.x is still a valid minimum version.

**Comment by kassbohm** [comment]
Thanks!

**Comment by mattpap** [comment]
I will leave this open until PR #9430 is merged.

**Comment by kassbohm** [comment]
Have installed node v12.13.1 now following these [instructions](https://github.com/nodesource/distributions/blob/master/README.md#debinstall). And Latex-Labels work fine now with Bokeh 1.4.0. Thanks again.
