### ISSUE TITLE
Allow to invalidate sampledata cache

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#9589]
```
$ make html
sphinx-build -b html -d build/doctrees  source -W build/html
Running Sphinx v2.3.1
making output directory... done
creating gallery file entries... [100%] logaxis.rst                                                                                           
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 249 source files that are out of date
updating environment: [new config] 249 added, 0 changed, 0 removed
copying bokeh-plot files... [100%] bokeh-plot-ffe21e7ce7b148779c29dec3d149f1c6-external-docs-user_guide-plotting.js                           

Exception occurred:
  File "/home/mateusz/repo/bokeh3/bokeh/sphinxext/bokeh_plot.py", line 156, in run
    raise RuntimeError("Sphinx bokeh-plot exception: \n\n%s\n\n Failed on:\n\n %s" % (e,source))
RuntimeError: Sphinx bokeh-plot exception: 

Traceback (most recent call last):
  File "/home/mateusz/conda/envs/bk/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 410, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 435, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 146, in pandas._libs.index.IndexEngine._get_loc_duplicates
KeyError: '2010-10-06'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mateusz/conda/envs/bk/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py", line 1057, in get_loc
    return Index.get_loc(self, key, method, tolerance)
  File "/home/mateusz/conda/envs/bk/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 410, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 435, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 146, in pandas._libs.index.IndexEngine._get_loc_duplicates
KeyError: '2010-10-06'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mateusz/conda/envs/bk/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 410, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 435, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 146, in pandas._libs.index.IndexEngine._get_loc_duplicates
KeyError: 1286323200000000000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mateusz/conda/envs/bk/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py", line 1070, in get_loc
    return Index.get_loc(self, stamp, method, tolerance)
  File "/home/mateusz/conda/envs/bk/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 410, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 435, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 146, in pandas._libs.index.IndexEngine._get_loc_duplicates
KeyError: 1286323200000000000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mateusz/repo/bokeh3/bokeh/application/handlers/code_runner.py", line 174, in run
    exec(self._code, module.__dict__)
  File "/home/mateusz/repo/bokeh3/sphinx/source/docs/user_guide/examples/styling_glyph_hover.py", line 7, in <module>
    subset = data.loc['2010-10-06']
  File "/home/mateusz/conda/envs/bk/lib/python3.8/site-packages/pandas/core/indexing.py", line 1424, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/mateusz/conda/envs/bk/lib/python3.8/site-packages/pandas/core/indexing.py", line 1850, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/mateusz/conda/envs/bk/lib/python3.8/site-packages/pandas/core/indexing.py", line 160, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/home/mateusz/conda/envs/bk/lib/python3.8/site-packages/pandas/core/generic.py", line 3737, in xs
    loc = self.index.get_loc(key)
  File "/home/mateusz/conda/envs/bk/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py", line 1072, in get_loc
    raise KeyError(key)
KeyError: '2010-10-06'


 Failed on:

 from bokeh.models import HoverTool
from bokeh.plotting import figure, output_file, show
from bokeh.sampledata.glucose import data

output_file("styling_hover.html")

subset = data.loc['2010-10-06']

x, y = subset.index.to_series(), subset['glucose']

# Basic plot setup
plot = figure(plot_width=600, plot_height=300, x_axis_type="datetime", tools="",
              toolbar_location=None, title='Hover over points')

plot.line(x, y, line_dash="4 4", line_width=1, color='gray')

cr = plot.circle(x, y, size=20,
                fill_color="grey", hover_fill_color="firebrick",
                fill_alpha=0.05, hover_alpha=0.3,
                line_color=None, hover_line_color="white")

plot.add_tools(HoverTool(tooltips=None, renderers=[cr], mode='hline'))

show(plot)
```

**Comment by bryevdv** [comment]
This must be a change in pandas?

**Comment by mattpap** [comment]
Linux, pandas 0.25.3.

**Comment by bryevdv** [comment]
That's the same version used in the (successful) CI docs build on linux:

https://github.com/bokeh/bokeh/pull/9588/checks?check_run_id=399074120

I def can't repro any issue on OS X with 0.25.3 (runing the `hover_glyph.py` example directly, not building the docs)

**Comment by mattpap** [comment]
The problem is with sample data being updated, but `~/.bokeh/data` not being invalidated. All downloaded sample data should be hashed and checked before usage. If there's a mismatch, then it should be downloaded again.

**Comment by bryevdv** [comment]
When and how often is the data updated? And why was this particular file updated recently at all? The recent work to add hashes put the hashes in the python package itself. That obviously only makes sense on the assumption that the already published data files don't ever really change, which I thought was in fact the case. I would like to learn why it is not.

**Comment by bryevdv** [comment]
I am going to go ahead and close this.  We should not udpate published files on CDN, since it will potentially break things for old releases. If we need to change the file somehow, we should upload a new file with a new filename and start using that with a new hash in the python code with whatever new release is next.
