### ISSUE TITLE
The bokeh server is redirecting to an empty page

### ISSUE THREAD

**Issue by bpriya11** [bokeh/bokeh#9632]
I have been running my code on Jupyter Notebook using the bokeh server, but I am again and again redirected to the empty page. I even tried this code from google but got the same output.
Here is the code:
from random import random
from bokeh.layouts import column
from bokeh.models import Button
from bokeh.palettes import RdYlBu3
from bokeh.plotting import figure, curdoc
p = figure(x_range=(0, 100), y_range=(0, 100), toolbar_location=None)
p.border_fill_color = 'black'
p.background_fill_color = 'black'
p.outline_line_color = None
p.grid.grid_line_color = None
r = p.text(x=[], y=[], text=[], text_color=[], text_font_size="20pt",
           text_baseline="middle", text_align="center")
i = 0
ds = r.data_source
def callback():
    global i
    # BEST PRACTICE --- update .data in one step with a new dict
    new_data = dict()
    new_data['x'] = ds.data['x'] + [random()*70 + 15]
    new_data['y'] = ds.data['y'] + [random()*70 + 15]
    new_data['text_color'] = ds.data['text_color'] + [RdYlBu3[i%3]]
    new_data['text'] = ds.data['text'] + [str(i)]
    ds.data = new_data
    i = i + 1
button = Button(label="Press Me")
button.on_click(callback)
curdoc().add_root(column(button, p))

This is the code taken from https://docs.bokeh.org/en/latest/docs/user_guide/server.html.
Every other code is giving the same result with this message on terminal.
(base) PS C:\Users\DELL> bokeh serve --show dd.py
2020-02-04 15:03:28,430 Starting Bokeh server version 1.3.4 (running on Tornado 6.0.3)
2020-02-04 15:03:28,446 Bokeh app running at: http://localhost:5006/dd
2020-02-04 15:03:28,446 Starting Bokeh server with process id: 15316
2020-02-04 15:03:28,989 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x000001B99C5CAB48>: name 'null' is not defined
File "dd.py", line 55, in <module>:
"execution_count": null, Traceback (most recent call last):
  File "C:\Users\DELL\Anaconda3\lib\site-packages\bokeh\application\handlers\code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "C:\Users\DELL\dd.py", line 55, in <module>
    "execution_count": null,
NameError: name 'null' is not defined

2020-02-04 15:03:29,011 200 GET /dd (::1) 26.98ms
2020-02-04 15:03:29,842 101 GET /dd/ws?bokeh-protocol-version=1.0&bokeh-session-id=N3dJeEkvI48wzk3y381O5qUsaZb8PUbHxbILPCqXM6La (::1) 3.01ms
2020-02-04 15:03:29,843 WebSocket connection opened
2020-02-04 15:03:29,847 ServerConnection created

**Comment by bryevdv** [comment]
When I run the code at the link it works as expected. The code you have posted above is not consistent with the error message:
```
File "dd.py", line 55, in :
"execution_count": null, Traceback (most recent call last):
File "C:\Users\DELL\Anaconda3\lib\site-packages\bokeh\application\handlers\code_runner.py", line 179, in run
``` 
This error message is stating exactly what what the problem is: you have a syntax error in thecae you are trying to run in the `dd.py` file. In any case this is a usage/support question, so discussion should go on the Project Discourse, not the tracker:

https://discourse.bokeh.org/
