### ISSUE TITLE
[BUG] Can't build BokehJS on OSX

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9997]
Have tried all of the following tp get unstuck, to no avail:

* `npm cache clear --force`
* `rm -rf node_modules`
* updating to nodejs 12.x

Also tried manually installing `esquery` after all that. Always get:
```
[19:10:02] Starting 'compiler:build'...
[19:10:03] Failed 'compiler:build' after 521 ms
[19:10:03] Error: '/Users/bryan/work/bokeh/bokehjs/node_modules/esquery/esquery.js doesn't exist
[19:10:03]     at Linker.new_module (/Users/bryan/work/bokeh/bokehjs/src/compiler/linker.ts:552:13)
[19:10:03]     at Linker.resolve (/Users/bryan/work/bokeh/bokehjs/src/compiler/linker.ts:711:27)
[19:10:03]     at Linker.link (/Users/bryan/work/bokeh/bokehjs/src/compiler/linker.ts:267:28)
[19:10:03]     at Task.fn (/Users/bryan/work/bokeh/bokehjs/make/tasks/compiler.ts:31:27)
[19:10:03]     at exec_task (/Users/bryan/work/bokeh/bokehjs/make/task.ts:147:34)
[19:10:03]     at _run (/Users/bryan/work/bokeh/bokehjs/make/task.ts:176:24)
[19:10:03]     at _run (/Users/bryan/work/bokeh/bokehjs/make/task.ts:168:26)
[19:10:03]     at _run (/Users/bryan/work/bokeh/bokehjs/make/task.ts:168:26)
[19:10:03]     at Object.run (/Users/bryan/work/bokeh/bokehjs/make/task.ts:192:22)
[19:10:03]     at main (/Users/bryan/work/bokeh/bokehjs/make/main.ts:18:16)
```

**Comment by bryevdv** [comment]
Manually installing esquery 0.4 "fixes":
```
(dev) ❯ ls node_modules/esquery
README.md  esquery.js  license.txt  package.json  parser.js
```

**Comment by RyanRio** [comment]
Same error and then one additional error on Windows (Windows 10 in conda environment):
`timezone` error:
![image](https://user-images.githubusercontent.com/25875031/81434425-1aab9200-9134-11ea-82a2-0c6157085701.png)

Then the `esquery` error:
![image](https://user-images.githubusercontent.com/25875031/81434468-2d25cb80-9134-11ea-9bf6-3b2ee695742a.png)

When installing esquery manually with `npm install esquery@0.4` I now get this error:
![image](https://user-images.githubusercontent.com/25875031/81434645-7ece5600-9134-11ea-932d-4e15dc736bc1.png)

**Comment by mattpap** [comment]
I can now reproduce some form of this issue on Linux:
```
Failed 'compiler:build' after 1.00 s
[17:30:38] Error: '/home/mateusz/repo/bokeh/bokehjs/node_modules/esquery/dist/esquery.min.js doesn't exist
```

**Comment by mattpap** [comment]
The problem is with caching in bokehjs' build, which doesn't recognize structural changes to packages and fails to invalidate itself. If you see those error messages, then a workaround is to issue `node make build --rebuild` (this ignores the cache). This wasn't caught by my earlier attempt to reproduce this (PR #9991), because in CI we always build from scratch.

**Comment by RyanRio** [comment]
Workaround solves the issue on Windows too - I'm trying to figure out where the caching problem you've pointed out exists but I'm having a tough time since the error can happen in multiple tasks. Is there a specific ts file where the caching functionality is written?

**Comment by mattpap** [comment]
@RyanRio, `bokehjs/src/compiler/linker.ts` which is then used in `bokehjs/make/tasks/*`.

**Comment by bryevdv** [comment]
@mattpap is this still relevant?

**Comment by mattpap** [comment]
Some improvements were made and but a variation of this problem may still appear, e.g. when changing far off branches. Though personally I didn't experience this issue in a while. The quick solution is to `node make clean:all` when something fishy is going on.
